$axure.loadCurrentPage({
  "url":"详情页_1.html",
  "generationDate":new Date(1432872285329.94),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"e534f7c2eae04c1b89cdd1db38560954",
    "type":"Axure:Page",
    "name":"详情页",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"08ac1991afb5446b855d73c0be76accd",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
},
          "adaptiveStyles":{
},
          "masterId":"a9e111da73474fc58a4e9af309efe76e"},
{
          "id":"0b6e119d196942c7a53544c406d290c2",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":200,
              "y":150},
            "size":{
              "width":200,
              "height":80},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFD7D7D7}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6eea296d667247e8be5e719ba1b19e22",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":200,
                  "y":150},
                "size":{
                  "width":200,
                  "height":80},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的工作台/u26.png"}},
{
          "id":"c85ddb26dbfd4a9dbc4eb99cbaf4644d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFE4E4E4},
            "location":{
              "x":200,
              "y":230},
            "size":{
              "width":200,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFD7D7D7}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"82ad0dc755384d36be89acfe5fdf38b7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4},
                "location":{
                  "x":200,
                  "y":230},
                "size":{
                  "width":200,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的工作台/u28.png"}},
{
          "id":"0485d62b907c4861a35702f2c0d5b5bb",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":200,
              "y":360},
            "size":{
              "width":200,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFD7D7D7}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e91e2de7e10a486e98cea3b2cf1620e7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":200,
                  "y":360},
                "size":{
                  "width":200,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的工作台/u30.png"}},
{
          "id":"aef2e3fe610c4600a68b208a02304bd5",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":200,
              "y":400},
            "size":{
              "width":200,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFD7D7D7}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4adc4f2a1f1d483c863be4f738f3d9ea",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":200,
                  "y":400},
                "size":{
                  "width":200,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的工作台/u30.png"}},
{
          "id":"e80105308e9f4279b522c2e4f6f299cf",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":200,
              "y":440},
            "size":{
              "width":200,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFD7D7D7}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9b8c9e3fce684484a355a45c3c40c95b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":200,
                  "y":440},
                "size":{
                  "width":200,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的工作台/u30.png"}},
{
          "id":"f4603132a42c444ca2b6cd81ff5e9316",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":200,
              "y":480},
            "size":{
              "width":200,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFD7D7D7}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4e3523b67b454811ba6af841834f9fc5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":200,
                  "y":480},
                "size":{
                  "width":200,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的工作台/u30.png"}},
{
          "id":"e32fa6db0fe24a90846b047ae1ab8e20",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "fill":{
              "fillType":"solid",
              "color":0xFFE4E4E4},
            "location":{
              "x":210,
              "y":300},
            "size":{
              "width":190,
              "height":30},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFD7D7D7}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"01130efc115242b58c58b17294bc8c85",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4},
                "location":{
                  "x":210,
                  "y":300},
                "size":{
                  "width":190,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/管理资源单/u233.png"}},
{
          "id":"2d1aff47e32b43b18f71bb9b2ad929e6",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "location":{
              "x":210,
              "y":330},
            "size":{
              "width":190,
              "height":30},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFD7D7D7}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"766e16b5f51f4e1ebc68b1cf62a6aeeb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "location":{
                  "x":210,
                  "y":330},
                "size":{
                  "width":190,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/管理资源单/u235.png"}},
{
          "id":"56c907980b5a411982ccb52a1d51ccce",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "location":{
              "x":210,
              "y":270},
            "size":{
              "width":190,
              "height":30},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFD7D7D7}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7569254c65af4080a38730131aaccd79",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "location":{
                  "x":210,
                  "y":270},
                "size":{
                  "width":190,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/管理资源单/u235.png"}},
{
          "id":"7f5f9b3c91c040f89fa489557dca500f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":420,
              "y":150},
            "size":{
              "width":780,
              "height":1091},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFD7D7D7}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ebf700ffdde343afac22c08c933ff83b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":420,
                  "y":150},
                "size":{
                  "width":780,
                  "height":1091},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/详情页_1/u42.png"}},
{
          "id":"298aa60254e44766b7fcbff1d0fe4271",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "location":{
              "x":440,
              "y":164},
            "size":{
              "width":210,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7a9e4ed10ee34be3b126e51ef2f86c96",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "location":{
                  "x":440,
                  "y":164},
                "size":{
                  "width":210,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d3d791ba04c241bb88d0d495d0f4963a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":440,
              "y":272},
            "size":{
              "width":90,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d5e20919787c41d4bfba87ef58a9292f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":440,
                  "y":272},
                "size":{
                  "width":90,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"efe7a8bc665e4889992b3bf88cd5ca70",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":440,
              "y":305},
            "size":{
              "width":90,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a423e45b77874d45af8397f2805f4512",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":440,
                  "y":305},
                "size":{
                  "width":90,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"87b39a5b0b714fb8beee77fa257accc5",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":440,
              "y":339},
            "size":{
              "width":90,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4a0c8817755e41919dc7c81bf51898b0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":440,
                  "y":339},
                "size":{
                  "width":90,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d65ee3a65ce44f3a8cfb2a6e2fba6be0",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":440,
              "y":373},
            "size":{
              "width":90,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7491976b80554d408500481e39f56b5c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":440,
                  "y":373},
                "size":{
                  "width":90,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"68a6462c5a7d4c2abde6ccb5c82981ec",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":440,
              "y":1203},
            "size":{
              "width":110,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1e1eb05129cf4db5af273a17971b113c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":440,
                  "y":1203},
                "size":{
                  "width":110,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a8d77f7e72044a27bc037369d0e09586",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":440,
              "y":409},
            "size":{
              "width":90,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"444b13090f9f449f81de2459f4bb8344",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":440,
                  "y":409},
                "size":{
                  "width":90,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"da1a3005dbd8490d98948aa6334d2daf",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":510,
              "y":409},
            "size":{
              "width":166,
              "height":118}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e0c69fb148bc4da4abde90654f3a65f7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":510,
                  "y":409},
                "size":{
                  "width":166,
                  "height":118}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/增加车辆/u196.png"}},
{
          "id":"0be0975c39ff4409b014e70825f71d6e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "lineSpacing":"20px",
            "location":{
              "x":880,
              "y":507},
            "size":{
              "width":440,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c0b00f4fc8d147739d264a6dfea08147",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "lineSpacing":"20px",
                "location":{
                  "x":880,
                  "y":507},
                "size":{
                  "width":440,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9a9458febc4c4b54b927f3846ae7be5d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":440,
              "y":557},
            "size":{
              "width":90,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"eab88a24d03940c39311cba09b27c289",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":440,
                  "y":557},
                "size":{
                  "width":90,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2a2e1174ef8d4c23afb94b4a0ab318b0",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":534,
              "y":557},
            "size":{
              "width":166,
              "height":118}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dd7027d98f3a4fcc8ea72b66dd2b6f97",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":534,
                  "y":557},
                "size":{
                  "width":166,
                  "height":118}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/增加车辆/u196.png"}},
{
          "id":"f9e0033e6b9d4edf90730466c5364147",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":440,
              "y":701},
            "size":{
              "width":90,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"38eed667709e4ae3a5f90e76b861d0a1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":440,
                  "y":701},
                "size":{
                  "width":90,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f77906894d71436d8abce8e5816b742f",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":534,
              "y":701},
            "size":{
              "width":166,
              "height":118}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f3b142735dfb4f488615595c0cfa3638",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":534,
                  "y":701},
                "size":{
                  "width":166,
                  "height":118}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/增加车辆/u196.png"}},
{
          "id":"101b0406940344aeb4ef9de20c13ea67",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":440,
              "y":1149},
            "size":{
              "width":90,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b5188069f06847a3b8cfa7a0405e88a7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":440,
                  "y":1149},
                "size":{
                  "width":90,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e63341f45941448c9e59f418f33b3b18",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":440,
              "y":849},
            "size":{
              "width":90,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"84859d2688514b1b89bb32d72ad0f908",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":440,
                  "y":849},
                "size":{
                  "width":90,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"bbdd0df880a245829742d7368f481b1c",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":534,
              "y":849},
            "size":{
              "width":166,
              "height":118}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d16d7e443a6d40119471c1cb784e1226",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":534,
                  "y":849},
                "size":{
                  "width":166,
                  "height":118}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/增加车辆/u196.png"}},
{
          "id":"73d52894817548fca923ce6c782d2626",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":698,
              "y":409},
            "size":{
              "width":166,
              "height":118}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ca67820c05674f6a8d2377fe9434f565",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":698,
                  "y":409},
                "size":{
                  "width":166,
                  "height":118}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/增加车辆/u196.png"}},
{
          "id":"05166f3f53cd452c9f2b074be668e557",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":440,
              "y":999},
            "size":{
              "width":90,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ccc2cde56f50403b8e2322f58a7d60bb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":440,
                  "y":999},
                "size":{
                  "width":90,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2ed0d924afc245cd94eaa0c04606ee2a",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":534,
              "y":999},
            "size":{
              "width":166,
              "height":118}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1ce30199a4da4e4c9c210318ad44eff5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":534,
                  "y":999},
                "size":{
                  "width":166,
                  "height":118}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/增加车辆/u196.png"}},
{
          "id":"a117a9755e2a406a80beba37cf7419c9",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":729,
              "y":999},
            "size":{
              "width":166,
              "height":118}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0ec9f3b006c04efd8a79d23871f05bcc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":729,
                  "y":999},
                "size":{
                  "width":166,
                  "height":118}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/增加车辆/u196.png"}},
{
          "id":"ab4627aba6954a6dab03cc4e203e73b2",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":924,
              "y":999},
            "size":{
              "width":166,
              "height":118}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"53eee409098546fcb6d535383110b605",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":924,
                  "y":999},
                "size":{
                  "width":166,
                  "height":118}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/增加车辆/u196.png"}},
{
          "id":"16f063160f6c4c9d82dbcb63b1be44fe",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":510,
              "y":272},
            "size":{
              "width":90,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f9cf53d725d246f3b609760282d42fb6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":510,
                  "y":272},
                "size":{
                  "width":90,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0eeec2838c944c0fb2ac24e1b9319cae",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":510,
              "y":305},
            "size":{
              "width":90,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"632d50bf28044eb49c6edccae7e55c07",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":510,
                  "y":305},
                "size":{
                  "width":90,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"828a05bc4f004593915935a2b5ab1a09",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":510,
              "y":339},
            "size":{
              "width":90,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c6ca919c1b054818a850216cef680117",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":510,
                  "y":339},
                "size":{
                  "width":90,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5301333ad5244332a0bead0889ca515d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":510,
              "y":373},
            "size":{
              "width":90,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"43c43d11cc464651b5e982acc8eb1cd0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":510,
                  "y":373},
                "size":{
                  "width":90,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"99e78a8c194d44deaa3073cf65d47cbd",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "lineSpacing":"20px",
            "location":{
              "x":710,
              "y":655},
            "size":{
              "width":440,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"01672894f902401ca4340a71bcc9495c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "lineSpacing":"20px",
                "location":{
                  "x":710,
                  "y":655},
                "size":{
                  "width":440,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b8522476e3bb4cb78841aeed6dfff9be",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "lineSpacing":"20px",
            "location":{
              "x":710,
              "y":799},
            "size":{
              "width":440,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cf1d0e42318148ec969f4126090e8ebd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "lineSpacing":"20px",
                "location":{
                  "x":710,
                  "y":799},
                "size":{
                  "width":440,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"721721c3f1174815af8ee290868de0fa",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "lineSpacing":"20px",
            "location":{
              "x":710,
              "y":947},
            "size":{
              "width":440,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"03102333de2a43f49907feed530486ef",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "lineSpacing":"20px",
                "location":{
                  "x":710,
                  "y":947},
                "size":{
                  "width":440,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ef10f5aa23cd4f14b82cf8b9ffcbbcae",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":510,
              "y":1149},
            "size":{
              "width":90,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d7e3e0f3585240868776d91f2c86f072",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":510,
                  "y":1149},
                "size":{
                  "width":90,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a1e984a62262446f975c913affbe7be1",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":534,
              "y":1203},
            "size":{
              "width":686,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c3af03d540f54ba193750753055aff20",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":534,
                  "y":1203},
                "size":{
                  "width":686,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ce01068c3edd459aa1fa0b817323d608",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontWeight":"700",
            "location":{
              "x":420,
              "y":1251},
            "size":{
              "width":218,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6410d3d2f083418ba025c06380142a3f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"700",
                "location":{
                  "x":420,
                  "y":1251},
                "size":{
                  "width":218,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"31f691f0df6b47d996ff49f38d29da60",
          "label":"",
          "type":"table",
          "styleType":"table",
          "visible":true,
          "style":{
            "location":{
              "x":420,
              "y":1277},
            "size":{
              "width":780,
              "height":106}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e4132e99be95449d98ad1cc6db3a1561",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"700",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "size":{
                  "width":148,
                  "height":35},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"0e8edb591c844513bab65bc71f5990e4",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Arial Negreta', 'Arial'",
                    "fontWeight":"700",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFF2F2F2},
                    "size":{
                      "width":148,
                      "height":35},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFD7D7D7}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/审核_1/u115.png"}},
{
              "id":"763801308817430db195968e50b20798",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":70},
                "size":{
                  "width":148,
                  "height":36},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"e4f353729c6047068fa7b8b93786c63c",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":70},
                    "size":{
                      "width":148,
                      "height":36},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFD7D7D7}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/审核_1/u121.png"}},
{
              "id":"dcb31acfaff74b779015d018a74582a3",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"700",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":148,
                  "y":0},
                "size":{
                  "width":125,
                  "height":35},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"600128387b3940a2bb672f877a132819",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Arial Negreta', 'Arial'",
                    "fontWeight":"700",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFF2F2F2},
                    "location":{
                      "x":148,
                      "y":0},
                    "size":{
                      "width":125,
                      "height":35},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFD7D7D7}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/审核_1/u117.png"}},
{
              "id":"a58b5618f1564c66bc01befc178c1db6",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "verticalAlignment":"middle",
                "location":{
                  "x":148,
                  "y":70},
                "size":{
                  "width":125,
                  "height":36},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"6a679d1aa1454d8691679fb2178fc76d",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "verticalAlignment":"middle",
                    "location":{
                      "x":148,
                      "y":70},
                    "size":{
                      "width":125,
                      "height":36},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFD7D7D7}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/审核_1/u123.png"}},
{
              "id":"c2de2be9f9d64c94af1b9591565f4fd6",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"700",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":273,
                  "y":0},
                "size":{
                  "width":507,
                  "height":35},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"4ff01f00b7d4446a9b9fca333aa5f4f4",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Arial Negreta', 'Arial'",
                    "fontWeight":"700",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFF2F2F2},
                    "location":{
                      "x":273,
                      "y":0},
                    "size":{
                      "width":507,
                      "height":35},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFD7D7D7}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/审核_1/u119.png"}},
{
              "id":"fe37d9a845ab47b9b171088df7506c7a",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "verticalAlignment":"middle",
                "location":{
                  "x":273,
                  "y":70},
                "size":{
                  "width":507,
                  "height":36},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"6b133424ddf34eb5bdf51797f227ce4c",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "verticalAlignment":"middle",
                    "location":{
                      "x":273,
                      "y":70},
                    "size":{
                      "width":507,
                      "height":36},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFD7D7D7}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/审核_1/u125.png"}},
{
              "id":"d248aaf191d1448d9f4eebf2cd2cbd7c",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":35},
                "size":{
                  "width":148,
                  "height":35},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"82439d4c5fbf4e4ba38d6d6da024f0a4",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":35},
                    "size":{
                      "width":148,
                      "height":35},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFD7D7D7}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/已关闭/u65.png"}},
{
              "id":"9607a7919e744046bb7356dfd0181b21",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "verticalAlignment":"middle",
                "location":{
                  "x":148,
                  "y":35},
                "size":{
                  "width":125,
                  "height":35},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"b1d4f7a2486c48bc93d68dc1ee25f38c",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "verticalAlignment":"middle",
                    "location":{
                      "x":148,
                      "y":35},
                    "size":{
                      "width":125,
                      "height":35},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFD7D7D7}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/详情页/u115.png"}},
{
              "id":"3a963a83e731448fb80392d66143ccb2",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "verticalAlignment":"middle",
                "location":{
                  "x":273,
                  "y":35},
                "size":{
                  "width":507,
                  "height":35},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"ad95a22a1f774c37ac2dbabe07878052",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "verticalAlignment":"middle",
                    "location":{
                      "x":273,
                      "y":35},
                    "size":{
                      "width":507,
                      "height":35},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFD7D7D7}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/详情页/u117.png"}}]},
{
          "id":"7c6621c627854ba0aa7a8632839b7770",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":1400}},
          "adaptiveStyles":{
},
          "masterId":"9aa3da306ba24637b281c884b1c30bca"},
{
          "id":"7da14f57442f49a99a82c57b10a0c491",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":440,
              "y":200},
            "size":{
              "width":90,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bdc4a6bee6d144c982429db2d42dcd11",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":440,
                  "y":200},
                "size":{
                  "width":90,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7a2600ee13c6457a92ac764e0ccae004",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":510,
              "y":200},
            "size":{
              "width":90,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b20ebc3687f8478c8e2b6b7a533e7bf9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":510,
                  "y":200},
                "size":{
                  "width":90,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"af4540eeb0544bddb7ffdb527db253e5",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":440,
              "y":226},
            "size":{
              "width":730,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"249800dddbfc4c94bdc98f92be0a9d27",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":440,
                  "y":226},
                "size":{
                  "width":730,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"128daa516f8745c9b3aa6f2c89c1c603",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":200,
              "y":520},
            "size":{
              "width":200,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFD7D7D7}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0b8351a3fdd646c6bf854658f2fc3eac",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":200,
                  "y":520},
                "size":{
                  "width":200,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的工作台/u30.png"}}]}},
  "masters":{
    "a9e111da73474fc58a4e9af309efe76e":{
      "packageId":"a9e111da73474fc58a4e9af309efe76e",
      "type":"Axure:Master",
      "name":"交易员头部--承运管理",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"应用字体",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"11a2262448e0441f9a29e02867462317",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "size":{
                "width":1400,
                "height":90},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFD7D7D7}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"2fb6fec02a5946deb468d94b926d5702",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "size":{
                    "width":1400,
                    "height":90},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFD7D7D7}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/我的工作台/u3.png"}},
{
            "id":"d272761cc28841aabfc377d601a1ee83",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":200,
                "y":15},
              "size":{
                "width":200,
                "height":60},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFD7D7D7}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"304b1fa2e1004612895198bae19aad1c",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":200,
                    "y":15},
                  "size":{
                    "width":200,
                    "height":60},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFD7D7D7}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/我的工作台/u5.png"}},
{
            "id":"1ff87331235e44d3907f0495638c3ee8",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFFF2F2F2},
              "location":{
                "x":0,
                "y":90},
              "size":{
                "width":1400,
                "height":35},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFD7D7D7}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"8dea732008a44e7ba0aa5e0d23bc0e6b",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFF2F2F2},
                  "location":{
                    "x":0,
                    "y":90},
                  "size":{
                    "width":1400,
                    "height":35},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFD7D7D7}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/首页/u33.png"}},
{
            "id":"0ae756c78f1d4827bd92090a57c2445d",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":200,
                "y":90},
              "size":{
                "width":130,
                "height":35},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFD7D7D7}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"fa593240b6704c1390d0e2aefef6074a",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":200,
                    "y":90},
                  "size":{
                    "width":130,
                    "height":35},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFD7D7D7}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/我的工作台/u11.png"}},
{
            "id":"3718fe3583d442998538f8f62ebde4ea",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":330,
                "y":90},
              "size":{
                "width":130,
                "height":35},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFD7D7D7}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"13c36587be2d43fe8c5570fc2d88bd70",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":330,
                    "y":90},
                  "size":{
                    "width":130,
                    "height":35},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFD7D7D7}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/我的工作台/u11.png"}},
{
            "id":"482ddefbf1b94c4183138f489a3af059",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "horizontalAlignment":"right",
              "location":{
                "x":940,
                "y":15},
              "size":{
                "width":260,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"790516a0e63b4a738672d162eb75bbee",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "horizontalAlignment":"right",
                  "location":{
                    "x":940,
                    "y":15},
                  "size":{
                    "width":260,
                    "height":16}},
                "adaptiveStyles":{
},
                "objects":[{
                    "id":"89ef4c8d3211448595cc574e09210793",
                    "label":"",
                    "type":"hyperlink",
                    "styleType":"hyperlink",
                    "visible":true,
                    "style":{
},
                    "adaptiveStyles":{
},
                    "interactionMap":{
                      "onClick":{
                        "description":"OnClick",
                        "cases":[{
                            "description":"用例 1",
                            "isNewIfGroup":false,
                            "actions":[{
                                "action":"linkWindow",
                                "description":"在 当前窗口 打开 帐号设置",
                                "target":{
                                  "targetType":"page",
                                  "url":"帐号设置.html",
                                  "includeVariables":true},
                                "linkType":"current"}]}]}},
                    "tabbable":true}]}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"1dde2786457c4a03ad2520b794c38eaa",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":460,
                "y":90},
              "size":{
                "width":130,
                "height":35},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFD7D7D7}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"d077be6ea4d84cc695fc46e280f10374",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":460,
                    "y":90},
                  "size":{
                    "width":130,
                    "height":35},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFD7D7D7}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/我的工作台/u11.png"}},
{
            "id":"fad8689927314969bdd7cc6a59f7699a",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":590,
                "y":90},
              "size":{
                "width":130,
                "height":35},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFD7D7D7}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"b696734bb164452eb4dfbf0253e65191",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":590,
                    "y":90},
                  "size":{
                    "width":130,
                    "height":35},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFD7D7D7}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/我的工作台/u11.png"}},
{
            "id":"d6530536be2c439682beb237555b0ac0",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFFE4E4E4},
              "location":{
                "x":720,
                "y":90},
              "size":{
                "width":130,
                "height":35},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFD7D7D7}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"3e27027186624cb88b9b0650e15fa5e2",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFE4E4E4},
                  "location":{
                    "x":720,
                    "y":90},
                  "size":{
                    "width":130,
                    "height":35},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFD7D7D7}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/我的工作台/u9.png"}},
{
            "id":"4a2cbc1c2e694133808618f4c7848012",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":850,
                "y":90},
              "size":{
                "width":130,
                "height":35},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFD7D7D7}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"68913fdfca4f4e63a10405f8167cce60",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":850,
                    "y":90},
                  "size":{
                    "width":130,
                    "height":35},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFD7D7D7}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/我的工作台/u11.png"}},
{
            "id":"e4a12249d50141fd96e9f562187f1c5b",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":980,
                "y":90},
              "size":{
                "width":130,
                "height":35},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFD7D7D7}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"1c16f2463de5451a9af0b5d3d819bf80",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":980,
                    "y":90},
                  "size":{
                    "width":130,
                    "height":35},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFD7D7D7}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/我的工作台/u11.png"}}]}},
    "9aa3da306ba24637b281c884b1c30bca":{
      "packageId":"9aa3da306ba24637b281c884b1c30bca",
      "type":"Axure:Master",
      "name":"交易员底部",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"应用字体",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"aa94056b817049cbb1fa6bacb8c1e519",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "size":{
                "width":1400,
                "height":40},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFD7D7D7}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"d0f70829d22f42fea545dfa7923b52be",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "size":{
                    "width":1400,
                    "height":40},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFD7D7D7}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/首页/u13.png"}}]}}},
  "objectPaths":{
    "08ac1991afb5446b855d73c0be76accd":{
      "scriptId":"u0",
      "11a2262448e0441f9a29e02867462317":{
        "scriptId":"u1"},
      "2fb6fec02a5946deb468d94b926d5702":{
        "scriptId":"u2"},
      "d272761cc28841aabfc377d601a1ee83":{
        "scriptId":"u3"},
      "304b1fa2e1004612895198bae19aad1c":{
        "scriptId":"u4"},
      "1ff87331235e44d3907f0495638c3ee8":{
        "scriptId":"u5"},
      "8dea732008a44e7ba0aa5e0d23bc0e6b":{
        "scriptId":"u6"},
      "0ae756c78f1d4827bd92090a57c2445d":{
        "scriptId":"u7"},
      "fa593240b6704c1390d0e2aefef6074a":{
        "scriptId":"u8"},
      "3718fe3583d442998538f8f62ebde4ea":{
        "scriptId":"u9"},
      "13c36587be2d43fe8c5570fc2d88bd70":{
        "scriptId":"u10"},
      "482ddefbf1b94c4183138f489a3af059":{
        "scriptId":"u11"},
      "790516a0e63b4a738672d162eb75bbee":{
        "scriptId":"u12"},
      "89ef4c8d3211448595cc574e09210793":{
        "scriptId":"u13"},
      "1dde2786457c4a03ad2520b794c38eaa":{
        "scriptId":"u14"},
      "d077be6ea4d84cc695fc46e280f10374":{
        "scriptId":"u15"},
      "fad8689927314969bdd7cc6a59f7699a":{
        "scriptId":"u16"},
      "b696734bb164452eb4dfbf0253e65191":{
        "scriptId":"u17"},
      "d6530536be2c439682beb237555b0ac0":{
        "scriptId":"u18"},
      "3e27027186624cb88b9b0650e15fa5e2":{
        "scriptId":"u19"},
      "4a2cbc1c2e694133808618f4c7848012":{
        "scriptId":"u20"},
      "68913fdfca4f4e63a10405f8167cce60":{
        "scriptId":"u21"},
      "e4a12249d50141fd96e9f562187f1c5b":{
        "scriptId":"u22"},
      "1c16f2463de5451a9af0b5d3d819bf80":{
        "scriptId":"u23"}},
    "0b6e119d196942c7a53544c406d290c2":{
      "scriptId":"u24"},
    "6eea296d667247e8be5e719ba1b19e22":{
      "scriptId":"u25"},
    "c85ddb26dbfd4a9dbc4eb99cbaf4644d":{
      "scriptId":"u26"},
    "82ad0dc755384d36be89acfe5fdf38b7":{
      "scriptId":"u27"},
    "0485d62b907c4861a35702f2c0d5b5bb":{
      "scriptId":"u28"},
    "e91e2de7e10a486e98cea3b2cf1620e7":{
      "scriptId":"u29"},
    "aef2e3fe610c4600a68b208a02304bd5":{
      "scriptId":"u30"},
    "4adc4f2a1f1d483c863be4f738f3d9ea":{
      "scriptId":"u31"},
    "e80105308e9f4279b522c2e4f6f299cf":{
      "scriptId":"u32"},
    "9b8c9e3fce684484a355a45c3c40c95b":{
      "scriptId":"u33"},
    "f4603132a42c444ca2b6cd81ff5e9316":{
      "scriptId":"u34"},
    "4e3523b67b454811ba6af841834f9fc5":{
      "scriptId":"u35"},
    "e32fa6db0fe24a90846b047ae1ab8e20":{
      "scriptId":"u36"},
    "01130efc115242b58c58b17294bc8c85":{
      "scriptId":"u37"},
    "2d1aff47e32b43b18f71bb9b2ad929e6":{
      "scriptId":"u38"},
    "766e16b5f51f4e1ebc68b1cf62a6aeeb":{
      "scriptId":"u39"},
    "56c907980b5a411982ccb52a1d51ccce":{
      "scriptId":"u40"},
    "7569254c65af4080a38730131aaccd79":{
      "scriptId":"u41"},
    "7f5f9b3c91c040f89fa489557dca500f":{
      "scriptId":"u42"},
    "ebf700ffdde343afac22c08c933ff83b":{
      "scriptId":"u43"},
    "298aa60254e44766b7fcbff1d0fe4271":{
      "scriptId":"u44"},
    "7a9e4ed10ee34be3b126e51ef2f86c96":{
      "scriptId":"u45"},
    "d3d791ba04c241bb88d0d495d0f4963a":{
      "scriptId":"u46"},
    "d5e20919787c41d4bfba87ef58a9292f":{
      "scriptId":"u47"},
    "efe7a8bc665e4889992b3bf88cd5ca70":{
      "scriptId":"u48"},
    "a423e45b77874d45af8397f2805f4512":{
      "scriptId":"u49"},
    "87b39a5b0b714fb8beee77fa257accc5":{
      "scriptId":"u50"},
    "4a0c8817755e41919dc7c81bf51898b0":{
      "scriptId":"u51"},
    "d65ee3a65ce44f3a8cfb2a6e2fba6be0":{
      "scriptId":"u52"},
    "7491976b80554d408500481e39f56b5c":{
      "scriptId":"u53"},
    "68a6462c5a7d4c2abde6ccb5c82981ec":{
      "scriptId":"u54"},
    "1e1eb05129cf4db5af273a17971b113c":{
      "scriptId":"u55"},
    "a8d77f7e72044a27bc037369d0e09586":{
      "scriptId":"u56"},
    "444b13090f9f449f81de2459f4bb8344":{
      "scriptId":"u57"},
    "da1a3005dbd8490d98948aa6334d2daf":{
      "scriptId":"u58"},
    "e0c69fb148bc4da4abde90654f3a65f7":{
      "scriptId":"u59"},
    "0be0975c39ff4409b014e70825f71d6e":{
      "scriptId":"u60"},
    "c0b00f4fc8d147739d264a6dfea08147":{
      "scriptId":"u61"},
    "9a9458febc4c4b54b927f3846ae7be5d":{
      "scriptId":"u62"},
    "eab88a24d03940c39311cba09b27c289":{
      "scriptId":"u63"},
    "2a2e1174ef8d4c23afb94b4a0ab318b0":{
      "scriptId":"u64"},
    "dd7027d98f3a4fcc8ea72b66dd2b6f97":{
      "scriptId":"u65"},
    "f9e0033e6b9d4edf90730466c5364147":{
      "scriptId":"u66"},
    "38eed667709e4ae3a5f90e76b861d0a1":{
      "scriptId":"u67"},
    "f77906894d71436d8abce8e5816b742f":{
      "scriptId":"u68"},
    "f3b142735dfb4f488615595c0cfa3638":{
      "scriptId":"u69"},
    "101b0406940344aeb4ef9de20c13ea67":{
      "scriptId":"u70"},
    "b5188069f06847a3b8cfa7a0405e88a7":{
      "scriptId":"u71"},
    "e63341f45941448c9e59f418f33b3b18":{
      "scriptId":"u72"},
    "84859d2688514b1b89bb32d72ad0f908":{
      "scriptId":"u73"},
    "bbdd0df880a245829742d7368f481b1c":{
      "scriptId":"u74"},
    "d16d7e443a6d40119471c1cb784e1226":{
      "scriptId":"u75"},
    "73d52894817548fca923ce6c782d2626":{
      "scriptId":"u76"},
    "ca67820c05674f6a8d2377fe9434f565":{
      "scriptId":"u77"},
    "05166f3f53cd452c9f2b074be668e557":{
      "scriptId":"u78"},
    "ccc2cde56f50403b8e2322f58a7d60bb":{
      "scriptId":"u79"},
    "2ed0d924afc245cd94eaa0c04606ee2a":{
      "scriptId":"u80"},
    "1ce30199a4da4e4c9c210318ad44eff5":{
      "scriptId":"u81"},
    "a117a9755e2a406a80beba37cf7419c9":{
      "scriptId":"u82"},
    "0ec9f3b006c04efd8a79d23871f05bcc":{
      "scriptId":"u83"},
    "ab4627aba6954a6dab03cc4e203e73b2":{
      "scriptId":"u84"},
    "53eee409098546fcb6d535383110b605":{
      "scriptId":"u85"},
    "16f063160f6c4c9d82dbcb63b1be44fe":{
      "scriptId":"u86"},
    "f9cf53d725d246f3b609760282d42fb6":{
      "scriptId":"u87"},
    "0eeec2838c944c0fb2ac24e1b9319cae":{
      "scriptId":"u88"},
    "632d50bf28044eb49c6edccae7e55c07":{
      "scriptId":"u89"},
    "828a05bc4f004593915935a2b5ab1a09":{
      "scriptId":"u90"},
    "c6ca919c1b054818a850216cef680117":{
      "scriptId":"u91"},
    "5301333ad5244332a0bead0889ca515d":{
      "scriptId":"u92"},
    "43c43d11cc464651b5e982acc8eb1cd0":{
      "scriptId":"u93"},
    "99e78a8c194d44deaa3073cf65d47cbd":{
      "scriptId":"u94"},
    "01672894f902401ca4340a71bcc9495c":{
      "scriptId":"u95"},
    "b8522476e3bb4cb78841aeed6dfff9be":{
      "scriptId":"u96"},
    "cf1d0e42318148ec969f4126090e8ebd":{
      "scriptId":"u97"},
    "721721c3f1174815af8ee290868de0fa":{
      "scriptId":"u98"},
    "03102333de2a43f49907feed530486ef":{
      "scriptId":"u99"},
    "ef10f5aa23cd4f14b82cf8b9ffcbbcae":{
      "scriptId":"u100"},
    "d7e3e0f3585240868776d91f2c86f072":{
      "scriptId":"u101"},
    "a1e984a62262446f975c913affbe7be1":{
      "scriptId":"u102"},
    "c3af03d540f54ba193750753055aff20":{
      "scriptId":"u103"},
    "ce01068c3edd459aa1fa0b817323d608":{
      "scriptId":"u104"},
    "6410d3d2f083418ba025c06380142a3f":{
      "scriptId":"u105"},
    "31f691f0df6b47d996ff49f38d29da60":{
      "scriptId":"u106"},
    "e4132e99be95449d98ad1cc6db3a1561":{
      "scriptId":"u107"},
    "0e8edb591c844513bab65bc71f5990e4":{
      "scriptId":"u108"},
    "dcb31acfaff74b779015d018a74582a3":{
      "scriptId":"u109"},
    "600128387b3940a2bb672f877a132819":{
      "scriptId":"u110"},
    "c2de2be9f9d64c94af1b9591565f4fd6":{
      "scriptId":"u111"},
    "4ff01f00b7d4446a9b9fca333aa5f4f4":{
      "scriptId":"u112"},
    "d248aaf191d1448d9f4eebf2cd2cbd7c":{
      "scriptId":"u113"},
    "82439d4c5fbf4e4ba38d6d6da024f0a4":{
      "scriptId":"u114"},
    "9607a7919e744046bb7356dfd0181b21":{
      "scriptId":"u115"},
    "b1d4f7a2486c48bc93d68dc1ee25f38c":{
      "scriptId":"u116"},
    "3a963a83e731448fb80392d66143ccb2":{
      "scriptId":"u117"},
    "ad95a22a1f774c37ac2dbabe07878052":{
      "scriptId":"u118"},
    "763801308817430db195968e50b20798":{
      "scriptId":"u119"},
    "e4f353729c6047068fa7b8b93786c63c":{
      "scriptId":"u120"},
    "a58b5618f1564c66bc01befc178c1db6":{
      "scriptId":"u121"},
    "6a679d1aa1454d8691679fb2178fc76d":{
      "scriptId":"u122"},
    "fe37d9a845ab47b9b171088df7506c7a":{
      "scriptId":"u123"},
    "6b133424ddf34eb5bdf51797f227ce4c":{
      "scriptId":"u124"},
    "7c6621c627854ba0aa7a8632839b7770":{
      "scriptId":"u125",
      "aa94056b817049cbb1fa6bacb8c1e519":{
        "scriptId":"u126"},
      "d0f70829d22f42fea545dfa7923b52be":{
        "scriptId":"u127"}},
    "7da14f57442f49a99a82c57b10a0c491":{
      "scriptId":"u128"},
    "bdc4a6bee6d144c982429db2d42dcd11":{
      "scriptId":"u129"},
    "7a2600ee13c6457a92ac764e0ccae004":{
      "scriptId":"u130"},
    "b20ebc3687f8478c8e2b6b7a533e7bf9":{
      "scriptId":"u131"},
    "af4540eeb0544bddb7ffdb527db253e5":{
      "scriptId":"u132"},
    "249800dddbfc4c94bdc98f92be0a9d27":{
      "scriptId":"u133"},
    "128daa516f8745c9b3aa6f2c89c1c603":{
      "scriptId":"u134"},
    "0b8351a3fdd646c6bf854658f2fc3eac":{
      "scriptId":"u135"}}});