$axure.loadCurrentPage({
  "url":"新闻详细页.html",
  "generationDate":new Date(1432872221556.29),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"89a4848315e84897a1637e7470d53ff1",
    "type":"Axure:Page",
    "name":"新闻详细页",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"1067a21d19fc4f39af29aef9415a174b",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
},
          "adaptiveStyles":{
},
          "masterId":"496537f1e3d34e84bff1d3b9cc7d3781"},
{
          "id":"920a75aa67b84d4ea359f7b04aabbe27",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":1124}},
          "adaptiveStyles":{
},
          "masterId":"526482f429714d2da20c04d5a7d4329e"},
{
          "id":"1afca48492a54d12ae30468c46b2bd56",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "fill":{
              "fillType":"solid",
              "color":0xFFF8F8F8},
            "location":{
              "x":200,
              "y":220},
            "size":{
              "width":210,
              "height":100},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFC9C9C9}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"00d5ea614fb24d82851ea247c67f88b6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF8F8F8},
                "location":{
                  "x":200,
                  "y":220},
                "size":{
                  "width":210,
                  "height":100},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFC9C9C9}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/新闻列表/u35.png"}},
{
          "id":"335f42643de443d086e8b9374e24dd19",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFE4E4E4},
            "location":{
              "x":200,
              "y":320},
            "size":{
              "width":210,
              "height":30},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFC9C9C9}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fbfdeb14db77437f9ccad9695c4c4e71",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4},
                "location":{
                  "x":200,
                  "y":320},
                "size":{
                  "width":210,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFC9C9C9}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/新闻列表/u37.png"}},
{
          "id":"c0240e3c80d645abbf74225bd1334907",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":200,
              "y":350},
            "size":{
              "width":210,
              "height":30},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFC9C9C9}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e3673d7570b64c4b9e8fd976b6449d1d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":200,
                  "y":350},
                "size":{
                  "width":210,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFC9C9C9}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/新闻列表/u39.png"}},
{
          "id":"b06941e7f45d418b8265f72daf60cf91",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":440,
              "y":220},
            "size":{
              "width":760,
              "height":880},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFC9C9C9}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c77808d2d7094daaa78142e32f6d0ccf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":440,
                  "y":220},
                "size":{
                  "width":760,
                  "height":880},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFC9C9C9}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/新闻详细页/u41.png"}},
{
          "id":"7cfa77947aee4e5e9b210af13e3b2eb3",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":200,
              "y":400},
            "size":{
              "width":210,
              "height":320},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFC9C9C9}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3d7465a49b8445bc9fb2dd217bea94e1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":200,
                  "y":400},
                "size":{
                  "width":210,
                  "height":320},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFC9C9C9}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/新闻列表/u43.png"}},
{
          "id":"014cc8270ca2409d8a662a8b06af551a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"14px",
            "fontWeight":"700",
            "location":{
              "x":210,
              "y":414},
            "size":{
              "width":70,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6ce73803718440fca5a04296611e4b30",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"14px",
                "fontWeight":"700",
                "location":{
                  "x":210,
                  "y":414},
                "size":{
                  "width":70,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"defd5edc00314d47a5505444784a9876",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":210,
              "y":440},
            "size":{
              "width":190,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8379752dfbf540d686bfd5d2bdf71ae4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":210,
                  "y":440},
                "size":{
                  "width":190,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3dbf1da7b40a404daafd3d378021246f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":210,
              "y":470},
            "size":{
              "width":190,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6d0c0a9468a0420b9241c9ae569d87c6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":210,
                  "y":470},
                "size":{
                  "width":190,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ef510bf7109c4bd0940167f2ea357061",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":210,
              "y":501},
            "size":{
              "width":190,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2453117aa4544fd8a2bce33024d31b26",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":210,
                  "y":501},
                "size":{
                  "width":190,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"574d9ddb508d4a6d9cf34f099890f7fd",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":210,
              "y":532},
            "size":{
              "width":190,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e19fb4c2e6bd4ebf937c19637bea3710",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":210,
                  "y":532},
                "size":{
                  "width":190,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d0fd84d5cb974065950989d43f342222",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":210,
              "y":562},
            "size":{
              "width":190,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"952b8dcc761846c9865e694bdd3105f1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":210,
                  "y":562},
                "size":{
                  "width":190,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2cac2f2ab63a46da8de34cd268906c04",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":210,
              "y":592},
            "size":{
              "width":190,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d55811fb0f294d5a9a58402fad6ab4d8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":210,
                  "y":592},
                "size":{
                  "width":190,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"497bb1f4438b42f5b1497f8d8407530f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":210,
              "y":623},
            "size":{
              "width":190,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"38085d4b00e4476d9f1a076960f511d7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":210,
                  "y":623},
                "size":{
                  "width":190,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"fac145369c494b96bdc82046971a6e95",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":210,
              "y":654},
            "size":{
              "width":190,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"89d327ebc2bd45daa708d48582198536",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":210,
                  "y":654},
                "size":{
                  "width":190,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d8491f6500d24e3ca76b6f4530d30a6d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":210,
              "y":684},
            "size":{
              "width":190,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5f313da786d049bfa7f2c85081b07b44",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":210,
                  "y":684},
                "size":{
                  "width":190,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6745f4f6a6ce45b3bd0a3809f9e8b4fd",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "horizontalAlignment":"center",
            "location":{
              "x":552,
              "y":249},
            "size":{
              "width":536,
              "height":19},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b215a43f0cd64456a312d5e0b98cb117",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "horizontalAlignment":"center",
                "location":{
                  "x":552,
                  "y":249},
                "size":{
                  "width":536,
                  "height":19},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d4452319c8e944e1a276dd5c5fb758b2",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "horizontalAlignment":"center",
            "location":{
              "x":660,
              "y":278},
            "size":{
              "width":320,
              "height":15},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"744150829f8c4363b021d9895b9cae27",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "horizontalAlignment":"center",
                "location":{
                  "x":660,
                  "y":278},
                "size":{
                  "width":320,
                  "height":15},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"11a2672da505419b943580d1ab9c0f17",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":460,
              "y":300},
            "size":{
              "width":719,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFD7D7D7},
            "linePattern":"dashed"},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/新闻详细页/u69_line.png"}},
{
          "id":"0683bdeac6dc41d8b6cf1a23e4849286",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"center",
            "location":{
              "x":780,
              "y":552},
            "size":{
              "width":79,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"46b28af094a747669e88d714783daf32",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "location":{
                  "x":780,
                  "y":552},
                "size":{
                  "width":79,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"889edb59417247bc89ba4ec07d1aefaa",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":458,
              "y":1048},
            "size":{
              "width":719,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFD7D7D7},
            "linePattern":"dashed"},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/新闻详细页/u69_line.png"}},
{
          "id":"876457ada53b496f83c4173d9b2f0fb8",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":458,
              "y":1063},
            "size":{
              "width":290,
              "height":16},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"eb6926bca2504fa5b68779f0a6418d42",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":458,
                  "y":1063},
                "size":{
                  "width":290,
                  "height":16},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c962f10e79df448ba32fdea48acdf50a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"right",
            "location":{
              "x":887,
              "y":1063},
            "size":{
              "width":290,
              "height":16},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"339cd8808f114b2998139be4bdcc3a6d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"right",
                "location":{
                  "x":887,
                  "y":1063},
                "size":{
                  "width":290,
                  "height":16},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
    "496537f1e3d34e84bff1d3b9cc7d3781":{
      "packageId":"496537f1e3d34e84bff1d3b9cc7d3781",
      "type":"Axure:Master",
      "name":"物流头部",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"应用字体",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"be355ce83e944039947e531f2a3c65bf",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":0,
                "y":150},
              "size":{
                "width":1400,
                "height":40},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFD7D7D7}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"7ad610fe1fd94f489f35d1adf33b9af1",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":0,
                    "y":150},
                  "size":{
                    "width":1400,
                    "height":40},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFD7D7D7}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/首页/u13.png"}},
{
            "id":"aa3cf84e2bbd46a28151af5ccb7dfbf6",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fontName":"'微软雅黑 Regular', '微软雅黑'",
              "location":{
                "x":325,
                "y":150},
              "size":{
                "width":125,
                "height":40},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFD7D7D7}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"cf98c532bd864dcc8adeb788cba04559",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'微软雅黑 Regular', '微软雅黑'",
                  "location":{
                    "x":325,
                    "y":150},
                  "size":{
                    "width":125,
                    "height":40},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFD7D7D7}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/物流/u9.png"}},
{
            "id":"6007835eb6e94566a4ce3334bd18ac62",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fontName":"'微软雅黑 Regular', '微软雅黑'",
              "location":{
                "x":450,
                "y":150},
              "size":{
                "width":125,
                "height":40},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFD7D7D7}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"384a059abd7b46e298aafb2cd9c43187",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'微软雅黑 Regular', '微软雅黑'",
                  "location":{
                    "x":450,
                    "y":150},
                  "size":{
                    "width":125,
                    "height":40},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFD7D7D7}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/物流/u9.png"}},
{
            "id":"7c9058fa398c4796a04243c49a790a49",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fontName":"'微软雅黑 Regular', '微软雅黑'",
              "location":{
                "x":575,
                "y":150},
              "size":{
                "width":125,
                "height":40},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFD7D7D7}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"438b60b6102f4768af4f0703a5815f11",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'微软雅黑 Regular', '微软雅黑'",
                  "location":{
                    "x":575,
                    "y":150},
                  "size":{
                    "width":125,
                    "height":40},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFD7D7D7}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/物流/u9.png"}},
{
            "id":"d4dbd3f981904f4fa63897125413dd32",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fontName":"'微软雅黑 Regular', '微软雅黑'",
              "location":{
                "x":825,
                "y":150},
              "size":{
                "width":125,
                "height":40},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFD7D7D7}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"609d5aa69b7f4e68b5e6717d43d879bd",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'微软雅黑 Regular', '微软雅黑'",
                  "location":{
                    "x":825,
                    "y":150},
                  "size":{
                    "width":125,
                    "height":40},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFD7D7D7}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/物流/u9.png"}},
{
            "id":"8a3db1216f984f9cb223ca8379348c88",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fontName":"'微软雅黑 Regular', '微软雅黑'",
              "location":{
                "x":700,
                "y":150},
              "size":{
                "width":125,
                "height":40},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFD7D7D7}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"156ee2878c014482ad208a835bfdfd57",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'微软雅黑 Regular', '微软雅黑'",
                  "location":{
                    "x":700,
                    "y":150},
                  "size":{
                    "width":125,
                    "height":40},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFD7D7D7}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/物流/u9.png"}},
{
            "id":"a982eb6988b44874aec2f7a7563f3bbc",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fontName":"'微软雅黑 Regular', '微软雅黑'",
              "location":{
                "x":200,
                "y":150},
              "size":{
                "width":125,
                "height":40},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFD7D7D7}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"3c448fc8af0f4a8e9fb1b5c15b818d05",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'微软雅黑 Regular', '微软雅黑'",
                  "location":{
                    "x":200,
                    "y":150},
                  "size":{
                    "width":125,
                    "height":40},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFD7D7D7}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/物流/u9.png"}},
{
            "id":"dfba4f993e4e48d4b2d57c920a9037ef",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fontName":"'微软雅黑 Regular', '微软雅黑'",
              "location":{
                "x":950,
                "y":150},
              "size":{
                "width":125,
                "height":40},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFD7D7D7}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"3a4567cc67374e3d95142abc1567d0bd",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'微软雅黑 Regular', '微软雅黑'",
                  "location":{
                    "x":950,
                    "y":150},
                  "size":{
                    "width":125,
                    "height":40},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFD7D7D7}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/物流/u9.png"}},
{
            "id":"28346d4547e147abb42f1e03fe9d2d51",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fontName":"'微软雅黑 Regular', '微软雅黑'",
              "location":{
                "x":1075,
                "y":150},
              "size":{
                "width":125,
                "height":40},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFD7D7D7}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"11a8cd2c460a4915858ba5e52d96207c",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'微软雅黑 Regular', '微软雅黑'",
                  "location":{
                    "x":1075,
                    "y":150},
                  "size":{
                    "width":125,
                    "height":40},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFD7D7D7}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/物流/u9.png"}},
{
            "id":"774e6c3744c644c2bd17b7fa7892feac",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFFF8F8F8},
              "size":{
                "width":1400,
                "height":35},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFD7D7D7}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"f9137a915a3f4fc2b4388e5d7f1767ba",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFF8F8F8},
                  "size":{
                    "width":1400,
                    "height":35},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFD7D7D7}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/物流/u25.png"}},
{
            "id":"148da07c87f142879097b9a411344180",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "location":{
                "x":200,
                "y":10},
              "size":{
                "width":340,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"4d20535595e94f17ba4488bc15e48676",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":200,
                    "y":10},
                  "size":{
                    "width":340,
                    "height":16}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"56f736c3d24947ab9a3e62c329fd19a4",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontName":"'微软雅黑 Regular', '微软雅黑'",
              "horizontalAlignment":"right",
              "location":{
                "x":660,
                "y":6},
              "size":{
                "width":540,
                "height":19}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"2bef87c6b612443d814a873ce10c6e28",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'微软雅黑 Regular', '微软雅黑'",
                  "horizontalAlignment":"right",
                  "location":{
                    "x":660,
                    "y":6},
                  "size":{
                    "width":540,
                    "height":19}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"315dd3063b454753b9694c00bdb7bac0",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":200,
                "y":50},
              "size":{
                "width":150,
                "height":70},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFD7D7D7}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"e3835d78c26e4225b56136c0f7cee8e9",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":200,
                    "y":50},
                  "size":{
                    "width":150,
                    "height":70},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFD7D7D7}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/物流/u31.png"}},
{
            "id":"2ffd3ddb833f48348e4ffdbba2c2ba86",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontSize":"24px",
              "location":{
                "x":370,
                "y":77},
              "size":{
                "width":130,
                "height":28}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"428b4de1cfa54a9794166f743cdd9895",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"24px",
                  "location":{
                    "x":370,
                    "y":77},
                  "size":{
                    "width":130,
                    "height":28}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}}]}},
    "526482f429714d2da20c04d5a7d4329e":{
      "packageId":"526482f429714d2da20c04d5a7d4329e",
      "type":"Axure:Master",
      "name":"物流底部",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"应用字体",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"6d839a3937d045bf813b8be7d50e2149",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFFE4E4E4},
              "location":{
                "x":0,
                "y":5},
              "size":{
                "width":1400,
                "height":100},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFD7D7D7}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"960f638a92ca40d4bab16f14077f2f59",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFE4E4E4},
                  "location":{
                    "x":0,
                    "y":5},
                  "size":{
                    "width":1400,
                    "height":100},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFD7D7D7}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/物流/u1.png"}},
{
            "id":"90d533b4c8c24b3883b34a888ba79377",
            "label":"",
            "type":"horizontalLine",
            "styleType":"horizontalLine",
            "visible":true,
            "style":{
              "size":{
                "width":1400,
                "height":10},
              "borderWidth":"2",
              "borderFill":{
                "fillType":"solid",
                "color":0xFFD7D7D7}},
            "adaptiveStyles":{
},
            "images":{
              "start~":"resources/images/transparent.gif",
              "end~":"resources/images/transparent.gif",
              "line~":"images/物流/u3_line.png"}},
{
            "id":"1a689a258f484998bcd2508e44f2c22d",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "horizontalAlignment":"center",
              "lineSpacing":"20px",
              "location":{
                "x":346,
                "y":35},
              "size":{
                "width":708,
                "height":40}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"ea03187483ce4b12a1e0624a4f493d0a",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "horizontalAlignment":"center",
                  "lineSpacing":"20px",
                  "location":{
                    "x":346,
                    "y":35},
                  "size":{
                    "width":708,
                    "height":40}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}}]}}},
  "objectPaths":{
    "1067a21d19fc4f39af29aef9415a174b":{
      "scriptId":"u0",
      "be355ce83e944039947e531f2a3c65bf":{
        "scriptId":"u1"},
      "7ad610fe1fd94f489f35d1adf33b9af1":{
        "scriptId":"u2"},
      "aa3cf84e2bbd46a28151af5ccb7dfbf6":{
        "scriptId":"u3"},
      "cf98c532bd864dcc8adeb788cba04559":{
        "scriptId":"u4"},
      "6007835eb6e94566a4ce3334bd18ac62":{
        "scriptId":"u5"},
      "384a059abd7b46e298aafb2cd9c43187":{
        "scriptId":"u6"},
      "7c9058fa398c4796a04243c49a790a49":{
        "scriptId":"u7"},
      "438b60b6102f4768af4f0703a5815f11":{
        "scriptId":"u8"},
      "d4dbd3f981904f4fa63897125413dd32":{
        "scriptId":"u9"},
      "609d5aa69b7f4e68b5e6717d43d879bd":{
        "scriptId":"u10"},
      "8a3db1216f984f9cb223ca8379348c88":{
        "scriptId":"u11"},
      "156ee2878c014482ad208a835bfdfd57":{
        "scriptId":"u12"},
      "a982eb6988b44874aec2f7a7563f3bbc":{
        "scriptId":"u13"},
      "3c448fc8af0f4a8e9fb1b5c15b818d05":{
        "scriptId":"u14"},
      "dfba4f993e4e48d4b2d57c920a9037ef":{
        "scriptId":"u15"},
      "3a4567cc67374e3d95142abc1567d0bd":{
        "scriptId":"u16"},
      "28346d4547e147abb42f1e03fe9d2d51":{
        "scriptId":"u17"},
      "11a8cd2c460a4915858ba5e52d96207c":{
        "scriptId":"u18"},
      "774e6c3744c644c2bd17b7fa7892feac":{
        "scriptId":"u19"},
      "f9137a915a3f4fc2b4388e5d7f1767ba":{
        "scriptId":"u20"},
      "148da07c87f142879097b9a411344180":{
        "scriptId":"u21"},
      "4d20535595e94f17ba4488bc15e48676":{
        "scriptId":"u22"},
      "56f736c3d24947ab9a3e62c329fd19a4":{
        "scriptId":"u23"},
      "2bef87c6b612443d814a873ce10c6e28":{
        "scriptId":"u24"},
      "315dd3063b454753b9694c00bdb7bac0":{
        "scriptId":"u25"},
      "e3835d78c26e4225b56136c0f7cee8e9":{
        "scriptId":"u26"},
      "2ffd3ddb833f48348e4ffdbba2c2ba86":{
        "scriptId":"u27"},
      "428b4de1cfa54a9794166f743cdd9895":{
        "scriptId":"u28"}},
    "920a75aa67b84d4ea359f7b04aabbe27":{
      "scriptId":"u29",
      "6d839a3937d045bf813b8be7d50e2149":{
        "scriptId":"u30"},
      "960f638a92ca40d4bab16f14077f2f59":{
        "scriptId":"u31"},
      "90d533b4c8c24b3883b34a888ba79377":{
        "scriptId":"u32"},
      "1a689a258f484998bcd2508e44f2c22d":{
        "scriptId":"u33"},
      "ea03187483ce4b12a1e0624a4f493d0a":{
        "scriptId":"u34"}},
    "1afca48492a54d12ae30468c46b2bd56":{
      "scriptId":"u35"},
    "00d5ea614fb24d82851ea247c67f88b6":{
      "scriptId":"u36"},
    "335f42643de443d086e8b9374e24dd19":{
      "scriptId":"u37"},
    "fbfdeb14db77437f9ccad9695c4c4e71":{
      "scriptId":"u38"},
    "c0240e3c80d645abbf74225bd1334907":{
      "scriptId":"u39"},
    "e3673d7570b64c4b9e8fd976b6449d1d":{
      "scriptId":"u40"},
    "b06941e7f45d418b8265f72daf60cf91":{
      "scriptId":"u41"},
    "c77808d2d7094daaa78142e32f6d0ccf":{
      "scriptId":"u42"},
    "7cfa77947aee4e5e9b210af13e3b2eb3":{
      "scriptId":"u43"},
    "3d7465a49b8445bc9fb2dd217bea94e1":{
      "scriptId":"u44"},
    "014cc8270ca2409d8a662a8b06af551a":{
      "scriptId":"u45"},
    "6ce73803718440fca5a04296611e4b30":{
      "scriptId":"u46"},
    "defd5edc00314d47a5505444784a9876":{
      "scriptId":"u47"},
    "8379752dfbf540d686bfd5d2bdf71ae4":{
      "scriptId":"u48"},
    "3dbf1da7b40a404daafd3d378021246f":{
      "scriptId":"u49"},
    "6d0c0a9468a0420b9241c9ae569d87c6":{
      "scriptId":"u50"},
    "ef510bf7109c4bd0940167f2ea357061":{
      "scriptId":"u51"},
    "2453117aa4544fd8a2bce33024d31b26":{
      "scriptId":"u52"},
    "574d9ddb508d4a6d9cf34f099890f7fd":{
      "scriptId":"u53"},
    "e19fb4c2e6bd4ebf937c19637bea3710":{
      "scriptId":"u54"},
    "d0fd84d5cb974065950989d43f342222":{
      "scriptId":"u55"},
    "952b8dcc761846c9865e694bdd3105f1":{
      "scriptId":"u56"},
    "2cac2f2ab63a46da8de34cd268906c04":{
      "scriptId":"u57"},
    "d55811fb0f294d5a9a58402fad6ab4d8":{
      "scriptId":"u58"},
    "497bb1f4438b42f5b1497f8d8407530f":{
      "scriptId":"u59"},
    "38085d4b00e4476d9f1a076960f511d7":{
      "scriptId":"u60"},
    "fac145369c494b96bdc82046971a6e95":{
      "scriptId":"u61"},
    "89d327ebc2bd45daa708d48582198536":{
      "scriptId":"u62"},
    "d8491f6500d24e3ca76b6f4530d30a6d":{
      "scriptId":"u63"},
    "5f313da786d049bfa7f2c85081b07b44":{
      "scriptId":"u64"},
    "6745f4f6a6ce45b3bd0a3809f9e8b4fd":{
      "scriptId":"u65"},
    "b215a43f0cd64456a312d5e0b98cb117":{
      "scriptId":"u66"},
    "d4452319c8e944e1a276dd5c5fb758b2":{
      "scriptId":"u67"},
    "744150829f8c4363b021d9895b9cae27":{
      "scriptId":"u68"},
    "11a2672da505419b943580d1ab9c0f17":{
      "scriptId":"u69"},
    "0683bdeac6dc41d8b6cf1a23e4849286":{
      "scriptId":"u70"},
    "46b28af094a747669e88d714783daf32":{
      "scriptId":"u71"},
    "889edb59417247bc89ba4ec07d1aefaa":{
      "scriptId":"u72"},
    "876457ada53b496f83c4173d9b2f0fb8":{
      "scriptId":"u73"},
    "eb6926bca2504fa5b68779f0a6418d42":{
      "scriptId":"u74"},
    "c962f10e79df448ba32fdea48acdf50a":{
      "scriptId":"u75"},
    "339cd8808f114b2998139be4bdcc3a6d":{
      "scriptId":"u76"}}});