$axure.loadCurrentPage({
  "url":"审核.html",
  "generationDate":new Date(1432872278789.56),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"7eaf6a72fc6f452282ce70c202050739",
    "type":"Axure:Page",
    "name":"审核",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"a2517fa6cd9c454799f9ac06bade023e",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":1120}},
          "adaptiveStyles":{
},
          "masterId":"9aa3da306ba24637b281c884b1c30bca"},
{
          "id":"ae8c37fe0fd84aeb87b697befc737f57",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":420,
              "y":150},
            "size":{
              "width":780,
              "height":820},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFD7D7D7}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"331ca0a1eca94c67908a13ff95849187",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":420,
                  "y":150},
                "size":{
                  "width":780,
                  "height":820},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/审核/u3.png"}},
{
          "id":"49986a3ab88a4cf39d5bbe33d52e3dfd",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":450,
              "y":159},
            "size":{
              "width":480,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2706d45dd1bd495588a9a449ac5034d8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":450,
                  "y":159},
                "size":{
                  "width":480,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1d754b4eaac84803ac101c31bf6ba52e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":530,
              "y":200},
            "size":{
              "width":160,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3fabee892de448b7a910a4fc56133556",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":530,
                  "y":200},
                "size":{
                  "width":160,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"887179836f10461c8c4fdb94b3773815",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":450,
              "y":466},
            "size":{
              "width":200,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"25781352871745b28f2e010290c00197",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":450,
                  "y":466},
                "size":{
                  "width":200,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"143cf445a40845f2aa24fc93c88f0fb3",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":450,
              "y":234},
            "size":{
              "width":200,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8308c4b6661a49afa3a15e4635335c5c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":450,
                  "y":234},
                "size":{
                  "width":200,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"21edd9f4efe045478494f1d0c001719e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":450,
              "y":269},
            "size":{
              "width":200,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2d05e7b6584b4c7485ed9ff06c8a2c5e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":450,
                  "y":269},
                "size":{
                  "width":200,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b961ab3312f24fd1ad2e6bdb2c1495de",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":450,
              "y":306},
            "size":{
              "width":200,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dd75b008452a41398358630dfe47c5f1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":450,
                  "y":306},
                "size":{
                  "width":200,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e027785fcb344d27bcb2d2091a6a8690",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":450,
              "y":341},
            "size":{
              "width":200,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"545edb442fe64cd49cedea7fc1ea11f2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":450,
                  "y":341},
                "size":{
                  "width":200,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c1f7fa68745841b5a67d964f7c5b8cdd",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":450,
              "y":379},
            "size":{
              "width":200,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ce5ef9fee3804276b65b610eef0176c3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":450,
                  "y":379},
                "size":{
                  "width":200,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a7e700aeca9340778d6ee4a7608c3194",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":450,
              "y":418},
            "size":{
              "width":200,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"56f784aa25674ccdab3012b40334a27b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":450,
                  "y":418},
                "size":{
                  "width":200,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d2fb599d39214d4cbbcfbcfa1433619c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":450,
              "y":681},
            "size":{
              "width":176,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8c921ad1f2ff4c53ab4048d05a20b92d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":450,
                  "y":681},
                "size":{
                  "width":176,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"fef1ddcaf8c64756a25d775280ce7bf5",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":450,
              "y":648},
            "size":{
              "width":200,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bdc4162dbeec439bbb6c0f8a06e20fe9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":450,
                  "y":648},
                "size":{
                  "width":200,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0b8b369eca8243fd891336298f029b57",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":450,
              "y":589},
            "size":{
              "width":200,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d773f7b0461e4b9dac133306fbef3c91",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":450,
                  "y":589},
                "size":{
                  "width":200,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2ba6ef0abf794933ad8479dc7f2836b2",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":450,
              "y":619},
            "size":{
              "width":200,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7b3119b89ca3414685b38f00bb32696f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":450,
                  "y":619},
                "size":{
                  "width":200,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e561a0ae4b6f454686edbf645cc876d6",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "lineSpacing":"20px",
            "location":{
              "x":530,
              "y":466},
            "size":{
              "width":640,
              "height":80}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b76e5444821941db9f83b62650919cd8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "lineSpacing":"20px",
                "location":{
                  "x":530,
                  "y":466},
                "size":{
                  "width":640,
                  "height":80}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a50d8810ae154a2da2c532878831f0d7",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":530,
              "y":234},
            "size":{
              "width":200,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f2cc5793b4124bf9a79b7bf19b6aef67",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":530,
                  "y":234},
                "size":{
                  "width":200,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b8a75cb037164418aaf918bcb2ab6b5c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":530,
              "y":269},
            "size":{
              "width":200,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5f18b1c1e67a4101ba3eee0cd743dc52",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":530,
                  "y":269},
                "size":{
                  "width":200,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"824e9ea209ee4c7cb7a43aa15b6dc0f9",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":530,
              "y":306},
            "size":{
              "width":200,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"17ef8fb2644e40ca8a97ca3a83d875f9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":530,
                  "y":306},
                "size":{
                  "width":200,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e32cc5c064f04bb0a778b58ed4d73291",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":530,
              "y":341},
            "size":{
              "width":200,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"da04171506d34f439efd938917a2a787",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":530,
                  "y":341},
                "size":{
                  "width":200,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b88ba9e6d4b04ba5908008ef6f395d66",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":530,
              "y":379},
            "size":{
              "width":200,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"aa266d9c1e014cb8853510b71bb61b65",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":530,
                  "y":379},
                "size":{
                  "width":200,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"78f79bda2c0f4006bf7271d4f3180fd0",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":530,
              "y":418},
            "size":{
              "width":200,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0698368f529e4db58b167eebaf2a0681",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":530,
                  "y":418},
                "size":{
                  "width":200,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"49b8fd962c364ee198c85a900931c0fe",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":530,
              "y":648},
            "size":{
              "width":410,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3d055436781c4e1ba89207721f690d82",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":530,
                  "y":648},
                "size":{
                  "width":410,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f62d3ac518ec40cfb615fc080299d9dc",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":530,
              "y":589},
            "size":{
              "width":200,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0a0a7b7c8f054cdcbc466e9c5ae011d7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":530,
                  "y":589},
                "size":{
                  "width":200,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9a59e6466ba14d76b345f40bb209104e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":530,
              "y":619},
            "size":{
              "width":200,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5cdfb1ebcaee433f9d5c8631008a2a13",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":530,
                  "y":619},
                "size":{
                  "width":200,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c2b26a412c304368b183aa353e918233",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":540,
              "y":681},
            "size":{
              "width":410,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3c660dcf463644dc9fe2a49d82208fdf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":540,
                  "y":681},
                "size":{
                  "width":410,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a4172139ce284fa6af4bd668d50b73b8",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"700",
            "location":{
              "x":450,
              "y":727},
            "size":{
              "width":200,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c6a77c1893964d9986261462be35d317",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"700",
                "location":{
                  "x":450,
                  "y":727},
                "size":{
                  "width":200,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"cab3615c0a1a414cbd2447493d790a2b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":450,
              "y":772},
            "size":{
              "width":200,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"173265315222436f86bbdd77665ed6ed",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":450,
                  "y":772},
                "size":{
                  "width":200,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"67af3a05445c41949a329473a6e285e0",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":450,
              "y":807},
            "size":{
              "width":200,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7ddcf972df3b4ed9b4dcd474c73866cb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":450,
                  "y":807},
                "size":{
                  "width":200,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7653eb9ac6f545a98a86af98fd765a40",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":450,
              "y":843},
            "size":{
              "width":200,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"29f63f3e7b2d4cff9a27cc81b99b1fc6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":450,
                  "y":843},
                "size":{
                  "width":200,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"64d34d67a8a5425aaf44db17d857c97a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":530,
              "y":772},
            "size":{
              "width":200,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ba8bf2de126c447386482135a9d2b272",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":530,
                  "y":772},
                "size":{
                  "width":200,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b00c9c4253aa4de5bdc45f801880812d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":530,
              "y":807},
            "size":{
              "width":200,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"de65043e03fb437cb6267ae5ece1144f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":530,
                  "y":807},
                "size":{
                  "width":200,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"bbc8aeb3050c460892ac2b6d9a858391",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":530,
              "y":843},
            "size":{
              "width":200,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"de347bf8c79747378aaa73a0dc7f2e93",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":530,
                  "y":843},
                "size":{
                  "width":200,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b1e981c9388e476d9a511fc24107c44a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":450,
              "y":200},
            "size":{
              "width":200,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dbf57be7e72049dca96fb8b4a9471fea",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":450,
                  "y":200},
                "size":{
                  "width":200,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"21a7b0fdc8794616b750016869efc4a4",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontWeight":"700",
            "location":{
              "x":420,
              "y":995},
            "size":{
              "width":218,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"12dbcf80001844efae7c8d3164032876",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"700",
                "location":{
                  "x":420,
                  "y":995},
                "size":{
                  "width":218,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"35b33af5eb9e4cd49794468261591432",
          "label":"",
          "type":"table",
          "styleType":"table",
          "visible":true,
          "style":{
            "location":{
              "x":420,
              "y":1021},
            "size":{
              "width":780,
              "height":77}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e0076b26e4634073b5c6227cf3ceb303",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"700",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "size":{
                  "width":153,
                  "height":35},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"ee70cf7bca744badbdffedf59f15f1ca",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Arial Negreta', 'Arial'",
                    "fontWeight":"700",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFF2F2F2},
                    "size":{
                      "width":153,
                      "height":35},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFD7D7D7}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/标准单详情/u356.png"}},
{
              "id":"7889bc0033794e86a4de38a657c11fcf",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":35},
                "size":{
                  "width":153,
                  "height":42},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"1a4a2461bfdf4a1d8765427232ba104c",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":35},
                    "size":{
                      "width":153,
                      "height":42},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFD7D7D7}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/标准单详情/u362.png"}},
{
              "id":"6ab116c0c6e1410e846a6d99e6ffaa63",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"700",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":153,
                  "y":0},
                "size":{
                  "width":140,
                  "height":35},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"133b034c85ee430ba03f240a9da3b8bc",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Arial Negreta', 'Arial'",
                    "fontWeight":"700",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFF2F2F2},
                    "location":{
                      "x":153,
                      "y":0},
                    "size":{
                      "width":140,
                      "height":35},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFD7D7D7}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/标准单详情/u358.png"}},
{
              "id":"b47042d89d2b4dd1a63bf08a5bef35ef",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "verticalAlignment":"middle",
                "location":{
                  "x":153,
                  "y":35},
                "size":{
                  "width":140,
                  "height":42},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"a9e1e029e71044feb6fe96459fbd1e9a",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "verticalAlignment":"middle",
                    "location":{
                      "x":153,
                      "y":35},
                    "size":{
                      "width":140,
                      "height":42},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFD7D7D7}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/标准单详情/u364.png"}},
{
              "id":"6755f8439aea4461b4af683c29445fc1",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"700",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":293,
                  "y":0},
                "size":{
                  "width":487,
                  "height":35},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"99e373abcfdc4378b144f7b1d94e0ec0",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Arial Negreta', 'Arial'",
                    "fontWeight":"700",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFF2F2F2},
                    "location":{
                      "x":293,
                      "y":0},
                    "size":{
                      "width":487,
                      "height":35},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFD7D7D7}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/标准单详情/u360.png"}},
{
              "id":"f5f36f95269b4741a99b44ecce727e83",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "verticalAlignment":"middle",
                "location":{
                  "x":293,
                  "y":35},
                "size":{
                  "width":487,
                  "height":42},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"03d68a2232a749e3986886d774bca051",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "verticalAlignment":"middle",
                    "location":{
                      "x":293,
                      "y":35},
                    "size":{
                      "width":487,
                      "height":42},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFD7D7D7}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/标准单详情/u366.png"}}]},
{
          "id":"0ef794c370fd44f4bc0925928d2c6743",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
},
          "adaptiveStyles":{
},
          "masterId":"d46401a06c1e4b89b7df1b25949937b2"},
{
          "id":"ff8a9e850db948598048d9834efae4de",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":200,
              "y":150},
            "size":{
              "width":200,
              "height":80},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFD7D7D7}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f87c6af5307c49859c0cee563df66b70",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":200,
                  "y":150},
                "size":{
                  "width":200,
                  "height":80},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的工作台/u26.png"}},
{
          "id":"2d2acd6123af4bf0922f91f1546b0fc6",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":200,
              "y":230},
            "size":{
              "width":200,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFD7D7D7}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5a9d7009aa5a479e8978589d9f241ac2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":200,
                  "y":230},
                "size":{
                  "width":200,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的工作台/u30.png"}},
{
          "id":"8609f723f48b48788372361fd09ea218",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFE4E4E4},
            "location":{
              "x":200,
              "y":270},
            "size":{
              "width":200,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFD7D7D7}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7ae4d2b13ece43ca9f6ddaa8b9397892",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4},
                "location":{
                  "x":200,
                  "y":270},
                "size":{
                  "width":200,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的工作台/u28.png"}},
{
          "id":"30ae93a51fc14f449e527781436abc63",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":200,
              "y":430},
            "size":{
              "width":200,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFD7D7D7}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"af8c6af365c740d2905d5c75c5959be8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":200,
                  "y":430},
                "size":{
                  "width":200,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的工作台/u30.png"}},
{
          "id":"62689d74bad04aa2988a039e306b8840",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "fill":{
              "fillType":"solid",
              "color":0xFFE4E4E4},
            "location":{
              "x":210,
              "y":310},
            "size":{
              "width":190,
              "height":30},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFD7D7D7}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3ea91febe18a446984f01fb29afc302c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4},
                "location":{
                  "x":210,
                  "y":310},
                "size":{
                  "width":190,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/管理资源单/u233.png"}},
{
          "id":"215f2cc34c8e43acb04d3521499ddfec",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "location":{
              "x":210,
              "y":340},
            "size":{
              "width":190,
              "height":30},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFD7D7D7}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9e885e3ef0424a138035f529bb30d961",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "location":{
                  "x":210,
                  "y":340},
                "size":{
                  "width":190,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/管理资源单/u235.png"}},
{
          "id":"ce3a8b1e87cb48fb91b5a8a1a9597ee3",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "location":{
              "x":210,
              "y":370},
            "size":{
              "width":190,
              "height":30},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFD7D7D7}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"46c62a1158ce4285bc928969fb17e04e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "location":{
                  "x":210,
                  "y":370},
                "size":{
                  "width":190,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/管理资源单/u235.png"}},
{
          "id":"79c41eb06fc844d89825e3855e2f613a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "location":{
              "x":210,
              "y":400},
            "size":{
              "width":190,
              "height":30},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFD7D7D7}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"da0cd8c7aa3c4f10a42e62733840969a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "location":{
                  "x":210,
                  "y":400},
                "size":{
                  "width":190,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/管理资源单/u235.png"}},
{
          "id":"ae71a36b9c1e407399fd9f242bcca52b",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF008000,
              "opacity":1},
            "location":{
              "x":450,
              "y":900},
            "size":{
              "width":140,
              "height":40}},
          "adaptiveStyles":{
}},
{
          "id":"d778bfd6aed04b388e9805e89678f57c",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":610,
              "y":900},
            "size":{
              "width":150,
              "height":40}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 修改发布",
                      "target":{
                        "targetType":"page",
                        "url":"修改发布_1.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"658278b5e37943979e59e5df84da752b",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":780,
              "y":900},
            "size":{
              "width":180,
              "height":40}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示 关闭采购单",
                      "objectsToFades":[{
                          "objectPath":["c3085183fff7414586efd331bb46f069"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}}]}]}]}},
          "tabbable":true},
{
          "id":"c3085183fff7414586efd331bb46f069",
          "label":"关闭采购单",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":false,
          "style":{
            "location":{
              "x":604,
              "y":580},
            "size":{
              "width":10,
              "height":10},
            "visible":false},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":true,
          "propagate":false,
          "diagrams":[{
              "id":"898d0fdee59442c9b0072c05e9093e2c",
              "label":"状态1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"959ca5d035e44c18bd60653ee629398a",
                  "label":"",
                  "parentDynamicPanel":"c3085183fff7414586efd331bb46f069",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":472,
                      "height":270},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFD7D7D7}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"e19c1671b17d44a391339ba97cca74d2",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"c3085183fff7414586efd331bb46f069",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":472,
                          "height":270},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFD7D7D7}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/供应管理/u211.png"}},
{
                  "id":"bd369c9a54ec40cb88d9faf720f2ffd9",
                  "label":"",
                  "parentDynamicPanel":"c3085183fff7414586efd331bb46f069",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":16,
                      "y":28},
                    "size":{
                      "width":110,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"c1588e99c7944d7286b9fc276a7f3d68",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"c3085183fff7414586efd331bb46f069",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":16,
                          "y":28},
                        "size":{
                          "width":110,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"35d4f70da3894442b018691f86205729",
                  "label":"",
                  "parentDynamicPanel":"c3085183fff7414586efd331bb46f069",
                  "type":"comboBox",
                  "styleType":"comboBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":92,
                      "y":24},
                    "size":{
                      "width":163,
                      "height":22}},
                  "adaptiveStyles":{
}},
{
                  "id":"f3bc118f1a604e7ab550c536c9f1b1b4",
                  "label":"",
                  "parentDynamicPanel":"c3085183fff7414586efd331bb46f069",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":92,
                      "y":62},
                    "size":{
                      "width":295,
                      "height":122},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFD7D7D7}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"e9682ce2332a486892ef45fe5c72a88c",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"c3085183fff7414586efd331bb46f069",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":92,
                          "y":62},
                        "size":{
                          "width":295,
                          "height":122},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFD7D7D7}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/供应管理/u216.png"}},
{
                  "id":"7f1efc7505334e4c8e45fab963631c85",
                  "label":"",
                  "parentDynamicPanel":"c3085183fff7414586efd331bb46f069",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":16,
                      "y":62},
                    "size":{
                      "width":110,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"c477479c0a114aacb20d7248bce22ef1",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"c3085183fff7414586efd331bb46f069",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":16,
                          "y":62},
                        "size":{
                          "width":110,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"8bf64f156bb142789919324bcbac4b85",
                  "label":"",
                  "parentDynamicPanel":"c3085183fff7414586efd331bb46f069",
                  "type":"button",
                  "styleType":"button",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":92,
                      "y":206},
                    "size":{
                      "width":100,
                      "height":35}},
                  "adaptiveStyles":{
},
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"fadeWidget",
                              "description":"隐藏 关闭采购单",
                              "objectsToFades":[{
                                  "objectPath":["c3085183fff7414586efd331bb46f069"],
                                  "fadeInfo":{
                                    "fadeType":"hide",
                                    "options":{
                                      "showType":"none"}}}]}]}]}},
                  "tabbable":true}]}]}]}},
  "masters":{
    "9aa3da306ba24637b281c884b1c30bca":{
      "packageId":"9aa3da306ba24637b281c884b1c30bca",
      "type":"Axure:Master",
      "name":"交易员底部",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"应用字体",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"aa94056b817049cbb1fa6bacb8c1e519",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "size":{
                "width":1400,
                "height":40},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFD7D7D7}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"d0f70829d22f42fea545dfa7923b52be",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "size":{
                    "width":1400,
                    "height":40},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFD7D7D7}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/首页/u13.png"}}]}},
    "d46401a06c1e4b89b7df1b25949937b2":{
      "packageId":"d46401a06c1e4b89b7df1b25949937b2",
      "type":"Axure:Master",
      "name":"交易员头部--采购",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"应用字体",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"11a2262448e0441f9a29e02867462317",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "size":{
                "width":1400,
                "height":90},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFD7D7D7}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"2fb6fec02a5946deb468d94b926d5702",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "size":{
                    "width":1400,
                    "height":90},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFD7D7D7}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/我的工作台/u3.png"}},
{
            "id":"d272761cc28841aabfc377d601a1ee83",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":200,
                "y":15},
              "size":{
                "width":200,
                "height":60},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFD7D7D7}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"304b1fa2e1004612895198bae19aad1c",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":200,
                    "y":15},
                  "size":{
                    "width":200,
                    "height":60},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFD7D7D7}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/我的工作台/u5.png"}},
{
            "id":"1ff87331235e44d3907f0495638c3ee8",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":0,
                "y":90},
              "size":{
                "width":1400,
                "height":35},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFD7D7D7}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"8dea732008a44e7ba0aa5e0d23bc0e6b",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":0,
                    "y":90},
                  "size":{
                    "width":1400,
                    "height":35},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFD7D7D7}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/采购管理_1/u17.png"}},
{
            "id":"0ae756c78f1d4827bd92090a57c2445d",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":200,
                "y":90},
              "size":{
                "width":130,
                "height":35},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFD7D7D7}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"fa593240b6704c1390d0e2aefef6074a",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":200,
                    "y":90},
                  "size":{
                    "width":130,
                    "height":35},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFD7D7D7}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/我的工作台/u11.png"}},
{
            "id":"3718fe3583d442998538f8f62ebde4ea",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":330,
                "y":90},
              "size":{
                "width":130,
                "height":35},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFD7D7D7}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"13c36587be2d43fe8c5570fc2d88bd70",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":330,
                    "y":90},
                  "size":{
                    "width":130,
                    "height":35},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFD7D7D7}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/我的工作台/u11.png"}},
{
            "id":"7605c42231844874b2c96607badb0850",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "horizontalAlignment":"right",
              "location":{
                "x":940,
                "y":15},
              "size":{
                "width":260,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"984bcf4d07254baba8671ebc15bf96cb",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "horizontalAlignment":"right",
                  "location":{
                    "x":940,
                    "y":15},
                  "size":{
                    "width":260,
                    "height":16}},
                "adaptiveStyles":{
},
                "objects":[{
                    "id":"2f74abe178134b94b65ef27c84a0b10c",
                    "label":"",
                    "type":"hyperlink",
                    "styleType":"hyperlink",
                    "visible":true,
                    "style":{
},
                    "adaptiveStyles":{
},
                    "interactionMap":{
                      "onClick":{
                        "description":"OnClick",
                        "cases":[{
                            "description":"用例 1",
                            "isNewIfGroup":false,
                            "actions":[{
                                "action":"linkWindow",
                                "description":"在 当前窗口 打开 帐号设置",
                                "target":{
                                  "targetType":"page",
                                  "url":"帐号设置.html",
                                  "includeVariables":true},
                                "linkType":"current"}]}]}},
                    "tabbable":true}]}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"a429c1e2aff64addaaa099e07e66daf5",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":460,
                "y":90},
              "size":{
                "width":130,
                "height":35},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFD7D7D7}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"881c32b5d1f94845a14d88dbbbfd5243",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":460,
                    "y":90},
                  "size":{
                    "width":130,
                    "height":35},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFD7D7D7}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/我的工作台/u11.png"}},
{
            "id":"b126bc9f382d48879198610315ee4e59",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFFE4E4E4},
              "location":{
                "x":590,
                "y":90},
              "size":{
                "width":130,
                "height":35},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFD7D7D7}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"bdc5a116b70e44d38274557da8097264",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFE4E4E4},
                  "location":{
                    "x":590,
                    "y":90},
                  "size":{
                    "width":130,
                    "height":35},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFD7D7D7}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/我的工作台/u9.png"}},
{
            "id":"a4ba979bdeba41d29e3cd3326b6c3198",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":720,
                "y":90},
              "size":{
                "width":130,
                "height":35},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFD7D7D7}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"bab036d936394aecb0ad756249f71cde",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":720,
                    "y":90},
                  "size":{
                    "width":130,
                    "height":35},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFD7D7D7}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/我的工作台/u11.png"}},
{
            "id":"10506aa0892a466ea5a09fd469114a67",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":850,
                "y":90},
              "size":{
                "width":130,
                "height":35},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFD7D7D7}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"584f0797854c4c60942fdc3c761fd9b9",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":850,
                    "y":90},
                  "size":{
                    "width":130,
                    "height":35},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFD7D7D7}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/我的工作台/u11.png"}},
{
            "id":"5ac36443a26244dbb4de436ae575e0b1",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":980,
                "y":90},
              "size":{
                "width":130,
                "height":35},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFD7D7D7}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"88a5040bb63a4e1389a8aaf44f149200",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":980,
                    "y":90},
                  "size":{
                    "width":130,
                    "height":35},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFD7D7D7}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/我的工作台/u11.png"}}]}}},
  "objectPaths":{
    "a2517fa6cd9c454799f9ac06bade023e":{
      "scriptId":"u0",
      "aa94056b817049cbb1fa6bacb8c1e519":{
        "scriptId":"u1"},
      "d0f70829d22f42fea545dfa7923b52be":{
        "scriptId":"u2"}},
    "ae8c37fe0fd84aeb87b697befc737f57":{
      "scriptId":"u3"},
    "331ca0a1eca94c67908a13ff95849187":{
      "scriptId":"u4"},
    "49986a3ab88a4cf39d5bbe33d52e3dfd":{
      "scriptId":"u5"},
    "2706d45dd1bd495588a9a449ac5034d8":{
      "scriptId":"u6"},
    "1d754b4eaac84803ac101c31bf6ba52e":{
      "scriptId":"u7"},
    "3fabee892de448b7a910a4fc56133556":{
      "scriptId":"u8"},
    "887179836f10461c8c4fdb94b3773815":{
      "scriptId":"u9"},
    "25781352871745b28f2e010290c00197":{
      "scriptId":"u10"},
    "143cf445a40845f2aa24fc93c88f0fb3":{
      "scriptId":"u11"},
    "8308c4b6661a49afa3a15e4635335c5c":{
      "scriptId":"u12"},
    "21edd9f4efe045478494f1d0c001719e":{
      "scriptId":"u13"},
    "2d05e7b6584b4c7485ed9ff06c8a2c5e":{
      "scriptId":"u14"},
    "b961ab3312f24fd1ad2e6bdb2c1495de":{
      "scriptId":"u15"},
    "dd75b008452a41398358630dfe47c5f1":{
      "scriptId":"u16"},
    "e027785fcb344d27bcb2d2091a6a8690":{
      "scriptId":"u17"},
    "545edb442fe64cd49cedea7fc1ea11f2":{
      "scriptId":"u18"},
    "c1f7fa68745841b5a67d964f7c5b8cdd":{
      "scriptId":"u19"},
    "ce5ef9fee3804276b65b610eef0176c3":{
      "scriptId":"u20"},
    "a7e700aeca9340778d6ee4a7608c3194":{
      "scriptId":"u21"},
    "56f784aa25674ccdab3012b40334a27b":{
      "scriptId":"u22"},
    "d2fb599d39214d4cbbcfbcfa1433619c":{
      "scriptId":"u23"},
    "8c921ad1f2ff4c53ab4048d05a20b92d":{
      "scriptId":"u24"},
    "fef1ddcaf8c64756a25d775280ce7bf5":{
      "scriptId":"u25"},
    "bdc4162dbeec439bbb6c0f8a06e20fe9":{
      "scriptId":"u26"},
    "0b8b369eca8243fd891336298f029b57":{
      "scriptId":"u27"},
    "d773f7b0461e4b9dac133306fbef3c91":{
      "scriptId":"u28"},
    "2ba6ef0abf794933ad8479dc7f2836b2":{
      "scriptId":"u29"},
    "7b3119b89ca3414685b38f00bb32696f":{
      "scriptId":"u30"},
    "e561a0ae4b6f454686edbf645cc876d6":{
      "scriptId":"u31"},
    "b76e5444821941db9f83b62650919cd8":{
      "scriptId":"u32"},
    "a50d8810ae154a2da2c532878831f0d7":{
      "scriptId":"u33"},
    "f2cc5793b4124bf9a79b7bf19b6aef67":{
      "scriptId":"u34"},
    "b8a75cb037164418aaf918bcb2ab6b5c":{
      "scriptId":"u35"},
    "5f18b1c1e67a4101ba3eee0cd743dc52":{
      "scriptId":"u36"},
    "824e9ea209ee4c7cb7a43aa15b6dc0f9":{
      "scriptId":"u37"},
    "17ef8fb2644e40ca8a97ca3a83d875f9":{
      "scriptId":"u38"},
    "e32cc5c064f04bb0a778b58ed4d73291":{
      "scriptId":"u39"},
    "da04171506d34f439efd938917a2a787":{
      "scriptId":"u40"},
    "b88ba9e6d4b04ba5908008ef6f395d66":{
      "scriptId":"u41"},
    "aa266d9c1e014cb8853510b71bb61b65":{
      "scriptId":"u42"},
    "78f79bda2c0f4006bf7271d4f3180fd0":{
      "scriptId":"u43"},
    "0698368f529e4db58b167eebaf2a0681":{
      "scriptId":"u44"},
    "49b8fd962c364ee198c85a900931c0fe":{
      "scriptId":"u45"},
    "3d055436781c4e1ba89207721f690d82":{
      "scriptId":"u46"},
    "f62d3ac518ec40cfb615fc080299d9dc":{
      "scriptId":"u47"},
    "0a0a7b7c8f054cdcbc466e9c5ae011d7":{
      "scriptId":"u48"},
    "9a59e6466ba14d76b345f40bb209104e":{
      "scriptId":"u49"},
    "5cdfb1ebcaee433f9d5c8631008a2a13":{
      "scriptId":"u50"},
    "c2b26a412c304368b183aa353e918233":{
      "scriptId":"u51"},
    "3c660dcf463644dc9fe2a49d82208fdf":{
      "scriptId":"u52"},
    "a4172139ce284fa6af4bd668d50b73b8":{
      "scriptId":"u53"},
    "c6a77c1893964d9986261462be35d317":{
      "scriptId":"u54"},
    "cab3615c0a1a414cbd2447493d790a2b":{
      "scriptId":"u55"},
    "173265315222436f86bbdd77665ed6ed":{
      "scriptId":"u56"},
    "67af3a05445c41949a329473a6e285e0":{
      "scriptId":"u57"},
    "7ddcf972df3b4ed9b4dcd474c73866cb":{
      "scriptId":"u58"},
    "7653eb9ac6f545a98a86af98fd765a40":{
      "scriptId":"u59"},
    "29f63f3e7b2d4cff9a27cc81b99b1fc6":{
      "scriptId":"u60"},
    "64d34d67a8a5425aaf44db17d857c97a":{
      "scriptId":"u61"},
    "ba8bf2de126c447386482135a9d2b272":{
      "scriptId":"u62"},
    "b00c9c4253aa4de5bdc45f801880812d":{
      "scriptId":"u63"},
    "de65043e03fb437cb6267ae5ece1144f":{
      "scriptId":"u64"},
    "bbc8aeb3050c460892ac2b6d9a858391":{
      "scriptId":"u65"},
    "de347bf8c79747378aaa73a0dc7f2e93":{
      "scriptId":"u66"},
    "b1e981c9388e476d9a511fc24107c44a":{
      "scriptId":"u67"},
    "dbf57be7e72049dca96fb8b4a9471fea":{
      "scriptId":"u68"},
    "21a7b0fdc8794616b750016869efc4a4":{
      "scriptId":"u69"},
    "12dbcf80001844efae7c8d3164032876":{
      "scriptId":"u70"},
    "35b33af5eb9e4cd49794468261591432":{
      "scriptId":"u71"},
    "e0076b26e4634073b5c6227cf3ceb303":{
      "scriptId":"u72"},
    "ee70cf7bca744badbdffedf59f15f1ca":{
      "scriptId":"u73"},
    "6ab116c0c6e1410e846a6d99e6ffaa63":{
      "scriptId":"u74"},
    "133b034c85ee430ba03f240a9da3b8bc":{
      "scriptId":"u75"},
    "6755f8439aea4461b4af683c29445fc1":{
      "scriptId":"u76"},
    "99e373abcfdc4378b144f7b1d94e0ec0":{
      "scriptId":"u77"},
    "7889bc0033794e86a4de38a657c11fcf":{
      "scriptId":"u78"},
    "1a4a2461bfdf4a1d8765427232ba104c":{
      "scriptId":"u79"},
    "b47042d89d2b4dd1a63bf08a5bef35ef":{
      "scriptId":"u80"},
    "a9e1e029e71044feb6fe96459fbd1e9a":{
      "scriptId":"u81"},
    "f5f36f95269b4741a99b44ecce727e83":{
      "scriptId":"u82"},
    "03d68a2232a749e3986886d774bca051":{
      "scriptId":"u83"},
    "0ef794c370fd44f4bc0925928d2c6743":{
      "scriptId":"u84",
      "11a2262448e0441f9a29e02867462317":{
        "scriptId":"u85"},
      "2fb6fec02a5946deb468d94b926d5702":{
        "scriptId":"u86"},
      "d272761cc28841aabfc377d601a1ee83":{
        "scriptId":"u87"},
      "304b1fa2e1004612895198bae19aad1c":{
        "scriptId":"u88"},
      "1ff87331235e44d3907f0495638c3ee8":{
        "scriptId":"u89"},
      "8dea732008a44e7ba0aa5e0d23bc0e6b":{
        "scriptId":"u90"},
      "0ae756c78f1d4827bd92090a57c2445d":{
        "scriptId":"u91"},
      "fa593240b6704c1390d0e2aefef6074a":{
        "scriptId":"u92"},
      "3718fe3583d442998538f8f62ebde4ea":{
        "scriptId":"u93"},
      "13c36587be2d43fe8c5570fc2d88bd70":{
        "scriptId":"u94"},
      "7605c42231844874b2c96607badb0850":{
        "scriptId":"u95"},
      "984bcf4d07254baba8671ebc15bf96cb":{
        "scriptId":"u96"},
      "2f74abe178134b94b65ef27c84a0b10c":{
        "scriptId":"u97"},
      "a429c1e2aff64addaaa099e07e66daf5":{
        "scriptId":"u98"},
      "881c32b5d1f94845a14d88dbbbfd5243":{
        "scriptId":"u99"},
      "b126bc9f382d48879198610315ee4e59":{
        "scriptId":"u100"},
      "bdc5a116b70e44d38274557da8097264":{
        "scriptId":"u101"},
      "a4ba979bdeba41d29e3cd3326b6c3198":{
        "scriptId":"u102"},
      "bab036d936394aecb0ad756249f71cde":{
        "scriptId":"u103"},
      "10506aa0892a466ea5a09fd469114a67":{
        "scriptId":"u104"},
      "584f0797854c4c60942fdc3c761fd9b9":{
        "scriptId":"u105"},
      "5ac36443a26244dbb4de436ae575e0b1":{
        "scriptId":"u106"},
      "88a5040bb63a4e1389a8aaf44f149200":{
        "scriptId":"u107"}},
    "ff8a9e850db948598048d9834efae4de":{
      "scriptId":"u108"},
    "f87c6af5307c49859c0cee563df66b70":{
      "scriptId":"u109"},
    "2d2acd6123af4bf0922f91f1546b0fc6":{
      "scriptId":"u110"},
    "5a9d7009aa5a479e8978589d9f241ac2":{
      "scriptId":"u111"},
    "8609f723f48b48788372361fd09ea218":{
      "scriptId":"u112"},
    "7ae4d2b13ece43ca9f6ddaa8b9397892":{
      "scriptId":"u113"},
    "30ae93a51fc14f449e527781436abc63":{
      "scriptId":"u114"},
    "af8c6af365c740d2905d5c75c5959be8":{
      "scriptId":"u115"},
    "62689d74bad04aa2988a039e306b8840":{
      "scriptId":"u116"},
    "3ea91febe18a446984f01fb29afc302c":{
      "scriptId":"u117"},
    "215f2cc34c8e43acb04d3521499ddfec":{
      "scriptId":"u118"},
    "9e885e3ef0424a138035f529bb30d961":{
      "scriptId":"u119"},
    "ce3a8b1e87cb48fb91b5a8a1a9597ee3":{
      "scriptId":"u120"},
    "46c62a1158ce4285bc928969fb17e04e":{
      "scriptId":"u121"},
    "79c41eb06fc844d89825e3855e2f613a":{
      "scriptId":"u122"},
    "da0cd8c7aa3c4f10a42e62733840969a":{
      "scriptId":"u123"},
    "ae71a36b9c1e407399fd9f242bcca52b":{
      "scriptId":"u124"},
    "d778bfd6aed04b388e9805e89678f57c":{
      "scriptId":"u125"},
    "658278b5e37943979e59e5df84da752b":{
      "scriptId":"u126"},
    "c3085183fff7414586efd331bb46f069":{
      "scriptId":"u127"},
    "959ca5d035e44c18bd60653ee629398a":{
      "scriptId":"u128"},
    "e19c1671b17d44a391339ba97cca74d2":{
      "scriptId":"u129"},
    "bd369c9a54ec40cb88d9faf720f2ffd9":{
      "scriptId":"u130"},
    "c1588e99c7944d7286b9fc276a7f3d68":{
      "scriptId":"u131"},
    "35d4f70da3894442b018691f86205729":{
      "scriptId":"u132"},
    "f3bc118f1a604e7ab550c536c9f1b1b4":{
      "scriptId":"u133"},
    "e9682ce2332a486892ef45fe5c72a88c":{
      "scriptId":"u134"},
    "7f1efc7505334e4c8e45fab963631c85":{
      "scriptId":"u135"},
    "c477479c0a114aacb20d7248bce22ef1":{
      "scriptId":"u136"},
    "8bf64f156bb142789919324bcbac4b85":{
      "scriptId":"u137"}}});