$axure.loadCurrentPage({
  "url":"商品详情.html",
  "generationDate":new Date(1432872278075.52),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"43f92a3af5214356bea7230d3ff2fa9e",
    "type":"Axure:Page",
    "name":"商品详情",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"501c6570c6ef496d9a16b0e0dd8aa6ed",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":420,
              "y":150},
            "size":{
              "width":780,
              "height":450},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFD7D7D7}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6047ce40332e4614ba692e10a6f7604c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":420,
                  "y":150},
                "size":{
                  "width":780,
                  "height":450},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/商品详情/u0.png"}},
{
          "id":"62baf4f4a59d489dabc5d8ef512db7bd",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":450,
              "y":175},
            "size":{
              "width":100,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"385c4bf54e674ad1b0009f473cf587c4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":450,
                  "y":175},
                "size":{
                  "width":100,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"afee4523d1404435b0c495c1b46c0222",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":530,
              "y":175},
            "size":{
              "width":190,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"26096458752c4b7db41114a988615f7d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":530,
                  "y":175},
                "size":{
                  "width":190,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"34ae1deceb7f4cab95776e350405bef2",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":450,
              "y":214},
            "size":{
              "width":100,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9db3e8630c764a3a80a58101d178070e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":450,
                  "y":214},
                "size":{
                  "width":100,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"bf58ebb9f10d4164ad0c8105f9ba2ad4",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":450,
              "y":254},
            "size":{
              "width":100,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c62868073b1a43debe92763845dcf9fd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":450,
                  "y":254},
                "size":{
                  "width":100,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"77bb1e01dccd45deb79630928d981248",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":450,
              "y":293},
            "size":{
              "width":100,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a8901795f62844f7aead1a13e005a994",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":450,
                  "y":293},
                "size":{
                  "width":100,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4359faa9cfdb415d8d1183961a012572",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":450,
              "y":332},
            "size":{
              "width":100,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4d27f31841bc4e0481f500d85458cee3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":450,
                  "y":332},
                "size":{
                  "width":100,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6019f7d991b04429a4a5fa55c69e1a2e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":450,
              "y":372},
            "size":{
              "width":100,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4967381eb55b41ae9b68cd1fa5c4e159",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":450,
                  "y":372},
                "size":{
                  "width":100,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f93c6e2d56884abdbbb299a96a782622",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":450,
              "y":411},
            "size":{
              "width":100,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6ad43586222f444193feec0ed04e6f13",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":450,
                  "y":411},
                "size":{
                  "width":100,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6ac37a853e204c608e825c54e0f1f763",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":450,
              "y":450},
            "size":{
              "width":100,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6b5683e9bc5a466c89938640b1803be2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":450,
                  "y":450},
                "size":{
                  "width":100,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9fb46ca6aebf4b219d9dceb990a32894",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":450,
              "y":495},
            "size":{
              "width":100,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"102a125e18f04561a990a1e777265d5c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":450,
                  "y":495},
                "size":{
                  "width":100,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3388b3842564468c92559457cbb09d18",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":530,
              "y":214},
            "size":{
              "width":190,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ed9e1ce2e64746c0a1ea74d8836bee91",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":530,
                  "y":214},
                "size":{
                  "width":190,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f42d22ba219f4ac7b557aba4d7c677e9",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":530,
              "y":254},
            "size":{
              "width":190,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3726c7a298164c698d6188ffd256706b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":530,
                  "y":254},
                "size":{
                  "width":190,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b4f56684b7584a18b5df2d6cd8f1befb",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":530,
              "y":293},
            "size":{
              "width":190,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"31277867f48e4886af6912eaaeec45ef",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":530,
                  "y":293},
                "size":{
                  "width":190,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6cc760045c354ff68787c523cc102666",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":530,
              "y":332},
            "size":{
              "width":190,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"22294b05b7c5427481470fb3c0a1283b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":530,
                  "y":332},
                "size":{
                  "width":190,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"cd0ed43a389d4776bac77605a9baea6d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":530,
              "y":370},
            "size":{
              "width":190,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ca175e3a5fb242e8b73f1c299764c1d4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":530,
                  "y":370},
                "size":{
                  "width":190,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"29fb141eb1b64a7996ac27bd6a638c66",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":530,
              "y":411},
            "size":{
              "width":190,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6c3905a74b614091b438e9244d298665",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":530,
                  "y":411},
                "size":{
                  "width":190,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"86ede0ca2e2244a58e5320ca5d726ffa",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":530,
              "y":450},
            "size":{
              "width":190,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a2dc7b232e934ea286dc7ac4d4cd193c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":530,
                  "y":450},
                "size":{
                  "width":190,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"df5ab609a7214ee8bfb8612df8acba69",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":530,
              "y":495},
            "size":{
              "width":190,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"026ff2fab83847918daf7fb37f65cc81",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":530,
                  "y":495},
                "size":{
                  "width":190,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"034ebe7ff65945ebbbbccc4cc7831bab",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":450,
              "y":535},
            "size":{
              "width":100,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"12b212781b9a44ce934f0645c5df991a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":450,
                  "y":535},
                "size":{
                  "width":100,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0b3f3a6a26ad42dda5843843dc336047",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF6633,
              "opacity":1},
            "location":{
              "x":530,
              "y":535},
            "size":{
              "width":190,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ba1f5c43716648e692dea8a95b4a31bd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF6633,
                  "opacity":1},
                "location":{
                  "x":530,
                  "y":535},
                "size":{
                  "width":190,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"120b10d6d6c74e0fb2f1e785970226c7",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
},
          "adaptiveStyles":{
},
          "masterId":"d46401a06c1e4b89b7df1b25949937b2"},
{
          "id":"b953c940019d4c47afbdfb5afe35d393",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":200,
              "y":150},
            "size":{
              "width":200,
              "height":80},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFD7D7D7}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0870d9babe38488c8173da99070040d7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":200,
                  "y":150},
                "size":{
                  "width":200,
                  "height":80},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的工作台/u26.png"}},
{
          "id":"2b31abbfd38d49d0a4528ab46207ad97",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFE4E4E4},
            "location":{
              "x":200,
              "y":230},
            "size":{
              "width":200,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFD7D7D7}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5a38e68a12e34b9da2da2d4af95d0db9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4},
                "location":{
                  "x":200,
                  "y":230},
                "size":{
                  "width":200,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的工作台/u28.png"}},
{
          "id":"ac8e6bbfd73a4eea801b4a6245cf0a4a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":200,
              "y":270},
            "size":{
              "width":200,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFD7D7D7}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"338fb280096b4f1ebc821a2cee119b72",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":200,
                  "y":270},
                "size":{
                  "width":200,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的工作台/u30.png"}},
{
          "id":"686bf98322794c8b9a6b3ea96fbc445e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":200,
              "y":310},
            "size":{
              "width":200,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFD7D7D7}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"33de21e8bb154eb299b282df9092f01d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":200,
                  "y":310},
                "size":{
                  "width":200,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的工作台/u30.png"}},
{
          "id":"e8c862f7ee124c31bbf98ced996b35b1",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "location":{
              "x":780,
              "y":497},
            "size":{
              "width":160,
              "height":57},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFD7D7D7}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"53afa0d7e1074d76984202179c7f1952",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "location":{
                  "x":780,
                  "y":497},
                "size":{
                  "width":160,
                  "height":57},
                "borderWidth":"2",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/订单详情_2/u73.png"}},
{
          "id":"05ed0a1015224a2fb21259dc644adf44",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":780,
              "y":474},
            "size":{
              "width":70,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4c7662ce73a74351bb65d49492bb5b82",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":780,
                  "y":474},
                "size":{
                  "width":70,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c93201026ded4a878f8d340083b39f14",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":909,
              "y":506},
            "size":{
              "width":21,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"eebb99f4eb1b4dbda59951c80db2951a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":909,
                  "y":506},
                "size":{
                  "width":21,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/基本会员/u238.png"}},
{
          "id":"81ada1d523b34a0fbe6179c5ebace763",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":620}},
          "adaptiveStyles":{
},
          "masterId":"9aa3da306ba24637b281c884b1c30bca"}]}},
  "masters":{
    "d46401a06c1e4b89b7df1b25949937b2":{
      "packageId":"d46401a06c1e4b89b7df1b25949937b2",
      "type":"Axure:Master",
      "name":"交易员头部--采购",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"应用字体",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"11a2262448e0441f9a29e02867462317",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "size":{
                "width":1400,
                "height":90},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFD7D7D7}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"2fb6fec02a5946deb468d94b926d5702",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "size":{
                    "width":1400,
                    "height":90},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFD7D7D7}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/我的工作台/u3.png"}},
{
            "id":"d272761cc28841aabfc377d601a1ee83",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":200,
                "y":15},
              "size":{
                "width":200,
                "height":60},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFD7D7D7}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"304b1fa2e1004612895198bae19aad1c",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":200,
                    "y":15},
                  "size":{
                    "width":200,
                    "height":60},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFD7D7D7}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/我的工作台/u5.png"}},
{
            "id":"1ff87331235e44d3907f0495638c3ee8",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":0,
                "y":90},
              "size":{
                "width":1400,
                "height":35},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFD7D7D7}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"8dea732008a44e7ba0aa5e0d23bc0e6b",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":0,
                    "y":90},
                  "size":{
                    "width":1400,
                    "height":35},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFD7D7D7}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/采购管理_1/u17.png"}},
{
            "id":"0ae756c78f1d4827bd92090a57c2445d",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":200,
                "y":90},
              "size":{
                "width":130,
                "height":35},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFD7D7D7}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"fa593240b6704c1390d0e2aefef6074a",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":200,
                    "y":90},
                  "size":{
                    "width":130,
                    "height":35},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFD7D7D7}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/我的工作台/u11.png"}},
{
            "id":"3718fe3583d442998538f8f62ebde4ea",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":330,
                "y":90},
              "size":{
                "width":130,
                "height":35},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFD7D7D7}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"13c36587be2d43fe8c5570fc2d88bd70",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":330,
                    "y":90},
                  "size":{
                    "width":130,
                    "height":35},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFD7D7D7}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/我的工作台/u11.png"}},
{
            "id":"7605c42231844874b2c96607badb0850",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "horizontalAlignment":"right",
              "location":{
                "x":940,
                "y":15},
              "size":{
                "width":260,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"984bcf4d07254baba8671ebc15bf96cb",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "horizontalAlignment":"right",
                  "location":{
                    "x":940,
                    "y":15},
                  "size":{
                    "width":260,
                    "height":16}},
                "adaptiveStyles":{
},
                "objects":[{
                    "id":"2f74abe178134b94b65ef27c84a0b10c",
                    "label":"",
                    "type":"hyperlink",
                    "styleType":"hyperlink",
                    "visible":true,
                    "style":{
},
                    "adaptiveStyles":{
},
                    "interactionMap":{
                      "onClick":{
                        "description":"OnClick",
                        "cases":[{
                            "description":"用例 1",
                            "isNewIfGroup":false,
                            "actions":[{
                                "action":"linkWindow",
                                "description":"在 当前窗口 打开 帐号设置",
                                "target":{
                                  "targetType":"page",
                                  "url":"帐号设置.html",
                                  "includeVariables":true},
                                "linkType":"current"}]}]}},
                    "tabbable":true}]}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"a429c1e2aff64addaaa099e07e66daf5",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":460,
                "y":90},
              "size":{
                "width":130,
                "height":35},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFD7D7D7}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"881c32b5d1f94845a14d88dbbbfd5243",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":460,
                    "y":90},
                  "size":{
                    "width":130,
                    "height":35},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFD7D7D7}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/我的工作台/u11.png"}},
{
            "id":"b126bc9f382d48879198610315ee4e59",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFFE4E4E4},
              "location":{
                "x":590,
                "y":90},
              "size":{
                "width":130,
                "height":35},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFD7D7D7}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"bdc5a116b70e44d38274557da8097264",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFE4E4E4},
                  "location":{
                    "x":590,
                    "y":90},
                  "size":{
                    "width":130,
                    "height":35},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFD7D7D7}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/我的工作台/u9.png"}},
{
            "id":"a4ba979bdeba41d29e3cd3326b6c3198",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":720,
                "y":90},
              "size":{
                "width":130,
                "height":35},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFD7D7D7}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"bab036d936394aecb0ad756249f71cde",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":720,
                    "y":90},
                  "size":{
                    "width":130,
                    "height":35},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFD7D7D7}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/我的工作台/u11.png"}},
{
            "id":"10506aa0892a466ea5a09fd469114a67",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":850,
                "y":90},
              "size":{
                "width":130,
                "height":35},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFD7D7D7}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"584f0797854c4c60942fdc3c761fd9b9",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":850,
                    "y":90},
                  "size":{
                    "width":130,
                    "height":35},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFD7D7D7}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/我的工作台/u11.png"}},
{
            "id":"5ac36443a26244dbb4de436ae575e0b1",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":980,
                "y":90},
              "size":{
                "width":130,
                "height":35},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFD7D7D7}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"88a5040bb63a4e1389a8aaf44f149200",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":980,
                    "y":90},
                  "size":{
                    "width":130,
                    "height":35},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFD7D7D7}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/我的工作台/u11.png"}}]}},
    "9aa3da306ba24637b281c884b1c30bca":{
      "packageId":"9aa3da306ba24637b281c884b1c30bca",
      "type":"Axure:Master",
      "name":"交易员底部",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"应用字体",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"aa94056b817049cbb1fa6bacb8c1e519",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "size":{
                "width":1400,
                "height":40},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFD7D7D7}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"d0f70829d22f42fea545dfa7923b52be",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "size":{
                    "width":1400,
                    "height":40},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFD7D7D7}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/首页/u13.png"}}]}}},
  "objectPaths":{
    "501c6570c6ef496d9a16b0e0dd8aa6ed":{
      "scriptId":"u0"},
    "6047ce40332e4614ba692e10a6f7604c":{
      "scriptId":"u1"},
    "62baf4f4a59d489dabc5d8ef512db7bd":{
      "scriptId":"u2"},
    "385c4bf54e674ad1b0009f473cf587c4":{
      "scriptId":"u3"},
    "afee4523d1404435b0c495c1b46c0222":{
      "scriptId":"u4"},
    "26096458752c4b7db41114a988615f7d":{
      "scriptId":"u5"},
    "34ae1deceb7f4cab95776e350405bef2":{
      "scriptId":"u6"},
    "9db3e8630c764a3a80a58101d178070e":{
      "scriptId":"u7"},
    "bf58ebb9f10d4164ad0c8105f9ba2ad4":{
      "scriptId":"u8"},
    "c62868073b1a43debe92763845dcf9fd":{
      "scriptId":"u9"},
    "77bb1e01dccd45deb79630928d981248":{
      "scriptId":"u10"},
    "a8901795f62844f7aead1a13e005a994":{
      "scriptId":"u11"},
    "4359faa9cfdb415d8d1183961a012572":{
      "scriptId":"u12"},
    "4d27f31841bc4e0481f500d85458cee3":{
      "scriptId":"u13"},
    "6019f7d991b04429a4a5fa55c69e1a2e":{
      "scriptId":"u14"},
    "4967381eb55b41ae9b68cd1fa5c4e159":{
      "scriptId":"u15"},
    "f93c6e2d56884abdbbb299a96a782622":{
      "scriptId":"u16"},
    "6ad43586222f444193feec0ed04e6f13":{
      "scriptId":"u17"},
    "6ac37a853e204c608e825c54e0f1f763":{
      "scriptId":"u18"},
    "6b5683e9bc5a466c89938640b1803be2":{
      "scriptId":"u19"},
    "9fb46ca6aebf4b219d9dceb990a32894":{
      "scriptId":"u20"},
    "102a125e18f04561a990a1e777265d5c":{
      "scriptId":"u21"},
    "3388b3842564468c92559457cbb09d18":{
      "scriptId":"u22"},
    "ed9e1ce2e64746c0a1ea74d8836bee91":{
      "scriptId":"u23"},
    "f42d22ba219f4ac7b557aba4d7c677e9":{
      "scriptId":"u24"},
    "3726c7a298164c698d6188ffd256706b":{
      "scriptId":"u25"},
    "b4f56684b7584a18b5df2d6cd8f1befb":{
      "scriptId":"u26"},
    "31277867f48e4886af6912eaaeec45ef":{
      "scriptId":"u27"},
    "6cc760045c354ff68787c523cc102666":{
      "scriptId":"u28"},
    "22294b05b7c5427481470fb3c0a1283b":{
      "scriptId":"u29"},
    "cd0ed43a389d4776bac77605a9baea6d":{
      "scriptId":"u30"},
    "ca175e3a5fb242e8b73f1c299764c1d4":{
      "scriptId":"u31"},
    "29fb141eb1b64a7996ac27bd6a638c66":{
      "scriptId":"u32"},
    "6c3905a74b614091b438e9244d298665":{
      "scriptId":"u33"},
    "86ede0ca2e2244a58e5320ca5d726ffa":{
      "scriptId":"u34"},
    "a2dc7b232e934ea286dc7ac4d4cd193c":{
      "scriptId":"u35"},
    "df5ab609a7214ee8bfb8612df8acba69":{
      "scriptId":"u36"},
    "026ff2fab83847918daf7fb37f65cc81":{
      "scriptId":"u37"},
    "034ebe7ff65945ebbbbccc4cc7831bab":{
      "scriptId":"u38"},
    "12b212781b9a44ce934f0645c5df991a":{
      "scriptId":"u39"},
    "0b3f3a6a26ad42dda5843843dc336047":{
      "scriptId":"u40"},
    "ba1f5c43716648e692dea8a95b4a31bd":{
      "scriptId":"u41"},
    "120b10d6d6c74e0fb2f1e785970226c7":{
      "scriptId":"u42",
      "11a2262448e0441f9a29e02867462317":{
        "scriptId":"u43"},
      "2fb6fec02a5946deb468d94b926d5702":{
        "scriptId":"u44"},
      "d272761cc28841aabfc377d601a1ee83":{
        "scriptId":"u45"},
      "304b1fa2e1004612895198bae19aad1c":{
        "scriptId":"u46"},
      "1ff87331235e44d3907f0495638c3ee8":{
        "scriptId":"u47"},
      "8dea732008a44e7ba0aa5e0d23bc0e6b":{
        "scriptId":"u48"},
      "0ae756c78f1d4827bd92090a57c2445d":{
        "scriptId":"u49"},
      "fa593240b6704c1390d0e2aefef6074a":{
        "scriptId":"u50"},
      "3718fe3583d442998538f8f62ebde4ea":{
        "scriptId":"u51"},
      "13c36587be2d43fe8c5570fc2d88bd70":{
        "scriptId":"u52"},
      "7605c42231844874b2c96607badb0850":{
        "scriptId":"u53"},
      "984bcf4d07254baba8671ebc15bf96cb":{
        "scriptId":"u54"},
      "2f74abe178134b94b65ef27c84a0b10c":{
        "scriptId":"u55"},
      "a429c1e2aff64addaaa099e07e66daf5":{
        "scriptId":"u56"},
      "881c32b5d1f94845a14d88dbbbfd5243":{
        "scriptId":"u57"},
      "b126bc9f382d48879198610315ee4e59":{
        "scriptId":"u58"},
      "bdc5a116b70e44d38274557da8097264":{
        "scriptId":"u59"},
      "a4ba979bdeba41d29e3cd3326b6c3198":{
        "scriptId":"u60"},
      "bab036d936394aecb0ad756249f71cde":{
        "scriptId":"u61"},
      "10506aa0892a466ea5a09fd469114a67":{
        "scriptId":"u62"},
      "584f0797854c4c60942fdc3c761fd9b9":{
        "scriptId":"u63"},
      "5ac36443a26244dbb4de436ae575e0b1":{
        "scriptId":"u64"},
      "88a5040bb63a4e1389a8aaf44f149200":{
        "scriptId":"u65"}},
    "b953c940019d4c47afbdfb5afe35d393":{
      "scriptId":"u66"},
    "0870d9babe38488c8173da99070040d7":{
      "scriptId":"u67"},
    "2b31abbfd38d49d0a4528ab46207ad97":{
      "scriptId":"u68"},
    "5a38e68a12e34b9da2da2d4af95d0db9":{
      "scriptId":"u69"},
    "ac8e6bbfd73a4eea801b4a6245cf0a4a":{
      "scriptId":"u70"},
    "338fb280096b4f1ebc821a2cee119b72":{
      "scriptId":"u71"},
    "686bf98322794c8b9a6b3ea96fbc445e":{
      "scriptId":"u72"},
    "33de21e8bb154eb299b282df9092f01d":{
      "scriptId":"u73"},
    "e8c862f7ee124c31bbf98ced996b35b1":{
      "scriptId":"u74"},
    "53afa0d7e1074d76984202179c7f1952":{
      "scriptId":"u75"},
    "05ed0a1015224a2fb21259dc644adf44":{
      "scriptId":"u76"},
    "4c7662ce73a74351bb65d49492bb5b82":{
      "scriptId":"u77"},
    "c93201026ded4a878f8d340083b39f14":{
      "scriptId":"u78"},
    "eebb99f4eb1b4dbda59951c80db2951a":{
      "scriptId":"u79"},
    "81ada1d523b34a0fbe6179c5ebace763":{
      "scriptId":"u80",
      "aa94056b817049cbb1fa6bacb8c1e519":{
        "scriptId":"u81"},
      "d0f70829d22f42fea545dfa7923b52be":{
        "scriptId":"u82"}}}});