$axure.loadCurrentPage({
  "url":"非标准单详情.html",
  "generationDate":new Date(1432872269131.01),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"71105f7c849a4d96b59045482f832a0c",
    "type":"Axure:Page",
    "name":"非标准单详情",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"7b17a0baa4a8431081bbc9422f2cf3d8",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
},
          "adaptiveStyles":{
},
          "masterId":"bc530238763041a488adf9d4c356e4fb"},
{
          "id":"faed7158097344729fb54280c6122c5b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":420,
              "y":150},
            "size":{
              "width":780,
              "height":670},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFD7D7D7}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6fd72ddcc9b94f31bf57b2d587a12fa7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":420,
                  "y":150},
                "size":{
                  "width":780,
                  "height":670},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/非标准单详情/u24.png"}},
{
          "id":"c7038d2add9d49c3a6a9e9b135048092",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":450,
              "y":220},
            "size":{
              "width":240,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d8dd63e355ab4d1e836ad04e854c3ebd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":450,
                  "y":220},
                "size":{
                  "width":240,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"54a98dc1cd1f4572ab34aa813967f5ce",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":450,
              "y":244},
            "size":{
              "width":280,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"aa1cb036e5b04820813ecb0cfbcdb573",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":450,
                  "y":244},
                "size":{
                  "width":280,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5e645d3e66a94f1ab258267691948a65",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "location":{
              "x":450,
              "y":170},
            "size":{
              "width":240,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"095c90a69711412f81937fed10c3ea02",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "location":{
                  "x":450,
                  "y":170},
                "size":{
                  "width":240,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3f219b2be2434a98919fdaed2f9e929d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":520,
              "y":220},
            "size":{
              "width":200,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c74816b7f5714da98009742b4bbd1786",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":520,
                  "y":220},
                "size":{
                  "width":200,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"28f759a8d9394f9e8ebb137aeef9adaa",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":520,
              "y":244},
            "size":{
              "width":200,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b6a12587d02648b19946040541af73c4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":520,
                  "y":244},
                "size":{
                  "width":200,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3a3276a8a4ea4b508124d6d8c5f2c496",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":450,
              "y":270},
            "size":{
              "width":280,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"87df86a146434920a7d93b735ad08689",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":450,
                  "y":270},
                "size":{
                  "width":280,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"041ac09eae1c4dc5b3f9195cdaaa3c03",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":520,
              "y":270},
            "size":{
              "width":200,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"39d24648d2444c249489b4a6fa14c274",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":520,
                  "y":270},
                "size":{
                  "width":200,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"78994ac90f984713bb6f576af6b7a0d4",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF8F8F8},
            "location":{
              "x":450,
              "y":310},
            "size":{
              "width":730,
              "height":400},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFD7D7D7}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"40ab97bd68ed4c479db50ae0e9af2d99",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF8F8F8},
                "location":{
                  "x":450,
                  "y":310},
                "size":{
                  "width":730,
                  "height":400},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/非标准单详情/u40.png"}},
{
          "id":"4e9aef733a244e4893ed220264ed4a82",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":982}},
          "adaptiveStyles":{
},
          "masterId":"9aa3da306ba24637b281c884b1c30bca"},
{
          "id":"b057d8b2eb3b49f3ac081e2bb94a6b64",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF008000,
              "opacity":1},
            "location":{
              "x":450,
              "y":740},
            "size":{
              "width":140,
              "height":40}},
          "adaptiveStyles":{
}},
{
          "id":"3f2eadc0375644a088110b614db9bb65",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":654,
              "y":740},
            "size":{
              "width":180,
              "height":40}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示 关闭资源单",
                      "objectsToFades":[{
                          "objectPath":["10f8eef44308483784d99efbff83d614"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}}]}]}]}},
          "tabbable":true},
{
          "id":"10f8eef44308483784d99efbff83d614",
          "label":"关闭资源单",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":false,
          "style":{
            "location":{
              "x":478,
              "y":420},
            "size":{
              "width":10,
              "height":10},
            "visible":false},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":true,
          "propagate":false,
          "diagrams":[{
              "id":"db529b8a42f047079de35b6e048c3892",
              "label":"状态1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"75ba217428a249af9d5f99d3e35b1b50",
                  "label":"",
                  "parentDynamicPanel":"10f8eef44308483784d99efbff83d614",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":472,
                      "height":270},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFD7D7D7}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"b63b640353fe48988806afcdc4d6ff69",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"10f8eef44308483784d99efbff83d614",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":472,
                          "height":270},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFD7D7D7}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/供应管理/u211.png"}},
{
                  "id":"ce82a96294dd46c6bfbe8ae35eaccad2",
                  "label":"",
                  "parentDynamicPanel":"10f8eef44308483784d99efbff83d614",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":16,
                      "y":28},
                    "size":{
                      "width":110,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"fbe7418caf7a45cf805fdc11f91c414b",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"10f8eef44308483784d99efbff83d614",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":16,
                          "y":28},
                        "size":{
                          "width":110,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"885a6e83b7f34b7fa563779d2d8767bb",
                  "label":"",
                  "parentDynamicPanel":"10f8eef44308483784d99efbff83d614",
                  "type":"comboBox",
                  "styleType":"comboBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":92,
                      "y":24},
                    "size":{
                      "width":163,
                      "height":22}},
                  "adaptiveStyles":{
}},
{
                  "id":"6a6c7ebab26542879c2e662c50020f08",
                  "label":"",
                  "parentDynamicPanel":"10f8eef44308483784d99efbff83d614",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":92,
                      "y":62},
                    "size":{
                      "width":295,
                      "height":122},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFD7D7D7}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"2a6add1c49e748db80c8fcbdd5816723",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"10f8eef44308483784d99efbff83d614",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":92,
                          "y":62},
                        "size":{
                          "width":295,
                          "height":122},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFD7D7D7}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/供应管理/u216.png"}},
{
                  "id":"cab26f1e89dd47279a8aa2bf40604be0",
                  "label":"",
                  "parentDynamicPanel":"10f8eef44308483784d99efbff83d614",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":16,
                      "y":62},
                    "size":{
                      "width":110,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"df8fc96b6db6478f9dff8f547a279409",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"10f8eef44308483784d99efbff83d614",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":16,
                          "y":62},
                        "size":{
                          "width":110,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"c5104dcedb7e456a90fc807dd8154dd6",
                  "label":"",
                  "parentDynamicPanel":"10f8eef44308483784d99efbff83d614",
                  "type":"button",
                  "styleType":"button",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":92,
                      "y":206},
                    "size":{
                      "width":100,
                      "height":35}},
                  "adaptiveStyles":{
},
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"fadeWidget",
                              "description":"隐藏 关闭资源单",
                              "objectsToFades":[{
                                  "objectPath":["10f8eef44308483784d99efbff83d614"],
                                  "fadeInfo":{
                                    "fadeType":"hide",
                                    "options":{
                                      "showType":"none"}}}]}]}]}},
                  "tabbable":true}]}]},
{
          "id":"9a1846420ede497090b098581e0b7e22",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontWeight":"700",
            "location":{
              "x":420,
              "y":847},
            "size":{
              "width":170,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0e8a18733af34ab19cd6b9ea7ee8078c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"700",
                "location":{
                  "x":420,
                  "y":847},
                "size":{
                  "width":170,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"be2df96fe7bd4859a7c603efc49b38c1",
          "label":"",
          "type":"table",
          "styleType":"table",
          "visible":true,
          "style":{
            "location":{
              "x":420,
              "y":873},
            "size":{
              "width":780,
              "height":77}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"46c29b1609a342e6814ea51430f76fd4",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"700",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "size":{
                  "width":153,
                  "height":35},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"2982330c3da24676b04a9144a83a69f9",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Arial Negreta', 'Arial'",
                    "fontWeight":"700",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFF2F2F2},
                    "size":{
                      "width":153,
                      "height":35},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFD7D7D7}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/标准单详情/u356.png"}},
{
              "id":"8da6e9437c9e4f77b7e8c6f8481f5bbc",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":35},
                "size":{
                  "width":153,
                  "height":42},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"1ae0e20d9e5443bca86cadd07a2e2eae",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":35},
                    "size":{
                      "width":153,
                      "height":42},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFD7D7D7}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/标准单详情/u362.png"}},
{
              "id":"df50f77b13d24674b76e7cf1b9edf1a9",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"700",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":153,
                  "y":0},
                "size":{
                  "width":140,
                  "height":35},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"6b324aa22cbf4109b052cf31b4b21d49",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Arial Negreta', 'Arial'",
                    "fontWeight":"700",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFF2F2F2},
                    "location":{
                      "x":153,
                      "y":0},
                    "size":{
                      "width":140,
                      "height":35},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFD7D7D7}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/标准单详情/u358.png"}},
{
              "id":"812cd4cb13de4e1b9425f0616a1e2376",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "verticalAlignment":"middle",
                "location":{
                  "x":153,
                  "y":35},
                "size":{
                  "width":140,
                  "height":42},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"a9227fbc3db548f59812314741171d1f",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "verticalAlignment":"middle",
                    "location":{
                      "x":153,
                      "y":35},
                    "size":{
                      "width":140,
                      "height":42},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFD7D7D7}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/标准单详情/u364.png"}},
{
              "id":"7487530e9f664a9e996bf474283c30d8",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"700",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":293,
                  "y":0},
                "size":{
                  "width":487,
                  "height":35},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"30791524d35c44a58800154f17a9b941",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Arial Negreta', 'Arial'",
                    "fontWeight":"700",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFF2F2F2},
                    "location":{
                      "x":293,
                      "y":0},
                    "size":{
                      "width":487,
                      "height":35},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFD7D7D7}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/标准单详情/u360.png"}},
{
              "id":"ff343bd47da8407e83808b1146dea10a",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "verticalAlignment":"middle",
                "location":{
                  "x":293,
                  "y":35},
                "size":{
                  "width":487,
                  "height":42},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"5b676a3568fa4c398928ad41ef9738a1",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "verticalAlignment":"middle",
                    "location":{
                      "x":293,
                      "y":35},
                    "size":{
                      "width":487,
                      "height":42},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFD7D7D7}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/标准单详情/u366.png"}}]},
{
          "id":"31a8ab23b1f94ee5a6908f81a6c07e87",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":200,
              "y":150},
            "size":{
              "width":200,
              "height":80},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFD7D7D7}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"13849e53af344ec5a58096087824ff87",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":200,
                  "y":150},
                "size":{
                  "width":200,
                  "height":80},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的工作台/u26.png"}},
{
          "id":"2a5fea414a974ded9ac1f5837b2016f4",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFE4E4E4},
            "location":{
              "x":200,
              "y":230},
            "size":{
              "width":200,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFD7D7D7}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"23c6bc9d3b024965a7ccd1140dd65e86",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4},
                "location":{
                  "x":200,
                  "y":230},
                "size":{
                  "width":200,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的工作台/u28.png"}},
{
          "id":"5a4adecdfd5248d9b47670d4453a2247",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "fill":{
              "fillType":"solid",
              "color":0xFFE4E4E4},
            "location":{
              "x":210,
              "y":270},
            "size":{
              "width":190,
              "height":30},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFD7D7D7}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5d3b513832d648f9ae87185f6be23e4b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4},
                "location":{
                  "x":210,
                  "y":270},
                "size":{
                  "width":190,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/管理资源单/u233.png"}},
{
          "id":"2e249bf5eb51401d9adbe63f9c26eec9",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "location":{
              "x":210,
              "y":300},
            "size":{
              "width":190,
              "height":30},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFD7D7D7}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cebb44d7cf6b4004b21f0e748414221b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "location":{
                  "x":210,
                  "y":300},
                "size":{
                  "width":190,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/管理资源单/u235.png"}},
{
          "id":"b8995328f2d2482485bd231d474ccae3",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "location":{
              "x":210,
              "y":330},
            "size":{
              "width":190,
              "height":30},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFD7D7D7}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"23f7062047ba4909b817dd6dff3336df",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "location":{
                  "x":210,
                  "y":330},
                "size":{
                  "width":190,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/管理资源单/u235.png"}},
{
          "id":"d126f7eedce6440680a47bcdad606f84",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":200,
              "y":360},
            "size":{
              "width":200,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFD7D7D7}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dc0506b89ebb43529fd70473ddf28064",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":200,
                  "y":360},
                "size":{
                  "width":200,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的工作台/u30.png"}},
{
          "id":"d155fe03c6f543dd94e1ea4f29fe825f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":200,
              "y":400},
            "size":{
              "width":200,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFD7D7D7}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"167fcb3fd6844275a3e908b3514e59e4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":200,
                  "y":400},
                "size":{
                  "width":200,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的工作台/u30.png"}}]}},
  "masters":{
    "bc530238763041a488adf9d4c356e4fb":{
      "packageId":"bc530238763041a488adf9d4c356e4fb",
      "type":"Axure:Master",
      "name":"交易员头部--工作台",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"应用字体",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"11a2262448e0441f9a29e02867462317",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "size":{
                "width":1400,
                "height":90},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFD7D7D7}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"2fb6fec02a5946deb468d94b926d5702",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "size":{
                    "width":1400,
                    "height":90},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFD7D7D7}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/我的工作台/u3.png"}},
{
            "id":"d272761cc28841aabfc377d601a1ee83",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":200,
                "y":15},
              "size":{
                "width":200,
                "height":60},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFD7D7D7}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"304b1fa2e1004612895198bae19aad1c",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":200,
                    "y":15},
                  "size":{
                    "width":200,
                    "height":60},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFD7D7D7}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/我的工作台/u5.png"}},
{
            "id":"1ff87331235e44d3907f0495638c3ee8",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFFF2F2F2},
              "location":{
                "x":0,
                "y":90},
              "size":{
                "width":1400,
                "height":35},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFD7D7D7}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"8dea732008a44e7ba0aa5e0d23bc0e6b",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFF2F2F2},
                  "location":{
                    "x":0,
                    "y":90},
                  "size":{
                    "width":1400,
                    "height":35},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFD7D7D7}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/首页/u33.png"}},
{
            "id":"0ae756c78f1d4827bd92090a57c2445d",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFFE4E4E4},
              "location":{
                "x":200,
                "y":90},
              "size":{
                "width":130,
                "height":35},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFD7D7D7}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"fa593240b6704c1390d0e2aefef6074a",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFE4E4E4},
                  "location":{
                    "x":200,
                    "y":90},
                  "size":{
                    "width":130,
                    "height":35},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFD7D7D7}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/我的工作台/u9.png"}},
{
            "id":"3718fe3583d442998538f8f62ebde4ea",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":330,
                "y":90},
              "size":{
                "width":130,
                "height":35},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFD7D7D7}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"13c36587be2d43fe8c5570fc2d88bd70",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":330,
                    "y":90},
                  "size":{
                    "width":130,
                    "height":35},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFD7D7D7}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/我的工作台/u11.png"}},
{
            "id":"624015d5abdd41e0a4e7ef44f5bcc9a4",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":460,
                "y":90},
              "size":{
                "width":130,
                "height":35},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFD7D7D7}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"9e3e06e20ea1413298faf9eddf4362cb",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":460,
                    "y":90},
                  "size":{
                    "width":130,
                    "height":35},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFD7D7D7}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/我的工作台/u11.png"}},
{
            "id":"86f8341a7fb94c419fd1fc6855fc9f44",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":590,
                "y":90},
              "size":{
                "width":130,
                "height":35},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFD7D7D7}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"638c63a8ab5540128457b7a30b8c258c",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":590,
                    "y":90},
                  "size":{
                    "width":130,
                    "height":35},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFD7D7D7}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/我的工作台/u11.png"}},
{
            "id":"097fea23495544949ad23a4c2a8caeef",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":720,
                "y":90},
              "size":{
                "width":130,
                "height":35},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFD7D7D7}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"ff5b86a4e47d42ec96edd236d910384b",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":720,
                    "y":90},
                  "size":{
                    "width":130,
                    "height":35},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFD7D7D7}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/我的工作台/u11.png"}},
{
            "id":"21f3ccbe065d40b9b394b8f533bd057a",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":850,
                "y":90},
              "size":{
                "width":130,
                "height":35},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFD7D7D7}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"d07540f5c61d4f3cb723d0ab23ac2d58",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":850,
                    "y":90},
                  "size":{
                    "width":130,
                    "height":35},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFD7D7D7}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/我的工作台/u11.png"}},
{
            "id":"b46c74a30f49471ebdafbf28e05d09f0",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":980,
                "y":90},
              "size":{
                "width":130,
                "height":35},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFD7D7D7}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"3a3f798151f24148a3b84f8d9c051ce9",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":980,
                    "y":90},
                  "size":{
                    "width":130,
                    "height":35},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFD7D7D7}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/我的工作台/u11.png"}},
{
            "id":"24291c4ce9dc43d7866054672260c419",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "horizontalAlignment":"right",
              "location":{
                "x":940,
                "y":15},
              "size":{
                "width":260,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"b175c1de53e0462fa92b7e6cf604c7c5",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "horizontalAlignment":"right",
                  "location":{
                    "x":940,
                    "y":15},
                  "size":{
                    "width":260,
                    "height":16}},
                "adaptiveStyles":{
},
                "objects":[{
                    "id":"9dbb43e095204646be1962d10f39c24b",
                    "label":"",
                    "type":"hyperlink",
                    "styleType":"hyperlink",
                    "visible":true,
                    "style":{
},
                    "adaptiveStyles":{
},
                    "interactionMap":{
                      "onClick":{
                        "description":"OnClick",
                        "cases":[{
                            "description":"用例 1",
                            "isNewIfGroup":false,
                            "actions":[{
                                "action":"linkWindow",
                                "description":"在 当前窗口 打开 帐号设置",
                                "target":{
                                  "targetType":"page",
                                  "url":"帐号设置.html",
                                  "includeVariables":true},
                                "linkType":"current"}]}]}},
                    "tabbable":true}]}],
            "images":{
              "normal~":"resources/images/transparent.gif"}}]}},
    "9aa3da306ba24637b281c884b1c30bca":{
      "packageId":"9aa3da306ba24637b281c884b1c30bca",
      "type":"Axure:Master",
      "name":"交易员底部",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"应用字体",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"aa94056b817049cbb1fa6bacb8c1e519",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "size":{
                "width":1400,
                "height":40},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFD7D7D7}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"d0f70829d22f42fea545dfa7923b52be",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "size":{
                    "width":1400,
                    "height":40},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFD7D7D7}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/首页/u13.png"}}]}}},
  "objectPaths":{
    "7b17a0baa4a8431081bbc9422f2cf3d8":{
      "scriptId":"u0",
      "11a2262448e0441f9a29e02867462317":{
        "scriptId":"u1"},
      "2fb6fec02a5946deb468d94b926d5702":{
        "scriptId":"u2"},
      "d272761cc28841aabfc377d601a1ee83":{
        "scriptId":"u3"},
      "304b1fa2e1004612895198bae19aad1c":{
        "scriptId":"u4"},
      "1ff87331235e44d3907f0495638c3ee8":{
        "scriptId":"u5"},
      "8dea732008a44e7ba0aa5e0d23bc0e6b":{
        "scriptId":"u6"},
      "0ae756c78f1d4827bd92090a57c2445d":{
        "scriptId":"u7"},
      "fa593240b6704c1390d0e2aefef6074a":{
        "scriptId":"u8"},
      "3718fe3583d442998538f8f62ebde4ea":{
        "scriptId":"u9"},
      "13c36587be2d43fe8c5570fc2d88bd70":{
        "scriptId":"u10"},
      "624015d5abdd41e0a4e7ef44f5bcc9a4":{
        "scriptId":"u11"},
      "9e3e06e20ea1413298faf9eddf4362cb":{
        "scriptId":"u12"},
      "86f8341a7fb94c419fd1fc6855fc9f44":{
        "scriptId":"u13"},
      "638c63a8ab5540128457b7a30b8c258c":{
        "scriptId":"u14"},
      "097fea23495544949ad23a4c2a8caeef":{
        "scriptId":"u15"},
      "ff5b86a4e47d42ec96edd236d910384b":{
        "scriptId":"u16"},
      "21f3ccbe065d40b9b394b8f533bd057a":{
        "scriptId":"u17"},
      "d07540f5c61d4f3cb723d0ab23ac2d58":{
        "scriptId":"u18"},
      "b46c74a30f49471ebdafbf28e05d09f0":{
        "scriptId":"u19"},
      "3a3f798151f24148a3b84f8d9c051ce9":{
        "scriptId":"u20"},
      "24291c4ce9dc43d7866054672260c419":{
        "scriptId":"u21"},
      "b175c1de53e0462fa92b7e6cf604c7c5":{
        "scriptId":"u22"},
      "9dbb43e095204646be1962d10f39c24b":{
        "scriptId":"u23"}},
    "faed7158097344729fb54280c6122c5b":{
      "scriptId":"u24"},
    "6fd72ddcc9b94f31bf57b2d587a12fa7":{
      "scriptId":"u25"},
    "c7038d2add9d49c3a6a9e9b135048092":{
      "scriptId":"u26"},
    "d8dd63e355ab4d1e836ad04e854c3ebd":{
      "scriptId":"u27"},
    "54a98dc1cd1f4572ab34aa813967f5ce":{
      "scriptId":"u28"},
    "aa1cb036e5b04820813ecb0cfbcdb573":{
      "scriptId":"u29"},
    "5e645d3e66a94f1ab258267691948a65":{
      "scriptId":"u30"},
    "095c90a69711412f81937fed10c3ea02":{
      "scriptId":"u31"},
    "3f219b2be2434a98919fdaed2f9e929d":{
      "scriptId":"u32"},
    "c74816b7f5714da98009742b4bbd1786":{
      "scriptId":"u33"},
    "28f759a8d9394f9e8ebb137aeef9adaa":{
      "scriptId":"u34"},
    "b6a12587d02648b19946040541af73c4":{
      "scriptId":"u35"},
    "3a3276a8a4ea4b508124d6d8c5f2c496":{
      "scriptId":"u36"},
    "87df86a146434920a7d93b735ad08689":{
      "scriptId":"u37"},
    "041ac09eae1c4dc5b3f9195cdaaa3c03":{
      "scriptId":"u38"},
    "39d24648d2444c249489b4a6fa14c274":{
      "scriptId":"u39"},
    "78994ac90f984713bb6f576af6b7a0d4":{
      "scriptId":"u40"},
    "40ab97bd68ed4c479db50ae0e9af2d99":{
      "scriptId":"u41"},
    "4e9aef733a244e4893ed220264ed4a82":{
      "scriptId":"u42",
      "aa94056b817049cbb1fa6bacb8c1e519":{
        "scriptId":"u43"},
      "d0f70829d22f42fea545dfa7923b52be":{
        "scriptId":"u44"}},
    "b057d8b2eb3b49f3ac081e2bb94a6b64":{
      "scriptId":"u45"},
    "3f2eadc0375644a088110b614db9bb65":{
      "scriptId":"u46"},
    "10f8eef44308483784d99efbff83d614":{
      "scriptId":"u47"},
    "75ba217428a249af9d5f99d3e35b1b50":{
      "scriptId":"u48"},
    "b63b640353fe48988806afcdc4d6ff69":{
      "scriptId":"u49"},
    "ce82a96294dd46c6bfbe8ae35eaccad2":{
      "scriptId":"u50"},
    "fbe7418caf7a45cf805fdc11f91c414b":{
      "scriptId":"u51"},
    "885a6e83b7f34b7fa563779d2d8767bb":{
      "scriptId":"u52"},
    "6a6c7ebab26542879c2e662c50020f08":{
      "scriptId":"u53"},
    "2a6add1c49e748db80c8fcbdd5816723":{
      "scriptId":"u54"},
    "cab26f1e89dd47279a8aa2bf40604be0":{
      "scriptId":"u55"},
    "df8fc96b6db6478f9dff8f547a279409":{
      "scriptId":"u56"},
    "c5104dcedb7e456a90fc807dd8154dd6":{
      "scriptId":"u57"},
    "9a1846420ede497090b098581e0b7e22":{
      "scriptId":"u58"},
    "0e8a18733af34ab19cd6b9ea7ee8078c":{
      "scriptId":"u59"},
    "be2df96fe7bd4859a7c603efc49b38c1":{
      "scriptId":"u60"},
    "46c29b1609a342e6814ea51430f76fd4":{
      "scriptId":"u61"},
    "2982330c3da24676b04a9144a83a69f9":{
      "scriptId":"u62"},
    "df50f77b13d24674b76e7cf1b9edf1a9":{
      "scriptId":"u63"},
    "6b324aa22cbf4109b052cf31b4b21d49":{
      "scriptId":"u64"},
    "7487530e9f664a9e996bf474283c30d8":{
      "scriptId":"u65"},
    "30791524d35c44a58800154f17a9b941":{
      "scriptId":"u66"},
    "8da6e9437c9e4f77b7e8c6f8481f5bbc":{
      "scriptId":"u67"},
    "1ae0e20d9e5443bca86cadd07a2e2eae":{
      "scriptId":"u68"},
    "812cd4cb13de4e1b9425f0616a1e2376":{
      "scriptId":"u69"},
    "a9227fbc3db548f59812314741171d1f":{
      "scriptId":"u70"},
    "ff343bd47da8407e83808b1146dea10a":{
      "scriptId":"u71"},
    "5b676a3568fa4c398928ad41ef9738a1":{
      "scriptId":"u72"},
    "31a8ab23b1f94ee5a6908f81a6c07e87":{
      "scriptId":"u73"},
    "13849e53af344ec5a58096087824ff87":{
      "scriptId":"u74"},
    "2a5fea414a974ded9ac1f5837b2016f4":{
      "scriptId":"u75"},
    "23c6bc9d3b024965a7ccd1140dd65e86":{
      "scriptId":"u76"},
    "5a4adecdfd5248d9b47670d4453a2247":{
      "scriptId":"u77"},
    "5d3b513832d648f9ae87185f6be23e4b":{
      "scriptId":"u78"},
    "2e249bf5eb51401d9adbe63f9c26eec9":{
      "scriptId":"u79"},
    "cebb44d7cf6b4004b21f0e748414221b":{
      "scriptId":"u80"},
    "b8995328f2d2482485bd231d474ccae3":{
      "scriptId":"u81"},
    "23f7062047ba4909b817dd6dff3336df":{
      "scriptId":"u82"},
    "d126f7eedce6440680a47bcdad606f84":{
      "scriptId":"u83"},
    "dc0506b89ebb43529fd70473ddf28064":{
      "scriptId":"u84"},
    "d155fe03c6f543dd94e1ea4f29fe825f":{
      "scriptId":"u85"},
    "167fcb3fd6844275a3e908b3514e59e4":{
      "scriptId":"u86"}}});