$axure.loadCurrentPage({
  "url":"进行中_2.html",
  "generationDate":new Date(1432872291931.31),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"6701cedc8a5d4236ab81e847c2f0ec13",
    "type":"Axure:Page",
    "name":"进行中",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"7e14ac995f0b4b62bb66aed4ca5af205",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":200,
              "y":150},
            "size":{
              "width":200,
              "height":80},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFD7D7D7}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8e37b518e5e74383ab1e88eb81eb4f05",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":200,
                  "y":150},
                "size":{
                  "width":200,
                  "height":80},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的工作台/u26.png"}},
{
          "id":"c3b66501dae1400aa5044a5dfd2df54f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFE4E4E4},
            "location":{
              "x":200,
              "y":230},
            "size":{
              "width":200,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFD7D7D7}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ea383d0557b74814bc69cffc7d723b32",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4},
                "location":{
                  "x":200,
                  "y":230},
                "size":{
                  "width":200,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的工作台/u28.png"}},
{
          "id":"cbf9240d37104121b2d477dbc58fb366",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":200,
              "y":330},
            "size":{
              "width":200,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFD7D7D7}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"95d6c6ca4af5436a93096edb1ede6bae",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":200,
                  "y":330},
                "size":{
                  "width":200,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的工作台/u30.png"}},
{
          "id":"d3553f67adb34663a7fd55452b613afa",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":1007}},
          "adaptiveStyles":{
},
          "masterId":"9aa3da306ba24637b281c884b1c30bca"},
{
          "id":"ea8fee36418046308dfed9766f4f8e94",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "location":{
              "x":210,
              "y":300},
            "size":{
              "width":190,
              "height":30},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFD7D7D7}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8361e49d3df2476fb845c2aa488324ed",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "location":{
                  "x":210,
                  "y":300},
                "size":{
                  "width":190,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/管理资源单/u235.png"}},
{
          "id":"55618e73c52148a29dce9c431cf76aae",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "fill":{
              "fillType":"solid",
              "color":0xFFE4E4E4},
            "location":{
              "x":210,
              "y":270},
            "size":{
              "width":190,
              "height":30},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFD7D7D7}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7619e4a5fa5347a7922da21e20f7681b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4},
                "location":{
                  "x":210,
                  "y":270},
                "size":{
                  "width":190,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/管理资源单/u233.png"}},
{
          "id":"145cb17cfe794efe91cabc4281296f06",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
},
          "adaptiveStyles":{
},
          "masterId":"d5b739f105d347138233b0627c50cf7b"},
{
          "id":"cc4b9acdb2de4615b1ccb03773254615",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":420,
              "y":266},
            "size":{
              "width":780,
              "height":724},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFD7D7D7}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4b2c94eb68ab4a60a8fbc799063682f8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":420,
                  "y":266},
                "size":{
                  "width":780,
                  "height":724},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/托运管理_1/u37.png"}},
{
          "id":"7387cdbf45c04af3acac86b870c167c8",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":420,
              "y":266},
            "size":{
              "width":780,
              "height":30},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFD7D7D7}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4a7178aa837e4a1ea3d3c44d82f5e662",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":420,
                  "y":266},
                "size":{
                  "width":780,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/竞价管理/u57.png"}},
{
          "id":"ee8ffe32df4f4dcdb13e0d6abb3b5e8b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontWeight":"700",
            "location":{
              "x":591,
              "y":273},
            "size":{
              "width":111,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d7f7dffd36bc4095bfc6ed496b7b8bf6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"700",
                "location":{
                  "x":591,
                  "y":273},
                "size":{
                  "width":111,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"983021ce9e344ccbac62c97949945f1c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontWeight":"700",
            "location":{
              "x":798,
              "y":273},
            "size":{
              "width":80,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"83049fe637994dc48acf229512bc5427",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"700",
                "location":{
                  "x":798,
                  "y":273},
                "size":{
                  "width":80,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5e8cc304eb4943d38e1625e286979c52",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":591,
              "y":315},
            "size":{
              "width":239,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a274aefd86944952a21f6f842c3fe7a1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":591,
                  "y":315},
                "size":{
                  "width":239,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e70e56cd7f6e43db9e723709529b832c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":591,
              "y":349},
            "size":{
              "width":239,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"39996d50c835457aad745a42f54a45a2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":591,
                  "y":349},
                "size":{
                  "width":239,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8bdf799c61fd45eea836c5ca238040cc",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":591,
              "y":380},
            "size":{
              "width":239,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"830c63da331e4b1eaa1e135e56e6328f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":591,
                  "y":380},
                "size":{
                  "width":239,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"113d3630f6a74df0a9f788c34127503d",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":436,
              "y":416},
            "size":{
              "width":748,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFD7D7D7}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/托运管理_1/u51_line.png"}},
{
          "id":"924da49fc7724592b400cdaa082b77ad",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"center",
            "location":{
              "x":768,
              "y":315},
            "size":{
              "width":103,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b06486660ee44d98a41775742aa4a49c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "location":{
                  "x":768,
                  "y":315},
                "size":{
                  "width":103,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a94acfc43cf140939668c5f5f46b7843",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontWeight":"700",
            "location":{
              "x":944,
              "y":273},
            "size":{
              "width":105,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"721b0a27070c4ea98772660449860ba8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"700",
                "location":{
                  "x":944,
                  "y":273},
                "size":{
                  "width":105,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e77c6dc2a6f24344acc60f27a703508c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":944,
              "y":315},
            "size":{
              "width":240,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8c9cd22a4d2f47c786db9974e4067946",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":944,
                  "y":315},
                "size":{
                  "width":240,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"35f2c73ed3a842c999e4e616514bd7be",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":591,
              "y":446},
            "size":{
              "width":239,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1720e03f68b54124947f46f51baa964f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":591,
                  "y":446},
                "size":{
                  "width":239,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ed2fe59625a84de284c9a0f44f96506f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":591,
              "y":480},
            "size":{
              "width":239,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"81065c598de94555a13b0a346c236183",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":591,
                  "y":480},
                "size":{
                  "width":239,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f0509428a88346df9e1b503a69faa89a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":591,
              "y":511},
            "size":{
              "width":239,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dc55f5e55dce45fb8051d7886b7bfe8f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":591,
                  "y":511},
                "size":{
                  "width":239,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a0d2d256d36241cea03442a269799979",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":436,
              "y":547},
            "size":{
              "width":748,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFD7D7D7}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/托运管理_1/u51_line.png"}},
{
          "id":"9c8a3a06b95d4f7bb9291eeb7e2c92ec",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"center",
            "location":{
              "x":769,
              "y":446},
            "size":{
              "width":103,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"783ff56c784545fcb85980b7845fec4e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "location":{
                  "x":769,
                  "y":446},
                "size":{
                  "width":103,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"586eacc606af4216831476e004628960",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":944,
              "y":446},
            "size":{
              "width":240,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4e34a5a5d92844cf8090912b6d1721aa",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":944,
                  "y":446},
                "size":{
                  "width":240,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"50ff9b12e4c84a32a5dd8f9d718738a6",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":944,
              "y":507},
            "size":{
              "width":105,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"a8491ff9936e4d0694f5c351d641e485",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":591,
              "y":585},
            "size":{
              "width":239,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"07b10e83bffe432e9bf545015d00a12c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":591,
                  "y":585},
                "size":{
                  "width":239,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e7aad682267d4715bf266f41b08105e0",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":591,
              "y":619},
            "size":{
              "width":239,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f6be45f276ac4787a19f8fe727d34cd0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":591,
                  "y":619},
                "size":{
                  "width":239,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5e9c4b59914940abbcd227f61b449b9b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":591,
              "y":650},
            "size":{
              "width":239,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4e883ee239694f32a2ca1ada31ef6a6a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":591,
                  "y":650},
                "size":{
                  "width":239,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e188dca67d2846929aecfba4e698ec5f",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":436,
              "y":686},
            "size":{
              "width":748,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFD7D7D7}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/托运管理_1/u51_line.png"}},
{
          "id":"e48a335c897540b19e351451dc6e51b9",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"center",
            "location":{
              "x":769,
              "y":585},
            "size":{
              "width":103,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9f283bd300604b36bc107ef7e355d6a8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "location":{
                  "x":769,
                  "y":585},
                "size":{
                  "width":103,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2f00a4c76ba748e981c4206b83d0a1c2",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":944,
              "y":585},
            "size":{
              "width":240,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5896fa1a9ad843cca66470bbe544225d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":944,
                  "y":585},
                "size":{
                  "width":240,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a635211b53f143108bdd2d1820ea0105",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":944,
              "y":646},
            "size":{
              "width":105,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"f09bf31f300241b2b80eae54193f601f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":591,
              "y":717},
            "size":{
              "width":239,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2f1152c762f54874bd99529901979025",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":591,
                  "y":717},
                "size":{
                  "width":239,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"04936c8f8c8645a9883f4a6a8707f6ca",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":591,
              "y":751},
            "size":{
              "width":239,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9f0e7e5d9a6b43d5b2c64f92c8f5fe49",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":591,
                  "y":751},
                "size":{
                  "width":239,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b3cfe5f1aee1467fbf3e80eda8c4b2e2",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":591,
              "y":782},
            "size":{
              "width":239,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a532663f7be04af49b649d08fadc0cda",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":591,
                  "y":782},
                "size":{
                  "width":239,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"db8f9a6b9a3845e6b0d594cd1dcc3ef9",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":436,
              "y":817},
            "size":{
              "width":748,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFD7D7D7}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/托运管理_1/u51_line.png"}},
{
          "id":"2f90bdf4d7ab4325a4fa86abaf7a69b2",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"center",
            "location":{
              "x":769,
              "y":716},
            "size":{
              "width":103,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ad6515da0d314decb801e184f7ebc164",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "location":{
                  "x":769,
                  "y":716},
                "size":{
                  "width":103,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4ffb395e06894f769ec9e1412827170b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":944,
              "y":716},
            "size":{
              "width":240,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d7be615d26094c9b8f44fe2f71734f6a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":944,
                  "y":716},
                "size":{
                  "width":240,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2e14841a3a804d049d3f733e4b182769",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":944,
              "y":777},
            "size":{
              "width":105,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"bdc38dda903649f29afe9b2ece165b14",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":591,
              "y":855},
            "size":{
              "width":239,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ba4063ba0a1e4cd0a684d84e3252a85b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":591,
                  "y":855},
                "size":{
                  "width":239,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"78923917c0d44808aea30dde9907a87e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":591,
              "y":889},
            "size":{
              "width":239,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"300d17c415f34c72a564239e099e948e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":591,
                  "y":889},
                "size":{
                  "width":239,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"76d837e432a14612bca9f0f6ee782f80",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":591,
              "y":920},
            "size":{
              "width":239,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"69315b8464ab4b70bb3d38a9550d7c39",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":591,
                  "y":920},
                "size":{
                  "width":239,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"fa7036e65d064f7ead284f3607185cb6",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"center",
            "location":{
              "x":769,
              "y":855},
            "size":{
              "width":103,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d265803a9df1458c9dad107722d25afc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "location":{
                  "x":769,
                  "y":855},
                "size":{
                  "width":103,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b8a388cef3944929ab76e93fd187d6fb",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":944,
              "y":855},
            "size":{
              "width":240,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fd0df0cee9d248e585b2516a1bfaac5e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":944,
                  "y":855},
                "size":{
                  "width":240,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1cc6b96f70934304861c262601ce0375",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":944,
              "y":916},
            "size":{
              "width":105,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"2364ae651e03427f9f7ad76370321ff7",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":576,
              "y":960},
            "size":{
              "width":504,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5bd6dcd097744d25a8fedf7c87255ad8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":576,
                  "y":960},
                "size":{
                  "width":504,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的收藏/u301.png"}},
{
          "id":"1558715293424bfcaa2703f598ce17c5",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":420,
              "y":150},
            "size":{
              "width":780,
              "height":100},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFD7D7D7}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"700d462b362240ea8406dfd480a51a70",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":420,
                  "y":150},
                "size":{
                  "width":780,
                  "height":100},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/托运管理_1/u107.png"}},
{
          "id":"cb62f74d6afb457b90420985e3588e72",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":436,
              "y":215},
            "size":{
              "width":111,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"edd8f8e1e6af4ebfbf58cd0a31611721",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":436,
                  "y":215},
                "size":{
                  "width":111,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d75d9effaba04c5aa2a0e3bcb7cfcde3",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":502,
              "y":211},
            "size":{
              "width":188,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"caeef46534da45b693548699f3539da8",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":902,
              "y":169},
            "size":{
              "width":111,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4b2e7251feee475bab3b0de8b1254b16",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":902,
                  "y":169},
                "size":{
                  "width":111,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4850fa818881431e96246297dc12eeac",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":967,
              "y":165},
            "size":{
              "width":135,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"85fc3d547ebc45cf87453b69bd08ad02",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":700,
              "y":211},
            "size":{
              "width":172,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"0864ff47b64a4275b8a38e70f8aee603",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":436,
              "y":170},
            "size":{
              "width":111,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c9b07ced75df464a843d4de52d5d9bf2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":436,
                  "y":170},
                "size":{
                  "width":111,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"228705a29fe148d4805d0e5f6e046463",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontWeight":"700",
            "location":{
              "x":436,
              "y":273},
            "size":{
              "width":111,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"49fdc27175394fa7b9d420f2bd0693c4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"700",
                "location":{
                  "x":436,
                  "y":273},
                "size":{
                  "width":111,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3c68238b81a44320b6ffc7cad78c7363",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":944,
              "y":371},
            "size":{
              "width":105,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"de26223b0c08411f9ba928cb29095ac6",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":436,
              "y":306},
            "size":{
              "width":84,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a3de77c599c9457ca77f137fd3b0db39",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":436,
                  "y":306},
                "size":{
                  "width":84,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d59086eeb6824ad4981c2bf6157dbd0d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":436,
              "y":436},
            "size":{
              "width":84,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b51eb5b84b3647bab37e5f3650f652fa",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":436,
                  "y":436},
                "size":{
                  "width":84,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"750189c6a07549e79a7c49834f6fbf23",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":436,
              "y":585},
            "size":{
              "width":84,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"10e4aaff0b80402f9b8677414b6e201a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":436,
                  "y":585},
                "size":{
                  "width":84,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a71a7ce155fe4450a3f0e71a035c7a14",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":436,
              "y":717},
            "size":{
              "width":84,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b84e62b05d0d4f6887984c520afdfa56",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":436,
                  "y":717},
                "size":{
                  "width":84,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"886389e1d4d7492988e6e00c85be8e6b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":436,
              "y":855},
            "size":{
              "width":84,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"88045603bf7a48da96d3f0be9bb35fdf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":436,
                  "y":855},
                "size":{
                  "width":84,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"958c08f5df104f08b9da41863eb180e7",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":502,
              "y":167},
            "size":{
              "width":135,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"c488fb55d0c14e01afeddd25944db93f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":668,
              "y":168},
            "size":{
              "width":114,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fc9dcce3ee7b4c0993a335c357eff5b7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":668,
                  "y":168},
                "size":{
                  "width":114,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"12497ff2ddb34d3c95c30cf862b4f1f9",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":737,
              "y":164},
            "size":{
              "width":135,
              "height":25}},
          "adaptiveStyles":{
}}]}},
  "masters":{
    "9aa3da306ba24637b281c884b1c30bca":{
      "packageId":"9aa3da306ba24637b281c884b1c30bca",
      "type":"Axure:Master",
      "name":"交易员底部",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"应用字体",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"aa94056b817049cbb1fa6bacb8c1e519",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "size":{
                "width":1400,
                "height":40},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFD7D7D7}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"d0f70829d22f42fea545dfa7923b52be",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "size":{
                    "width":1400,
                    "height":40},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFD7D7D7}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/首页/u13.png"}}]}},
    "d5b739f105d347138233b0627c50cf7b":{
      "packageId":"d5b739f105d347138233b0627c50cf7b",
      "type":"Axure:Master",
      "name":"交易员头部--托运",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"应用字体",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"ad29d0868e2d4e1ea04d2e3813cac53e",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "size":{
                "width":1400,
                "height":90},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFD7D7D7}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"705ba8054db8459aa453d6e8970360e1",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "size":{
                    "width":1400,
                    "height":90},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFD7D7D7}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/我的工作台/u3.png"}},
{
            "id":"435294aeef7344768378c778f254ae49",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":200,
                "y":15},
              "size":{
                "width":200,
                "height":60},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFD7D7D7}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"423f499025e441208a01286ce6aefd3d",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":200,
                    "y":15},
                  "size":{
                    "width":200,
                    "height":60},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFD7D7D7}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/我的工作台/u5.png"}},
{
            "id":"5bff7bb0f32e4aaba352a33b10354ace",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFFF2F2F2},
              "location":{
                "x":0,
                "y":90},
              "size":{
                "width":1400,
                "height":35},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFD7D7D7}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"4f781b78feb94e5c9e8d524ff73eadfc",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFF2F2F2},
                  "location":{
                    "x":0,
                    "y":90},
                  "size":{
                    "width":1400,
                    "height":35},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFD7D7D7}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/首页/u33.png"}},
{
            "id":"08ae0434c50140e782a3740366b35ef6",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":200,
                "y":90},
              "size":{
                "width":130,
                "height":35},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFD7D7D7}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"98765ab47746412d8d002e805dd3f5c8",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":200,
                    "y":90},
                  "size":{
                    "width":130,
                    "height":35},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFD7D7D7}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/我的工作台/u11.png"}},
{
            "id":"5b1950c85d9d43979ce7ee038d82addd",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":330,
                "y":90},
              "size":{
                "width":130,
                "height":35},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFD7D7D7}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"922258fa17a1468e89be4de887eb9242",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":330,
                    "y":90},
                  "size":{
                    "width":130,
                    "height":35},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFD7D7D7}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/我的工作台/u11.png"}},
{
            "id":"196b102fa5434693932ec2ccadc2aa72",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "horizontalAlignment":"right",
              "location":{
                "x":940,
                "y":15},
              "size":{
                "width":260,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"05799b485a82452f859a0923a542670d",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "horizontalAlignment":"right",
                  "location":{
                    "x":940,
                    "y":15},
                  "size":{
                    "width":260,
                    "height":16}},
                "adaptiveStyles":{
},
                "objects":[{
                    "id":"9224b06f5bc3462d9761fb8b32aaaefc",
                    "label":"",
                    "type":"hyperlink",
                    "styleType":"hyperlink",
                    "visible":true,
                    "style":{
},
                    "adaptiveStyles":{
},
                    "interactionMap":{
                      "onClick":{
                        "description":"OnClick",
                        "cases":[{
                            "description":"用例 1",
                            "isNewIfGroup":false,
                            "actions":[{
                                "action":"linkWindow",
                                "description":"在 当前窗口 打开 帐号设置",
                                "target":{
                                  "targetType":"page",
                                  "url":"帐号设置.html",
                                  "includeVariables":true},
                                "linkType":"current"}]}]}},
                    "tabbable":true}]}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"03c2d1c0a018442fbae9cadc97fdbf9e",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":460,
                "y":90},
              "size":{
                "width":130,
                "height":35},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFD7D7D7}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"e3ae0d1bffa6454e953785c75dd9411e",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":460,
                    "y":90},
                  "size":{
                    "width":130,
                    "height":35},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFD7D7D7}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/我的工作台/u11.png"}},
{
            "id":"29e560d07ab1441c8bd2c912e6128056",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":590,
                "y":90},
              "size":{
                "width":130,
                "height":35},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFD7D7D7}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"e21c32341ad54afcbba6d7060f2aed87",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":590,
                    "y":90},
                  "size":{
                    "width":130,
                    "height":35},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFD7D7D7}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/我的工作台/u11.png"}},
{
            "id":"a93032c21bff4eff9ce74ad7de209ec8",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":720,
                "y":90},
              "size":{
                "width":130,
                "height":35},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFD7D7D7}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"8f58a485ce114857b88238e6126eea08",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":720,
                    "y":90},
                  "size":{
                    "width":130,
                    "height":35},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFD7D7D7}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/我的工作台/u11.png"}},
{
            "id":"55c1a272476d4a028543b54a8dbbc346",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFFE4E4E4},
              "location":{
                "x":850,
                "y":90},
              "size":{
                "width":130,
                "height":35},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFD7D7D7}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"227b88b93913401bba3bd8014f0993e8",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFE4E4E4},
                  "location":{
                    "x":850,
                    "y":90},
                  "size":{
                    "width":130,
                    "height":35},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFD7D7D7}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/我的工作台/u9.png"}},
{
            "id":"30e27b2aeacd454b8ddd21f178272d3a",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":980,
                "y":90},
              "size":{
                "width":130,
                "height":35},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFD7D7D7}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"7851308e4e85456daf8cce58bc2f888f",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":980,
                    "y":90},
                  "size":{
                    "width":130,
                    "height":35},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFD7D7D7}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/我的工作台/u11.png"}}]}}},
  "objectPaths":{
    "7e14ac995f0b4b62bb66aed4ca5af205":{
      "scriptId":"u0"},
    "8e37b518e5e74383ab1e88eb81eb4f05":{
      "scriptId":"u1"},
    "c3b66501dae1400aa5044a5dfd2df54f":{
      "scriptId":"u2"},
    "ea383d0557b74814bc69cffc7d723b32":{
      "scriptId":"u3"},
    "cbf9240d37104121b2d477dbc58fb366":{
      "scriptId":"u4"},
    "95d6c6ca4af5436a93096edb1ede6bae":{
      "scriptId":"u5"},
    "d3553f67adb34663a7fd55452b613afa":{
      "scriptId":"u6",
      "aa94056b817049cbb1fa6bacb8c1e519":{
        "scriptId":"u7"},
      "d0f70829d22f42fea545dfa7923b52be":{
        "scriptId":"u8"}},
    "ea8fee36418046308dfed9766f4f8e94":{
      "scriptId":"u9"},
    "8361e49d3df2476fb845c2aa488324ed":{
      "scriptId":"u10"},
    "55618e73c52148a29dce9c431cf76aae":{
      "scriptId":"u11"},
    "7619e4a5fa5347a7922da21e20f7681b":{
      "scriptId":"u12"},
    "145cb17cfe794efe91cabc4281296f06":{
      "scriptId":"u13",
      "ad29d0868e2d4e1ea04d2e3813cac53e":{
        "scriptId":"u14"},
      "705ba8054db8459aa453d6e8970360e1":{
        "scriptId":"u15"},
      "435294aeef7344768378c778f254ae49":{
        "scriptId":"u16"},
      "423f499025e441208a01286ce6aefd3d":{
        "scriptId":"u17"},
      "5bff7bb0f32e4aaba352a33b10354ace":{
        "scriptId":"u18"},
      "4f781b78feb94e5c9e8d524ff73eadfc":{
        "scriptId":"u19"},
      "08ae0434c50140e782a3740366b35ef6":{
        "scriptId":"u20"},
      "98765ab47746412d8d002e805dd3f5c8":{
        "scriptId":"u21"},
      "5b1950c85d9d43979ce7ee038d82addd":{
        "scriptId":"u22"},
      "922258fa17a1468e89be4de887eb9242":{
        "scriptId":"u23"},
      "196b102fa5434693932ec2ccadc2aa72":{
        "scriptId":"u24"},
      "05799b485a82452f859a0923a542670d":{
        "scriptId":"u25"},
      "9224b06f5bc3462d9761fb8b32aaaefc":{
        "scriptId":"u26"},
      "03c2d1c0a018442fbae9cadc97fdbf9e":{
        "scriptId":"u27"},
      "e3ae0d1bffa6454e953785c75dd9411e":{
        "scriptId":"u28"},
      "29e560d07ab1441c8bd2c912e6128056":{
        "scriptId":"u29"},
      "e21c32341ad54afcbba6d7060f2aed87":{
        "scriptId":"u30"},
      "a93032c21bff4eff9ce74ad7de209ec8":{
        "scriptId":"u31"},
      "8f58a485ce114857b88238e6126eea08":{
        "scriptId":"u32"},
      "55c1a272476d4a028543b54a8dbbc346":{
        "scriptId":"u33"},
      "227b88b93913401bba3bd8014f0993e8":{
        "scriptId":"u34"},
      "30e27b2aeacd454b8ddd21f178272d3a":{
        "scriptId":"u35"},
      "7851308e4e85456daf8cce58bc2f888f":{
        "scriptId":"u36"}},
    "cc4b9acdb2de4615b1ccb03773254615":{
      "scriptId":"u37"},
    "4b2c94eb68ab4a60a8fbc799063682f8":{
      "scriptId":"u38"},
    "7387cdbf45c04af3acac86b870c167c8":{
      "scriptId":"u39"},
    "4a7178aa837e4a1ea3d3c44d82f5e662":{
      "scriptId":"u40"},
    "ee8ffe32df4f4dcdb13e0d6abb3b5e8b":{
      "scriptId":"u41"},
    "d7f7dffd36bc4095bfc6ed496b7b8bf6":{
      "scriptId":"u42"},
    "983021ce9e344ccbac62c97949945f1c":{
      "scriptId":"u43"},
    "83049fe637994dc48acf229512bc5427":{
      "scriptId":"u44"},
    "5e8cc304eb4943d38e1625e286979c52":{
      "scriptId":"u45"},
    "a274aefd86944952a21f6f842c3fe7a1":{
      "scriptId":"u46"},
    "e70e56cd7f6e43db9e723709529b832c":{
      "scriptId":"u47"},
    "39996d50c835457aad745a42f54a45a2":{
      "scriptId":"u48"},
    "8bdf799c61fd45eea836c5ca238040cc":{
      "scriptId":"u49"},
    "830c63da331e4b1eaa1e135e56e6328f":{
      "scriptId":"u50"},
    "113d3630f6a74df0a9f788c34127503d":{
      "scriptId":"u51"},
    "924da49fc7724592b400cdaa082b77ad":{
      "scriptId":"u52"},
    "b06486660ee44d98a41775742aa4a49c":{
      "scriptId":"u53"},
    "a94acfc43cf140939668c5f5f46b7843":{
      "scriptId":"u54"},
    "721b0a27070c4ea98772660449860ba8":{
      "scriptId":"u55"},
    "e77c6dc2a6f24344acc60f27a703508c":{
      "scriptId":"u56"},
    "8c9cd22a4d2f47c786db9974e4067946":{
      "scriptId":"u57"},
    "35f2c73ed3a842c999e4e616514bd7be":{
      "scriptId":"u58"},
    "1720e03f68b54124947f46f51baa964f":{
      "scriptId":"u59"},
    "ed2fe59625a84de284c9a0f44f96506f":{
      "scriptId":"u60"},
    "81065c598de94555a13b0a346c236183":{
      "scriptId":"u61"},
    "f0509428a88346df9e1b503a69faa89a":{
      "scriptId":"u62"},
    "dc55f5e55dce45fb8051d7886b7bfe8f":{
      "scriptId":"u63"},
    "a0d2d256d36241cea03442a269799979":{
      "scriptId":"u64"},
    "9c8a3a06b95d4f7bb9291eeb7e2c92ec":{
      "scriptId":"u65"},
    "783ff56c784545fcb85980b7845fec4e":{
      "scriptId":"u66"},
    "586eacc606af4216831476e004628960":{
      "scriptId":"u67"},
    "4e34a5a5d92844cf8090912b6d1721aa":{
      "scriptId":"u68"},
    "50ff9b12e4c84a32a5dd8f9d718738a6":{
      "scriptId":"u69"},
    "a8491ff9936e4d0694f5c351d641e485":{
      "scriptId":"u70"},
    "07b10e83bffe432e9bf545015d00a12c":{
      "scriptId":"u71"},
    "e7aad682267d4715bf266f41b08105e0":{
      "scriptId":"u72"},
    "f6be45f276ac4787a19f8fe727d34cd0":{
      "scriptId":"u73"},
    "5e9c4b59914940abbcd227f61b449b9b":{
      "scriptId":"u74"},
    "4e883ee239694f32a2ca1ada31ef6a6a":{
      "scriptId":"u75"},
    "e188dca67d2846929aecfba4e698ec5f":{
      "scriptId":"u76"},
    "e48a335c897540b19e351451dc6e51b9":{
      "scriptId":"u77"},
    "9f283bd300604b36bc107ef7e355d6a8":{
      "scriptId":"u78"},
    "2f00a4c76ba748e981c4206b83d0a1c2":{
      "scriptId":"u79"},
    "5896fa1a9ad843cca66470bbe544225d":{
      "scriptId":"u80"},
    "a635211b53f143108bdd2d1820ea0105":{
      "scriptId":"u81"},
    "f09bf31f300241b2b80eae54193f601f":{
      "scriptId":"u82"},
    "2f1152c762f54874bd99529901979025":{
      "scriptId":"u83"},
    "04936c8f8c8645a9883f4a6a8707f6ca":{
      "scriptId":"u84"},
    "9f0e7e5d9a6b43d5b2c64f92c8f5fe49":{
      "scriptId":"u85"},
    "b3cfe5f1aee1467fbf3e80eda8c4b2e2":{
      "scriptId":"u86"},
    "a532663f7be04af49b649d08fadc0cda":{
      "scriptId":"u87"},
    "db8f9a6b9a3845e6b0d594cd1dcc3ef9":{
      "scriptId":"u88"},
    "2f90bdf4d7ab4325a4fa86abaf7a69b2":{
      "scriptId":"u89"},
    "ad6515da0d314decb801e184f7ebc164":{
      "scriptId":"u90"},
    "4ffb395e06894f769ec9e1412827170b":{
      "scriptId":"u91"},
    "d7be615d26094c9b8f44fe2f71734f6a":{
      "scriptId":"u92"},
    "2e14841a3a804d049d3f733e4b182769":{
      "scriptId":"u93"},
    "bdc38dda903649f29afe9b2ece165b14":{
      "scriptId":"u94"},
    "ba4063ba0a1e4cd0a684d84e3252a85b":{
      "scriptId":"u95"},
    "78923917c0d44808aea30dde9907a87e":{
      "scriptId":"u96"},
    "300d17c415f34c72a564239e099e948e":{
      "scriptId":"u97"},
    "76d837e432a14612bca9f0f6ee782f80":{
      "scriptId":"u98"},
    "69315b8464ab4b70bb3d38a9550d7c39":{
      "scriptId":"u99"},
    "fa7036e65d064f7ead284f3607185cb6":{
      "scriptId":"u100"},
    "d265803a9df1458c9dad107722d25afc":{
      "scriptId":"u101"},
    "b8a388cef3944929ab76e93fd187d6fb":{
      "scriptId":"u102"},
    "fd0df0cee9d248e585b2516a1bfaac5e":{
      "scriptId":"u103"},
    "1cc6b96f70934304861c262601ce0375":{
      "scriptId":"u104"},
    "2364ae651e03427f9f7ad76370321ff7":{
      "scriptId":"u105"},
    "5bd6dcd097744d25a8fedf7c87255ad8":{
      "scriptId":"u106"},
    "1558715293424bfcaa2703f598ce17c5":{
      "scriptId":"u107"},
    "700d462b362240ea8406dfd480a51a70":{
      "scriptId":"u108"},
    "cb62f74d6afb457b90420985e3588e72":{
      "scriptId":"u109"},
    "edd8f8e1e6af4ebfbf58cd0a31611721":{
      "scriptId":"u110"},
    "d75d9effaba04c5aa2a0e3bcb7cfcde3":{
      "scriptId":"u111"},
    "caeef46534da45b693548699f3539da8":{
      "scriptId":"u112"},
    "4b2e7251feee475bab3b0de8b1254b16":{
      "scriptId":"u113"},
    "4850fa818881431e96246297dc12eeac":{
      "scriptId":"u114"},
    "85fc3d547ebc45cf87453b69bd08ad02":{
      "scriptId":"u115"},
    "0864ff47b64a4275b8a38e70f8aee603":{
      "scriptId":"u116"},
    "c9b07ced75df464a843d4de52d5d9bf2":{
      "scriptId":"u117"},
    "228705a29fe148d4805d0e5f6e046463":{
      "scriptId":"u118"},
    "49fdc27175394fa7b9d420f2bd0693c4":{
      "scriptId":"u119"},
    "3c68238b81a44320b6ffc7cad78c7363":{
      "scriptId":"u120"},
    "de26223b0c08411f9ba928cb29095ac6":{
      "scriptId":"u121"},
    "a3de77c599c9457ca77f137fd3b0db39":{
      "scriptId":"u122"},
    "d59086eeb6824ad4981c2bf6157dbd0d":{
      "scriptId":"u123"},
    "b51eb5b84b3647bab37e5f3650f652fa":{
      "scriptId":"u124"},
    "750189c6a07549e79a7c49834f6fbf23":{
      "scriptId":"u125"},
    "10e4aaff0b80402f9b8677414b6e201a":{
      "scriptId":"u126"},
    "a71a7ce155fe4450a3f0e71a035c7a14":{
      "scriptId":"u127"},
    "b84e62b05d0d4f6887984c520afdfa56":{
      "scriptId":"u128"},
    "886389e1d4d7492988e6e00c85be8e6b":{
      "scriptId":"u129"},
    "88045603bf7a48da96d3f0be9bb35fdf":{
      "scriptId":"u130"},
    "958c08f5df104f08b9da41863eb180e7":{
      "scriptId":"u131"},
    "c488fb55d0c14e01afeddd25944db93f":{
      "scriptId":"u132"},
    "fc9dcce3ee7b4c0993a335c357eff5b7":{
      "scriptId":"u133"},
    "12497ff2ddb34d3c95c30cf862b4f1f9":{
      "scriptId":"u134"}}});