$axure.loadCurrentPage({
  "url":"修改发布_1.html",
  "generationDate":new Date(1432872278955.57),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"2164d901079a4c018ea9275e563b27d0",
    "type":"Axure:Page",
    "name":"修改发布",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"ae8f94a672ed445f8dc17bb9e1b7a063",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":200,
              "y":170},
            "size":{
              "width":1000,
              "height":50},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFD7D7D7}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"76e520f7921643328fd076d2774e85bc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":200,
                  "y":170},
                "size":{
                  "width":1000,
                  "height":50},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/修改发布_1/u0.png"}},
{
          "id":"02a97ef64c4f40b68d06ebe3a5a05091",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":200,
              "y":220},
            "size":{
              "width":1000,
              "height":960},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFD7D7D7}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"79ef5e79ed184cde9c70f85bd6c8d079",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":200,
                  "y":220},
                "size":{
                  "width":1000,
                  "height":960},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/修改发布_1/u2.png"}},
{
          "id":"cb718ad299684a9f8fcbf829cf2051bd",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":256,
              "y":238},
            "size":{
              "width":93,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"06897969294b4783ab8f14e1e54abe65",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":256,
                  "y":238},
                "size":{
                  "width":93,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3f299f40c8d74c17947b9bad64db8cb3",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":379,
              "y":234},
            "size":{
              "width":495,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"7548ab1f41334d65a5b0c171eeba7f8d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":256,
              "y":274},
            "size":{
              "width":206,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fbdef277c95c4443ab48a4ffcd766737",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":256,
                  "y":274},
                "size":{
                  "width":206,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"544c020328ee48aaa61d4962c45f3b1e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"700",
            "location":{
              "x":256,
              "y":919},
            "size":{
              "width":206,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4dcd2056b79a4d00a34c3526932d70f9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"700",
                "location":{
                  "x":256,
                  "y":919},
                "size":{
                  "width":206,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"15899b2e5d24415186897f5c3e64f7a9",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":381,
              "y":566},
            "size":{
              "width":711,
              "height":165}},
          "adaptiveStyles":{
}},
{
          "id":"95ebb9bfa76241b891da251146e644a9",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":256,
              "y":964},
            "size":{
              "width":206,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"002712ec13884d169a604909946e15ae",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":256,
                  "y":964},
                "size":{
                  "width":206,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9cda915ea9ab4f2cb28154d9eebfc071",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":379,
              "y":960},
            "size":{
              "width":305,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"9d5e3fcf365c44eabeb181dd9f9635f0",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":256,
              "y":999},
            "size":{
              "width":206,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9039fc1c67954f4091fe54015bce097a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":256,
                  "y":999},
                "size":{
                  "width":206,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3aba557b4a724a788f0ef9fd677e4272",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":379,
              "y":995},
            "size":{
              "width":495,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"d2113f220deb4c37bc4ce0692bee92aa",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":379,
              "y":1098},
            "size":{
              "width":216,
              "height":50}},
          "adaptiveStyles":{
}},
{
          "id":"584564f5f05d4061b68b170822c064d8",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF949494,
              "opacity":1},
            "location":{
              "x":256,
              "y":182},
            "size":{
              "width":121,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1e2f48447ae64c8994ed74fccb1cc829",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF949494,
                  "opacity":1},
                "location":{
                  "x":256,
                  "y":182},
                "size":{
                  "width":121,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"efd0214c08234ebea3a54de66c988e94",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":256,
              "y":540},
            "size":{
              "width":206,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b69a7effa351489fa1e43b27b2cba99b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":256,
                  "y":540},
                "size":{
                  "width":206,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c7f7c45f509e4be58a722edaf4f717b2",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":379,
              "y":535},
            "size":{
              "width":718,
              "height":39}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"762218661554492c9f4f7af5666450f4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":379,
                  "y":535},
                "size":{
                  "width":718,
                  "height":39}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/上传资源单/u222.png"}},
{
          "id":"7c4d9804766c442ba67793de3f8efc22",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":256,
              "y":1035},
            "size":{
              "width":206,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3a612862e3ce48a1bc18401737810b81",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":256,
                  "y":1035},
                "size":{
                  "width":206,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"01daaadc47244c8194613514ccf8eb3b",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":379,
              "y":1030},
            "size":{
              "width":305,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"b2154b81c2ae4f489595dd985a4733be",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":379,
              "y":269},
            "size":{
              "width":495,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"010954d8dd694b2f9df4b23c5bfe3b0c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":256,
              "y":308},
            "size":{
              "width":206,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1087db38a8c94a4facd1547309f4605f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":256,
                  "y":308},
                "size":{
                  "width":206,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"eb2cf0889da7455eba82a560a112def0",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF333333,
              "opacity":1},
            "location":{
              "x":379,
              "y":304},
            "size":{
              "width":495,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"77714aec277e4456bbc8bda6e406811d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":256,
              "y":343},
            "size":{
              "width":206,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"288de883b98641a18ae740762c62a2df",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":256,
                  "y":343},
                "size":{
                  "width":206,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"fbc9f36f282c4ee5a9fb35f40d1e69c2",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":379,
              "y":339},
            "size":{
              "width":495,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"db8bc6b81dd84799bf413438721cf78f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":256,
              "y":380},
            "size":{
              "width":206,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"894fd16560974da9b9537c041f85ab56",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":256,
                  "y":380},
                "size":{
                  "width":206,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f286453b024f4244b43a37d1f9a00dcc",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":379,
              "y":376},
            "size":{
              "width":495,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"36aeb25e2ccd4e86a997fe1a33152bad",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":256,
              "y":415},
            "size":{
              "width":206,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"64d0e667d12d420b95ba4d32be11ba66",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":256,
                  "y":415},
                "size":{
                  "width":206,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6ee71763d25d4509be843d53b22aff6f",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":379,
              "y":411},
            "size":{
              "width":495,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"8f08553043af4718b1389d07ec16c1f4",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":256,
              "y":453},
            "size":{
              "width":206,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ae37e9a8f7c2473bb21795ef906df684",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":256,
                  "y":453},
                "size":{
                  "width":206,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7fac4c08f2e145fbb0c766aefadeb98f",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":379,
              "y":450},
            "size":{
              "width":206,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"b3cdb4c438f740ceb7f82ed9c2f079cb",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":256,
              "y":492},
            "size":{
              "width":206,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"23029ce4229a4ca0bc92821061db1017",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":256,
                  "y":492},
                "size":{
                  "width":206,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f941e6da05e04566bc574a26cab2d2b5",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":379,
              "y":489},
            "size":{
              "width":95,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"9cc4cf48a0ed4de48bae6496d7e494ac",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":485,
              "y":488},
            "size":{
              "width":101,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"c4c29840004a4771a759bdf6f665a357",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":597,
              "y":492},
            "size":{
              "width":206,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"57108606f9ec45a788d94f160f14f708",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":597,
                  "y":492},
                "size":{
                  "width":206,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2ac68299f01a4d8d8bd04117e2c44bd1",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":256,
              "y":854},
            "size":{
              "width":181,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2ebc4728df8c49d292c8ca4bbb9b6700",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":256,
                  "y":854},
                "size":{
                  "width":181,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5c73c089600f41c4904ce457fa61575b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":256,
              "y":821},
            "size":{
              "width":206,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c6da1528e01c47d79bef3b0cc3c63c37",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":256,
                  "y":821},
                "size":{
                  "width":206,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e59441660627473fb7185bf706c5b4bd",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":379,
              "y":818},
            "size":{
              "width":113,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"f4aa7d8e93184b84bf9dbe08709279b4",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":503,
              "y":818},
            "size":{
              "width":113,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"fb6dae1c79914f36a32e7cc7fd00143d",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":627,
              "y":818},
            "size":{
              "width":113,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"4851c76ea2af4f02993f468c0f13ee33",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":379,
              "y":850},
            "size":{
              "width":124,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"4317e1df804b4ca3af52c9d7742e91ad",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":484,
              "y":852},
            "size":{
              "width":18,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ed6b78f068264ab3bb2a8ea370bbdba0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":484,
                  "y":852},
                "size":{
                  "width":18,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/发布采购单/u97.png"}},
{
          "id":"16e3e8f236e34531801fff00e772978c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "lineSpacing":"20px",
            "location":{
              "x":511,
              "y":854},
            "size":{
              "width":666,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"407cf70eb75b4be890195cc1d0a6913d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "lineSpacing":"20px",
                "location":{
                  "x":511,
                  "y":854},
                "size":{
                  "width":666,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"da1310ab1ae4499ebdac4f231880c07f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":256,
              "y":762},
            "size":{
              "width":206,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"28a165b2e96d4df09e60d15e49f86bcb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":256,
                  "y":762},
                "size":{
                  "width":206,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"dde48095130144d18be3653cd1728f39",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":379,
              "y":757},
            "size":{
              "width":206,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"acfa5631c3f34460a088843c6bc94cbf",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":592,
              "y":762},
            "size":{
              "width":330,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cb8e1c8916b64a26ab47f27acbcaa9bc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":592,
                  "y":762},
                "size":{
                  "width":330,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"78b9c07ae73642b0a7133ea28d56eab9",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":256,
              "y":792},
            "size":{
              "width":206,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d1c12dda01cd445c8da39026d0f9089d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":256,
                  "y":792},
                "size":{
                  "width":206,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"54ffd21e10db4a5f8ad841c850d01b97",
          "label":"",
          "type":"radioButton",
          "styleType":"radioButton",
          "visible":true,
          "style":{
            "location":{
              "x":379,
              "y":792},
            "size":{
              "width":103,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"356418634249440fa3ace1ed0aad40b0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":379,
                  "y":792},
                "size":{
                  "width":103,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"4480243578f944629c003b26d68ebda0",
          "label":"",
          "type":"radioButton",
          "styleType":"radioButton",
          "visible":true,
          "style":{
            "location":{
              "x":482,
              "y":792},
            "size":{
              "width":103,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c2638ba6568246f7ad02ab4659cad999",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":482,
                  "y":792},
                "size":{
                  "width":103,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"6d969f6ac6f74d6994395cd6bda19247",
          "label":"",
          "type":"radioButton",
          "styleType":"radioButton",
          "visible":true,
          "style":{
            "location":{
              "x":586,
              "y":792},
            "size":{
              "width":103,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a7e95ffa5f80461a8f5b75d97b40c676",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":586,
                  "y":792},
                "size":{
                  "width":103,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"b979391e706f42f1b9caa3613e34fabe",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
},
          "adaptiveStyles":{
},
          "masterId":"d46401a06c1e4b89b7df1b25949937b2"},
{
          "id":"89d798bffbb9415ebc49341fbc286daf",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":1200}},
          "adaptiveStyles":{
},
          "masterId":"9aa3da306ba24637b281c884b1c30bca"}]}},
  "masters":{
    "d46401a06c1e4b89b7df1b25949937b2":{
      "packageId":"d46401a06c1e4b89b7df1b25949937b2",
      "type":"Axure:Master",
      "name":"交易员头部--采购",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"应用字体",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"11a2262448e0441f9a29e02867462317",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "size":{
                "width":1400,
                "height":90},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFD7D7D7}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"2fb6fec02a5946deb468d94b926d5702",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "size":{
                    "width":1400,
                    "height":90},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFD7D7D7}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/我的工作台/u3.png"}},
{
            "id":"d272761cc28841aabfc377d601a1ee83",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":200,
                "y":15},
              "size":{
                "width":200,
                "height":60},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFD7D7D7}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"304b1fa2e1004612895198bae19aad1c",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":200,
                    "y":15},
                  "size":{
                    "width":200,
                    "height":60},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFD7D7D7}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/我的工作台/u5.png"}},
{
            "id":"1ff87331235e44d3907f0495638c3ee8",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":0,
                "y":90},
              "size":{
                "width":1400,
                "height":35},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFD7D7D7}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"8dea732008a44e7ba0aa5e0d23bc0e6b",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":0,
                    "y":90},
                  "size":{
                    "width":1400,
                    "height":35},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFD7D7D7}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/采购管理_1/u17.png"}},
{
            "id":"0ae756c78f1d4827bd92090a57c2445d",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":200,
                "y":90},
              "size":{
                "width":130,
                "height":35},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFD7D7D7}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"fa593240b6704c1390d0e2aefef6074a",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":200,
                    "y":90},
                  "size":{
                    "width":130,
                    "height":35},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFD7D7D7}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/我的工作台/u11.png"}},
{
            "id":"3718fe3583d442998538f8f62ebde4ea",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":330,
                "y":90},
              "size":{
                "width":130,
                "height":35},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFD7D7D7}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"13c36587be2d43fe8c5570fc2d88bd70",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":330,
                    "y":90},
                  "size":{
                    "width":130,
                    "height":35},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFD7D7D7}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/我的工作台/u11.png"}},
{
            "id":"7605c42231844874b2c96607badb0850",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "horizontalAlignment":"right",
              "location":{
                "x":940,
                "y":15},
              "size":{
                "width":260,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"984bcf4d07254baba8671ebc15bf96cb",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "horizontalAlignment":"right",
                  "location":{
                    "x":940,
                    "y":15},
                  "size":{
                    "width":260,
                    "height":16}},
                "adaptiveStyles":{
},
                "objects":[{
                    "id":"2f74abe178134b94b65ef27c84a0b10c",
                    "label":"",
                    "type":"hyperlink",
                    "styleType":"hyperlink",
                    "visible":true,
                    "style":{
},
                    "adaptiveStyles":{
},
                    "interactionMap":{
                      "onClick":{
                        "description":"OnClick",
                        "cases":[{
                            "description":"用例 1",
                            "isNewIfGroup":false,
                            "actions":[{
                                "action":"linkWindow",
                                "description":"在 当前窗口 打开 帐号设置",
                                "target":{
                                  "targetType":"page",
                                  "url":"帐号设置.html",
                                  "includeVariables":true},
                                "linkType":"current"}]}]}},
                    "tabbable":true}]}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"a429c1e2aff64addaaa099e07e66daf5",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":460,
                "y":90},
              "size":{
                "width":130,
                "height":35},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFD7D7D7}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"881c32b5d1f94845a14d88dbbbfd5243",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":460,
                    "y":90},
                  "size":{
                    "width":130,
                    "height":35},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFD7D7D7}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/我的工作台/u11.png"}},
{
            "id":"b126bc9f382d48879198610315ee4e59",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFFE4E4E4},
              "location":{
                "x":590,
                "y":90},
              "size":{
                "width":130,
                "height":35},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFD7D7D7}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"bdc5a116b70e44d38274557da8097264",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFE4E4E4},
                  "location":{
                    "x":590,
                    "y":90},
                  "size":{
                    "width":130,
                    "height":35},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFD7D7D7}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/我的工作台/u9.png"}},
{
            "id":"a4ba979bdeba41d29e3cd3326b6c3198",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":720,
                "y":90},
              "size":{
                "width":130,
                "height":35},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFD7D7D7}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"bab036d936394aecb0ad756249f71cde",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":720,
                    "y":90},
                  "size":{
                    "width":130,
                    "height":35},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFD7D7D7}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/我的工作台/u11.png"}},
{
            "id":"10506aa0892a466ea5a09fd469114a67",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":850,
                "y":90},
              "size":{
                "width":130,
                "height":35},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFD7D7D7}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"584f0797854c4c60942fdc3c761fd9b9",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":850,
                    "y":90},
                  "size":{
                    "width":130,
                    "height":35},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFD7D7D7}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/我的工作台/u11.png"}},
{
            "id":"5ac36443a26244dbb4de436ae575e0b1",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":980,
                "y":90},
              "size":{
                "width":130,
                "height":35},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFD7D7D7}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"88a5040bb63a4e1389a8aaf44f149200",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":980,
                    "y":90},
                  "size":{
                    "width":130,
                    "height":35},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFD7D7D7}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/我的工作台/u11.png"}}]}},
    "9aa3da306ba24637b281c884b1c30bca":{
      "packageId":"9aa3da306ba24637b281c884b1c30bca",
      "type":"Axure:Master",
      "name":"交易员底部",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"应用字体",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"aa94056b817049cbb1fa6bacb8c1e519",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "size":{
                "width":1400,
                "height":40},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFD7D7D7}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"d0f70829d22f42fea545dfa7923b52be",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "size":{
                    "width":1400,
                    "height":40},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFD7D7D7}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/首页/u13.png"}}]}}},
  "objectPaths":{
    "ae8f94a672ed445f8dc17bb9e1b7a063":{
      "scriptId":"u0"},
    "76e520f7921643328fd076d2774e85bc":{
      "scriptId":"u1"},
    "02a97ef64c4f40b68d06ebe3a5a05091":{
      "scriptId":"u2"},
    "79ef5e79ed184cde9c70f85bd6c8d079":{
      "scriptId":"u3"},
    "cb718ad299684a9f8fcbf829cf2051bd":{
      "scriptId":"u4"},
    "06897969294b4783ab8f14e1e54abe65":{
      "scriptId":"u5"},
    "3f299f40c8d74c17947b9bad64db8cb3":{
      "scriptId":"u6"},
    "7548ab1f41334d65a5b0c171eeba7f8d":{
      "scriptId":"u7"},
    "fbdef277c95c4443ab48a4ffcd766737":{
      "scriptId":"u8"},
    "544c020328ee48aaa61d4962c45f3b1e":{
      "scriptId":"u9"},
    "4dcd2056b79a4d00a34c3526932d70f9":{
      "scriptId":"u10"},
    "15899b2e5d24415186897f5c3e64f7a9":{
      "scriptId":"u11"},
    "95ebb9bfa76241b891da251146e644a9":{
      "scriptId":"u12"},
    "002712ec13884d169a604909946e15ae":{
      "scriptId":"u13"},
    "9cda915ea9ab4f2cb28154d9eebfc071":{
      "scriptId":"u14"},
    "9d5e3fcf365c44eabeb181dd9f9635f0":{
      "scriptId":"u15"},
    "9039fc1c67954f4091fe54015bce097a":{
      "scriptId":"u16"},
    "3aba557b4a724a788f0ef9fd677e4272":{
      "scriptId":"u17"},
    "d2113f220deb4c37bc4ce0692bee92aa":{
      "scriptId":"u18"},
    "584564f5f05d4061b68b170822c064d8":{
      "scriptId":"u19"},
    "1e2f48447ae64c8994ed74fccb1cc829":{
      "scriptId":"u20"},
    "efd0214c08234ebea3a54de66c988e94":{
      "scriptId":"u21"},
    "b69a7effa351489fa1e43b27b2cba99b":{
      "scriptId":"u22"},
    "c7f7c45f509e4be58a722edaf4f717b2":{
      "scriptId":"u23"},
    "762218661554492c9f4f7af5666450f4":{
      "scriptId":"u24"},
    "7c4d9804766c442ba67793de3f8efc22":{
      "scriptId":"u25"},
    "3a612862e3ce48a1bc18401737810b81":{
      "scriptId":"u26"},
    "01daaadc47244c8194613514ccf8eb3b":{
      "scriptId":"u27"},
    "b2154b81c2ae4f489595dd985a4733be":{
      "scriptId":"u28"},
    "010954d8dd694b2f9df4b23c5bfe3b0c":{
      "scriptId":"u29"},
    "1087db38a8c94a4facd1547309f4605f":{
      "scriptId":"u30"},
    "eb2cf0889da7455eba82a560a112def0":{
      "scriptId":"u31"},
    "77714aec277e4456bbc8bda6e406811d":{
      "scriptId":"u32"},
    "288de883b98641a18ae740762c62a2df":{
      "scriptId":"u33"},
    "fbc9f36f282c4ee5a9fb35f40d1e69c2":{
      "scriptId":"u34"},
    "db8bc6b81dd84799bf413438721cf78f":{
      "scriptId":"u35"},
    "894fd16560974da9b9537c041f85ab56":{
      "scriptId":"u36"},
    "f286453b024f4244b43a37d1f9a00dcc":{
      "scriptId":"u37"},
    "36aeb25e2ccd4e86a997fe1a33152bad":{
      "scriptId":"u38"},
    "64d0e667d12d420b95ba4d32be11ba66":{
      "scriptId":"u39"},
    "6ee71763d25d4509be843d53b22aff6f":{
      "scriptId":"u40"},
    "8f08553043af4718b1389d07ec16c1f4":{
      "scriptId":"u41"},
    "ae37e9a8f7c2473bb21795ef906df684":{
      "scriptId":"u42"},
    "7fac4c08f2e145fbb0c766aefadeb98f":{
      "scriptId":"u43"},
    "b3cdb4c438f740ceb7f82ed9c2f079cb":{
      "scriptId":"u44"},
    "23029ce4229a4ca0bc92821061db1017":{
      "scriptId":"u45"},
    "f941e6da05e04566bc574a26cab2d2b5":{
      "scriptId":"u46"},
    "9cc4cf48a0ed4de48bae6496d7e494ac":{
      "scriptId":"u47"},
    "c4c29840004a4771a759bdf6f665a357":{
      "scriptId":"u48"},
    "57108606f9ec45a788d94f160f14f708":{
      "scriptId":"u49"},
    "2ac68299f01a4d8d8bd04117e2c44bd1":{
      "scriptId":"u50"},
    "2ebc4728df8c49d292c8ca4bbb9b6700":{
      "scriptId":"u51"},
    "5c73c089600f41c4904ce457fa61575b":{
      "scriptId":"u52"},
    "c6da1528e01c47d79bef3b0cc3c63c37":{
      "scriptId":"u53"},
    "e59441660627473fb7185bf706c5b4bd":{
      "scriptId":"u54"},
    "f4aa7d8e93184b84bf9dbe08709279b4":{
      "scriptId":"u55"},
    "fb6dae1c79914f36a32e7cc7fd00143d":{
      "scriptId":"u56"},
    "4851c76ea2af4f02993f468c0f13ee33":{
      "scriptId":"u57"},
    "4317e1df804b4ca3af52c9d7742e91ad":{
      "scriptId":"u58"},
    "ed6b78f068264ab3bb2a8ea370bbdba0":{
      "scriptId":"u59"},
    "16e3e8f236e34531801fff00e772978c":{
      "scriptId":"u60"},
    "407cf70eb75b4be890195cc1d0a6913d":{
      "scriptId":"u61"},
    "da1310ab1ae4499ebdac4f231880c07f":{
      "scriptId":"u62"},
    "28a165b2e96d4df09e60d15e49f86bcb":{
      "scriptId":"u63"},
    "dde48095130144d18be3653cd1728f39":{
      "scriptId":"u64"},
    "acfa5631c3f34460a088843c6bc94cbf":{
      "scriptId":"u65"},
    "cb8e1c8916b64a26ab47f27acbcaa9bc":{
      "scriptId":"u66"},
    "78b9c07ae73642b0a7133ea28d56eab9":{
      "scriptId":"u67"},
    "d1c12dda01cd445c8da39026d0f9089d":{
      "scriptId":"u68"},
    "54ffd21e10db4a5f8ad841c850d01b97":{
      "scriptId":"u69"},
    "356418634249440fa3ace1ed0aad40b0":{
      "scriptId":"u70"},
    "4480243578f944629c003b26d68ebda0":{
      "scriptId":"u71"},
    "c2638ba6568246f7ad02ab4659cad999":{
      "scriptId":"u72"},
    "6d969f6ac6f74d6994395cd6bda19247":{
      "scriptId":"u73"},
    "a7e95ffa5f80461a8f5b75d97b40c676":{
      "scriptId":"u74"},
    "b979391e706f42f1b9caa3613e34fabe":{
      "scriptId":"u75",
      "11a2262448e0441f9a29e02867462317":{
        "scriptId":"u76"},
      "2fb6fec02a5946deb468d94b926d5702":{
        "scriptId":"u77"},
      "d272761cc28841aabfc377d601a1ee83":{
        "scriptId":"u78"},
      "304b1fa2e1004612895198bae19aad1c":{
        "scriptId":"u79"},
      "1ff87331235e44d3907f0495638c3ee8":{
        "scriptId":"u80"},
      "8dea732008a44e7ba0aa5e0d23bc0e6b":{
        "scriptId":"u81"},
      "0ae756c78f1d4827bd92090a57c2445d":{
        "scriptId":"u82"},
      "fa593240b6704c1390d0e2aefef6074a":{
        "scriptId":"u83"},
      "3718fe3583d442998538f8f62ebde4ea":{
        "scriptId":"u84"},
      "13c36587be2d43fe8c5570fc2d88bd70":{
        "scriptId":"u85"},
      "7605c42231844874b2c96607badb0850":{
        "scriptId":"u86"},
      "984bcf4d07254baba8671ebc15bf96cb":{
        "scriptId":"u87"},
      "2f74abe178134b94b65ef27c84a0b10c":{
        "scriptId":"u88"},
      "a429c1e2aff64addaaa099e07e66daf5":{
        "scriptId":"u89"},
      "881c32b5d1f94845a14d88dbbbfd5243":{
        "scriptId":"u90"},
      "b126bc9f382d48879198610315ee4e59":{
        "scriptId":"u91"},
      "bdc5a116b70e44d38274557da8097264":{
        "scriptId":"u92"},
      "a4ba979bdeba41d29e3cd3326b6c3198":{
        "scriptId":"u93"},
      "bab036d936394aecb0ad756249f71cde":{
        "scriptId":"u94"},
      "10506aa0892a466ea5a09fd469114a67":{
        "scriptId":"u95"},
      "584f0797854c4c60942fdc3c761fd9b9":{
        "scriptId":"u96"},
      "5ac36443a26244dbb4de436ae575e0b1":{
        "scriptId":"u97"},
      "88a5040bb63a4e1389a8aaf44f149200":{
        "scriptId":"u98"}},
    "89d798bffbb9415ebc49341fbc286daf":{
      "scriptId":"u99",
      "aa94056b817049cbb1fa6bacb8c1e519":{
        "scriptId":"u100"},
      "d0f70829d22f42fea545dfa7923b52be":{
        "scriptId":"u101"}}}});