$axure.loadCurrentPage({
  "url":"发布采购单_1.html",
  "generationDate":new Date(1432872280825.68),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"f6299d3587764870ab5bd6a46f83aa7f",
    "type":"Axure:Page",
    "name":"发布采购单",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"2224f569720042e28523ee406fa346c5",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":200,
              "y":170},
            "size":{
              "width":1000,
              "height":50},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFD7D7D7}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9201cd9ec6d24e5f8ec5bfb45cf8060b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":200,
                  "y":170},
                "size":{
                  "width":1000,
                  "height":50},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/修改发布_1/u0.png"}},
{
          "id":"ee1f72382986436db12d3b57fa6f2467",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":200,
              "y":220},
            "size":{
              "width":1000,
              "height":990},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFD7D7D7}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7bbeb7ae06a64e01bb10541f6465a126",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":200,
                  "y":220},
                "size":{
                  "width":1000,
                  "height":990},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/发布采购单_1/u2.png"}},
{
          "id":"0b0e25ec710e40db99c5cb8074b1041d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":256,
              "y":284},
            "size":{
              "width":93,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"30b843c245504fccb8dd573ac6df946e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":256,
                  "y":284},
                "size":{
                  "width":93,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"26ebffe3d42d4cc2b7366e7179e4671b",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":379,
              "y":280},
            "size":{
              "width":495,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"4761508edd4e47838ad841d5096c717a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":256,
              "y":320},
            "size":{
              "width":206,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4adb26d1d13749c1a966e642a8b5a4b1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":256,
                  "y":320},
                "size":{
                  "width":206,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5a39e0fc4c8549feaa8f3d99622dc73d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"700",
            "location":{
              "x":256,
              "y":965},
            "size":{
              "width":206,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5728ca9deade45b7807788851c90f86b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"700",
                "location":{
                  "x":256,
                  "y":965},
                "size":{
                  "width":206,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a74dd55d22c84baa83297a0fb8f28dd1",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":381,
              "y":612},
            "size":{
              "width":711,
              "height":165}},
          "adaptiveStyles":{
}},
{
          "id":"471a88930bd34442a81109a738ae10ea",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":256,
              "y":1010},
            "size":{
              "width":206,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"938152f7b16d43c6b882ba574e53ce67",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":256,
                  "y":1010},
                "size":{
                  "width":206,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"22e3b34e521f4b79aa6169da36456c82",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":379,
              "y":1006},
            "size":{
              "width":305,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"bb02b7d4969b4f338489d5465fa46d6d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":256,
              "y":1045},
            "size":{
              "width":206,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"342caa5b70b4497782a8a9762c30e268",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":256,
                  "y":1045},
                "size":{
                  "width":206,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"98d0680aea834e02811fed1b53649ac7",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":379,
              "y":1041},
            "size":{
              "width":495,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"38ab3bf2a35f4093940160c680c681ca",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":379,
              "y":1144},
            "size":{
              "width":216,
              "height":50}},
          "adaptiveStyles":{
}},
{
          "id":"beef27c433804117858c85bab6ecb298",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF949494,
              "opacity":1},
            "location":{
              "x":256,
              "y":182},
            "size":{
              "width":121,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1e2b68d27f7941808e1e4316ae262208",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF949494,
                  "opacity":1},
                "location":{
                  "x":256,
                  "y":182},
                "size":{
                  "width":121,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c34070542883407286cd0f5f04453478",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":256,
              "y":586},
            "size":{
              "width":206,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f9e9abac420a4930aa192f30e068ce88",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":256,
                  "y":586},
                "size":{
                  "width":206,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f0c99b5aa3ec4bfb9b37a9c0295bc8a2",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":379,
              "y":581},
            "size":{
              "width":718,
              "height":39}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e19e273d543e4b90ad4368cce84a1b9d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":379,
                  "y":581},
                "size":{
                  "width":718,
                  "height":39}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/上传资源单/u222.png"}},
{
          "id":"9dacbbda41a74223882c8d6ef700c555",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":256,
              "y":1081},
            "size":{
              "width":206,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a061ed9f504142d68c4b3408b223e302",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":256,
                  "y":1081},
                "size":{
                  "width":206,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"350a76f2e8844a91898266248745e3c1",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":379,
              "y":1076},
            "size":{
              "width":305,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"079ca1029c0540ef916878e2e43ca8d9",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":379,
              "y":315},
            "size":{
              "width":495,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"73b935c799f34aada17e34d6be99bc0f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":256,
              "y":354},
            "size":{
              "width":206,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f088b78d0d594040b913df4172bf1026",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":256,
                  "y":354},
                "size":{
                  "width":206,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8bd3b1da4c9a4a129747228ce6f71263",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":379,
              "y":350},
            "size":{
              "width":495,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"1ad91f93999f4709b03c880509a0d987",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":256,
              "y":389},
            "size":{
              "width":206,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f4167fb859e341dc8eb554883e33f275",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":256,
                  "y":389},
                "size":{
                  "width":206,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6a8dbc64ff044431b0df8e3eb8c0052b",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":379,
              "y":385},
            "size":{
              "width":495,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"425ab2f428064c0486ae45dbfe3def15",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":256,
              "y":426},
            "size":{
              "width":206,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ac6ccc1fb4a346e9b05d66b6d57e3f60",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":256,
                  "y":426},
                "size":{
                  "width":206,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2fbb6aedd39143d9b1f467b6c72d9449",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":379,
              "y":422},
            "size":{
              "width":495,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"5533d6caa3604e9cb7eb261ffcce44a6",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":256,
              "y":461},
            "size":{
              "width":206,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"455f7f4563d9462b95d6b8483390dafc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":256,
                  "y":461},
                "size":{
                  "width":206,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4ce7f740c4e04da8aca545d0509ea9fb",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":379,
              "y":457},
            "size":{
              "width":495,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"6bbecdd6f9aa42e8b6c2d86d19818fed",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":256,
              "y":499},
            "size":{
              "width":206,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"533060e4e41b401fafb21fec9058a53c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":256,
                  "y":499},
                "size":{
                  "width":206,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f6934329222646fca0cdfbec97d8cfa2",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":379,
              "y":496},
            "size":{
              "width":206,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"00b1a51952694d0a889f79a9ad5e8e5d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":256,
              "y":538},
            "size":{
              "width":206,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"37b9498cfdf643bfbeb5bce76d9d65e3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":256,
                  "y":538},
                "size":{
                  "width":206,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6fa8a3955c7a4c9ea67639ece5fd647f",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":379,
              "y":535},
            "size":{
              "width":95,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"8a9393d76b7a42e3a164684d1069e414",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":485,
              "y":534},
            "size":{
              "width":101,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"0dd33c4a8a5748a9a5c7a9b864d80786",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":597,
              "y":538},
            "size":{
              "width":206,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7c4d327823384e0dac8de39e3c8f8e2d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":597,
                  "y":538},
                "size":{
                  "width":206,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"526daedcf2634c0080756d11f41d5984",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":256,
              "y":900},
            "size":{
              "width":181,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5becd5c220ed47bbbac1721db73557c3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":256,
                  "y":900},
                "size":{
                  "width":181,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a3266c11b06d4eaaacffc51dfd32f904",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":256,
              "y":867},
            "size":{
              "width":206,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4c0f182a57ec4a76b6cebe8f444a0aef",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":256,
                  "y":867},
                "size":{
                  "width":206,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7c9b5c973c9f48ea817724b7e3425c3c",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":379,
              "y":864},
            "size":{
              "width":113,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"48ceeb5bdc8047d6ac6cb301f8ee014f",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":503,
              "y":864},
            "size":{
              "width":113,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"e2a515424593488d8adef9283486dd53",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":627,
              "y":864},
            "size":{
              "width":113,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"7519d76a7c1f4f67889884cfe5c4b4ef",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":379,
              "y":896},
            "size":{
              "width":124,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"59f1c191adf6448087d6fba91ba12f87",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":484,
              "y":898},
            "size":{
              "width":18,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"03fcbb835d7d4c5c999854771f8c7b04",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":484,
                  "y":898},
                "size":{
                  "width":18,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/发布采购单/u97.png"}},
{
          "id":"f0ba903922a44069b44042f2c2fae361",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "lineSpacing":"20px",
            "location":{
              "x":511,
              "y":900},
            "size":{
              "width":666,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d41c577063e5406f807d9fedb172b963",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "lineSpacing":"20px",
                "location":{
                  "x":511,
                  "y":900},
                "size":{
                  "width":666,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5d06946a2534497c9b8f28f32d980246",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":256,
              "y":808},
            "size":{
              "width":206,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"824a8ae906dd4f999dba36a5ebaab6f5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":256,
                  "y":808},
                "size":{
                  "width":206,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1c6e425fce074da5acaad024d75f2283",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":379,
              "y":803},
            "size":{
              "width":206,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"f9cdc0d4d46f47baa00ed955f33bd536",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":592,
              "y":808},
            "size":{
              "width":330,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c01ba757750d45e7a0ac47af58124c5b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":592,
                  "y":808},
                "size":{
                  "width":330,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9778c7b493454ff29002e0b3cc8e104d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":256,
              "y":838},
            "size":{
              "width":206,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"803d6d8524e848d997ee30660e5302d3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":256,
                  "y":838},
                "size":{
                  "width":206,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8ca76eb751864f97a8c099cf572c0744",
          "label":"",
          "type":"radioButton",
          "styleType":"radioButton",
          "visible":true,
          "style":{
            "location":{
              "x":379,
              "y":838},
            "size":{
              "width":103,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e77cae4a366e4cda816533c5c71db128",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":379,
                  "y":838},
                "size":{
                  "width":103,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"7307a2b77c9e4b86ac95077a3a349cf6",
          "label":"",
          "type":"radioButton",
          "styleType":"radioButton",
          "visible":true,
          "style":{
            "location":{
              "x":482,
              "y":838},
            "size":{
              "width":103,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2a21df1156a54ec28011e33f9840bb22",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":482,
                  "y":838},
                "size":{
                  "width":103,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"5642d124d3b3456eb6966a308eeab91a",
          "label":"",
          "type":"radioButton",
          "styleType":"radioButton",
          "visible":true,
          "style":{
            "location":{
              "x":586,
              "y":838},
            "size":{
              "width":103,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"456eefea867e489f844954986beae296",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":586,
                  "y":838},
                "size":{
                  "width":103,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"66ca5707c7604dc09de87d75e99cd512",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
},
          "adaptiveStyles":{
},
          "masterId":"d46401a06c1e4b89b7df1b25949937b2"},
{
          "id":"ec499167f32547d68ed8b6c3953a7761",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontWeight":"700",
            "location":{
              "x":256,
              "y":236},
            "size":{
              "width":80,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"958493be59334b859820276cb174df1c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"700",
                "location":{
                  "x":256,
                  "y":236},
                "size":{
                  "width":80,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"bec28844f80c4e539dbd15d2021732d7",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":326,
              "y":233},
            "size":{
              "width":130,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"339c72a25bc346ddb20565dd2bc24b1d",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":1230}},
          "adaptiveStyles":{
},
          "masterId":"9aa3da306ba24637b281c884b1c30bca"}]}},
  "masters":{
    "d46401a06c1e4b89b7df1b25949937b2":{
      "packageId":"d46401a06c1e4b89b7df1b25949937b2",
      "type":"Axure:Master",
      "name":"交易员头部--采购",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"应用字体",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"11a2262448e0441f9a29e02867462317",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "size":{
                "width":1400,
                "height":90},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFD7D7D7}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"2fb6fec02a5946deb468d94b926d5702",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "size":{
                    "width":1400,
                    "height":90},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFD7D7D7}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/我的工作台/u3.png"}},
{
            "id":"d272761cc28841aabfc377d601a1ee83",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":200,
                "y":15},
              "size":{
                "width":200,
                "height":60},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFD7D7D7}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"304b1fa2e1004612895198bae19aad1c",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":200,
                    "y":15},
                  "size":{
                    "width":200,
                    "height":60},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFD7D7D7}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/我的工作台/u5.png"}},
{
            "id":"1ff87331235e44d3907f0495638c3ee8",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":0,
                "y":90},
              "size":{
                "width":1400,
                "height":35},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFD7D7D7}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"8dea732008a44e7ba0aa5e0d23bc0e6b",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":0,
                    "y":90},
                  "size":{
                    "width":1400,
                    "height":35},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFD7D7D7}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/采购管理_1/u17.png"}},
{
            "id":"0ae756c78f1d4827bd92090a57c2445d",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":200,
                "y":90},
              "size":{
                "width":130,
                "height":35},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFD7D7D7}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"fa593240b6704c1390d0e2aefef6074a",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":200,
                    "y":90},
                  "size":{
                    "width":130,
                    "height":35},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFD7D7D7}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/我的工作台/u11.png"}},
{
            "id":"3718fe3583d442998538f8f62ebde4ea",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":330,
                "y":90},
              "size":{
                "width":130,
                "height":35},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFD7D7D7}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"13c36587be2d43fe8c5570fc2d88bd70",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":330,
                    "y":90},
                  "size":{
                    "width":130,
                    "height":35},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFD7D7D7}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/我的工作台/u11.png"}},
{
            "id":"7605c42231844874b2c96607badb0850",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "horizontalAlignment":"right",
              "location":{
                "x":940,
                "y":15},
              "size":{
                "width":260,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"984bcf4d07254baba8671ebc15bf96cb",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "horizontalAlignment":"right",
                  "location":{
                    "x":940,
                    "y":15},
                  "size":{
                    "width":260,
                    "height":16}},
                "adaptiveStyles":{
},
                "objects":[{
                    "id":"2f74abe178134b94b65ef27c84a0b10c",
                    "label":"",
                    "type":"hyperlink",
                    "styleType":"hyperlink",
                    "visible":true,
                    "style":{
},
                    "adaptiveStyles":{
},
                    "interactionMap":{
                      "onClick":{
                        "description":"OnClick",
                        "cases":[{
                            "description":"用例 1",
                            "isNewIfGroup":false,
                            "actions":[{
                                "action":"linkWindow",
                                "description":"在 当前窗口 打开 帐号设置",
                                "target":{
                                  "targetType":"page",
                                  "url":"帐号设置.html",
                                  "includeVariables":true},
                                "linkType":"current"}]}]}},
                    "tabbable":true}]}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"a429c1e2aff64addaaa099e07e66daf5",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":460,
                "y":90},
              "size":{
                "width":130,
                "height":35},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFD7D7D7}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"881c32b5d1f94845a14d88dbbbfd5243",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":460,
                    "y":90},
                  "size":{
                    "width":130,
                    "height":35},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFD7D7D7}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/我的工作台/u11.png"}},
{
            "id":"b126bc9f382d48879198610315ee4e59",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFFE4E4E4},
              "location":{
                "x":590,
                "y":90},
              "size":{
                "width":130,
                "height":35},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFD7D7D7}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"bdc5a116b70e44d38274557da8097264",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFE4E4E4},
                  "location":{
                    "x":590,
                    "y":90},
                  "size":{
                    "width":130,
                    "height":35},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFD7D7D7}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/我的工作台/u9.png"}},
{
            "id":"a4ba979bdeba41d29e3cd3326b6c3198",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":720,
                "y":90},
              "size":{
                "width":130,
                "height":35},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFD7D7D7}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"bab036d936394aecb0ad756249f71cde",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":720,
                    "y":90},
                  "size":{
                    "width":130,
                    "height":35},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFD7D7D7}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/我的工作台/u11.png"}},
{
            "id":"10506aa0892a466ea5a09fd469114a67",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":850,
                "y":90},
              "size":{
                "width":130,
                "height":35},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFD7D7D7}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"584f0797854c4c60942fdc3c761fd9b9",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":850,
                    "y":90},
                  "size":{
                    "width":130,
                    "height":35},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFD7D7D7}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/我的工作台/u11.png"}},
{
            "id":"5ac36443a26244dbb4de436ae575e0b1",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":980,
                "y":90},
              "size":{
                "width":130,
                "height":35},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFD7D7D7}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"88a5040bb63a4e1389a8aaf44f149200",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":980,
                    "y":90},
                  "size":{
                    "width":130,
                    "height":35},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFD7D7D7}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/我的工作台/u11.png"}}]}},
    "9aa3da306ba24637b281c884b1c30bca":{
      "packageId":"9aa3da306ba24637b281c884b1c30bca",
      "type":"Axure:Master",
      "name":"交易员底部",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"应用字体",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"aa94056b817049cbb1fa6bacb8c1e519",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "size":{
                "width":1400,
                "height":40},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFD7D7D7}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"d0f70829d22f42fea545dfa7923b52be",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "size":{
                    "width":1400,
                    "height":40},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFD7D7D7}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/首页/u13.png"}}]}}},
  "objectPaths":{
    "2224f569720042e28523ee406fa346c5":{
      "scriptId":"u0"},
    "9201cd9ec6d24e5f8ec5bfb45cf8060b":{
      "scriptId":"u1"},
    "ee1f72382986436db12d3b57fa6f2467":{
      "scriptId":"u2"},
    "7bbeb7ae06a64e01bb10541f6465a126":{
      "scriptId":"u3"},
    "0b0e25ec710e40db99c5cb8074b1041d":{
      "scriptId":"u4"},
    "30b843c245504fccb8dd573ac6df946e":{
      "scriptId":"u5"},
    "26ebffe3d42d4cc2b7366e7179e4671b":{
      "scriptId":"u6"},
    "4761508edd4e47838ad841d5096c717a":{
      "scriptId":"u7"},
    "4adb26d1d13749c1a966e642a8b5a4b1":{
      "scriptId":"u8"},
    "5a39e0fc4c8549feaa8f3d99622dc73d":{
      "scriptId":"u9"},
    "5728ca9deade45b7807788851c90f86b":{
      "scriptId":"u10"},
    "a74dd55d22c84baa83297a0fb8f28dd1":{
      "scriptId":"u11"},
    "471a88930bd34442a81109a738ae10ea":{
      "scriptId":"u12"},
    "938152f7b16d43c6b882ba574e53ce67":{
      "scriptId":"u13"},
    "22e3b34e521f4b79aa6169da36456c82":{
      "scriptId":"u14"},
    "bb02b7d4969b4f338489d5465fa46d6d":{
      "scriptId":"u15"},
    "342caa5b70b4497782a8a9762c30e268":{
      "scriptId":"u16"},
    "98d0680aea834e02811fed1b53649ac7":{
      "scriptId":"u17"},
    "38ab3bf2a35f4093940160c680c681ca":{
      "scriptId":"u18"},
    "beef27c433804117858c85bab6ecb298":{
      "scriptId":"u19"},
    "1e2b68d27f7941808e1e4316ae262208":{
      "scriptId":"u20"},
    "c34070542883407286cd0f5f04453478":{
      "scriptId":"u21"},
    "f9e9abac420a4930aa192f30e068ce88":{
      "scriptId":"u22"},
    "f0c99b5aa3ec4bfb9b37a9c0295bc8a2":{
      "scriptId":"u23"},
    "e19e273d543e4b90ad4368cce84a1b9d":{
      "scriptId":"u24"},
    "9dacbbda41a74223882c8d6ef700c555":{
      "scriptId":"u25"},
    "a061ed9f504142d68c4b3408b223e302":{
      "scriptId":"u26"},
    "350a76f2e8844a91898266248745e3c1":{
      "scriptId":"u27"},
    "079ca1029c0540ef916878e2e43ca8d9":{
      "scriptId":"u28"},
    "73b935c799f34aada17e34d6be99bc0f":{
      "scriptId":"u29"},
    "f088b78d0d594040b913df4172bf1026":{
      "scriptId":"u30"},
    "8bd3b1da4c9a4a129747228ce6f71263":{
      "scriptId":"u31"},
    "1ad91f93999f4709b03c880509a0d987":{
      "scriptId":"u32"},
    "f4167fb859e341dc8eb554883e33f275":{
      "scriptId":"u33"},
    "6a8dbc64ff044431b0df8e3eb8c0052b":{
      "scriptId":"u34"},
    "425ab2f428064c0486ae45dbfe3def15":{
      "scriptId":"u35"},
    "ac6ccc1fb4a346e9b05d66b6d57e3f60":{
      "scriptId":"u36"},
    "2fbb6aedd39143d9b1f467b6c72d9449":{
      "scriptId":"u37"},
    "5533d6caa3604e9cb7eb261ffcce44a6":{
      "scriptId":"u38"},
    "455f7f4563d9462b95d6b8483390dafc":{
      "scriptId":"u39"},
    "4ce7f740c4e04da8aca545d0509ea9fb":{
      "scriptId":"u40"},
    "6bbecdd6f9aa42e8b6c2d86d19818fed":{
      "scriptId":"u41"},
    "533060e4e41b401fafb21fec9058a53c":{
      "scriptId":"u42"},
    "f6934329222646fca0cdfbec97d8cfa2":{
      "scriptId":"u43"},
    "00b1a51952694d0a889f79a9ad5e8e5d":{
      "scriptId":"u44"},
    "37b9498cfdf643bfbeb5bce76d9d65e3":{
      "scriptId":"u45"},
    "6fa8a3955c7a4c9ea67639ece5fd647f":{
      "scriptId":"u46"},
    "8a9393d76b7a42e3a164684d1069e414":{
      "scriptId":"u47"},
    "0dd33c4a8a5748a9a5c7a9b864d80786":{
      "scriptId":"u48"},
    "7c4d327823384e0dac8de39e3c8f8e2d":{
      "scriptId":"u49"},
    "526daedcf2634c0080756d11f41d5984":{
      "scriptId":"u50"},
    "5becd5c220ed47bbbac1721db73557c3":{
      "scriptId":"u51"},
    "a3266c11b06d4eaaacffc51dfd32f904":{
      "scriptId":"u52"},
    "4c0f182a57ec4a76b6cebe8f444a0aef":{
      "scriptId":"u53"},
    "7c9b5c973c9f48ea817724b7e3425c3c":{
      "scriptId":"u54"},
    "48ceeb5bdc8047d6ac6cb301f8ee014f":{
      "scriptId":"u55"},
    "e2a515424593488d8adef9283486dd53":{
      "scriptId":"u56"},
    "7519d76a7c1f4f67889884cfe5c4b4ef":{
      "scriptId":"u57"},
    "59f1c191adf6448087d6fba91ba12f87":{
      "scriptId":"u58"},
    "03fcbb835d7d4c5c999854771f8c7b04":{
      "scriptId":"u59"},
    "f0ba903922a44069b44042f2c2fae361":{
      "scriptId":"u60"},
    "d41c577063e5406f807d9fedb172b963":{
      "scriptId":"u61"},
    "5d06946a2534497c9b8f28f32d980246":{
      "scriptId":"u62"},
    "824a8ae906dd4f999dba36a5ebaab6f5":{
      "scriptId":"u63"},
    "1c6e425fce074da5acaad024d75f2283":{
      "scriptId":"u64"},
    "f9cdc0d4d46f47baa00ed955f33bd536":{
      "scriptId":"u65"},
    "c01ba757750d45e7a0ac47af58124c5b":{
      "scriptId":"u66"},
    "9778c7b493454ff29002e0b3cc8e104d":{
      "scriptId":"u67"},
    "803d6d8524e848d997ee30660e5302d3":{
      "scriptId":"u68"},
    "8ca76eb751864f97a8c099cf572c0744":{
      "scriptId":"u69"},
    "e77cae4a366e4cda816533c5c71db128":{
      "scriptId":"u70"},
    "7307a2b77c9e4b86ac95077a3a349cf6":{
      "scriptId":"u71"},
    "2a21df1156a54ec28011e33f9840bb22":{
      "scriptId":"u72"},
    "5642d124d3b3456eb6966a308eeab91a":{
      "scriptId":"u73"},
    "456eefea867e489f844954986beae296":{
      "scriptId":"u74"},
    "66ca5707c7604dc09de87d75e99cd512":{
      "scriptId":"u75",
      "11a2262448e0441f9a29e02867462317":{
        "scriptId":"u76"},
      "2fb6fec02a5946deb468d94b926d5702":{
        "scriptId":"u77"},
      "d272761cc28841aabfc377d601a1ee83":{
        "scriptId":"u78"},
      "304b1fa2e1004612895198bae19aad1c":{
        "scriptId":"u79"},
      "1ff87331235e44d3907f0495638c3ee8":{
        "scriptId":"u80"},
      "8dea732008a44e7ba0aa5e0d23bc0e6b":{
        "scriptId":"u81"},
      "0ae756c78f1d4827bd92090a57c2445d":{
        "scriptId":"u82"},
      "fa593240b6704c1390d0e2aefef6074a":{
        "scriptId":"u83"},
      "3718fe3583d442998538f8f62ebde4ea":{
        "scriptId":"u84"},
      "13c36587be2d43fe8c5570fc2d88bd70":{
        "scriptId":"u85"},
      "7605c42231844874b2c96607badb0850":{
        "scriptId":"u86"},
      "984bcf4d07254baba8671ebc15bf96cb":{
        "scriptId":"u87"},
      "2f74abe178134b94b65ef27c84a0b10c":{
        "scriptId":"u88"},
      "a429c1e2aff64addaaa099e07e66daf5":{
        "scriptId":"u89"},
      "881c32b5d1f94845a14d88dbbbfd5243":{
        "scriptId":"u90"},
      "b126bc9f382d48879198610315ee4e59":{
        "scriptId":"u91"},
      "bdc5a116b70e44d38274557da8097264":{
        "scriptId":"u92"},
      "a4ba979bdeba41d29e3cd3326b6c3198":{
        "scriptId":"u93"},
      "bab036d936394aecb0ad756249f71cde":{
        "scriptId":"u94"},
      "10506aa0892a466ea5a09fd469114a67":{
        "scriptId":"u95"},
      "584f0797854c4c60942fdc3c761fd9b9":{
        "scriptId":"u96"},
      "5ac36443a26244dbb4de436ae575e0b1":{
        "scriptId":"u97"},
      "88a5040bb63a4e1389a8aaf44f149200":{
        "scriptId":"u98"}},
    "ec499167f32547d68ed8b6c3953a7761":{
      "scriptId":"u99"},
    "958493be59334b859820276cb174df1c":{
      "scriptId":"u100"},
    "bec28844f80c4e539dbd15d2021732d7":{
      "scriptId":"u101"},
    "339c72a25bc346ddb20565dd2bc24b1d":{
      "scriptId":"u102",
      "aa94056b817049cbb1fa6bacb8c1e519":{
        "scriptId":"u103"},
      "d0f70829d22f42fea545dfa7923b52be":{
        "scriptId":"u104"}}}});