$axure.loadCurrentPage({
  "url":"审核_1.html",
  "generationDate":new Date(1432872284137.87),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"dabd97ae3e264a40b1618d27da65d784",
    "type":"Axure:Page",
    "name":"审核",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"878b883b71424b58b012e8e95594024b",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
},
          "adaptiveStyles":{
},
          "masterId":"a9e111da73474fc58a4e9af309efe76e"},
{
          "id":"a3591aa678ed45aba3e1c7bafc260629",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":200,
              "y":150},
            "size":{
              "width":200,
              "height":80},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFD7D7D7}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"57488c0e71af48aaab36fcba511fcf40",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":200,
                  "y":150},
                "size":{
                  "width":200,
                  "height":80},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的工作台/u26.png"}},
{
          "id":"938ac582bbc9475793edc8dd4ef1adc6",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFE4E4E4},
            "location":{
              "x":200,
              "y":230},
            "size":{
              "width":200,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFD7D7D7}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"63ecb87eaa5043ad87c44821b68bd5e3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4},
                "location":{
                  "x":200,
                  "y":230},
                "size":{
                  "width":200,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的工作台/u28.png"}},
{
          "id":"afb61ca40e9640c989e8647c0947c3b2",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":200,
              "y":360},
            "size":{
              "width":200,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFD7D7D7}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5cdb5b58b5634d78a13ab0a515818d9d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":200,
                  "y":360},
                "size":{
                  "width":200,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的工作台/u30.png"}},
{
          "id":"24313bcad25844379c004e7c6635f0df",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":200,
              "y":400},
            "size":{
              "width":200,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFD7D7D7}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4d8fd73c126d4c6d9f705b670df24862",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":200,
                  "y":400},
                "size":{
                  "width":200,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的工作台/u30.png"}},
{
          "id":"0ea4e23ad3da4bb1935658e895327488",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":200,
              "y":440},
            "size":{
              "width":200,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFD7D7D7}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e41d2e3948b64f268b04ee7b5c5b2313",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":200,
                  "y":440},
                "size":{
                  "width":200,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的工作台/u30.png"}},
{
          "id":"470ca1d23b1b40d5971f821b1e10c754",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":200,
              "y":480},
            "size":{
              "width":200,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFD7D7D7}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"601b98c100554d7381371ca4f01bea07",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":200,
                  "y":480},
                "size":{
                  "width":200,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的工作台/u30.png"}},
{
          "id":"9b483c53be9f4ecd83ff13dd639daaeb",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "location":{
              "x":210,
              "y":300},
            "size":{
              "width":190,
              "height":30},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFD7D7D7}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9594e6ad202d4cd1b087858f6dcc03fd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "location":{
                  "x":210,
                  "y":300},
                "size":{
                  "width":190,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/管理资源单/u235.png"}},
{
          "id":"9bb2e2a93d5d4fae844ab6ec5310047e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "location":{
              "x":210,
              "y":330},
            "size":{
              "width":190,
              "height":30},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFD7D7D7}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"edab6376abef4901a764697d012fb0d7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "location":{
                  "x":210,
                  "y":330},
                "size":{
                  "width":190,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/管理资源单/u235.png"}},
{
          "id":"25f72dc27ec54983bc3cfd2058de8e41",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "fill":{
              "fillType":"solid",
              "color":0xFFE4E4E4},
            "location":{
              "x":210,
              "y":270},
            "size":{
              "width":190,
              "height":30},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFD7D7D7}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a71d203f1deb4fd3a1232afe5ad04fd3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4},
                "location":{
                  "x":210,
                  "y":270},
                "size":{
                  "width":190,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/管理资源单/u233.png"}},
{
          "id":"ec8cdae2c5d24018993c42b9bdf35259",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":420,
              "y":150},
            "size":{
              "width":780,
              "height":1250},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFD7D7D7}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ec255d60cb794e97b8ee2e403965e2ce",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":420,
                  "y":150},
                "size":{
                  "width":780,
                  "height":1250},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/审核_1/u42.png"}},
{
          "id":"ed85eb18feb14521b6d0d79ff8ab0579",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "location":{
              "x":440,
              "y":164},
            "size":{
              "width":210,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ebe0d226f36e42dca57338c55517981a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "location":{
                  "x":440,
                  "y":164},
                "size":{
                  "width":210,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0b577342682a416397ca96f4dd09621f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":440,
              "y":225},
            "size":{
              "width":90,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6f23f7dd65f847f99f77c43166a43622",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":440,
                  "y":225},
                "size":{
                  "width":90,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2a8ad2e256684cf8b932d821f1c00a75",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":440,
              "y":258},
            "size":{
              "width":90,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9f8df5c5f7e94c128a55bda67fbc89c4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":440,
                  "y":258},
                "size":{
                  "width":90,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1cb34bcf3c804ebd9d840e29451a9c6e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":440,
              "y":292},
            "size":{
              "width":90,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bf836e2dee5942a3984268d5b8402a0f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":440,
                  "y":292},
                "size":{
                  "width":90,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e3d1a2c231c14b09938c412ec23d1d55",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":440,
              "y":326},
            "size":{
              "width":90,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"db9a6399732a4068832d72d64517a787",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":440,
                  "y":326},
                "size":{
                  "width":90,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"783c85d7eb9049e2851ecc48a6741923",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":440,
              "y":1163},
            "size":{
              "width":110,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"405ac77aa4b34a50a1fdea589e1e1882",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":440,
                  "y":1163},
                "size":{
                  "width":110,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ab859cdf6e444ad6950376b315e952ea",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":440,
              "y":359},
            "size":{
              "width":90,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9962f1a895494e27b30ccb1ac2482e3c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":440,
                  "y":359},
                "size":{
                  "width":90,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1a730b4d0a72454495ab932801501206",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":510,
              "y":359},
            "size":{
              "width":166,
              "height":118}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a2b04bbc6d334e5db1e27f7706ab8d94",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":510,
                  "y":359},
                "size":{
                  "width":166,
                  "height":118}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/增加车辆/u196.png"}},
{
          "id":"99f4cf488acd4f82832499a68c337e21",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "lineSpacing":"20px",
            "location":{
              "x":880,
              "y":457},
            "size":{
              "width":440,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7cfa295509cc4f15a8b530f372f7215b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "lineSpacing":"20px",
                "location":{
                  "x":880,
                  "y":457},
                "size":{
                  "width":440,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"468d677b62d64ad6b10dd06c96a09b39",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":440,
              "y":517},
            "size":{
              "width":90,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"44faeee4c3ef450a97428d560cb76af1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":440,
                  "y":517},
                "size":{
                  "width":90,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3d9843b78d044724b1f83dbe71fade96",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":534,
              "y":517},
            "size":{
              "width":166,
              "height":118}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"815dd791e7ec461681e4e2e86165b903",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":534,
                  "y":517},
                "size":{
                  "width":166,
                  "height":118}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/增加车辆/u196.png"}},
{
          "id":"40b7d2dca1bc47da95e159f276752071",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":440,
              "y":661},
            "size":{
              "width":90,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7b00319ea0c7474f967e21baecb84826",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":440,
                  "y":661},
                "size":{
                  "width":90,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"05b87e9044544e638a5d337bc6695a6b",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":534,
              "y":661},
            "size":{
              "width":166,
              "height":118}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ebb1613d45df483e9821d3bdb7556aee",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":534,
                  "y":661},
                "size":{
                  "width":166,
                  "height":118}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/增加车辆/u196.png"}},
{
          "id":"4cf71be1fe344ec4844b57fab9a9a4c0",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":440,
              "y":1109},
            "size":{
              "width":90,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"326ee3b39c734f17b9b89135517c5eb9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":440,
                  "y":1109},
                "size":{
                  "width":90,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"bc55e54460f44a52b6d34f4b6fc75893",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":440,
              "y":809},
            "size":{
              "width":90,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d93aca5112734c419074cc724967f9fa",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":440,
                  "y":809},
                "size":{
                  "width":90,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e0c7c27be7b94b1a943d381e8b31662b",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":534,
              "y":809},
            "size":{
              "width":166,
              "height":118}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"137eb6c102c34c569020359d3df9587c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":534,
                  "y":809},
                "size":{
                  "width":166,
                  "height":118}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/增加车辆/u196.png"}},
{
          "id":"ae3b451cfaa846eb81ef17031b174222",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":698,
              "y":359},
            "size":{
              "width":166,
              "height":118}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"05321bce0480417d8bccbe90653176ce",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":698,
                  "y":359},
                "size":{
                  "width":166,
                  "height":118}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/增加车辆/u196.png"}},
{
          "id":"c5b6dc810d3f4df59acc1195f24f7857",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":440,
              "y":959},
            "size":{
              "width":90,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d398d3f56ad44dc1b3dfd22d97569de2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":440,
                  "y":959},
                "size":{
                  "width":90,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9227be88b0a24e63a4a021733c842cb8",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":534,
              "y":959},
            "size":{
              "width":166,
              "height":118}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"034ce5926d6349f4b897e5019e02c480",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":534,
                  "y":959},
                "size":{
                  "width":166,
                  "height":118}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/增加车辆/u196.png"}},
{
          "id":"00d65cf0f13e41a8956e5daba973f3a3",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":729,
              "y":959},
            "size":{
              "width":166,
              "height":118}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b30542eae88540609de5f5dc00d8ad7c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":729,
                  "y":959},
                "size":{
                  "width":166,
                  "height":118}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/增加车辆/u196.png"}},
{
          "id":"e644e4ed9c724b4b9fc843b1ba52d2ab",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":924,
              "y":959},
            "size":{
              "width":166,
              "height":118}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d905a8b4c417430d82b58e4b0aebacd3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":924,
                  "y":959},
                "size":{
                  "width":166,
                  "height":118}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/增加车辆/u196.png"}},
{
          "id":"42d1f85b38984573a5dc5ca5d06e22e5",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":510,
              "y":225},
            "size":{
              "width":90,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3fd3a7cfa57a41ae9776ad260f89421e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":510,
                  "y":225},
                "size":{
                  "width":90,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5174a378ea3646b1a809608e8fe5bf47",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":510,
              "y":258},
            "size":{
              "width":90,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"67eae9eed8074ebd8273d3908a058e40",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":510,
                  "y":258},
                "size":{
                  "width":90,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"85b0f94501594484baf78657993f2a19",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":510,
              "y":292},
            "size":{
              "width":90,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b2f891494e454491b838ecde3c580b52",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":510,
                  "y":292},
                "size":{
                  "width":90,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4f6fc7e2426c46c1bcd47e52c7509619",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":510,
              "y":326},
            "size":{
              "width":90,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0395f5c3e3b84966bf72b1be3f6b0c62",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":510,
                  "y":326},
                "size":{
                  "width":90,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"89eace7ee19c437789aa4ed9415e6640",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "lineSpacing":"20px",
            "location":{
              "x":710,
              "y":615},
            "size":{
              "width":440,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ddd7a3536b854a0d9076fbac31875382",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "lineSpacing":"20px",
                "location":{
                  "x":710,
                  "y":615},
                "size":{
                  "width":440,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3bd43a7b78064f2eb7fbde905af8952d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "lineSpacing":"20px",
            "location":{
              "x":710,
              "y":759},
            "size":{
              "width":440,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2b3402c117da4573937429ce0005627e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "lineSpacing":"20px",
                "location":{
                  "x":710,
                  "y":759},
                "size":{
                  "width":440,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"92055bb431c04ab88f39fdbb63553682",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "lineSpacing":"20px",
            "location":{
              "x":710,
              "y":907},
            "size":{
              "width":440,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"61e7da11fb3848c7829ff1a20940365b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "lineSpacing":"20px",
                "location":{
                  "x":710,
                  "y":907},
                "size":{
                  "width":440,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d914e524b8c940fb908f1e73f3e2e7a8",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":510,
              "y":1109},
            "size":{
              "width":90,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"73b313cbe48e466c94002eb3eeb717ef",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":510,
                  "y":1109},
                "size":{
                  "width":90,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1ad03c6a400d492ea604cf8e05be36d0",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":534,
              "y":1163},
            "size":{
              "width":686,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"514d7ea5a7b648e8b2075ded3380aeff",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":534,
                  "y":1163},
                "size":{
                  "width":686,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c30b1318771d4674a6994dd403a3b7aa",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":440,
              "y":1198},
            "size":{
              "width":740,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFD7D7D7}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/审核_1/u104_line.png"}},
{
          "id":"dc3083ec6fa842acb7c4aa6129147506",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontWeight":"700",
            "location":{
              "x":440,
              "y":1218},
            "size":{
              "width":100,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a7afe7290dbc4b129dd1ea5217e0c32c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"700",
                "location":{
                  "x":440,
                  "y":1218},
                "size":{
                  "width":100,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3738eb2ef5ae4e699136d6723b369fa7",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":510,
              "y":1215},
            "size":{
              "width":140,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"6c7c175a5c194558a59235671a30da13",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":440,
              "y":1249},
            "size":{
              "width":60,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"74e5427de1f94b6b9328babde6180b54",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":440,
                  "y":1249},
                "size":{
                  "width":60,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7b88d4cf3c594aba83a8a3a759d9fa9f",
          "label":"",
          "type":"textArea",
          "styleType":"textArea",
          "visible":true,
          "style":{
            "location":{
              "x":510,
              "y":1247},
            "size":{
              "width":670,
              "height":91}},
          "adaptiveStyles":{
}},
{
          "id":"b4d4b257875540debe017e4a772f578e",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":510,
              "y":1348},
            "size":{
              "width":100,
              "height":40}},
          "adaptiveStyles":{
}},
{
          "id":"6e6a261685c2427eb6543b3b9d8ae950",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontWeight":"700",
            "location":{
              "x":420,
              "y":1410},
            "size":{
              "width":218,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"07e1b67992084684864ee56f9e8b0558",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"700",
                "location":{
                  "x":420,
                  "y":1410},
                "size":{
                  "width":218,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"543ca5154d9547b3aa1aead0e7815b2a",
          "label":"",
          "type":"table",
          "styleType":"table",
          "visible":true,
          "style":{
            "location":{
              "x":420,
              "y":1436},
            "size":{
              "width":780,
              "height":71}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"581f792829c046638a0a9848c81184e4",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"700",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "size":{
                  "width":148,
                  "height":35},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"c05eb68d857c47e1bc94b900c3acba21",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Arial Negreta', 'Arial'",
                    "fontWeight":"700",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFF2F2F2},
                    "size":{
                      "width":148,
                      "height":35},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFD7D7D7}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/审核_1/u115.png"}},
{
              "id":"45e4f404220d4f748ffb3b94394a0d62",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":35},
                "size":{
                  "width":148,
                  "height":36},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"28623f6407fd446dbd9e5907ed36a108",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":35},
                    "size":{
                      "width":148,
                      "height":36},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFD7D7D7}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/审核_1/u121.png"}},
{
              "id":"db4d334ec98f41e59c69fbbd0250074e",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"700",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":148,
                  "y":0},
                "size":{
                  "width":125,
                  "height":35},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"ef3e81ad4d204dc79426a0e0e9f872fa",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Arial Negreta', 'Arial'",
                    "fontWeight":"700",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFF2F2F2},
                    "location":{
                      "x":148,
                      "y":0},
                    "size":{
                      "width":125,
                      "height":35},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFD7D7D7}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/审核_1/u117.png"}},
{
              "id":"1e12a98d03984a6a9b54003deb9e24a1",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "verticalAlignment":"middle",
                "location":{
                  "x":148,
                  "y":35},
                "size":{
                  "width":125,
                  "height":36},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"1ab08da9b64d4ea3b272c7c9704b7ad1",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "verticalAlignment":"middle",
                    "location":{
                      "x":148,
                      "y":35},
                    "size":{
                      "width":125,
                      "height":36},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFD7D7D7}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/审核_1/u123.png"}},
{
              "id":"76afd076e02f49fcb0423cc3645ba510",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"700",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":273,
                  "y":0},
                "size":{
                  "width":507,
                  "height":35},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"5cefabdf534347e7b130b49b7cd0138e",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Arial Negreta', 'Arial'",
                    "fontWeight":"700",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFF2F2F2},
                    "location":{
                      "x":273,
                      "y":0},
                    "size":{
                      "width":507,
                      "height":35},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFD7D7D7}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/审核_1/u119.png"}},
{
              "id":"84a737be5fea484cbc1b62e55d8d628e",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "verticalAlignment":"middle",
                "location":{
                  "x":273,
                  "y":35},
                "size":{
                  "width":507,
                  "height":36},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"bc88906a88eb4716bd72657e1d2d0832",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "verticalAlignment":"middle",
                    "location":{
                      "x":273,
                      "y":35},
                    "size":{
                      "width":507,
                      "height":36},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFD7D7D7}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/审核_1/u125.png"}}]},
{
          "id":"c9b14943bf60487e874a6320bb46a11e",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":1528}},
          "adaptiveStyles":{
},
          "masterId":"9aa3da306ba24637b281c884b1c30bca"},
{
          "id":"3956780ca09e463d816453bc06525879",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":440,
              "y":196},
            "size":{
              "width":90,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"664ab3c52b4a47349153a34eda7bca41",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":440,
                  "y":196},
                "size":{
                  "width":90,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7f30c00689a445adb52babb748111f51",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":510,
              "y":196},
            "size":{
              "width":90,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a7e209d7d2044fc69091612484d706ef",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":510,
                  "y":196},
                "size":{
                  "width":90,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b283a273726a4711bfe6c78a4d6d8775",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":200,
              "y":520},
            "size":{
              "width":200,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFD7D7D7}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"95683a1461004b3585c9f2224b65a584",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":200,
                  "y":520},
                "size":{
                  "width":200,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的工作台/u30.png"}}]}},
  "masters":{
    "a9e111da73474fc58a4e9af309efe76e":{
      "packageId":"a9e111da73474fc58a4e9af309efe76e",
      "type":"Axure:Master",
      "name":"交易员头部--承运管理",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"应用字体",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"11a2262448e0441f9a29e02867462317",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "size":{
                "width":1400,
                "height":90},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFD7D7D7}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"2fb6fec02a5946deb468d94b926d5702",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "size":{
                    "width":1400,
                    "height":90},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFD7D7D7}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/我的工作台/u3.png"}},
{
            "id":"d272761cc28841aabfc377d601a1ee83",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":200,
                "y":15},
              "size":{
                "width":200,
                "height":60},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFD7D7D7}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"304b1fa2e1004612895198bae19aad1c",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":200,
                    "y":15},
                  "size":{
                    "width":200,
                    "height":60},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFD7D7D7}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/我的工作台/u5.png"}},
{
            "id":"1ff87331235e44d3907f0495638c3ee8",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFFF2F2F2},
              "location":{
                "x":0,
                "y":90},
              "size":{
                "width":1400,
                "height":35},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFD7D7D7}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"8dea732008a44e7ba0aa5e0d23bc0e6b",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFF2F2F2},
                  "location":{
                    "x":0,
                    "y":90},
                  "size":{
                    "width":1400,
                    "height":35},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFD7D7D7}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/首页/u33.png"}},
{
            "id":"0ae756c78f1d4827bd92090a57c2445d",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":200,
                "y":90},
              "size":{
                "width":130,
                "height":35},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFD7D7D7}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"fa593240b6704c1390d0e2aefef6074a",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":200,
                    "y":90},
                  "size":{
                    "width":130,
                    "height":35},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFD7D7D7}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/我的工作台/u11.png"}},
{
            "id":"3718fe3583d442998538f8f62ebde4ea",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":330,
                "y":90},
              "size":{
                "width":130,
                "height":35},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFD7D7D7}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"13c36587be2d43fe8c5570fc2d88bd70",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":330,
                    "y":90},
                  "size":{
                    "width":130,
                    "height":35},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFD7D7D7}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/我的工作台/u11.png"}},
{
            "id":"482ddefbf1b94c4183138f489a3af059",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "horizontalAlignment":"right",
              "location":{
                "x":940,
                "y":15},
              "size":{
                "width":260,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"790516a0e63b4a738672d162eb75bbee",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "horizontalAlignment":"right",
                  "location":{
                    "x":940,
                    "y":15},
                  "size":{
                    "width":260,
                    "height":16}},
                "adaptiveStyles":{
},
                "objects":[{
                    "id":"89ef4c8d3211448595cc574e09210793",
                    "label":"",
                    "type":"hyperlink",
                    "styleType":"hyperlink",
                    "visible":true,
                    "style":{
},
                    "adaptiveStyles":{
},
                    "interactionMap":{
                      "onClick":{
                        "description":"OnClick",
                        "cases":[{
                            "description":"用例 1",
                            "isNewIfGroup":false,
                            "actions":[{
                                "action":"linkWindow",
                                "description":"在 当前窗口 打开 帐号设置",
                                "target":{
                                  "targetType":"page",
                                  "url":"帐号设置.html",
                                  "includeVariables":true},
                                "linkType":"current"}]}]}},
                    "tabbable":true}]}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"1dde2786457c4a03ad2520b794c38eaa",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":460,
                "y":90},
              "size":{
                "width":130,
                "height":35},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFD7D7D7}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"d077be6ea4d84cc695fc46e280f10374",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":460,
                    "y":90},
                  "size":{
                    "width":130,
                    "height":35},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFD7D7D7}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/我的工作台/u11.png"}},
{
            "id":"fad8689927314969bdd7cc6a59f7699a",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":590,
                "y":90},
              "size":{
                "width":130,
                "height":35},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFD7D7D7}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"b696734bb164452eb4dfbf0253e65191",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":590,
                    "y":90},
                  "size":{
                    "width":130,
                    "height":35},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFD7D7D7}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/我的工作台/u11.png"}},
{
            "id":"d6530536be2c439682beb237555b0ac0",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFFE4E4E4},
              "location":{
                "x":720,
                "y":90},
              "size":{
                "width":130,
                "height":35},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFD7D7D7}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"3e27027186624cb88b9b0650e15fa5e2",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFE4E4E4},
                  "location":{
                    "x":720,
                    "y":90},
                  "size":{
                    "width":130,
                    "height":35},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFD7D7D7}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/我的工作台/u9.png"}},
{
            "id":"4a2cbc1c2e694133808618f4c7848012",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":850,
                "y":90},
              "size":{
                "width":130,
                "height":35},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFD7D7D7}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"68913fdfca4f4e63a10405f8167cce60",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":850,
                    "y":90},
                  "size":{
                    "width":130,
                    "height":35},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFD7D7D7}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/我的工作台/u11.png"}},
{
            "id":"e4a12249d50141fd96e9f562187f1c5b",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":980,
                "y":90},
              "size":{
                "width":130,
                "height":35},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFD7D7D7}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"1c16f2463de5451a9af0b5d3d819bf80",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":980,
                    "y":90},
                  "size":{
                    "width":130,
                    "height":35},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFD7D7D7}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/我的工作台/u11.png"}}]}},
    "9aa3da306ba24637b281c884b1c30bca":{
      "packageId":"9aa3da306ba24637b281c884b1c30bca",
      "type":"Axure:Master",
      "name":"交易员底部",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"应用字体",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"aa94056b817049cbb1fa6bacb8c1e519",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "size":{
                "width":1400,
                "height":40},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFD7D7D7}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"d0f70829d22f42fea545dfa7923b52be",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "size":{
                    "width":1400,
                    "height":40},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFD7D7D7}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/首页/u13.png"}}]}}},
  "objectPaths":{
    "878b883b71424b58b012e8e95594024b":{
      "scriptId":"u0",
      "11a2262448e0441f9a29e02867462317":{
        "scriptId":"u1"},
      "2fb6fec02a5946deb468d94b926d5702":{
        "scriptId":"u2"},
      "d272761cc28841aabfc377d601a1ee83":{
        "scriptId":"u3"},
      "304b1fa2e1004612895198bae19aad1c":{
        "scriptId":"u4"},
      "1ff87331235e44d3907f0495638c3ee8":{
        "scriptId":"u5"},
      "8dea732008a44e7ba0aa5e0d23bc0e6b":{
        "scriptId":"u6"},
      "0ae756c78f1d4827bd92090a57c2445d":{
        "scriptId":"u7"},
      "fa593240b6704c1390d0e2aefef6074a":{
        "scriptId":"u8"},
      "3718fe3583d442998538f8f62ebde4ea":{
        "scriptId":"u9"},
      "13c36587be2d43fe8c5570fc2d88bd70":{
        "scriptId":"u10"},
      "482ddefbf1b94c4183138f489a3af059":{
        "scriptId":"u11"},
      "790516a0e63b4a738672d162eb75bbee":{
        "scriptId":"u12"},
      "89ef4c8d3211448595cc574e09210793":{
        "scriptId":"u13"},
      "1dde2786457c4a03ad2520b794c38eaa":{
        "scriptId":"u14"},
      "d077be6ea4d84cc695fc46e280f10374":{
        "scriptId":"u15"},
      "fad8689927314969bdd7cc6a59f7699a":{
        "scriptId":"u16"},
      "b696734bb164452eb4dfbf0253e65191":{
        "scriptId":"u17"},
      "d6530536be2c439682beb237555b0ac0":{
        "scriptId":"u18"},
      "3e27027186624cb88b9b0650e15fa5e2":{
        "scriptId":"u19"},
      "4a2cbc1c2e694133808618f4c7848012":{
        "scriptId":"u20"},
      "68913fdfca4f4e63a10405f8167cce60":{
        "scriptId":"u21"},
      "e4a12249d50141fd96e9f562187f1c5b":{
        "scriptId":"u22"},
      "1c16f2463de5451a9af0b5d3d819bf80":{
        "scriptId":"u23"}},
    "a3591aa678ed45aba3e1c7bafc260629":{
      "scriptId":"u24"},
    "57488c0e71af48aaab36fcba511fcf40":{
      "scriptId":"u25"},
    "938ac582bbc9475793edc8dd4ef1adc6":{
      "scriptId":"u26"},
    "63ecb87eaa5043ad87c44821b68bd5e3":{
      "scriptId":"u27"},
    "afb61ca40e9640c989e8647c0947c3b2":{
      "scriptId":"u28"},
    "5cdb5b58b5634d78a13ab0a515818d9d":{
      "scriptId":"u29"},
    "24313bcad25844379c004e7c6635f0df":{
      "scriptId":"u30"},
    "4d8fd73c126d4c6d9f705b670df24862":{
      "scriptId":"u31"},
    "0ea4e23ad3da4bb1935658e895327488":{
      "scriptId":"u32"},
    "e41d2e3948b64f268b04ee7b5c5b2313":{
      "scriptId":"u33"},
    "470ca1d23b1b40d5971f821b1e10c754":{
      "scriptId":"u34"},
    "601b98c100554d7381371ca4f01bea07":{
      "scriptId":"u35"},
    "9b483c53be9f4ecd83ff13dd639daaeb":{
      "scriptId":"u36"},
    "9594e6ad202d4cd1b087858f6dcc03fd":{
      "scriptId":"u37"},
    "9bb2e2a93d5d4fae844ab6ec5310047e":{
      "scriptId":"u38"},
    "edab6376abef4901a764697d012fb0d7":{
      "scriptId":"u39"},
    "25f72dc27ec54983bc3cfd2058de8e41":{
      "scriptId":"u40"},
    "a71d203f1deb4fd3a1232afe5ad04fd3":{
      "scriptId":"u41"},
    "ec8cdae2c5d24018993c42b9bdf35259":{
      "scriptId":"u42"},
    "ec255d60cb794e97b8ee2e403965e2ce":{
      "scriptId":"u43"},
    "ed85eb18feb14521b6d0d79ff8ab0579":{
      "scriptId":"u44"},
    "ebe0d226f36e42dca57338c55517981a":{
      "scriptId":"u45"},
    "0b577342682a416397ca96f4dd09621f":{
      "scriptId":"u46"},
    "6f23f7dd65f847f99f77c43166a43622":{
      "scriptId":"u47"},
    "2a8ad2e256684cf8b932d821f1c00a75":{
      "scriptId":"u48"},
    "9f8df5c5f7e94c128a55bda67fbc89c4":{
      "scriptId":"u49"},
    "1cb34bcf3c804ebd9d840e29451a9c6e":{
      "scriptId":"u50"},
    "bf836e2dee5942a3984268d5b8402a0f":{
      "scriptId":"u51"},
    "e3d1a2c231c14b09938c412ec23d1d55":{
      "scriptId":"u52"},
    "db9a6399732a4068832d72d64517a787":{
      "scriptId":"u53"},
    "783c85d7eb9049e2851ecc48a6741923":{
      "scriptId":"u54"},
    "405ac77aa4b34a50a1fdea589e1e1882":{
      "scriptId":"u55"},
    "ab859cdf6e444ad6950376b315e952ea":{
      "scriptId":"u56"},
    "9962f1a895494e27b30ccb1ac2482e3c":{
      "scriptId":"u57"},
    "1a730b4d0a72454495ab932801501206":{
      "scriptId":"u58"},
    "a2b04bbc6d334e5db1e27f7706ab8d94":{
      "scriptId":"u59"},
    "99f4cf488acd4f82832499a68c337e21":{
      "scriptId":"u60"},
    "7cfa295509cc4f15a8b530f372f7215b":{
      "scriptId":"u61"},
    "468d677b62d64ad6b10dd06c96a09b39":{
      "scriptId":"u62"},
    "44faeee4c3ef450a97428d560cb76af1":{
      "scriptId":"u63"},
    "3d9843b78d044724b1f83dbe71fade96":{
      "scriptId":"u64"},
    "815dd791e7ec461681e4e2e86165b903":{
      "scriptId":"u65"},
    "40b7d2dca1bc47da95e159f276752071":{
      "scriptId":"u66"},
    "7b00319ea0c7474f967e21baecb84826":{
      "scriptId":"u67"},
    "05b87e9044544e638a5d337bc6695a6b":{
      "scriptId":"u68"},
    "ebb1613d45df483e9821d3bdb7556aee":{
      "scriptId":"u69"},
    "4cf71be1fe344ec4844b57fab9a9a4c0":{
      "scriptId":"u70"},
    "326ee3b39c734f17b9b89135517c5eb9":{
      "scriptId":"u71"},
    "bc55e54460f44a52b6d34f4b6fc75893":{
      "scriptId":"u72"},
    "d93aca5112734c419074cc724967f9fa":{
      "scriptId":"u73"},
    "e0c7c27be7b94b1a943d381e8b31662b":{
      "scriptId":"u74"},
    "137eb6c102c34c569020359d3df9587c":{
      "scriptId":"u75"},
    "ae3b451cfaa846eb81ef17031b174222":{
      "scriptId":"u76"},
    "05321bce0480417d8bccbe90653176ce":{
      "scriptId":"u77"},
    "c5b6dc810d3f4df59acc1195f24f7857":{
      "scriptId":"u78"},
    "d398d3f56ad44dc1b3dfd22d97569de2":{
      "scriptId":"u79"},
    "9227be88b0a24e63a4a021733c842cb8":{
      "scriptId":"u80"},
    "034ce5926d6349f4b897e5019e02c480":{
      "scriptId":"u81"},
    "00d65cf0f13e41a8956e5daba973f3a3":{
      "scriptId":"u82"},
    "b30542eae88540609de5f5dc00d8ad7c":{
      "scriptId":"u83"},
    "e644e4ed9c724b4b9fc843b1ba52d2ab":{
      "scriptId":"u84"},
    "d905a8b4c417430d82b58e4b0aebacd3":{
      "scriptId":"u85"},
    "42d1f85b38984573a5dc5ca5d06e22e5":{
      "scriptId":"u86"},
    "3fd3a7cfa57a41ae9776ad260f89421e":{
      "scriptId":"u87"},
    "5174a378ea3646b1a809608e8fe5bf47":{
      "scriptId":"u88"},
    "67eae9eed8074ebd8273d3908a058e40":{
      "scriptId":"u89"},
    "85b0f94501594484baf78657993f2a19":{
      "scriptId":"u90"},
    "b2f891494e454491b838ecde3c580b52":{
      "scriptId":"u91"},
    "4f6fc7e2426c46c1bcd47e52c7509619":{
      "scriptId":"u92"},
    "0395f5c3e3b84966bf72b1be3f6b0c62":{
      "scriptId":"u93"},
    "89eace7ee19c437789aa4ed9415e6640":{
      "scriptId":"u94"},
    "ddd7a3536b854a0d9076fbac31875382":{
      "scriptId":"u95"},
    "3bd43a7b78064f2eb7fbde905af8952d":{
      "scriptId":"u96"},
    "2b3402c117da4573937429ce0005627e":{
      "scriptId":"u97"},
    "92055bb431c04ab88f39fdbb63553682":{
      "scriptId":"u98"},
    "61e7da11fb3848c7829ff1a20940365b":{
      "scriptId":"u99"},
    "d914e524b8c940fb908f1e73f3e2e7a8":{
      "scriptId":"u100"},
    "73b313cbe48e466c94002eb3eeb717ef":{
      "scriptId":"u101"},
    "1ad03c6a400d492ea604cf8e05be36d0":{
      "scriptId":"u102"},
    "514d7ea5a7b648e8b2075ded3380aeff":{
      "scriptId":"u103"},
    "c30b1318771d4674a6994dd403a3b7aa":{
      "scriptId":"u104"},
    "dc3083ec6fa842acb7c4aa6129147506":{
      "scriptId":"u105"},
    "a7afe7290dbc4b129dd1ea5217e0c32c":{
      "scriptId":"u106"},
    "3738eb2ef5ae4e699136d6723b369fa7":{
      "scriptId":"u107"},
    "6c7c175a5c194558a59235671a30da13":{
      "scriptId":"u108"},
    "74e5427de1f94b6b9328babde6180b54":{
      "scriptId":"u109"},
    "7b88d4cf3c594aba83a8a3a759d9fa9f":{
      "scriptId":"u110"},
    "b4d4b257875540debe017e4a772f578e":{
      "scriptId":"u111"},
    "6e6a261685c2427eb6543b3b9d8ae950":{
      "scriptId":"u112"},
    "07e1b67992084684864ee56f9e8b0558":{
      "scriptId":"u113"},
    "543ca5154d9547b3aa1aead0e7815b2a":{
      "scriptId":"u114"},
    "581f792829c046638a0a9848c81184e4":{
      "scriptId":"u115"},
    "c05eb68d857c47e1bc94b900c3acba21":{
      "scriptId":"u116"},
    "db4d334ec98f41e59c69fbbd0250074e":{
      "scriptId":"u117"},
    "ef3e81ad4d204dc79426a0e0e9f872fa":{
      "scriptId":"u118"},
    "76afd076e02f49fcb0423cc3645ba510":{
      "scriptId":"u119"},
    "5cefabdf534347e7b130b49b7cd0138e":{
      "scriptId":"u120"},
    "45e4f404220d4f748ffb3b94394a0d62":{
      "scriptId":"u121"},
    "28623f6407fd446dbd9e5907ed36a108":{
      "scriptId":"u122"},
    "1e12a98d03984a6a9b54003deb9e24a1":{
      "scriptId":"u123"},
    "1ab08da9b64d4ea3b272c7c9704b7ad1":{
      "scriptId":"u124"},
    "84a737be5fea484cbc1b62e55d8d628e":{
      "scriptId":"u125"},
    "bc88906a88eb4716bd72657e1d2d0832":{
      "scriptId":"u126"},
    "c9b14943bf60487e874a6320bb46a11e":{
      "scriptId":"u127",
      "aa94056b817049cbb1fa6bacb8c1e519":{
        "scriptId":"u128"},
      "d0f70829d22f42fea545dfa7923b52be":{
        "scriptId":"u129"}},
    "3956780ca09e463d816453bc06525879":{
      "scriptId":"u130"},
    "664ab3c52b4a47349153a34eda7bca41":{
      "scriptId":"u131"},
    "7f30c00689a445adb52babb748111f51":{
      "scriptId":"u132"},
    "a7e209d7d2044fc69091612484d706ef":{
      "scriptId":"u133"},
    "b283a273726a4711bfe6c78a4d6d8775":{
      "scriptId":"u134"},
    "95683a1461004b3585c9f2224b65a584":{
      "scriptId":"u135"}}});