$axure.loadCurrentPage({
  "url":"详情页.html",
  "generationDate":new Date(1432872284756.9),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"575afd79914045c2a2481c1cb386df66",
    "type":"Axure:Page",
    "name":"详情页",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"4817ab1265b0486d97aae764117e2c1d",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
},
          "adaptiveStyles":{
},
          "masterId":"a9e111da73474fc58a4e9af309efe76e"},
{
          "id":"e0103945659a4f8aa619fe60947fb24b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":200,
              "y":150},
            "size":{
              "width":200,
              "height":80},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFD7D7D7}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"340acbed6acc40c09f256969abf71cd1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":200,
                  "y":150},
                "size":{
                  "width":200,
                  "height":80},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的工作台/u26.png"}},
{
          "id":"239cab260713447da4015eb6ff879725",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFE4E4E4},
            "location":{
              "x":200,
              "y":230},
            "size":{
              "width":200,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFD7D7D7}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f78d1e8852fc49558548e255ca816f67",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4},
                "location":{
                  "x":200,
                  "y":230},
                "size":{
                  "width":200,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的工作台/u28.png"}},
{
          "id":"ff7a621f68364030b3d71f78df31a81f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":200,
              "y":360},
            "size":{
              "width":200,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFD7D7D7}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"32c1126ef8de41b39192bd9a234c8bae",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":200,
                  "y":360},
                "size":{
                  "width":200,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的工作台/u30.png"}},
{
          "id":"da5f8fc04b56455b85689393d0cb6306",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":200,
              "y":400},
            "size":{
              "width":200,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFD7D7D7}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"46b83d685e1b41edbaa1a2346ee83952",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":200,
                  "y":400},
                "size":{
                  "width":200,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的工作台/u30.png"}},
{
          "id":"e765bfc2a0454012833ecfdadf13183b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":200,
              "y":440},
            "size":{
              "width":200,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFD7D7D7}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"86a7724e60904f2797253b60919579c3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":200,
                  "y":440},
                "size":{
                  "width":200,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的工作台/u30.png"}},
{
          "id":"38be7506e6814584908cd0fa587b2ecd",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":200,
              "y":480},
            "size":{
              "width":200,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFD7D7D7}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2d73997b6025442a93c3abcd4552c280",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":200,
                  "y":480},
                "size":{
                  "width":200,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的工作台/u30.png"}},
{
          "id":"93699304bdb146ffa1d73999ed4dbfa7",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "fill":{
              "fillType":"solid",
              "color":0xFFE4E4E4},
            "location":{
              "x":210,
              "y":300},
            "size":{
              "width":190,
              "height":30},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFD7D7D7}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1b5bd137658e4f36bd4d9509a73610aa",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4},
                "location":{
                  "x":210,
                  "y":300},
                "size":{
                  "width":190,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/管理资源单/u233.png"}},
{
          "id":"2ad20a619ad84f7b82193adfd1a7382b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "location":{
              "x":210,
              "y":330},
            "size":{
              "width":190,
              "height":30},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFD7D7D7}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a21ed920855f48fa913c73ffd398a558",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "location":{
                  "x":210,
                  "y":330},
                "size":{
                  "width":190,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/管理资源单/u235.png"}},
{
          "id":"ba2dddc0c1b8449ba77fc595a58fae7b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "location":{
              "x":210,
              "y":270},
            "size":{
              "width":190,
              "height":30},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFD7D7D7}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"24e1dd2d2a454594af9ba77fd721d47b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "location":{
                  "x":210,
                  "y":270},
                "size":{
                  "width":190,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/管理资源单/u235.png"}},
{
          "id":"e89aeff533ae4d9e9816424e84a0e36f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":420,
              "y":150},
            "size":{
              "width":780,
              "height":1070},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFD7D7D7}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c95503da52c1426e8aa4fcbbcd8334aa",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":420,
                  "y":150},
                "size":{
                  "width":780,
                  "height":1070},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/详情页/u42.png"}},
{
          "id":"97bdc4a1bd1a4c5dab32279375034c8d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "location":{
              "x":440,
              "y":164},
            "size":{
              "width":210,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"17f08d3f257a45e98661425f45f5d863",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "location":{
                  "x":440,
                  "y":164},
                "size":{
                  "width":210,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"013ca12dca374e63b4906a26797c8fde",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":440,
              "y":232},
            "size":{
              "width":90,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1f412f556e7e4963974b579af2703c1c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":440,
                  "y":232},
                "size":{
                  "width":90,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"abf6243e8c2e4530bbc0a2e5aa6f4c7a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":440,
              "y":265},
            "size":{
              "width":90,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0a7ff45cb8614172a440ff5bcff177ce",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":440,
                  "y":265},
                "size":{
                  "width":90,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a8ef61bb3bb743818459215789c80cdd",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":440,
              "y":299},
            "size":{
              "width":90,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"45e0418acf644b8db751e8c8cf186332",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":440,
                  "y":299},
                "size":{
                  "width":90,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a423a7c0823e4d10a7bb87b07ef09abc",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":440,
              "y":333},
            "size":{
              "width":90,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e170b30ce4144351801c1f0e2b9e4ea8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":440,
                  "y":333},
                "size":{
                  "width":90,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8b74125f0b034827a6d1c6782cf7e083",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":440,
              "y":1163},
            "size":{
              "width":110,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bd38fe55612141dab6d085c5e55a9be3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":440,
                  "y":1163},
                "size":{
                  "width":110,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"eba63f0e1a7e4148b676048b2f7320ed",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":440,
              "y":369},
            "size":{
              "width":90,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dae60312bc46499d93da307348ab0db9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":440,
                  "y":369},
                "size":{
                  "width":90,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"40c3f803bf364ff092acd88849615602",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":510,
              "y":369},
            "size":{
              "width":166,
              "height":118}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c4b8fc46169f47e18cfa5839107dc5af",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":510,
                  "y":369},
                "size":{
                  "width":166,
                  "height":118}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/增加车辆/u196.png"}},
{
          "id":"26d51fe2540e4b879ddeb3398dbdf2a5",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "lineSpacing":"20px",
            "location":{
              "x":880,
              "y":467},
            "size":{
              "width":440,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cc19e8090a104913a350fb59cd6b8087",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "lineSpacing":"20px",
                "location":{
                  "x":880,
                  "y":467},
                "size":{
                  "width":440,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6935ff45492b4491a2b8a7d1b3b1e97a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":440,
              "y":517},
            "size":{
              "width":90,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"54080ff32a51470a87b826ecc7b0e73f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":440,
                  "y":517},
                "size":{
                  "width":90,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"216428d763ef4d36957adc954f47707e",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":534,
              "y":517},
            "size":{
              "width":166,
              "height":118}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d5909961338840ff838661bb971d08c7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":534,
                  "y":517},
                "size":{
                  "width":166,
                  "height":118}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/增加车辆/u196.png"}},
{
          "id":"4d444cf80cf740d38d6a58bceea0b283",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":440,
              "y":661},
            "size":{
              "width":90,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9c9c736dd0964049a1cc103bc34c463f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":440,
                  "y":661},
                "size":{
                  "width":90,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2abc8493b3164e94837a2f49789caef3",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":534,
              "y":661},
            "size":{
              "width":166,
              "height":118}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cfccdc27b97f49818b1475c628dae9b0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":534,
                  "y":661},
                "size":{
                  "width":166,
                  "height":118}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/增加车辆/u196.png"}},
{
          "id":"166ba73c1c6f43499a114fbcb440c30d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":440,
              "y":1109},
            "size":{
              "width":90,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"79ea692659e546f3adbf9684bddd437c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":440,
                  "y":1109},
                "size":{
                  "width":90,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e40da4bc6f1c4979ac8b8c3b53c3ffdd",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":440,
              "y":809},
            "size":{
              "width":90,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0159d0535eed4992a1dd316f2ecebf0f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":440,
                  "y":809},
                "size":{
                  "width":90,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b6a2797b1e56464988251da41273b24b",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":534,
              "y":809},
            "size":{
              "width":166,
              "height":118}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"52d210d78cf942ae9ff7fc26fcfc15fc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":534,
                  "y":809},
                "size":{
                  "width":166,
                  "height":118}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/增加车辆/u196.png"}},
{
          "id":"a92a6494ca694a078fc3588788095f2e",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":698,
              "y":369},
            "size":{
              "width":166,
              "height":118}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a5fc03327f9b4f86a5612823bbed0d70",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":698,
                  "y":369},
                "size":{
                  "width":166,
                  "height":118}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/增加车辆/u196.png"}},
{
          "id":"41a06fc15eb0491dbf5fd719222ba769",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":440,
              "y":959},
            "size":{
              "width":90,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"76ea3316d9ab4b629dc1bc08a41617fd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":440,
                  "y":959},
                "size":{
                  "width":90,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"335cc7bb81854c5a82e9dd9f2ec5c694",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":534,
              "y":959},
            "size":{
              "width":166,
              "height":118}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0e2841dcdf30423292abbf0602f3ea37",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":534,
                  "y":959},
                "size":{
                  "width":166,
                  "height":118}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/增加车辆/u196.png"}},
{
          "id":"0bdf4569d6d142eb89834a09e614c4c1",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":729,
              "y":959},
            "size":{
              "width":166,
              "height":118}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"62f61e0f31b44277a044c9984eef63fc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":729,
                  "y":959},
                "size":{
                  "width":166,
                  "height":118}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/增加车辆/u196.png"}},
{
          "id":"1f80970dffc240deb8f6a9ec84b86390",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":924,
              "y":959},
            "size":{
              "width":166,
              "height":118}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"64211a945a094a1785e8720c59d92064",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":924,
                  "y":959},
                "size":{
                  "width":166,
                  "height":118}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/增加车辆/u196.png"}},
{
          "id":"aad305d95b5841f988e4e568d1c5168c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":510,
              "y":232},
            "size":{
              "width":90,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"41a73b1bd2094d7c9682f16337c40695",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":510,
                  "y":232},
                "size":{
                  "width":90,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7a7fb8bfd2184fe5b1d0d0735cd0d833",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":510,
              "y":265},
            "size":{
              "width":90,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"197252fca757488bbbc0c9b7103d0121",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":510,
                  "y":265},
                "size":{
                  "width":90,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"874f12a49b074bf1b60a9c076a2f531a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":510,
              "y":299},
            "size":{
              "width":90,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bcfc6b8235fa4b1492ea16720ee11c8f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":510,
                  "y":299},
                "size":{
                  "width":90,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"289da5e292684f7ba2fe5cb085887da4",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":510,
              "y":333},
            "size":{
              "width":90,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fd2555b565134162a09ec4245d32e73c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":510,
                  "y":333},
                "size":{
                  "width":90,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d86fc11f9abb49968b56ea124312eba0",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "lineSpacing":"20px",
            "location":{
              "x":710,
              "y":615},
            "size":{
              "width":440,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2ed4fa978742416cb7fd7c42a27757ed",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "lineSpacing":"20px",
                "location":{
                  "x":710,
                  "y":615},
                "size":{
                  "width":440,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6a108cbe732c456eb2731d933f02e86d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "lineSpacing":"20px",
            "location":{
              "x":710,
              "y":759},
            "size":{
              "width":440,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1e1d240256a544b6b31db93f7483938c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "lineSpacing":"20px",
                "location":{
                  "x":710,
                  "y":759},
                "size":{
                  "width":440,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9e6a0e8d83b14363831a2aa657bed42b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "lineSpacing":"20px",
            "location":{
              "x":710,
              "y":907},
            "size":{
              "width":440,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"09e6fe7ffba64e98bfd1c0e40d33f4e1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "lineSpacing":"20px",
                "location":{
                  "x":710,
                  "y":907},
                "size":{
                  "width":440,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1a1ddba47a06423488bc12fc5e5dfa29",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":510,
              "y":1109},
            "size":{
              "width":90,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5b8d4404fab84f3c9d183248b63d1e87",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":510,
                  "y":1109},
                "size":{
                  "width":90,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ebe9c7180dd443e59049230e077973ce",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":534,
              "y":1163},
            "size":{
              "width":686,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1e6d8103017347d1b3e3a797c9801972",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":534,
                  "y":1163},
                "size":{
                  "width":686,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"20fdfe4f223240cdacee3ab506e3bcf3",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontWeight":"700",
            "location":{
              "x":420,
              "y":1243},
            "size":{
              "width":218,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4dbff0d25ca14d289bb5be1c02a0114e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"700",
                "location":{
                  "x":420,
                  "y":1243},
                "size":{
                  "width":218,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"fc4350af268b40cd8155d02669b11603",
          "label":"",
          "type":"table",
          "styleType":"table",
          "visible":true,
          "style":{
            "location":{
              "x":420,
              "y":1269},
            "size":{
              "width":780,
              "height":106}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"671693fb21c94ba18a50850ee330b57c",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"700",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "size":{
                  "width":148,
                  "height":35},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"92f604ce0a87440ba4ed0008d14ad9c6",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Arial Negreta', 'Arial'",
                    "fontWeight":"700",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFF2F2F2},
                    "size":{
                      "width":148,
                      "height":35},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFD7D7D7}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/审核_1/u115.png"}},
{
              "id":"87a4e9e9ec424cb0bb13b342f8043eeb",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":70},
                "size":{
                  "width":148,
                  "height":36},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"b547cb018c0c497da2ea05d97aea73a3",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":70},
                    "size":{
                      "width":148,
                      "height":36},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFD7D7D7}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/审核_1/u121.png"}},
{
              "id":"58e6c0c423784ff98a231c9954ac2e52",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"700",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":148,
                  "y":0},
                "size":{
                  "width":125,
                  "height":35},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"480ac62623514f948e2efc2eea18bdc4",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Arial Negreta', 'Arial'",
                    "fontWeight":"700",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFF2F2F2},
                    "location":{
                      "x":148,
                      "y":0},
                    "size":{
                      "width":125,
                      "height":35},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFD7D7D7}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/审核_1/u117.png"}},
{
              "id":"f47b09428422462fa4524215312203f1",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "verticalAlignment":"middle",
                "location":{
                  "x":148,
                  "y":70},
                "size":{
                  "width":125,
                  "height":36},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"b2f93760941b449c94c9e1a76682561a",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "verticalAlignment":"middle",
                    "location":{
                      "x":148,
                      "y":70},
                    "size":{
                      "width":125,
                      "height":36},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFD7D7D7}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/审核_1/u123.png"}},
{
              "id":"03f90455bbcb44b2bf176384765d6efd",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"700",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":273,
                  "y":0},
                "size":{
                  "width":507,
                  "height":35},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"a037338f2431413a8394fc0eced14f4d",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Arial Negreta', 'Arial'",
                    "fontWeight":"700",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFF2F2F2},
                    "location":{
                      "x":273,
                      "y":0},
                    "size":{
                      "width":507,
                      "height":35},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFD7D7D7}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/审核_1/u119.png"}},
{
              "id":"055e07d74696473c992e1b46068e3228",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "verticalAlignment":"middle",
                "location":{
                  "x":273,
                  "y":70},
                "size":{
                  "width":507,
                  "height":36},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"e064e6f463134ac282d2fbc61fca1f99",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "verticalAlignment":"middle",
                    "location":{
                      "x":273,
                      "y":70},
                    "size":{
                      "width":507,
                      "height":36},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFD7D7D7}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/审核_1/u125.png"}},
{
              "id":"57ec382e01884f748309ba237e3059ea",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":35},
                "size":{
                  "width":148,
                  "height":35},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"2a1b96e223d848c3b2fcdf137c6341d4",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":35},
                    "size":{
                      "width":148,
                      "height":35},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFD7D7D7}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/已关闭/u65.png"}},
{
              "id":"37ec2857e0fa4d888eb7e2043ff778ae",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "verticalAlignment":"middle",
                "location":{
                  "x":148,
                  "y":35},
                "size":{
                  "width":125,
                  "height":35},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"4a82661495c248aca3b854a2d300cb0f",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "verticalAlignment":"middle",
                    "location":{
                      "x":148,
                      "y":35},
                    "size":{
                      "width":125,
                      "height":35},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFD7D7D7}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/详情页/u115.png"}},
{
              "id":"2113232854d84219bc9126cdb4b556c3",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "verticalAlignment":"middle",
                "location":{
                  "x":273,
                  "y":35},
                "size":{
                  "width":507,
                  "height":35},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"21633f2d2df74ec0a61271835673a8e9",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "verticalAlignment":"middle",
                    "location":{
                      "x":273,
                      "y":35},
                    "size":{
                      "width":507,
                      "height":35},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFD7D7D7}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/详情页/u117.png"}}]},
{
          "id":"57610a6be5c943d2b1a8788d247b7f6e",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":1400}},
          "adaptiveStyles":{
},
          "masterId":"9aa3da306ba24637b281c884b1c30bca"},
{
          "id":"6a3a19ce20cd464e826fc2608317d496",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":440,
              "y":200},
            "size":{
              "width":90,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a414997eb7d543dfaefd8d500a319682",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":440,
                  "y":200},
                "size":{
                  "width":90,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"dba2340677df4bd0af4369aaf11bb487",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":510,
              "y":200},
            "size":{
              "width":90,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fc5270cd9ff845648f84c1b16bb09a1c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":510,
                  "y":200},
                "size":{
                  "width":90,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"dfe99cc89e8a4bc98e440f9e64f82dfc",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":200,
              "y":520},
            "size":{
              "width":200,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFD7D7D7}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"370a35d42f37406988c9e2eac6dd57d9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":200,
                  "y":520},
                "size":{
                  "width":200,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的工作台/u30.png"}}]}},
  "masters":{
    "a9e111da73474fc58a4e9af309efe76e":{
      "packageId":"a9e111da73474fc58a4e9af309efe76e",
      "type":"Axure:Master",
      "name":"交易员头部--承运管理",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"应用字体",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"11a2262448e0441f9a29e02867462317",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "size":{
                "width":1400,
                "height":90},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFD7D7D7}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"2fb6fec02a5946deb468d94b926d5702",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "size":{
                    "width":1400,
                    "height":90},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFD7D7D7}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/我的工作台/u3.png"}},
{
            "id":"d272761cc28841aabfc377d601a1ee83",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":200,
                "y":15},
              "size":{
                "width":200,
                "height":60},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFD7D7D7}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"304b1fa2e1004612895198bae19aad1c",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":200,
                    "y":15},
                  "size":{
                    "width":200,
                    "height":60},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFD7D7D7}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/我的工作台/u5.png"}},
{
            "id":"1ff87331235e44d3907f0495638c3ee8",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFFF2F2F2},
              "location":{
                "x":0,
                "y":90},
              "size":{
                "width":1400,
                "height":35},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFD7D7D7}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"8dea732008a44e7ba0aa5e0d23bc0e6b",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFF2F2F2},
                  "location":{
                    "x":0,
                    "y":90},
                  "size":{
                    "width":1400,
                    "height":35},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFD7D7D7}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/首页/u33.png"}},
{
            "id":"0ae756c78f1d4827bd92090a57c2445d",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":200,
                "y":90},
              "size":{
                "width":130,
                "height":35},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFD7D7D7}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"fa593240b6704c1390d0e2aefef6074a",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":200,
                    "y":90},
                  "size":{
                    "width":130,
                    "height":35},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFD7D7D7}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/我的工作台/u11.png"}},
{
            "id":"3718fe3583d442998538f8f62ebde4ea",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":330,
                "y":90},
              "size":{
                "width":130,
                "height":35},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFD7D7D7}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"13c36587be2d43fe8c5570fc2d88bd70",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":330,
                    "y":90},
                  "size":{
                    "width":130,
                    "height":35},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFD7D7D7}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/我的工作台/u11.png"}},
{
            "id":"482ddefbf1b94c4183138f489a3af059",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "horizontalAlignment":"right",
              "location":{
                "x":940,
                "y":15},
              "size":{
                "width":260,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"790516a0e63b4a738672d162eb75bbee",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "horizontalAlignment":"right",
                  "location":{
                    "x":940,
                    "y":15},
                  "size":{
                    "width":260,
                    "height":16}},
                "adaptiveStyles":{
},
                "objects":[{
                    "id":"89ef4c8d3211448595cc574e09210793",
                    "label":"",
                    "type":"hyperlink",
                    "styleType":"hyperlink",
                    "visible":true,
                    "style":{
},
                    "adaptiveStyles":{
},
                    "interactionMap":{
                      "onClick":{
                        "description":"OnClick",
                        "cases":[{
                            "description":"用例 1",
                            "isNewIfGroup":false,
                            "actions":[{
                                "action":"linkWindow",
                                "description":"在 当前窗口 打开 帐号设置",
                                "target":{
                                  "targetType":"page",
                                  "url":"帐号设置.html",
                                  "includeVariables":true},
                                "linkType":"current"}]}]}},
                    "tabbable":true}]}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"1dde2786457c4a03ad2520b794c38eaa",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":460,
                "y":90},
              "size":{
                "width":130,
                "height":35},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFD7D7D7}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"d077be6ea4d84cc695fc46e280f10374",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":460,
                    "y":90},
                  "size":{
                    "width":130,
                    "height":35},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFD7D7D7}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/我的工作台/u11.png"}},
{
            "id":"fad8689927314969bdd7cc6a59f7699a",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":590,
                "y":90},
              "size":{
                "width":130,
                "height":35},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFD7D7D7}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"b696734bb164452eb4dfbf0253e65191",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":590,
                    "y":90},
                  "size":{
                    "width":130,
                    "height":35},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFD7D7D7}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/我的工作台/u11.png"}},
{
            "id":"d6530536be2c439682beb237555b0ac0",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFFE4E4E4},
              "location":{
                "x":720,
                "y":90},
              "size":{
                "width":130,
                "height":35},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFD7D7D7}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"3e27027186624cb88b9b0650e15fa5e2",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFE4E4E4},
                  "location":{
                    "x":720,
                    "y":90},
                  "size":{
                    "width":130,
                    "height":35},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFD7D7D7}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/我的工作台/u9.png"}},
{
            "id":"4a2cbc1c2e694133808618f4c7848012",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":850,
                "y":90},
              "size":{
                "width":130,
                "height":35},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFD7D7D7}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"68913fdfca4f4e63a10405f8167cce60",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":850,
                    "y":90},
                  "size":{
                    "width":130,
                    "height":35},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFD7D7D7}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/我的工作台/u11.png"}},
{
            "id":"e4a12249d50141fd96e9f562187f1c5b",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":980,
                "y":90},
              "size":{
                "width":130,
                "height":35},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFD7D7D7}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"1c16f2463de5451a9af0b5d3d819bf80",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":980,
                    "y":90},
                  "size":{
                    "width":130,
                    "height":35},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFD7D7D7}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/我的工作台/u11.png"}}]}},
    "9aa3da306ba24637b281c884b1c30bca":{
      "packageId":"9aa3da306ba24637b281c884b1c30bca",
      "type":"Axure:Master",
      "name":"交易员底部",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"应用字体",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"aa94056b817049cbb1fa6bacb8c1e519",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "size":{
                "width":1400,
                "height":40},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFD7D7D7}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"d0f70829d22f42fea545dfa7923b52be",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "size":{
                    "width":1400,
                    "height":40},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFD7D7D7}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/首页/u13.png"}}]}}},
  "objectPaths":{
    "4817ab1265b0486d97aae764117e2c1d":{
      "scriptId":"u0",
      "11a2262448e0441f9a29e02867462317":{
        "scriptId":"u1"},
      "2fb6fec02a5946deb468d94b926d5702":{
        "scriptId":"u2"},
      "d272761cc28841aabfc377d601a1ee83":{
        "scriptId":"u3"},
      "304b1fa2e1004612895198bae19aad1c":{
        "scriptId":"u4"},
      "1ff87331235e44d3907f0495638c3ee8":{
        "scriptId":"u5"},
      "8dea732008a44e7ba0aa5e0d23bc0e6b":{
        "scriptId":"u6"},
      "0ae756c78f1d4827bd92090a57c2445d":{
        "scriptId":"u7"},
      "fa593240b6704c1390d0e2aefef6074a":{
        "scriptId":"u8"},
      "3718fe3583d442998538f8f62ebde4ea":{
        "scriptId":"u9"},
      "13c36587be2d43fe8c5570fc2d88bd70":{
        "scriptId":"u10"},
      "482ddefbf1b94c4183138f489a3af059":{
        "scriptId":"u11"},
      "790516a0e63b4a738672d162eb75bbee":{
        "scriptId":"u12"},
      "89ef4c8d3211448595cc574e09210793":{
        "scriptId":"u13"},
      "1dde2786457c4a03ad2520b794c38eaa":{
        "scriptId":"u14"},
      "d077be6ea4d84cc695fc46e280f10374":{
        "scriptId":"u15"},
      "fad8689927314969bdd7cc6a59f7699a":{
        "scriptId":"u16"},
      "b696734bb164452eb4dfbf0253e65191":{
        "scriptId":"u17"},
      "d6530536be2c439682beb237555b0ac0":{
        "scriptId":"u18"},
      "3e27027186624cb88b9b0650e15fa5e2":{
        "scriptId":"u19"},
      "4a2cbc1c2e694133808618f4c7848012":{
        "scriptId":"u20"},
      "68913fdfca4f4e63a10405f8167cce60":{
        "scriptId":"u21"},
      "e4a12249d50141fd96e9f562187f1c5b":{
        "scriptId":"u22"},
      "1c16f2463de5451a9af0b5d3d819bf80":{
        "scriptId":"u23"}},
    "e0103945659a4f8aa619fe60947fb24b":{
      "scriptId":"u24"},
    "340acbed6acc40c09f256969abf71cd1":{
      "scriptId":"u25"},
    "239cab260713447da4015eb6ff879725":{
      "scriptId":"u26"},
    "f78d1e8852fc49558548e255ca816f67":{
      "scriptId":"u27"},
    "ff7a621f68364030b3d71f78df31a81f":{
      "scriptId":"u28"},
    "32c1126ef8de41b39192bd9a234c8bae":{
      "scriptId":"u29"},
    "da5f8fc04b56455b85689393d0cb6306":{
      "scriptId":"u30"},
    "46b83d685e1b41edbaa1a2346ee83952":{
      "scriptId":"u31"},
    "e765bfc2a0454012833ecfdadf13183b":{
      "scriptId":"u32"},
    "86a7724e60904f2797253b60919579c3":{
      "scriptId":"u33"},
    "38be7506e6814584908cd0fa587b2ecd":{
      "scriptId":"u34"},
    "2d73997b6025442a93c3abcd4552c280":{
      "scriptId":"u35"},
    "93699304bdb146ffa1d73999ed4dbfa7":{
      "scriptId":"u36"},
    "1b5bd137658e4f36bd4d9509a73610aa":{
      "scriptId":"u37"},
    "2ad20a619ad84f7b82193adfd1a7382b":{
      "scriptId":"u38"},
    "a21ed920855f48fa913c73ffd398a558":{
      "scriptId":"u39"},
    "ba2dddc0c1b8449ba77fc595a58fae7b":{
      "scriptId":"u40"},
    "24e1dd2d2a454594af9ba77fd721d47b":{
      "scriptId":"u41"},
    "e89aeff533ae4d9e9816424e84a0e36f":{
      "scriptId":"u42"},
    "c95503da52c1426e8aa4fcbbcd8334aa":{
      "scriptId":"u43"},
    "97bdc4a1bd1a4c5dab32279375034c8d":{
      "scriptId":"u44"},
    "17f08d3f257a45e98661425f45f5d863":{
      "scriptId":"u45"},
    "013ca12dca374e63b4906a26797c8fde":{
      "scriptId":"u46"},
    "1f412f556e7e4963974b579af2703c1c":{
      "scriptId":"u47"},
    "abf6243e8c2e4530bbc0a2e5aa6f4c7a":{
      "scriptId":"u48"},
    "0a7ff45cb8614172a440ff5bcff177ce":{
      "scriptId":"u49"},
    "a8ef61bb3bb743818459215789c80cdd":{
      "scriptId":"u50"},
    "45e0418acf644b8db751e8c8cf186332":{
      "scriptId":"u51"},
    "a423a7c0823e4d10a7bb87b07ef09abc":{
      "scriptId":"u52"},
    "e170b30ce4144351801c1f0e2b9e4ea8":{
      "scriptId":"u53"},
    "8b74125f0b034827a6d1c6782cf7e083":{
      "scriptId":"u54"},
    "bd38fe55612141dab6d085c5e55a9be3":{
      "scriptId":"u55"},
    "eba63f0e1a7e4148b676048b2f7320ed":{
      "scriptId":"u56"},
    "dae60312bc46499d93da307348ab0db9":{
      "scriptId":"u57"},
    "40c3f803bf364ff092acd88849615602":{
      "scriptId":"u58"},
    "c4b8fc46169f47e18cfa5839107dc5af":{
      "scriptId":"u59"},
    "26d51fe2540e4b879ddeb3398dbdf2a5":{
      "scriptId":"u60"},
    "cc19e8090a104913a350fb59cd6b8087":{
      "scriptId":"u61"},
    "6935ff45492b4491a2b8a7d1b3b1e97a":{
      "scriptId":"u62"},
    "54080ff32a51470a87b826ecc7b0e73f":{
      "scriptId":"u63"},
    "216428d763ef4d36957adc954f47707e":{
      "scriptId":"u64"},
    "d5909961338840ff838661bb971d08c7":{
      "scriptId":"u65"},
    "4d444cf80cf740d38d6a58bceea0b283":{
      "scriptId":"u66"},
    "9c9c736dd0964049a1cc103bc34c463f":{
      "scriptId":"u67"},
    "2abc8493b3164e94837a2f49789caef3":{
      "scriptId":"u68"},
    "cfccdc27b97f49818b1475c628dae9b0":{
      "scriptId":"u69"},
    "166ba73c1c6f43499a114fbcb440c30d":{
      "scriptId":"u70"},
    "79ea692659e546f3adbf9684bddd437c":{
      "scriptId":"u71"},
    "e40da4bc6f1c4979ac8b8c3b53c3ffdd":{
      "scriptId":"u72"},
    "0159d0535eed4992a1dd316f2ecebf0f":{
      "scriptId":"u73"},
    "b6a2797b1e56464988251da41273b24b":{
      "scriptId":"u74"},
    "52d210d78cf942ae9ff7fc26fcfc15fc":{
      "scriptId":"u75"},
    "a92a6494ca694a078fc3588788095f2e":{
      "scriptId":"u76"},
    "a5fc03327f9b4f86a5612823bbed0d70":{
      "scriptId":"u77"},
    "41a06fc15eb0491dbf5fd719222ba769":{
      "scriptId":"u78"},
    "76ea3316d9ab4b629dc1bc08a41617fd":{
      "scriptId":"u79"},
    "335cc7bb81854c5a82e9dd9f2ec5c694":{
      "scriptId":"u80"},
    "0e2841dcdf30423292abbf0602f3ea37":{
      "scriptId":"u81"},
    "0bdf4569d6d142eb89834a09e614c4c1":{
      "scriptId":"u82"},
    "62f61e0f31b44277a044c9984eef63fc":{
      "scriptId":"u83"},
    "1f80970dffc240deb8f6a9ec84b86390":{
      "scriptId":"u84"},
    "64211a945a094a1785e8720c59d92064":{
      "scriptId":"u85"},
    "aad305d95b5841f988e4e568d1c5168c":{
      "scriptId":"u86"},
    "41a73b1bd2094d7c9682f16337c40695":{
      "scriptId":"u87"},
    "7a7fb8bfd2184fe5b1d0d0735cd0d833":{
      "scriptId":"u88"},
    "197252fca757488bbbc0c9b7103d0121":{
      "scriptId":"u89"},
    "874f12a49b074bf1b60a9c076a2f531a":{
      "scriptId":"u90"},
    "bcfc6b8235fa4b1492ea16720ee11c8f":{
      "scriptId":"u91"},
    "289da5e292684f7ba2fe5cb085887da4":{
      "scriptId":"u92"},
    "fd2555b565134162a09ec4245d32e73c":{
      "scriptId":"u93"},
    "d86fc11f9abb49968b56ea124312eba0":{
      "scriptId":"u94"},
    "2ed4fa978742416cb7fd7c42a27757ed":{
      "scriptId":"u95"},
    "6a108cbe732c456eb2731d933f02e86d":{
      "scriptId":"u96"},
    "1e1d240256a544b6b31db93f7483938c":{
      "scriptId":"u97"},
    "9e6a0e8d83b14363831a2aa657bed42b":{
      "scriptId":"u98"},
    "09e6fe7ffba64e98bfd1c0e40d33f4e1":{
      "scriptId":"u99"},
    "1a1ddba47a06423488bc12fc5e5dfa29":{
      "scriptId":"u100"},
    "5b8d4404fab84f3c9d183248b63d1e87":{
      "scriptId":"u101"},
    "ebe9c7180dd443e59049230e077973ce":{
      "scriptId":"u102"},
    "1e6d8103017347d1b3e3a797c9801972":{
      "scriptId":"u103"},
    "20fdfe4f223240cdacee3ab506e3bcf3":{
      "scriptId":"u104"},
    "4dbff0d25ca14d289bb5be1c02a0114e":{
      "scriptId":"u105"},
    "fc4350af268b40cd8155d02669b11603":{
      "scriptId":"u106"},
    "671693fb21c94ba18a50850ee330b57c":{
      "scriptId":"u107"},
    "92f604ce0a87440ba4ed0008d14ad9c6":{
      "scriptId":"u108"},
    "58e6c0c423784ff98a231c9954ac2e52":{
      "scriptId":"u109"},
    "480ac62623514f948e2efc2eea18bdc4":{
      "scriptId":"u110"},
    "03f90455bbcb44b2bf176384765d6efd":{
      "scriptId":"u111"},
    "a037338f2431413a8394fc0eced14f4d":{
      "scriptId":"u112"},
    "57ec382e01884f748309ba237e3059ea":{
      "scriptId":"u113"},
    "2a1b96e223d848c3b2fcdf137c6341d4":{
      "scriptId":"u114"},
    "37ec2857e0fa4d888eb7e2043ff778ae":{
      "scriptId":"u115"},
    "4a82661495c248aca3b854a2d300cb0f":{
      "scriptId":"u116"},
    "2113232854d84219bc9126cdb4b556c3":{
      "scriptId":"u117"},
    "21633f2d2df74ec0a61271835673a8e9":{
      "scriptId":"u118"},
    "87a4e9e9ec424cb0bb13b342f8043eeb":{
      "scriptId":"u119"},
    "b547cb018c0c497da2ea05d97aea73a3":{
      "scriptId":"u120"},
    "f47b09428422462fa4524215312203f1":{
      "scriptId":"u121"},
    "b2f93760941b449c94c9e1a76682561a":{
      "scriptId":"u122"},
    "055e07d74696473c992e1b46068e3228":{
      "scriptId":"u123"},
    "e064e6f463134ac282d2fbc61fca1f99":{
      "scriptId":"u124"},
    "57610a6be5c943d2b1a8788d247b7f6e":{
      "scriptId":"u125",
      "aa94056b817049cbb1fa6bacb8c1e519":{
        "scriptId":"u126"},
      "d0f70829d22f42fea545dfa7923b52be":{
        "scriptId":"u127"}},
    "6a3a19ce20cd464e826fc2608317d496":{
      "scriptId":"u128"},
    "a414997eb7d543dfaefd8d500a319682":{
      "scriptId":"u129"},
    "dba2340677df4bd0af4369aaf11bb487":{
      "scriptId":"u130"},
    "fc5270cd9ff845648f84c1b16bb09a1c":{
      "scriptId":"u131"},
    "dfe99cc89e8a4bc98e440f9e64f82dfc":{
      "scriptId":"u132"},
    "370a35d42f37406988c9e2eac6dd57d9":{
      "scriptId":"u133"}}});