$axure.loadCurrentPage({
  "url":"订单改价.html",
  "generationDate":new Date(1432872275006.35),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"44324c776b984ef4ad1f8a50d27cb132",
    "type":"Axure:Page",
    "name":"订单改价",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"7917e4d30eb145e3968e8c789ef7ba14",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
},
          "adaptiveStyles":{
},
          "masterId":"21e4130fae884c10a964094359915ae7"},
{
          "id":"a14d4b527f484f9eb0464391f4723b5c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":200,
              "y":150},
            "size":{
              "width":200,
              "height":80},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFD7D7D7}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"82583bad9b7f41bbaf550e736814d1ed",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":200,
                  "y":150},
                "size":{
                  "width":200,
                  "height":80},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的工作台/u26.png"}},
{
          "id":"3772c878709248b1a69547adaf116df1",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":200,
              "y":230},
            "size":{
              "width":200,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFD7D7D7}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bbfceda3ea0948f5a4c3f518bbdb31ce",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":200,
                  "y":230},
                "size":{
                  "width":200,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的工作台/u30.png"}},
{
          "id":"1527a2cb854f4352b364f5b7da39d4cf",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "fill":{
              "fillType":"solid",
              "color":0xFFE4E4E4},
            "location":{
              "x":210,
              "y":350},
            "size":{
              "width":190,
              "height":30},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFD7D7D7}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e4d868af91ce47f78a53cef9325f6474",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4},
                "location":{
                  "x":210,
                  "y":350},
                "size":{
                  "width":190,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/管理资源单/u233.png"}},
{
          "id":"fc8896fbed1a413db31faefc9ce3ec26",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "location":{
              "x":210,
              "y":380},
            "size":{
              "width":190,
              "height":30},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFD7D7D7}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"41509ce18135400d810e638499431fa3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "location":{
                  "x":210,
                  "y":380},
                "size":{
                  "width":190,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/管理资源单/u235.png"}},
{
          "id":"e33540d64dc742e98698b99d033c0de4",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":200,
              "y":270},
            "size":{
              "width":200,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFD7D7D7}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0ccd1dd4c2644b968cd74afce80edc97",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":200,
                  "y":270},
                "size":{
                  "width":200,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的工作台/u30.png"}},
{
          "id":"5444764a0a2b48069e090bbfdbc8d922",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFE4E4E4},
            "location":{
              "x":200,
              "y":310},
            "size":{
              "width":200,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFD7D7D7}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7f056c0a12984de39e9e322521ffbeae",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4},
                "location":{
                  "x":200,
                  "y":310},
                "size":{
                  "width":200,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的工作台/u28.png"}},
{
          "id":"455d5e129edd475d91d79af61be56b21",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":770}},
          "adaptiveStyles":{
},
          "masterId":"9aa3da306ba24637b281c884b1c30bca"},
{
          "id":"1485a79957f740c2b3eaeca479471aff",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "location":{
              "x":210,
              "y":410},
            "size":{
              "width":190,
              "height":30},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFD7D7D7}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ba1f0760bd6b4c25b6c88a90d31bcc0e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "location":{
                  "x":210,
                  "y":410},
                "size":{
                  "width":190,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/管理资源单/u235.png"}},
{
          "id":"054cd4a297e64a00875cade452e6969e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "location":{
              "x":420,
              "y":150},
            "size":{
              "width":150,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8b561119d8d14d1abb55bec81e5bcf66",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "location":{
                  "x":420,
                  "y":150},
                "size":{
                  "width":150,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"01040bce84084b46938e4b998b145344",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":420,
              "y":182},
            "size":{
              "width":780,
              "height":280},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFD7D7D7}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1295150414ef43bd90f35ea60394eaa0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":420,
                  "y":182},
                "size":{
                  "width":780,
                  "height":280},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/订单改价/u43.png"}},
{
          "id":"fdb1c01dfe9e410c851f60611885fa4c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontWeight":"700",
            "location":{
              "x":440,
              "y":196},
            "size":{
              "width":260,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dcbbb3ad074a4d9eb2de105d3918572f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"700",
                "location":{
                  "x":440,
                  "y":196},
                "size":{
                  "width":260,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8f1add5b5c5b42e2aa0c788e14b951ea",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":440,
              "y":234},
            "size":{
              "width":38,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"35f399cd8b6b4a89b75876fd047d33fa",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":440,
                  "y":234},
                "size":{
                  "width":38,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a9e535dc48764448be389ca11ec6de5c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"center",
            "location":{
              "x":801,
              "y":234},
            "size":{
              "width":70,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bc078158035e42378ce833dfd6e8f779",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "location":{
                  "x":801,
                  "y":234},
                "size":{
                  "width":70,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"70c88065e5e5405ba287959f3001c529",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"center",
            "location":{
              "x":924,
              "y":234},
            "size":{
              "width":79,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"aeb985a7b51e478db013df70d20876b8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "location":{
                  "x":924,
                  "y":234},
                "size":{
                  "width":79,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ac506b6a48974fbfa60ab3535e606ba3",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"center",
            "location":{
              "x":1115,
              "y":234},
            "size":{
              "width":38,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b79425ce6bd84271a26dbb7d8660f302",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "location":{
                  "x":1115,
                  "y":234},
                "size":{
                  "width":38,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"dda925b63d9e48d593d6e83575136fd8",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"center",
            "location":{
              "x":572,
              "y":234},
            "size":{
              "width":38,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2c060ac7eeea42df9bdedeadc9c462ad",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "location":{
                  "x":572,
                  "y":234},
                "size":{
                  "width":38,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"72ab4a623980488dbbebe2407ed8b445",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"center",
            "location":{
              "x":705,
              "y":234},
            "size":{
              "width":38,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"28fa3031b97d469fa47117b4a5694f73",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "location":{
                  "x":705,
                  "y":234},
                "size":{
                  "width":38,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2558db8ab4a74d1685572c2fcd33794e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":440,
              "y":284},
            "size":{
              "width":92,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e002f53eccfa43a0b90e7fac8edac7a8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":440,
                  "y":284},
                "size":{
                  "width":92,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9f183cf78e4441df8e456a922475251d",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":440,
              "y":262},
            "size":{
              "width":732,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFD7D7D7}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/订单改价/u61_line.png"}},
{
          "id":"f6f292d7aa1641398d1369dceaa5f638",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"center",
            "location":{
              "x":545,
              "y":284},
            "size":{
              "width":92,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f2984c67b43f454ab6b28f771d472d35",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "location":{
                  "x":545,
                  "y":284},
                "size":{
                  "width":92,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"357e915ec57645b9a8015d1803ee0d18",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"center",
            "location":{
              "x":678,
              "y":284},
            "size":{
              "width":92,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"17a35e84b0e44edab3ea5cca93b69365",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "location":{
                  "x":678,
                  "y":284},
                "size":{
                  "width":92,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"90bfbba6b43d4d0ab86b8794b137ed0b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"center",
            "location":{
              "x":790,
              "y":284},
            "size":{
              "width":92,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f88066da971c481380ecd997eedefe08",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "location":{
                  "x":790,
                  "y":284},
                "size":{
                  "width":92,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1ec5834380244205b661558b8b0b62cc",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF3333,
              "opacity":1},
            "location":{
              "x":919,
              "y":284},
            "size":{
              "width":92,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2d20dae376a44cbe8676fef00c954505",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF3333,
                  "opacity":1},
                "location":{
                  "x":919,
                  "y":284},
                "size":{
                  "width":92,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"cbe0bf4385ac4e13949ff2e2d014582a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF3333,
              "opacity":1},
            "location":{
              "x":1088,
              "y":284},
            "size":{
              "width":92,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a47fce56bd944ca6bcd642f4f96cc571",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF3333,
                  "opacity":1},
                "location":{
                  "x":1088,
                  "y":284},
                "size":{
                  "width":92,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6f876616586943178b008639ee9345de",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":440,
              "y":314},
            "size":{
              "width":92,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f81eab36dc7546fcb434cf2fd374f144",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":440,
                  "y":314},
                "size":{
                  "width":92,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a64e4ebf6df34cf1b23fec6fb777f01c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"center",
            "location":{
              "x":545,
              "y":314},
            "size":{
              "width":92,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fc0f4ce788744f79b7870133b1620bc3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "location":{
                  "x":545,
                  "y":314},
                "size":{
                  "width":92,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"491db07f98f045bda4aee5f9d26e8b1e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"center",
            "location":{
              "x":678,
              "y":314},
            "size":{
              "width":92,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a2d32d06f05243b9988c6a84b59bc100",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "location":{
                  "x":678,
                  "y":314},
                "size":{
                  "width":92,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6ead5eaf15894f689ea1a4e568a63c2a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"center",
            "location":{
              "x":790,
              "y":314},
            "size":{
              "width":92,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1c779fe64fad4e90910c346b90516ef3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "location":{
                  "x":790,
                  "y":314},
                "size":{
                  "width":92,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3a781bcb69ec4926931c44c112356e84",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF3333,
              "opacity":1},
            "location":{
              "x":919,
              "y":314},
            "size":{
              "width":92,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8130b93957c14f45ab665c25d43f98de",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF3333,
                  "opacity":1},
                "location":{
                  "x":919,
                  "y":314},
                "size":{
                  "width":92,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"74bbf475804b486a9c05e3589c3c44e8",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF3333,
              "opacity":1},
            "location":{
              "x":1088,
              "y":314},
            "size":{
              "width":92,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"908fef74e1ab4bb98bab470b54613b19",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF3333,
                  "opacity":1},
                "location":{
                  "x":1088,
                  "y":314},
                "size":{
                  "width":92,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"378d580a795c4d9eba05a285a6848930",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":440,
              "y":342},
            "size":{
              "width":92,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"df25b96549064009b2f927f94eb2635a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":440,
                  "y":342},
                "size":{
                  "width":92,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"974d62d861864843b992c6fce54f4bd2",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"center",
            "location":{
              "x":545,
              "y":342},
            "size":{
              "width":92,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fcacb4ff14304988a9a2db1ae0b9103f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "location":{
                  "x":545,
                  "y":342},
                "size":{
                  "width":92,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"cea4122fd07448328432e336552a7161",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"center",
            "location":{
              "x":678,
              "y":342},
            "size":{
              "width":92,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8f4f4391fcdb4c9cb2f1475edd7185d4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "location":{
                  "x":678,
                  "y":342},
                "size":{
                  "width":92,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"bc79844c8a564b89821d17ea44149bc5",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"center",
            "location":{
              "x":790,
              "y":342},
            "size":{
              "width":92,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ad400c7c779141c8a3edf4202de0e023",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "location":{
                  "x":790,
                  "y":342},
                "size":{
                  "width":92,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7b1e7d706cdb42a8bcf89fd71ae20298",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF3333,
              "opacity":1},
            "location":{
              "x":919,
              "y":342},
            "size":{
              "width":92,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"87432cea679547a9bb2d62696e831f50",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF3333,
                  "opacity":1},
                "location":{
                  "x":919,
                  "y":342},
                "size":{
                  "width":92,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f4fcb576b5894b5cb95fcffc1bc00841",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF3333,
              "opacity":1},
            "location":{
              "x":1088,
              "y":342},
            "size":{
              "width":92,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7f924fe191a84e8199ecf9db852fc804",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF3333,
                  "opacity":1},
                "location":{
                  "x":1088,
                  "y":342},
                "size":{
                  "width":92,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f239cd4bdc104af0acae91cf369d3516",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":972,
              "y":392},
            "size":{
              "width":200,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/订单改价/u96_line.png"}},
{
          "id":"897641628c804378b646512c67a196df",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"right",
            "location":{
              "x":963,
              "y":426},
            "size":{
              "width":90,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f3666c4cf831457ca91c263ec6a2445a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"right",
                "location":{
                  "x":963,
                  "y":426},
                "size":{
                  "width":90,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0f428cac104b4cedbc3ed7c31b6db91c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"right",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF3333,
              "opacity":1},
            "location":{
              "x":1072,
              "y":426},
            "size":{
              "width":100,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6459189084754631bcfabe27a65436ee",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"right",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF3333,
                  "opacity":1},
                "location":{
                  "x":1072,
                  "y":426},
                "size":{
                  "width":100,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"12a4ed0c6594438db285f07bd4e9d9eb",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":420,
              "y":480},
            "size":{
              "width":780,
              "height":260},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFD7D7D7}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cc4fe387879345c19e29808a62725555",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":420,
                  "y":480},
                "size":{
                  "width":780,
                  "height":260},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/订单改价/u101.png"}},
{
          "id":"e0fab0c20adb4807b985f8dee9364466",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontWeight":"700",
            "location":{
              "x":440,
              "y":494},
            "size":{
              "width":260,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2e2549d7a287489c92e56679aa7c10ba",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"700",
                "location":{
                  "x":440,
                  "y":494},
                "size":{
                  "width":260,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"813e81b66ab6413682666c7eb1899c14",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":456,
              "y":534},
            "size":{
              "width":76,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f4bd5b69a790479c872d83c1403b1d1b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":456,
                  "y":534},
                "size":{
                  "width":76,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9c01c4b7129a427c9f6532a686d653ea",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":532,
              "y":534},
            "size":{
              "width":640,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"59df8d86395047a4b409dbb6da0046ea",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":532,
                  "y":534},
                "size":{
                  "width":640,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"337e3a349a3e49f2872bbc394a089434",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":456,
              "y":570},
            "size":{
              "width":76,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d2cb892081444ac3a5ae7cb592ca8daa",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":456,
                  "y":570},
                "size":{
                  "width":76,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"37b6bec0c7d343a18e9d258c540b3fca",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":532,
              "y":566},
            "size":{
              "width":98,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"1e61e3fbe96f438689b98f1f62e0d4ca",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":640,
              "y":570},
            "size":{
              "width":532,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5356a2d076a94a87a89d5f8cf5e37680",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":640,
                  "y":570},
                "size":{
                  "width":532,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b20e29b1d00e4f5095b488bd76578762",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":456,
              "y":604},
            "size":{
              "width":76,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4418fe518c2e4042974e7e65abbe9dc0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":456,
                  "y":604},
                "size":{
                  "width":76,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"39036dd8460e488ba7154a9df7d7a9bf",
          "label":"",
          "type":"textArea",
          "styleType":"textArea",
          "visible":true,
          "style":{
            "location":{
              "x":532,
              "y":604},
            "size":{
              "width":640,
              "height":76}},
          "adaptiveStyles":{
}},
{
          "id":"ba0f1a7fda68473987adc2555850b906",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":532,
              "y":690},
            "size":{
              "width":100,
              "height":30}},
          "adaptiveStyles":{
}}]}},
  "masters":{
    "21e4130fae884c10a964094359915ae7":{
      "packageId":"21e4130fae884c10a964094359915ae7",
      "type":"Axure:Master",
      "name":"交易员头部--供应",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"应用字体",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"11a2262448e0441f9a29e02867462317",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "size":{
                "width":1400,
                "height":90},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFD7D7D7}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"2fb6fec02a5946deb468d94b926d5702",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "size":{
                    "width":1400,
                    "height":90},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFD7D7D7}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/我的工作台/u3.png"}},
{
            "id":"d272761cc28841aabfc377d601a1ee83",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":200,
                "y":15},
              "size":{
                "width":200,
                "height":60},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFD7D7D7}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"304b1fa2e1004612895198bae19aad1c",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":200,
                    "y":15},
                  "size":{
                    "width":200,
                    "height":60},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFD7D7D7}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/我的工作台/u5.png"}},
{
            "id":"1ff87331235e44d3907f0495638c3ee8",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFFF2F2F2},
              "location":{
                "x":0,
                "y":90},
              "size":{
                "width":1400,
                "height":35},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFD7D7D7}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"8dea732008a44e7ba0aa5e0d23bc0e6b",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFF2F2F2},
                  "location":{
                    "x":0,
                    "y":90},
                  "size":{
                    "width":1400,
                    "height":35},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFD7D7D7}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/首页/u33.png"}},
{
            "id":"0ae756c78f1d4827bd92090a57c2445d",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":200,
                "y":90},
              "size":{
                "width":130,
                "height":35},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFD7D7D7}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"fa593240b6704c1390d0e2aefef6074a",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":200,
                    "y":90},
                  "size":{
                    "width":130,
                    "height":35},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFD7D7D7}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/我的工作台/u11.png"}},
{
            "id":"3718fe3583d442998538f8f62ebde4ea",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":330,
                "y":90},
              "size":{
                "width":130,
                "height":35},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFD7D7D7}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"13c36587be2d43fe8c5570fc2d88bd70",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":330,
                    "y":90},
                  "size":{
                    "width":130,
                    "height":35},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFD7D7D7}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/我的工作台/u11.png"}},
{
            "id":"740447a8f9974829b66fda708f6c498a",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "horizontalAlignment":"right",
              "location":{
                "x":940,
                "y":15},
              "size":{
                "width":260,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"e59823160cf343a7b7b15c68842e9ec4",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "horizontalAlignment":"right",
                  "location":{
                    "x":940,
                    "y":15},
                  "size":{
                    "width":260,
                    "height":16}},
                "adaptiveStyles":{
},
                "objects":[{
                    "id":"71c3f17e76ad4da094bbbc83ef6d89c6",
                    "label":"",
                    "type":"hyperlink",
                    "styleType":"hyperlink",
                    "visible":true,
                    "style":{
},
                    "adaptiveStyles":{
},
                    "interactionMap":{
                      "onClick":{
                        "description":"OnClick",
                        "cases":[{
                            "description":"用例 1",
                            "isNewIfGroup":false,
                            "actions":[{
                                "action":"linkWindow",
                                "description":"在 当前窗口 打开 帐号设置",
                                "target":{
                                  "targetType":"page",
                                  "url":"帐号设置.html",
                                  "includeVariables":true},
                                "linkType":"current"}]}]}},
                    "tabbable":true}]}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"26e90f6816b141c2a3ccc90fcb4e3ad2",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFFE4E4E4},
              "location":{
                "x":460,
                "y":90},
              "size":{
                "width":130,
                "height":35},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFD7D7D7}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"87f924faedc44651acc076fb8bcf26ec",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFE4E4E4},
                  "location":{
                    "x":460,
                    "y":90},
                  "size":{
                    "width":130,
                    "height":35},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFD7D7D7}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/我的工作台/u9.png"}},
{
            "id":"d405562eefe64e40b9eee95bd35f86d2",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":590,
                "y":90},
              "size":{
                "width":130,
                "height":35},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFD7D7D7}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"680fbf1cc0354878b448474e2f56ea9c",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":590,
                    "y":90},
                  "size":{
                    "width":130,
                    "height":35},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFD7D7D7}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/我的工作台/u11.png"}},
{
            "id":"42aa15f9c68b43258f7a7ba1cc419f4f",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":720,
                "y":90},
              "size":{
                "width":130,
                "height":35},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFD7D7D7}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"e1e480361e0e40ebb87f11d7feeb3fed",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":720,
                    "y":90},
                  "size":{
                    "width":130,
                    "height":35},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFD7D7D7}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/我的工作台/u11.png"}},
{
            "id":"064ceb8707214861bd923caade5be54b",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":850,
                "y":90},
              "size":{
                "width":130,
                "height":35},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFD7D7D7}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"c3f014af43f345c98ffd04d02934454e",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":850,
                    "y":90},
                  "size":{
                    "width":130,
                    "height":35},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFD7D7D7}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/我的工作台/u11.png"}},
{
            "id":"8538fb5ca9d145199d86ad77c4219af4",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":980,
                "y":90},
              "size":{
                "width":130,
                "height":35},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFD7D7D7}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"1ef2674e65ec4d95842cf8713564dbe0",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":980,
                    "y":90},
                  "size":{
                    "width":130,
                    "height":35},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFD7D7D7}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/我的工作台/u11.png"}}]}},
    "9aa3da306ba24637b281c884b1c30bca":{
      "packageId":"9aa3da306ba24637b281c884b1c30bca",
      "type":"Axure:Master",
      "name":"交易员底部",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"应用字体",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"aa94056b817049cbb1fa6bacb8c1e519",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "size":{
                "width":1400,
                "height":40},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFD7D7D7}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"d0f70829d22f42fea545dfa7923b52be",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "size":{
                    "width":1400,
                    "height":40},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFD7D7D7}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/首页/u13.png"}}]}}},
  "objectPaths":{
    "7917e4d30eb145e3968e8c789ef7ba14":{
      "scriptId":"u0",
      "11a2262448e0441f9a29e02867462317":{
        "scriptId":"u1"},
      "2fb6fec02a5946deb468d94b926d5702":{
        "scriptId":"u2"},
      "d272761cc28841aabfc377d601a1ee83":{
        "scriptId":"u3"},
      "304b1fa2e1004612895198bae19aad1c":{
        "scriptId":"u4"},
      "1ff87331235e44d3907f0495638c3ee8":{
        "scriptId":"u5"},
      "8dea732008a44e7ba0aa5e0d23bc0e6b":{
        "scriptId":"u6"},
      "0ae756c78f1d4827bd92090a57c2445d":{
        "scriptId":"u7"},
      "fa593240b6704c1390d0e2aefef6074a":{
        "scriptId":"u8"},
      "3718fe3583d442998538f8f62ebde4ea":{
        "scriptId":"u9"},
      "13c36587be2d43fe8c5570fc2d88bd70":{
        "scriptId":"u10"},
      "740447a8f9974829b66fda708f6c498a":{
        "scriptId":"u11"},
      "e59823160cf343a7b7b15c68842e9ec4":{
        "scriptId":"u12"},
      "71c3f17e76ad4da094bbbc83ef6d89c6":{
        "scriptId":"u13"},
      "26e90f6816b141c2a3ccc90fcb4e3ad2":{
        "scriptId":"u14"},
      "87f924faedc44651acc076fb8bcf26ec":{
        "scriptId":"u15"},
      "d405562eefe64e40b9eee95bd35f86d2":{
        "scriptId":"u16"},
      "680fbf1cc0354878b448474e2f56ea9c":{
        "scriptId":"u17"},
      "42aa15f9c68b43258f7a7ba1cc419f4f":{
        "scriptId":"u18"},
      "e1e480361e0e40ebb87f11d7feeb3fed":{
        "scriptId":"u19"},
      "064ceb8707214861bd923caade5be54b":{
        "scriptId":"u20"},
      "c3f014af43f345c98ffd04d02934454e":{
        "scriptId":"u21"},
      "8538fb5ca9d145199d86ad77c4219af4":{
        "scriptId":"u22"},
      "1ef2674e65ec4d95842cf8713564dbe0":{
        "scriptId":"u23"}},
    "a14d4b527f484f9eb0464391f4723b5c":{
      "scriptId":"u24"},
    "82583bad9b7f41bbaf550e736814d1ed":{
      "scriptId":"u25"},
    "3772c878709248b1a69547adaf116df1":{
      "scriptId":"u26"},
    "bbfceda3ea0948f5a4c3f518bbdb31ce":{
      "scriptId":"u27"},
    "1527a2cb854f4352b364f5b7da39d4cf":{
      "scriptId":"u28"},
    "e4d868af91ce47f78a53cef9325f6474":{
      "scriptId":"u29"},
    "fc8896fbed1a413db31faefc9ce3ec26":{
      "scriptId":"u30"},
    "41509ce18135400d810e638499431fa3":{
      "scriptId":"u31"},
    "e33540d64dc742e98698b99d033c0de4":{
      "scriptId":"u32"},
    "0ccd1dd4c2644b968cd74afce80edc97":{
      "scriptId":"u33"},
    "5444764a0a2b48069e090bbfdbc8d922":{
      "scriptId":"u34"},
    "7f056c0a12984de39e9e322521ffbeae":{
      "scriptId":"u35"},
    "455d5e129edd475d91d79af61be56b21":{
      "scriptId":"u36",
      "aa94056b817049cbb1fa6bacb8c1e519":{
        "scriptId":"u37"},
      "d0f70829d22f42fea545dfa7923b52be":{
        "scriptId":"u38"}},
    "1485a79957f740c2b3eaeca479471aff":{
      "scriptId":"u39"},
    "ba1f0760bd6b4c25b6c88a90d31bcc0e":{
      "scriptId":"u40"},
    "054cd4a297e64a00875cade452e6969e":{
      "scriptId":"u41"},
    "8b561119d8d14d1abb55bec81e5bcf66":{
      "scriptId":"u42"},
    "01040bce84084b46938e4b998b145344":{
      "scriptId":"u43"},
    "1295150414ef43bd90f35ea60394eaa0":{
      "scriptId":"u44"},
    "fdb1c01dfe9e410c851f60611885fa4c":{
      "scriptId":"u45"},
    "dcbbb3ad074a4d9eb2de105d3918572f":{
      "scriptId":"u46"},
    "8f1add5b5c5b42e2aa0c788e14b951ea":{
      "scriptId":"u47"},
    "35f399cd8b6b4a89b75876fd047d33fa":{
      "scriptId":"u48"},
    "a9e535dc48764448be389ca11ec6de5c":{
      "scriptId":"u49"},
    "bc078158035e42378ce833dfd6e8f779":{
      "scriptId":"u50"},
    "70c88065e5e5405ba287959f3001c529":{
      "scriptId":"u51"},
    "aeb985a7b51e478db013df70d20876b8":{
      "scriptId":"u52"},
    "ac506b6a48974fbfa60ab3535e606ba3":{
      "scriptId":"u53"},
    "b79425ce6bd84271a26dbb7d8660f302":{
      "scriptId":"u54"},
    "dda925b63d9e48d593d6e83575136fd8":{
      "scriptId":"u55"},
    "2c060ac7eeea42df9bdedeadc9c462ad":{
      "scriptId":"u56"},
    "72ab4a623980488dbbebe2407ed8b445":{
      "scriptId":"u57"},
    "28fa3031b97d469fa47117b4a5694f73":{
      "scriptId":"u58"},
    "2558db8ab4a74d1685572c2fcd33794e":{
      "scriptId":"u59"},
    "e002f53eccfa43a0b90e7fac8edac7a8":{
      "scriptId":"u60"},
    "9f183cf78e4441df8e456a922475251d":{
      "scriptId":"u61"},
    "f6f292d7aa1641398d1369dceaa5f638":{
      "scriptId":"u62"},
    "f2984c67b43f454ab6b28f771d472d35":{
      "scriptId":"u63"},
    "357e915ec57645b9a8015d1803ee0d18":{
      "scriptId":"u64"},
    "17a35e84b0e44edab3ea5cca93b69365":{
      "scriptId":"u65"},
    "90bfbba6b43d4d0ab86b8794b137ed0b":{
      "scriptId":"u66"},
    "f88066da971c481380ecd997eedefe08":{
      "scriptId":"u67"},
    "1ec5834380244205b661558b8b0b62cc":{
      "scriptId":"u68"},
    "2d20dae376a44cbe8676fef00c954505":{
      "scriptId":"u69"},
    "cbe0bf4385ac4e13949ff2e2d014582a":{
      "scriptId":"u70"},
    "a47fce56bd944ca6bcd642f4f96cc571":{
      "scriptId":"u71"},
    "6f876616586943178b008639ee9345de":{
      "scriptId":"u72"},
    "f81eab36dc7546fcb434cf2fd374f144":{
      "scriptId":"u73"},
    "a64e4ebf6df34cf1b23fec6fb777f01c":{
      "scriptId":"u74"},
    "fc0f4ce788744f79b7870133b1620bc3":{
      "scriptId":"u75"},
    "491db07f98f045bda4aee5f9d26e8b1e":{
      "scriptId":"u76"},
    "a2d32d06f05243b9988c6a84b59bc100":{
      "scriptId":"u77"},
    "6ead5eaf15894f689ea1a4e568a63c2a":{
      "scriptId":"u78"},
    "1c779fe64fad4e90910c346b90516ef3":{
      "scriptId":"u79"},
    "3a781bcb69ec4926931c44c112356e84":{
      "scriptId":"u80"},
    "8130b93957c14f45ab665c25d43f98de":{
      "scriptId":"u81"},
    "74bbf475804b486a9c05e3589c3c44e8":{
      "scriptId":"u82"},
    "908fef74e1ab4bb98bab470b54613b19":{
      "scriptId":"u83"},
    "378d580a795c4d9eba05a285a6848930":{
      "scriptId":"u84"},
    "df25b96549064009b2f927f94eb2635a":{
      "scriptId":"u85"},
    "974d62d861864843b992c6fce54f4bd2":{
      "scriptId":"u86"},
    "fcacb4ff14304988a9a2db1ae0b9103f":{
      "scriptId":"u87"},
    "cea4122fd07448328432e336552a7161":{
      "scriptId":"u88"},
    "8f4f4391fcdb4c9cb2f1475edd7185d4":{
      "scriptId":"u89"},
    "bc79844c8a564b89821d17ea44149bc5":{
      "scriptId":"u90"},
    "ad400c7c779141c8a3edf4202de0e023":{
      "scriptId":"u91"},
    "7b1e7d706cdb42a8bcf89fd71ae20298":{
      "scriptId":"u92"},
    "87432cea679547a9bb2d62696e831f50":{
      "scriptId":"u93"},
    "f4fcb576b5894b5cb95fcffc1bc00841":{
      "scriptId":"u94"},
    "7f924fe191a84e8199ecf9db852fc804":{
      "scriptId":"u95"},
    "f239cd4bdc104af0acae91cf369d3516":{
      "scriptId":"u96"},
    "897641628c804378b646512c67a196df":{
      "scriptId":"u97"},
    "f3666c4cf831457ca91c263ec6a2445a":{
      "scriptId":"u98"},
    "0f428cac104b4cedbc3ed7c31b6db91c":{
      "scriptId":"u99"},
    "6459189084754631bcfabe27a65436ee":{
      "scriptId":"u100"},
    "12a4ed0c6594438db285f07bd4e9d9eb":{
      "scriptId":"u101"},
    "cc4fe387879345c19e29808a62725555":{
      "scriptId":"u102"},
    "e0fab0c20adb4807b985f8dee9364466":{
      "scriptId":"u103"},
    "2e2549d7a287489c92e56679aa7c10ba":{
      "scriptId":"u104"},
    "813e81b66ab6413682666c7eb1899c14":{
      "scriptId":"u105"},
    "f4bd5b69a790479c872d83c1403b1d1b":{
      "scriptId":"u106"},
    "9c01c4b7129a427c9f6532a686d653ea":{
      "scriptId":"u107"},
    "59df8d86395047a4b409dbb6da0046ea":{
      "scriptId":"u108"},
    "337e3a349a3e49f2872bbc394a089434":{
      "scriptId":"u109"},
    "d2cb892081444ac3a5ae7cb592ca8daa":{
      "scriptId":"u110"},
    "37b6bec0c7d343a18e9d258c540b3fca":{
      "scriptId":"u111"},
    "1e61e3fbe96f438689b98f1f62e0d4ca":{
      "scriptId":"u112"},
    "5356a2d076a94a87a89d5f8cf5e37680":{
      "scriptId":"u113"},
    "b20e29b1d00e4f5095b488bd76578762":{
      "scriptId":"u114"},
    "4418fe518c2e4042974e7e65abbe9dc0":{
      "scriptId":"u115"},
    "39036dd8460e488ba7154a9df7d7a9bf":{
      "scriptId":"u116"},
    "ba0f1a7fda68473987adc2555850b906":{
      "scriptId":"u117"}}});