$axure.loadCurrentPage({
  "url":"托运管理_1.html",
  "generationDate":new Date(1432872291755.3),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"cb55d54d10464d4a8a17fe6a88f07b4b",
    "type":"Axure:Page",
    "name":"托运管理",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"ec7ad943e33143f9a37ac5d8757cd99b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":200,
              "y":150},
            "size":{
              "width":200,
              "height":80},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFD7D7D7}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f5eac5691794432d9fd149617ab82471",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":200,
                  "y":150},
                "size":{
                  "width":200,
                  "height":80},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的工作台/u26.png"}},
{
          "id":"80378f6d952b46a1a9575ded331d8f30",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFE4E4E4},
            "location":{
              "x":200,
              "y":230},
            "size":{
              "width":200,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFD7D7D7}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e9c994e2b1484293ab3a073aa42198d9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4},
                "location":{
                  "x":200,
                  "y":230},
                "size":{
                  "width":200,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的工作台/u28.png"}},
{
          "id":"47f384a2cb774eeead965ca452043bd4",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":200,
              "y":330},
            "size":{
              "width":200,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFD7D7D7}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7513e70cf52c49a1ad44183192e970d5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":200,
                  "y":330},
                "size":{
                  "width":200,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的工作台/u30.png"}},
{
          "id":"b2d98d2bd4054e65be9527af17268764",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":1007}},
          "adaptiveStyles":{
},
          "masterId":"9aa3da306ba24637b281c884b1c30bca"},
{
          "id":"a162a782c7f94ad48e970fb5ed8142c0",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "location":{
              "x":210,
              "y":300},
            "size":{
              "width":190,
              "height":30},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFD7D7D7}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2150748958a94a42bb6d2252b9b56c5d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "location":{
                  "x":210,
                  "y":300},
                "size":{
                  "width":190,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/管理资源单/u235.png"}},
{
          "id":"84a385ad74e04bf592e3d9ed7806bade",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "fill":{
              "fillType":"solid",
              "color":0xFFE4E4E4},
            "location":{
              "x":210,
              "y":270},
            "size":{
              "width":190,
              "height":30},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFD7D7D7}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cd4521f5f1d44e5db17416bb7c511b10",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4},
                "location":{
                  "x":210,
                  "y":270},
                "size":{
                  "width":190,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/管理资源单/u233.png"}},
{
          "id":"344d020ea80140f39a1b4c20c80b45e0",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
},
          "adaptiveStyles":{
},
          "masterId":"d5b739f105d347138233b0627c50cf7b"},
{
          "id":"1f110d8e44c44c548e9300a484c9824a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":420,
              "y":266},
            "size":{
              "width":780,
              "height":724},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFD7D7D7}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4f142478882e48e488c01c7930fb4c7c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":420,
                  "y":266},
                "size":{
                  "width":780,
                  "height":724},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/托运管理_1/u37.png"}},
{
          "id":"4aa01aa346124edbbc992072cc327352",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":420,
              "y":266},
            "size":{
              "width":780,
              "height":30},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFD7D7D7}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c9c2d7e9ea284993a00352854669c72a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":420,
                  "y":266},
                "size":{
                  "width":780,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/竞价管理/u57.png"}},
{
          "id":"8f7e00062ecb4d9a8e81fc03f5a67a5a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontWeight":"700",
            "location":{
              "x":591,
              "y":273},
            "size":{
              "width":111,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e711d957baa24689a7f85bb9fb8c53ef",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"700",
                "location":{
                  "x":591,
                  "y":273},
                "size":{
                  "width":111,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"92b8db6576eb4bd5a20ffaa5a4d77162",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontWeight":"700",
            "location":{
              "x":798,
              "y":273},
            "size":{
              "width":80,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"17e7902e94c2490892ac1bc00d641898",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"700",
                "location":{
                  "x":798,
                  "y":273},
                "size":{
                  "width":80,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"187f2b814fb24d5f9f27cd2a1354d183",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":591,
              "y":315},
            "size":{
              "width":239,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4554ef83473e4518af9a78f832b31f48",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":591,
                  "y":315},
                "size":{
                  "width":239,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b0033cbc0a134f779397fad48f931b4b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":591,
              "y":349},
            "size":{
              "width":239,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8282b9556e4049e088f23b660baf41da",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":591,
                  "y":349},
                "size":{
                  "width":239,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"db0a2cc41fb2403599c65ecf1bb6aa66",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":591,
              "y":380},
            "size":{
              "width":239,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"69351cac68294090b54859f0f3c9aa1a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":591,
                  "y":380},
                "size":{
                  "width":239,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0c8a1b5ba1704104938a10a19012491c",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":436,
              "y":416},
            "size":{
              "width":748,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFD7D7D7}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/托运管理_1/u51_line.png"}},
{
          "id":"c33a9bf6ae7d4d5bb981b8c8af9c0872",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"center",
            "location":{
              "x":768,
              "y":315},
            "size":{
              "width":103,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"257eb3968ad541f6aeea431a1bfd70e1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "location":{
                  "x":768,
                  "y":315},
                "size":{
                  "width":103,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b6c075f1910c4b1aa6e55d68e2af8c61",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontWeight":"700",
            "location":{
              "x":944,
              "y":273},
            "size":{
              "width":105,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6e68a4675efb4841a7117010e834ac6d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"700",
                "location":{
                  "x":944,
                  "y":273},
                "size":{
                  "width":105,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0f663232faa14259b921ddaab3a4bfb2",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":944,
              "y":315},
            "size":{
              "width":240,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"23afcf52f2f54c8f99c8c3e0636db7c3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":944,
                  "y":315},
                "size":{
                  "width":240,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"31fdd3ef56f947b2ade74d2237d9de8e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":591,
              "y":446},
            "size":{
              "width":239,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fb20677895d94a37a6c7b4978ad2e84b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":591,
                  "y":446},
                "size":{
                  "width":239,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e41e059de11046888b089f8fa24ed030",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":591,
              "y":480},
            "size":{
              "width":239,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cff118c537be4926b0893800aff23147",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":591,
                  "y":480},
                "size":{
                  "width":239,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"09efe07b6a9e410888e1bd5abd501866",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":591,
              "y":511},
            "size":{
              "width":239,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5320a35ec6024b739c904c36c7d95c40",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":591,
                  "y":511},
                "size":{
                  "width":239,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7185d60986b7435fa24eaf199fc8778e",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":436,
              "y":547},
            "size":{
              "width":748,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFD7D7D7}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/托运管理_1/u51_line.png"}},
{
          "id":"a3fdf8ffc2874ceea12daace1b72ec83",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"center",
            "location":{
              "x":769,
              "y":446},
            "size":{
              "width":103,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"02bf7a75340444779c8a93f1ccaecca3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "location":{
                  "x":769,
                  "y":446},
                "size":{
                  "width":103,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6f2a4f43a0f248968b5711e11421cd0b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":944,
              "y":446},
            "size":{
              "width":240,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d673e81b925649cca7d05c778fd4ba93",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":944,
                  "y":446},
                "size":{
                  "width":240,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f3ed62212d94475399393694bc8719f8",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":944,
              "y":507},
            "size":{
              "width":105,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"5e3f0aed18db48e693ef575cf9422742",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":591,
              "y":585},
            "size":{
              "width":239,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"20af94d8014647f7aed73a8e88285a91",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":591,
                  "y":585},
                "size":{
                  "width":239,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"86ce250ad9944b05985c8a3604231beb",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":591,
              "y":619},
            "size":{
              "width":239,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e3963682ef5a453ba958b13e5d8e70e0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":591,
                  "y":619},
                "size":{
                  "width":239,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5ef623b704c34900a08ff0cec8f6f828",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":591,
              "y":650},
            "size":{
              "width":239,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9adb41e95da84e889f665154e47c44b5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":591,
                  "y":650},
                "size":{
                  "width":239,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ac03e1b99109420d991fb10adab8fb03",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":436,
              "y":686},
            "size":{
              "width":748,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFD7D7D7}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/托运管理_1/u51_line.png"}},
{
          "id":"bf2d11bfb86f470abd3aeb28aa55f8e7",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"center",
            "location":{
              "x":769,
              "y":585},
            "size":{
              "width":103,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8d687ac23cfb46cfa3d2c5cd150e47c7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "location":{
                  "x":769,
                  "y":585},
                "size":{
                  "width":103,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c660c30d31ae44c2b0a11bbcfb5b8509",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":944,
              "y":585},
            "size":{
              "width":240,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"646fb846480644cebfe33e91fd80707f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":944,
                  "y":585},
                "size":{
                  "width":240,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6c6add651fa84dbab9518e8551cee49c",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":944,
              "y":646},
            "size":{
              "width":105,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"9bd5782139cc4aef919b2b5300617e56",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":591,
              "y":717},
            "size":{
              "width":239,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9949263383534e7f8150131811838e9c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":591,
                  "y":717},
                "size":{
                  "width":239,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1a05279ce1f84b8492263df933347f8c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":591,
              "y":751},
            "size":{
              "width":239,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a7c6695facfc468b932f2600b72c69eb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":591,
                  "y":751},
                "size":{
                  "width":239,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b43b2130af8d47f9b2899708dd2551a8",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":591,
              "y":782},
            "size":{
              "width":239,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"96f3cd68333942e7adc7d635ccf05b78",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":591,
                  "y":782},
                "size":{
                  "width":239,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9041acb2e191441e80bf057024483090",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":436,
              "y":817},
            "size":{
              "width":748,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFD7D7D7}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/托运管理_1/u51_line.png"}},
{
          "id":"06881f83c5c247edaaeb0efa50d67fe1",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"center",
            "location":{
              "x":769,
              "y":716},
            "size":{
              "width":103,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"52cc6896ccf94e36b0398c771f2437f8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "location":{
                  "x":769,
                  "y":716},
                "size":{
                  "width":103,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c1f644fd58e74f1db319ab52a3d04df4",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":944,
              "y":716},
            "size":{
              "width":240,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"43b3cf9b79964d4d97fbd15e5f43cf5b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":944,
                  "y":716},
                "size":{
                  "width":240,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c1b0bf1225c84154a442f49dc724cba4",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":944,
              "y":777},
            "size":{
              "width":105,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"ea51288dcb2c4ab4b60b7c809868f6fd",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":591,
              "y":855},
            "size":{
              "width":239,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"aced37551f274e92a683241e7fda5fed",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":591,
                  "y":855},
                "size":{
                  "width":239,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"cc69849d3bed4edb9cee94e7475c56f1",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":591,
              "y":889},
            "size":{
              "width":239,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2c2caaca2f824e8aaf9eab2950c1a4ed",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":591,
                  "y":889},
                "size":{
                  "width":239,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2c3c1848f3c648dda0540901843592cb",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":591,
              "y":920},
            "size":{
              "width":239,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9bd66a0fc5fe487dbc1d99d134694e95",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":591,
                  "y":920},
                "size":{
                  "width":239,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e9e8503cb77c402797a0a8fd65bc682f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"center",
            "location":{
              "x":769,
              "y":855},
            "size":{
              "width":103,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7f91c13406f84e0ca4ca3e7103dbe108",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "location":{
                  "x":769,
                  "y":855},
                "size":{
                  "width":103,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"cb00dd9ade0e482eb7ad460f0e04daf1",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":944,
              "y":855},
            "size":{
              "width":240,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d5ff62ba3c524287ab211059b7de6879",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":944,
                  "y":855},
                "size":{
                  "width":240,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"277b63f1ace349b482e7102326db3b5a",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":944,
              "y":916},
            "size":{
              "width":105,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"1175f394150043c7a02a4e79b33e48ff",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":576,
              "y":960},
            "size":{
              "width":504,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"981524d6b1c84410be702070fa37a819",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":576,
                  "y":960},
                "size":{
                  "width":504,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的收藏/u301.png"}},
{
          "id":"4d5b48cfb03c4a0f87cf71a0a81e9e29",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":420,
              "y":150},
            "size":{
              "width":780,
              "height":100},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFD7D7D7}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"53761eb703f54e81978c75cccbbf0626",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":420,
                  "y":150},
                "size":{
                  "width":780,
                  "height":100},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/托运管理_1/u107.png"}},
{
          "id":"7cdfd8aa4c2a4863adfb8248a134db29",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":436,
              "y":215},
            "size":{
              "width":111,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"66712b998fbe4c9484f5cf8888bd4e60",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":436,
                  "y":215},
                "size":{
                  "width":111,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"13904d8c37e94fdda4f3cd5359856ff1",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":502,
              "y":211},
            "size":{
              "width":188,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"12068f1a939c452ab4527c6bc0acc83b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":902,
              "y":169},
            "size":{
              "width":111,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ab9327509b9645c0be5feae2d4a6a7c2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":902,
                  "y":169},
                "size":{
                  "width":111,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b2e5ec6ec4ca4d70aed5837116eae833",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":967,
              "y":165},
            "size":{
              "width":135,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"c29dd3c441304d0f968a7b363a4b67a7",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":700,
              "y":211},
            "size":{
              "width":172,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"b58e352561c44ec0bd27a48b19d22495",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":436,
              "y":170},
            "size":{
              "width":111,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"aeae97d029ca4460a1c4f13cb261dbfb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":436,
                  "y":170},
                "size":{
                  "width":111,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8463610d35c743e3883fd92958ed3de3",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontWeight":"700",
            "location":{
              "x":436,
              "y":273},
            "size":{
              "width":111,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"40ff65d9f51742c6911ce73899606367",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"700",
                "location":{
                  "x":436,
                  "y":273},
                "size":{
                  "width":111,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ebd26bfbd88a494c92a091af09729ec5",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":944,
              "y":371},
            "size":{
              "width":105,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"39050940d69d465fa14123b22ed75909",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":436,
              "y":306},
            "size":{
              "width":84,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f3b6d6cb06e54b3091a45f86708fff4a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":436,
                  "y":306},
                "size":{
                  "width":84,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"967cd186d5ff4627b391b5326437ca4c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":436,
              "y":436},
            "size":{
              "width":84,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d6f101ffbc844687aee7c7202b69b1f0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":436,
                  "y":436},
                "size":{
                  "width":84,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3b831fa779c4469589809b17e3c6dc59",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":436,
              "y":585},
            "size":{
              "width":84,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c60a199917bb4ee9bf3e1d4e7d03c9fb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":436,
                  "y":585},
                "size":{
                  "width":84,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"feb774ad98164035aae3c44389c3f7bb",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":436,
              "y":717},
            "size":{
              "width":84,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9e3adc30787040cfad8f9c05bdc613b7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":436,
                  "y":717},
                "size":{
                  "width":84,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"51fcd4852fdc478285f5dadb6bebbb4a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":436,
              "y":855},
            "size":{
              "width":84,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f93e57d2dcb341d78b5df8e5c8a2888c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":436,
                  "y":855},
                "size":{
                  "width":84,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7fdb47b42fde48d289270ab23d90baaa",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":502,
              "y":167},
            "size":{
              "width":135,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"e6c5942e94764ab4bb81e644e51b8046",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":668,
              "y":168},
            "size":{
              "width":114,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5ece4056a0cd4789b9bc43f59034e5f2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":668,
                  "y":168},
                "size":{
                  "width":114,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9bfb421c0ed14bf8a8ff3ea2b22b3048",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":737,
              "y":164},
            "size":{
              "width":135,
              "height":25}},
          "adaptiveStyles":{
}}]}},
  "masters":{
    "9aa3da306ba24637b281c884b1c30bca":{
      "packageId":"9aa3da306ba24637b281c884b1c30bca",
      "type":"Axure:Master",
      "name":"交易员底部",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"应用字体",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"aa94056b817049cbb1fa6bacb8c1e519",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "size":{
                "width":1400,
                "height":40},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFD7D7D7}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"d0f70829d22f42fea545dfa7923b52be",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "size":{
                    "width":1400,
                    "height":40},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFD7D7D7}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/首页/u13.png"}}]}},
    "d5b739f105d347138233b0627c50cf7b":{
      "packageId":"d5b739f105d347138233b0627c50cf7b",
      "type":"Axure:Master",
      "name":"交易员头部--托运",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"应用字体",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"ad29d0868e2d4e1ea04d2e3813cac53e",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "size":{
                "width":1400,
                "height":90},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFD7D7D7}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"705ba8054db8459aa453d6e8970360e1",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "size":{
                    "width":1400,
                    "height":90},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFD7D7D7}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/我的工作台/u3.png"}},
{
            "id":"435294aeef7344768378c778f254ae49",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":200,
                "y":15},
              "size":{
                "width":200,
                "height":60},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFD7D7D7}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"423f499025e441208a01286ce6aefd3d",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":200,
                    "y":15},
                  "size":{
                    "width":200,
                    "height":60},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFD7D7D7}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/我的工作台/u5.png"}},
{
            "id":"5bff7bb0f32e4aaba352a33b10354ace",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFFF2F2F2},
              "location":{
                "x":0,
                "y":90},
              "size":{
                "width":1400,
                "height":35},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFD7D7D7}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"4f781b78feb94e5c9e8d524ff73eadfc",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFF2F2F2},
                  "location":{
                    "x":0,
                    "y":90},
                  "size":{
                    "width":1400,
                    "height":35},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFD7D7D7}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/首页/u33.png"}},
{
            "id":"08ae0434c50140e782a3740366b35ef6",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":200,
                "y":90},
              "size":{
                "width":130,
                "height":35},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFD7D7D7}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"98765ab47746412d8d002e805dd3f5c8",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":200,
                    "y":90},
                  "size":{
                    "width":130,
                    "height":35},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFD7D7D7}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/我的工作台/u11.png"}},
{
            "id":"5b1950c85d9d43979ce7ee038d82addd",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":330,
                "y":90},
              "size":{
                "width":130,
                "height":35},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFD7D7D7}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"922258fa17a1468e89be4de887eb9242",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":330,
                    "y":90},
                  "size":{
                    "width":130,
                    "height":35},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFD7D7D7}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/我的工作台/u11.png"}},
{
            "id":"196b102fa5434693932ec2ccadc2aa72",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "horizontalAlignment":"right",
              "location":{
                "x":940,
                "y":15},
              "size":{
                "width":260,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"05799b485a82452f859a0923a542670d",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "horizontalAlignment":"right",
                  "location":{
                    "x":940,
                    "y":15},
                  "size":{
                    "width":260,
                    "height":16}},
                "adaptiveStyles":{
},
                "objects":[{
                    "id":"9224b06f5bc3462d9761fb8b32aaaefc",
                    "label":"",
                    "type":"hyperlink",
                    "styleType":"hyperlink",
                    "visible":true,
                    "style":{
},
                    "adaptiveStyles":{
},
                    "interactionMap":{
                      "onClick":{
                        "description":"OnClick",
                        "cases":[{
                            "description":"用例 1",
                            "isNewIfGroup":false,
                            "actions":[{
                                "action":"linkWindow",
                                "description":"在 当前窗口 打开 帐号设置",
                                "target":{
                                  "targetType":"page",
                                  "url":"帐号设置.html",
                                  "includeVariables":true},
                                "linkType":"current"}]}]}},
                    "tabbable":true}]}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"03c2d1c0a018442fbae9cadc97fdbf9e",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":460,
                "y":90},
              "size":{
                "width":130,
                "height":35},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFD7D7D7}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"e3ae0d1bffa6454e953785c75dd9411e",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":460,
                    "y":90},
                  "size":{
                    "width":130,
                    "height":35},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFD7D7D7}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/我的工作台/u11.png"}},
{
            "id":"29e560d07ab1441c8bd2c912e6128056",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":590,
                "y":90},
              "size":{
                "width":130,
                "height":35},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFD7D7D7}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"e21c32341ad54afcbba6d7060f2aed87",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":590,
                    "y":90},
                  "size":{
                    "width":130,
                    "height":35},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFD7D7D7}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/我的工作台/u11.png"}},
{
            "id":"a93032c21bff4eff9ce74ad7de209ec8",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":720,
                "y":90},
              "size":{
                "width":130,
                "height":35},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFD7D7D7}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"8f58a485ce114857b88238e6126eea08",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":720,
                    "y":90},
                  "size":{
                    "width":130,
                    "height":35},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFD7D7D7}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/我的工作台/u11.png"}},
{
            "id":"55c1a272476d4a028543b54a8dbbc346",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFFE4E4E4},
              "location":{
                "x":850,
                "y":90},
              "size":{
                "width":130,
                "height":35},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFD7D7D7}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"227b88b93913401bba3bd8014f0993e8",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFE4E4E4},
                  "location":{
                    "x":850,
                    "y":90},
                  "size":{
                    "width":130,
                    "height":35},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFD7D7D7}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/我的工作台/u9.png"}},
{
            "id":"30e27b2aeacd454b8ddd21f178272d3a",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":980,
                "y":90},
              "size":{
                "width":130,
                "height":35},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFD7D7D7}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"7851308e4e85456daf8cce58bc2f888f",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":980,
                    "y":90},
                  "size":{
                    "width":130,
                    "height":35},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFD7D7D7}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/我的工作台/u11.png"}}]}}},
  "objectPaths":{
    "ec7ad943e33143f9a37ac5d8757cd99b":{
      "scriptId":"u0"},
    "f5eac5691794432d9fd149617ab82471":{
      "scriptId":"u1"},
    "80378f6d952b46a1a9575ded331d8f30":{
      "scriptId":"u2"},
    "e9c994e2b1484293ab3a073aa42198d9":{
      "scriptId":"u3"},
    "47f384a2cb774eeead965ca452043bd4":{
      "scriptId":"u4"},
    "7513e70cf52c49a1ad44183192e970d5":{
      "scriptId":"u5"},
    "b2d98d2bd4054e65be9527af17268764":{
      "scriptId":"u6",
      "aa94056b817049cbb1fa6bacb8c1e519":{
        "scriptId":"u7"},
      "d0f70829d22f42fea545dfa7923b52be":{
        "scriptId":"u8"}},
    "a162a782c7f94ad48e970fb5ed8142c0":{
      "scriptId":"u9"},
    "2150748958a94a42bb6d2252b9b56c5d":{
      "scriptId":"u10"},
    "84a385ad74e04bf592e3d9ed7806bade":{
      "scriptId":"u11"},
    "cd4521f5f1d44e5db17416bb7c511b10":{
      "scriptId":"u12"},
    "344d020ea80140f39a1b4c20c80b45e0":{
      "scriptId":"u13",
      "ad29d0868e2d4e1ea04d2e3813cac53e":{
        "scriptId":"u14"},
      "705ba8054db8459aa453d6e8970360e1":{
        "scriptId":"u15"},
      "435294aeef7344768378c778f254ae49":{
        "scriptId":"u16"},
      "423f499025e441208a01286ce6aefd3d":{
        "scriptId":"u17"},
      "5bff7bb0f32e4aaba352a33b10354ace":{
        "scriptId":"u18"},
      "4f781b78feb94e5c9e8d524ff73eadfc":{
        "scriptId":"u19"},
      "08ae0434c50140e782a3740366b35ef6":{
        "scriptId":"u20"},
      "98765ab47746412d8d002e805dd3f5c8":{
        "scriptId":"u21"},
      "5b1950c85d9d43979ce7ee038d82addd":{
        "scriptId":"u22"},
      "922258fa17a1468e89be4de887eb9242":{
        "scriptId":"u23"},
      "196b102fa5434693932ec2ccadc2aa72":{
        "scriptId":"u24"},
      "05799b485a82452f859a0923a542670d":{
        "scriptId":"u25"},
      "9224b06f5bc3462d9761fb8b32aaaefc":{
        "scriptId":"u26"},
      "03c2d1c0a018442fbae9cadc97fdbf9e":{
        "scriptId":"u27"},
      "e3ae0d1bffa6454e953785c75dd9411e":{
        "scriptId":"u28"},
      "29e560d07ab1441c8bd2c912e6128056":{
        "scriptId":"u29"},
      "e21c32341ad54afcbba6d7060f2aed87":{
        "scriptId":"u30"},
      "a93032c21bff4eff9ce74ad7de209ec8":{
        "scriptId":"u31"},
      "8f58a485ce114857b88238e6126eea08":{
        "scriptId":"u32"},
      "55c1a272476d4a028543b54a8dbbc346":{
        "scriptId":"u33"},
      "227b88b93913401bba3bd8014f0993e8":{
        "scriptId":"u34"},
      "30e27b2aeacd454b8ddd21f178272d3a":{
        "scriptId":"u35"},
      "7851308e4e85456daf8cce58bc2f888f":{
        "scriptId":"u36"}},
    "1f110d8e44c44c548e9300a484c9824a":{
      "scriptId":"u37"},
    "4f142478882e48e488c01c7930fb4c7c":{
      "scriptId":"u38"},
    "4aa01aa346124edbbc992072cc327352":{
      "scriptId":"u39"},
    "c9c2d7e9ea284993a00352854669c72a":{
      "scriptId":"u40"},
    "8f7e00062ecb4d9a8e81fc03f5a67a5a":{
      "scriptId":"u41"},
    "e711d957baa24689a7f85bb9fb8c53ef":{
      "scriptId":"u42"},
    "92b8db6576eb4bd5a20ffaa5a4d77162":{
      "scriptId":"u43"},
    "17e7902e94c2490892ac1bc00d641898":{
      "scriptId":"u44"},
    "187f2b814fb24d5f9f27cd2a1354d183":{
      "scriptId":"u45"},
    "4554ef83473e4518af9a78f832b31f48":{
      "scriptId":"u46"},
    "b0033cbc0a134f779397fad48f931b4b":{
      "scriptId":"u47"},
    "8282b9556e4049e088f23b660baf41da":{
      "scriptId":"u48"},
    "db0a2cc41fb2403599c65ecf1bb6aa66":{
      "scriptId":"u49"},
    "69351cac68294090b54859f0f3c9aa1a":{
      "scriptId":"u50"},
    "0c8a1b5ba1704104938a10a19012491c":{
      "scriptId":"u51"},
    "c33a9bf6ae7d4d5bb981b8c8af9c0872":{
      "scriptId":"u52"},
    "257eb3968ad541f6aeea431a1bfd70e1":{
      "scriptId":"u53"},
    "b6c075f1910c4b1aa6e55d68e2af8c61":{
      "scriptId":"u54"},
    "6e68a4675efb4841a7117010e834ac6d":{
      "scriptId":"u55"},
    "0f663232faa14259b921ddaab3a4bfb2":{
      "scriptId":"u56"},
    "23afcf52f2f54c8f99c8c3e0636db7c3":{
      "scriptId":"u57"},
    "31fdd3ef56f947b2ade74d2237d9de8e":{
      "scriptId":"u58"},
    "fb20677895d94a37a6c7b4978ad2e84b":{
      "scriptId":"u59"},
    "e41e059de11046888b089f8fa24ed030":{
      "scriptId":"u60"},
    "cff118c537be4926b0893800aff23147":{
      "scriptId":"u61"},
    "09efe07b6a9e410888e1bd5abd501866":{
      "scriptId":"u62"},
    "5320a35ec6024b739c904c36c7d95c40":{
      "scriptId":"u63"},
    "7185d60986b7435fa24eaf199fc8778e":{
      "scriptId":"u64"},
    "a3fdf8ffc2874ceea12daace1b72ec83":{
      "scriptId":"u65"},
    "02bf7a75340444779c8a93f1ccaecca3":{
      "scriptId":"u66"},
    "6f2a4f43a0f248968b5711e11421cd0b":{
      "scriptId":"u67"},
    "d673e81b925649cca7d05c778fd4ba93":{
      "scriptId":"u68"},
    "f3ed62212d94475399393694bc8719f8":{
      "scriptId":"u69"},
    "5e3f0aed18db48e693ef575cf9422742":{
      "scriptId":"u70"},
    "20af94d8014647f7aed73a8e88285a91":{
      "scriptId":"u71"},
    "86ce250ad9944b05985c8a3604231beb":{
      "scriptId":"u72"},
    "e3963682ef5a453ba958b13e5d8e70e0":{
      "scriptId":"u73"},
    "5ef623b704c34900a08ff0cec8f6f828":{
      "scriptId":"u74"},
    "9adb41e95da84e889f665154e47c44b5":{
      "scriptId":"u75"},
    "ac03e1b99109420d991fb10adab8fb03":{
      "scriptId":"u76"},
    "bf2d11bfb86f470abd3aeb28aa55f8e7":{
      "scriptId":"u77"},
    "8d687ac23cfb46cfa3d2c5cd150e47c7":{
      "scriptId":"u78"},
    "c660c30d31ae44c2b0a11bbcfb5b8509":{
      "scriptId":"u79"},
    "646fb846480644cebfe33e91fd80707f":{
      "scriptId":"u80"},
    "6c6add651fa84dbab9518e8551cee49c":{
      "scriptId":"u81"},
    "9bd5782139cc4aef919b2b5300617e56":{
      "scriptId":"u82"},
    "9949263383534e7f8150131811838e9c":{
      "scriptId":"u83"},
    "1a05279ce1f84b8492263df933347f8c":{
      "scriptId":"u84"},
    "a7c6695facfc468b932f2600b72c69eb":{
      "scriptId":"u85"},
    "b43b2130af8d47f9b2899708dd2551a8":{
      "scriptId":"u86"},
    "96f3cd68333942e7adc7d635ccf05b78":{
      "scriptId":"u87"},
    "9041acb2e191441e80bf057024483090":{
      "scriptId":"u88"},
    "06881f83c5c247edaaeb0efa50d67fe1":{
      "scriptId":"u89"},
    "52cc6896ccf94e36b0398c771f2437f8":{
      "scriptId":"u90"},
    "c1f644fd58e74f1db319ab52a3d04df4":{
      "scriptId":"u91"},
    "43b3cf9b79964d4d97fbd15e5f43cf5b":{
      "scriptId":"u92"},
    "c1b0bf1225c84154a442f49dc724cba4":{
      "scriptId":"u93"},
    "ea51288dcb2c4ab4b60b7c809868f6fd":{
      "scriptId":"u94"},
    "aced37551f274e92a683241e7fda5fed":{
      "scriptId":"u95"},
    "cc69849d3bed4edb9cee94e7475c56f1":{
      "scriptId":"u96"},
    "2c2caaca2f824e8aaf9eab2950c1a4ed":{
      "scriptId":"u97"},
    "2c3c1848f3c648dda0540901843592cb":{
      "scriptId":"u98"},
    "9bd66a0fc5fe487dbc1d99d134694e95":{
      "scriptId":"u99"},
    "e9e8503cb77c402797a0a8fd65bc682f":{
      "scriptId":"u100"},
    "7f91c13406f84e0ca4ca3e7103dbe108":{
      "scriptId":"u101"},
    "cb00dd9ade0e482eb7ad460f0e04daf1":{
      "scriptId":"u102"},
    "d5ff62ba3c524287ab211059b7de6879":{
      "scriptId":"u103"},
    "277b63f1ace349b482e7102326db3b5a":{
      "scriptId":"u104"},
    "1175f394150043c7a02a4e79b33e48ff":{
      "scriptId":"u105"},
    "981524d6b1c84410be702070fa37a819":{
      "scriptId":"u106"},
    "4d5b48cfb03c4a0f87cf71a0a81e9e29":{
      "scriptId":"u107"},
    "53761eb703f54e81978c75cccbbf0626":{
      "scriptId":"u108"},
    "7cdfd8aa4c2a4863adfb8248a134db29":{
      "scriptId":"u109"},
    "66712b998fbe4c9484f5cf8888bd4e60":{
      "scriptId":"u110"},
    "13904d8c37e94fdda4f3cd5359856ff1":{
      "scriptId":"u111"},
    "12068f1a939c452ab4527c6bc0acc83b":{
      "scriptId":"u112"},
    "ab9327509b9645c0be5feae2d4a6a7c2":{
      "scriptId":"u113"},
    "b2e5ec6ec4ca4d70aed5837116eae833":{
      "scriptId":"u114"},
    "c29dd3c441304d0f968a7b363a4b67a7":{
      "scriptId":"u115"},
    "b58e352561c44ec0bd27a48b19d22495":{
      "scriptId":"u116"},
    "aeae97d029ca4460a1c4f13cb261dbfb":{
      "scriptId":"u117"},
    "8463610d35c743e3883fd92958ed3de3":{
      "scriptId":"u118"},
    "40ff65d9f51742c6911ce73899606367":{
      "scriptId":"u119"},
    "ebd26bfbd88a494c92a091af09729ec5":{
      "scriptId":"u120"},
    "39050940d69d465fa14123b22ed75909":{
      "scriptId":"u121"},
    "f3b6d6cb06e54b3091a45f86708fff4a":{
      "scriptId":"u122"},
    "967cd186d5ff4627b391b5326437ca4c":{
      "scriptId":"u123"},
    "d6f101ffbc844687aee7c7202b69b1f0":{
      "scriptId":"u124"},
    "3b831fa779c4469589809b17e3c6dc59":{
      "scriptId":"u125"},
    "c60a199917bb4ee9bf3e1d4e7d03c9fb":{
      "scriptId":"u126"},
    "feb774ad98164035aae3c44389c3f7bb":{
      "scriptId":"u127"},
    "9e3adc30787040cfad8f9c05bdc613b7":{
      "scriptId":"u128"},
    "51fcd4852fdc478285f5dadb6bebbb4a":{
      "scriptId":"u129"},
    "f93e57d2dcb341d78b5df8e5c8a2888c":{
      "scriptId":"u130"},
    "7fdb47b42fde48d289270ab23d90baaa":{
      "scriptId":"u131"},
    "e6c5942e94764ab4bb81e644e51b8046":{
      "scriptId":"u132"},
    "5ece4056a0cd4789b9bc43f59034e5f2":{
      "scriptId":"u133"},
    "9bfb421c0ed14bf8a8ff3ea2b22b3048":{
      "scriptId":"u134"}}});