$axure.loadCurrentPage({
  "url":"新闻列表.html",
  "generationDate":new Date(1432872221243.27),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"b64b7bc69d094e4394b1d6d50b9e2dd2",
    "type":"Axure:Page",
    "name":"新闻列表",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"7f89581bfaad42dbb98e91429d78d8d6",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
},
          "adaptiveStyles":{
},
          "masterId":"496537f1e3d34e84bff1d3b9cc7d3781"},
{
          "id":"8c240d25d50b4d439aa8015bd587e9e1",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":1260}},
          "adaptiveStyles":{
},
          "masterId":"526482f429714d2da20c04d5a7d4329e"},
{
          "id":"05bd801f271145e29b0d8ab0affabce7",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "fill":{
              "fillType":"solid",
              "color":0xFFF8F8F8},
            "location":{
              "x":200,
              "y":220},
            "size":{
              "width":210,
              "height":100},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFC9C9C9}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f657f1aa8ad048ac84181fd650388b51",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF8F8F8},
                "location":{
                  "x":200,
                  "y":220},
                "size":{
                  "width":210,
                  "height":100},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFC9C9C9}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/新闻列表/u35.png"}},
{
          "id":"9ce485a2f92944f9815e15dd82a6355e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFE4E4E4},
            "location":{
              "x":200,
              "y":320},
            "size":{
              "width":210,
              "height":30},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFC9C9C9}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d5868a5bcd214957a7b3dfd22ae78aba",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4},
                "location":{
                  "x":200,
                  "y":320},
                "size":{
                  "width":210,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFC9C9C9}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/新闻列表/u37.png"}},
{
          "id":"394c49cd7a9b4cec9787487b2960ef97",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":200,
              "y":350},
            "size":{
              "width":210,
              "height":30},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFC9C9C9}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7596e3512edc4b7d89e92837b70dd516",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":200,
                  "y":350},
                "size":{
                  "width":210,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFC9C9C9}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/新闻列表/u39.png"}},
{
          "id":"91a05b1257f34c7895d13a610307d217",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":440,
              "y":220},
            "size":{
              "width":760,
              "height":1020},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFC9C9C9}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bdce72107dcc45ff80da70584eb32048",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":440,
                  "y":220},
                "size":{
                  "width":760,
                  "height":1020},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFC9C9C9}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/新闻列表/u41.png"}},
{
          "id":"ed9c88bda82845759219174c65abf572",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":200,
              "y":400},
            "size":{
              "width":210,
              "height":320},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFC9C9C9}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3d74846235e14a978dd91b040a8b4f3a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":200,
                  "y":400},
                "size":{
                  "width":210,
                  "height":320},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFC9C9C9}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/新闻列表/u43.png"}},
{
          "id":"dbf4efe14aed431b94a2ea8f35038128",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"14px",
            "fontWeight":"700",
            "location":{
              "x":210,
              "y":414},
            "size":{
              "width":70,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"94c48ed1432949baae36555b4d55ae91",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"14px",
                "fontWeight":"700",
                "location":{
                  "x":210,
                  "y":414},
                "size":{
                  "width":70,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3d179ebff8c64b319268e88c56bbf859",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":210,
              "y":440},
            "size":{
              "width":190,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3548c86004ea42d38d2e59cf119bf2ae",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":210,
                  "y":440},
                "size":{
                  "width":190,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d27b2a3a454a44199efb01514ee5bbfa",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":210,
              "y":470},
            "size":{
              "width":190,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9b5bf400a85d444389896c6f34e857d3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":210,
                  "y":470},
                "size":{
                  "width":190,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"676170529be5428bb36cf7b439e1c68b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":210,
              "y":501},
            "size":{
              "width":190,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"07a443ea144c40a9898ec469d02edd02",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":210,
                  "y":501},
                "size":{
                  "width":190,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"048bd1e665a644eeb3601f6668ba22ec",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":210,
              "y":532},
            "size":{
              "width":190,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1e3b578c74cd467faadaa138bec2fbb4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":210,
                  "y":532},
                "size":{
                  "width":190,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"97c23bc071bd4754b719def6d04a2b4a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":210,
              "y":562},
            "size":{
              "width":190,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8f9b2b4361344e2cbb5a7eba2eea190d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":210,
                  "y":562},
                "size":{
                  "width":190,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3badc887742549d2a0c4a6ca7f60a421",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":210,
              "y":592},
            "size":{
              "width":190,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"47ad76af79384dbbb03ebc3451aedd08",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":210,
                  "y":592},
                "size":{
                  "width":190,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"dca8ca68ca0d4624bd7190990ee672b9",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":210,
              "y":623},
            "size":{
              "width":190,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"316b095ae7c74c12b34eb88c90ba6dcc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":210,
                  "y":623},
                "size":{
                  "width":190,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4030ee7223374da690b44d7b700343c9",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":210,
              "y":654},
            "size":{
              "width":190,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7e8e0b337c20459b9a408cdd8e9fb815",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":210,
                  "y":654},
                "size":{
                  "width":190,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"81b89a87cda74bfba8e89ad2631e3919",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":210,
              "y":684},
            "size":{
              "width":190,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"439e422a556c4866a80ca142ad5f72f2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":210,
                  "y":684},
                "size":{
                  "width":190,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"119dd3f2c22048f195ce0954c6504723",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'文鼎CS中等线 Regular', '文鼎CS中等线'",
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":1075,
              "y":252},
            "size":{
              "width":96,
              "height":20},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0e45421250b940cba9046fc8164112d0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'文鼎CS中等线 Regular', '文鼎CS中等线'",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":1075,
                  "y":252},
                "size":{
                  "width":96,
                  "height":20},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/新闻列表/u65.png"}},
{
          "id":"19a26e94782847b680d7a7798b3256e6",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":470,
              "y":253},
            "size":{
              "width":539,
              "height":19},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6649a330d70347e199790d64645718b1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":470,
                  "y":253},
                "size":{
                  "width":539,
                  "height":19},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 新闻详细页",
                      "target":{
                        "targetType":"page",
                        "url":"新闻详细页.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1fd5bda6ae164c5dab0ecb01a2381acf",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "baseStyle":"627587b6038d43cca051c114ac41ad32",
            "lineSpacing":"20px",
            "location":{
              "x":470,
              "y":282},
            "size":{
              "width":701,
              "height":40},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b0a0946c663c4c5aaed57cbe2a69f0c0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "baseStyle":"627587b6038d43cca051c114ac41ad32",
                "lineSpacing":"20px",
                "location":{
                  "x":470,
                  "y":282},
                "size":{
                  "width":701,
                  "height":40},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5390720076284e68bd72cf3cdfcfb821",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":470,
              "y":363},
            "size":{
              "width":701,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFD7D7D7},
            "linePattern":"dashed"},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/新闻列表/u71_line.png"}},
{
          "id":"9df196dc16804d8cb141f200587f27bf",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":1100,
              "y":327},
            "size":{
              "width":71,
              "height":25},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8b8edcfa65754fff9c09aacb3db7f4eb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1100,
                  "y":327},
                "size":{
                  "width":71,
                  "height":25},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 新闻详细页",
                      "target":{
                        "targetType":"page",
                        "url":"新闻详细页.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/新闻列表/u72.png"}},
{
          "id":"b3cb35822f4f4ed0afd3b7a6ae570267",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'文鼎CS中等线 Regular', '文鼎CS中等线'",
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":1076,
              "y":384},
            "size":{
              "width":95,
              "height":20},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c577e65f3cc04a0ba20fe43997afd619",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'文鼎CS中等线 Regular', '文鼎CS中等线'",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":1076,
                  "y":384},
                "size":{
                  "width":95,
                  "height":20},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/新闻列表/u74.png"}},
{
          "id":"fd622a7a47a2477b9c6b7014f49c70f5",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":470,
              "y":385},
            "size":{
              "width":540,
              "height":19},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"39a130a90d6a4eb192546f8f480e54ec",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":470,
                  "y":385},
                "size":{
                  "width":540,
                  "height":19},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 新闻详细页",
                      "target":{
                        "targetType":"page",
                        "url":"新闻详细页.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8d500023ab764284aaa1d85160b7bcc9",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "baseStyle":"627587b6038d43cca051c114ac41ad32",
            "lineSpacing":"20px",
            "location":{
              "x":470,
              "y":414},
            "size":{
              "width":701,
              "height":40},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c7817f8a2363463f924bbffcbe127973",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "baseStyle":"627587b6038d43cca051c114ac41ad32",
                "lineSpacing":"20px",
                "location":{
                  "x":470,
                  "y":414},
                "size":{
                  "width":701,
                  "height":40},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3942040b06e34cc28fdad26403d17ab8",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":470,
              "y":495},
            "size":{
              "width":701,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFD7D7D7},
            "linePattern":"dashed"},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/新闻列表/u71_line.png"}},
{
          "id":"26aa46ff50c845ad9273820a6aa17b00",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":1100,
              "y":459},
            "size":{
              "width":71,
              "height":25},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"069e4bd5c8b54a9882614d4f4c1daaed",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1100,
                  "y":459},
                "size":{
                  "width":71,
                  "height":25},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 新闻详细页",
                      "target":{
                        "targetType":"page",
                        "url":"新闻详细页.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/新闻列表/u72.png"}},
{
          "id":"2b0a775a07cb4138a09059a0df9c9cb2",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'文鼎CS中等线 Regular', '文鼎CS中等线'",
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":1076,
              "y":517},
            "size":{
              "width":95,
              "height":20},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"adcdbd86da4944638773bf76775563d3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'文鼎CS中等线 Regular', '文鼎CS中等线'",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":1076,
                  "y":517},
                "size":{
                  "width":95,
                  "height":20},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/新闻列表/u74.png"}},
{
          "id":"a3711f1bf46444078dc7b77841e125ae",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":470,
              "y":518},
            "size":{
              "width":540,
              "height":19},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bb0f0a1dc3c84ababeab417fe124d91e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":470,
                  "y":518},
                "size":{
                  "width":540,
                  "height":19},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 新闻详细页",
                      "target":{
                        "targetType":"page",
                        "url":"新闻详细页.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e5aecee15af049c5b54b284d08e15517",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "baseStyle":"627587b6038d43cca051c114ac41ad32",
            "lineSpacing":"20px",
            "location":{
              "x":470,
              "y":547},
            "size":{
              "width":701,
              "height":40},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c5b6dec984054043b41ef1289cdb64a1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "baseStyle":"627587b6038d43cca051c114ac41ad32",
                "lineSpacing":"20px",
                "location":{
                  "x":470,
                  "y":547},
                "size":{
                  "width":701,
                  "height":40},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"bdd22eede1b848dab46f4e052faaeb10",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":470,
              "y":628},
            "size":{
              "width":701,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFD7D7D7},
            "linePattern":"dashed"},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/新闻列表/u71_line.png"}},
{
          "id":"91d51a042b164971aa20e6c74a8b0af3",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":1100,
              "y":592},
            "size":{
              "width":71,
              "height":25},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cd32d8f6ca7e420d9e9f9f482214b7f6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1100,
                  "y":592},
                "size":{
                  "width":71,
                  "height":25},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 新闻详细页",
                      "target":{
                        "targetType":"page",
                        "url":"新闻详细页.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/新闻列表/u72.png"}},
{
          "id":"0229b494f5644ca186201585cdcd9150",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'文鼎CS中等线 Regular', '文鼎CS中等线'",
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":1076,
              "y":649},
            "size":{
              "width":95,
              "height":20},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"518b11d8bf214064bfa0b139168acc13",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'文鼎CS中等线 Regular', '文鼎CS中等线'",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":1076,
                  "y":649},
                "size":{
                  "width":95,
                  "height":20},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/新闻列表/u74.png"}},
{
          "id":"0637ca2768df40b3a4786a50bcd283d4",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":470,
              "y":650},
            "size":{
              "width":540,
              "height":19},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ef37a1cd72594833ad5ba078ef6d54f4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":470,
                  "y":650},
                "size":{
                  "width":540,
                  "height":19},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 新闻详细页",
                      "target":{
                        "targetType":"page",
                        "url":"新闻详细页.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7690b197289d4a3880ec309588ce3bb3",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "baseStyle":"627587b6038d43cca051c114ac41ad32",
            "lineSpacing":"20px",
            "location":{
              "x":470,
              "y":679},
            "size":{
              "width":701,
              "height":40},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"927923e6d8bc452e89ad245942e939bf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "baseStyle":"627587b6038d43cca051c114ac41ad32",
                "lineSpacing":"20px",
                "location":{
                  "x":470,
                  "y":679},
                "size":{
                  "width":701,
                  "height":40},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b58439355ca841bea56ca87afe3c8118",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":470,
              "y":760},
            "size":{
              "width":701,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFD7D7D7},
            "linePattern":"dashed"},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/新闻列表/u71_line.png"}},
{
          "id":"4978a2b7d3d94897b831dcce5138e445",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":1100,
              "y":724},
            "size":{
              "width":71,
              "height":25},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a2c0f4e67a124070a54c399ac606a8f0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1100,
                  "y":724},
                "size":{
                  "width":71,
                  "height":25},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 新闻详细页",
                      "target":{
                        "targetType":"page",
                        "url":"新闻详细页.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/新闻列表/u72.png"}},
{
          "id":"7df3c2ef3be44743948ee537f634e3da",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'文鼎CS中等线 Regular', '文鼎CS中等线'",
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":1076,
              "y":781},
            "size":{
              "width":95,
              "height":20},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fdef81cdc293429b82e66465d9e10eab",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'文鼎CS中等线 Regular', '文鼎CS中等线'",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":1076,
                  "y":781},
                "size":{
                  "width":95,
                  "height":20},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/新闻列表/u74.png"}},
{
          "id":"00d14424f44d4065b72248d71a659a59",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":470,
              "y":782},
            "size":{
              "width":540,
              "height":19},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"606a8b86389f4442ad8050489e58d362",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":470,
                  "y":782},
                "size":{
                  "width":540,
                  "height":19},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 新闻详细页",
                      "target":{
                        "targetType":"page",
                        "url":"新闻详细页.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"14d12f8c41b34b38a7d56b00eb283cf7",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "baseStyle":"627587b6038d43cca051c114ac41ad32",
            "lineSpacing":"20px",
            "location":{
              "x":470,
              "y":811},
            "size":{
              "width":701,
              "height":40},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"682ea5f508314252ade111cdb3c15adf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "baseStyle":"627587b6038d43cca051c114ac41ad32",
                "lineSpacing":"20px",
                "location":{
                  "x":470,
                  "y":811},
                "size":{
                  "width":701,
                  "height":40},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0bf282564bc840ae8573901454ec6e32",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":470,
              "y":892},
            "size":{
              "width":701,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFD7D7D7},
            "linePattern":"dashed"},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/新闻列表/u71_line.png"}},
{
          "id":"b1933968507f48838dd7e00d34d11989",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":1100,
              "y":856},
            "size":{
              "width":71,
              "height":25},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f3222abe15ba4406b27c4eea99bf983c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1100,
                  "y":856},
                "size":{
                  "width":71,
                  "height":25},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 新闻详细页",
                      "target":{
                        "targetType":"page",
                        "url":"新闻详细页.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/新闻列表/u72.png"}},
{
          "id":"ff5afccf082b4441b40d9cc5d1113645",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'文鼎CS中等线 Regular', '文鼎CS中等线'",
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":1076,
              "y":914},
            "size":{
              "width":95,
              "height":20},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1a25936ab3d748218cc4cb5f5adc2aa3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'文鼎CS中等线 Regular', '文鼎CS中等线'",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":1076,
                  "y":914},
                "size":{
                  "width":95,
                  "height":20},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/新闻列表/u74.png"}},
{
          "id":"5bc956f721c4452291572654263dba31",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":470,
              "y":915},
            "size":{
              "width":540,
              "height":19},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"10ca8942844b4d9d8459432922054dd9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":470,
                  "y":915},
                "size":{
                  "width":540,
                  "height":19},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 新闻详细页",
                      "target":{
                        "targetType":"page",
                        "url":"新闻详细页.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a9f32289a4f948798baac12310582ee5",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "baseStyle":"627587b6038d43cca051c114ac41ad32",
            "lineSpacing":"20px",
            "location":{
              "x":470,
              "y":944},
            "size":{
              "width":701,
              "height":40},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fe48d9a9ec074cb2ae4f481317b5918f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "baseStyle":"627587b6038d43cca051c114ac41ad32",
                "lineSpacing":"20px",
                "location":{
                  "x":470,
                  "y":944},
                "size":{
                  "width":701,
                  "height":40},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ee4b6d9368fa4b67b6ea8a5165dc5838",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":470,
              "y":1025},
            "size":{
              "width":701,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFD7D7D7},
            "linePattern":"dashed"},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/新闻列表/u71_line.png"}},
{
          "id":"addcb34a51204445a831edb2043f10d4",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":1100,
              "y":989},
            "size":{
              "width":71,
              "height":25},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"538dfd03ee454d72ac0ab27158bf8dfd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1100,
                  "y":989},
                "size":{
                  "width":71,
                  "height":25},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 新闻详细页",
                      "target":{
                        "targetType":"page",
                        "url":"新闻详细页.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/新闻列表/u72.png"}},
{
          "id":"c20b8b17ae0a49688df77b2435bd7471",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'文鼎CS中等线 Regular', '文鼎CS中等线'",
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":1076,
              "y":1046},
            "size":{
              "width":95,
              "height":20},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0cc3e640bb1446c1a64c166bc5043ec7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'文鼎CS中等线 Regular', '文鼎CS中等线'",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":1076,
                  "y":1046},
                "size":{
                  "width":95,
                  "height":20},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/新闻列表/u74.png"}},
{
          "id":"10b13cc9133b40baac248e7adfb2bcfb",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":470,
              "y":1047},
            "size":{
              "width":540,
              "height":19},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"56d834b68aed4bca97b94d0d99cbc038",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":470,
                  "y":1047},
                "size":{
                  "width":540,
                  "height":19},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 新闻详细页",
                      "target":{
                        "targetType":"page",
                        "url":"新闻详细页.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"951bbd6ee0c547848b5ef99b09670937",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "baseStyle":"627587b6038d43cca051c114ac41ad32",
            "lineSpacing":"20px",
            "location":{
              "x":470,
              "y":1076},
            "size":{
              "width":701,
              "height":40},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9dbea300d2474b4399ff42e3321e580e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "baseStyle":"627587b6038d43cca051c114ac41ad32",
                "lineSpacing":"20px",
                "location":{
                  "x":470,
                  "y":1076},
                "size":{
                  "width":701,
                  "height":40},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"22d40c89d74d4cd797aad2c8ab59a30a",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":470,
              "y":1157},
            "size":{
              "width":701,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFD7D7D7},
            "linePattern":"dashed"},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/新闻列表/u71_line.png"}},
{
          "id":"be43435f333d40d8acc2111de801266e",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":1100,
              "y":1121},
            "size":{
              "width":71,
              "height":25},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"66c2227f95c44ce78d89c5447e7f7e07",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1100,
                  "y":1121},
                "size":{
                  "width":71,
                  "height":25},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 新闻详细页",
                      "target":{
                        "targetType":"page",
                        "url":"新闻详细页.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/新闻列表/u72.png"}},
{
          "id":"1c70e48e37d5470ca5e1e219b6c9e3a5",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":576.5,
              "y":1190},
            "size":{
              "width":487,
              "height":26},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e2616b928b5541619996e3731796b92c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":576.5,
                  "y":1190},
                "size":{
                  "width":487,
                  "height":26},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/新闻列表/u128.png"}}]}},
  "masters":{
    "496537f1e3d34e84bff1d3b9cc7d3781":{
      "packageId":"496537f1e3d34e84bff1d3b9cc7d3781",
      "type":"Axure:Master",
      "name":"物流头部",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"应用字体",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"be355ce83e944039947e531f2a3c65bf",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":0,
                "y":150},
              "size":{
                "width":1400,
                "height":40},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFD7D7D7}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"7ad610fe1fd94f489f35d1adf33b9af1",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":0,
                    "y":150},
                  "size":{
                    "width":1400,
                    "height":40},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFD7D7D7}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/首页/u13.png"}},
{
            "id":"aa3cf84e2bbd46a28151af5ccb7dfbf6",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fontName":"'微软雅黑 Regular', '微软雅黑'",
              "location":{
                "x":325,
                "y":150},
              "size":{
                "width":125,
                "height":40},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFD7D7D7}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"cf98c532bd864dcc8adeb788cba04559",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'微软雅黑 Regular', '微软雅黑'",
                  "location":{
                    "x":325,
                    "y":150},
                  "size":{
                    "width":125,
                    "height":40},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFD7D7D7}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/物流/u9.png"}},
{
            "id":"6007835eb6e94566a4ce3334bd18ac62",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fontName":"'微软雅黑 Regular', '微软雅黑'",
              "location":{
                "x":450,
                "y":150},
              "size":{
                "width":125,
                "height":40},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFD7D7D7}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"384a059abd7b46e298aafb2cd9c43187",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'微软雅黑 Regular', '微软雅黑'",
                  "location":{
                    "x":450,
                    "y":150},
                  "size":{
                    "width":125,
                    "height":40},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFD7D7D7}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/物流/u9.png"}},
{
            "id":"7c9058fa398c4796a04243c49a790a49",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fontName":"'微软雅黑 Regular', '微软雅黑'",
              "location":{
                "x":575,
                "y":150},
              "size":{
                "width":125,
                "height":40},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFD7D7D7}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"438b60b6102f4768af4f0703a5815f11",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'微软雅黑 Regular', '微软雅黑'",
                  "location":{
                    "x":575,
                    "y":150},
                  "size":{
                    "width":125,
                    "height":40},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFD7D7D7}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/物流/u9.png"}},
{
            "id":"d4dbd3f981904f4fa63897125413dd32",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fontName":"'微软雅黑 Regular', '微软雅黑'",
              "location":{
                "x":825,
                "y":150},
              "size":{
                "width":125,
                "height":40},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFD7D7D7}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"609d5aa69b7f4e68b5e6717d43d879bd",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'微软雅黑 Regular', '微软雅黑'",
                  "location":{
                    "x":825,
                    "y":150},
                  "size":{
                    "width":125,
                    "height":40},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFD7D7D7}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/物流/u9.png"}},
{
            "id":"8a3db1216f984f9cb223ca8379348c88",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fontName":"'微软雅黑 Regular', '微软雅黑'",
              "location":{
                "x":700,
                "y":150},
              "size":{
                "width":125,
                "height":40},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFD7D7D7}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"156ee2878c014482ad208a835bfdfd57",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'微软雅黑 Regular', '微软雅黑'",
                  "location":{
                    "x":700,
                    "y":150},
                  "size":{
                    "width":125,
                    "height":40},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFD7D7D7}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/物流/u9.png"}},
{
            "id":"a982eb6988b44874aec2f7a7563f3bbc",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fontName":"'微软雅黑 Regular', '微软雅黑'",
              "location":{
                "x":200,
                "y":150},
              "size":{
                "width":125,
                "height":40},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFD7D7D7}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"3c448fc8af0f4a8e9fb1b5c15b818d05",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'微软雅黑 Regular', '微软雅黑'",
                  "location":{
                    "x":200,
                    "y":150},
                  "size":{
                    "width":125,
                    "height":40},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFD7D7D7}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/物流/u9.png"}},
{
            "id":"dfba4f993e4e48d4b2d57c920a9037ef",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fontName":"'微软雅黑 Regular', '微软雅黑'",
              "location":{
                "x":950,
                "y":150},
              "size":{
                "width":125,
                "height":40},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFD7D7D7}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"3a4567cc67374e3d95142abc1567d0bd",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'微软雅黑 Regular', '微软雅黑'",
                  "location":{
                    "x":950,
                    "y":150},
                  "size":{
                    "width":125,
                    "height":40},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFD7D7D7}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/物流/u9.png"}},
{
            "id":"28346d4547e147abb42f1e03fe9d2d51",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fontName":"'微软雅黑 Regular', '微软雅黑'",
              "location":{
                "x":1075,
                "y":150},
              "size":{
                "width":125,
                "height":40},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFD7D7D7}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"11a8cd2c460a4915858ba5e52d96207c",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'微软雅黑 Regular', '微软雅黑'",
                  "location":{
                    "x":1075,
                    "y":150},
                  "size":{
                    "width":125,
                    "height":40},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFD7D7D7}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/物流/u9.png"}},
{
            "id":"774e6c3744c644c2bd17b7fa7892feac",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFFF8F8F8},
              "size":{
                "width":1400,
                "height":35},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFD7D7D7}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"f9137a915a3f4fc2b4388e5d7f1767ba",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFF8F8F8},
                  "size":{
                    "width":1400,
                    "height":35},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFD7D7D7}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/物流/u25.png"}},
{
            "id":"148da07c87f142879097b9a411344180",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "location":{
                "x":200,
                "y":10},
              "size":{
                "width":340,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"4d20535595e94f17ba4488bc15e48676",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":200,
                    "y":10},
                  "size":{
                    "width":340,
                    "height":16}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"56f736c3d24947ab9a3e62c329fd19a4",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontName":"'微软雅黑 Regular', '微软雅黑'",
              "horizontalAlignment":"right",
              "location":{
                "x":660,
                "y":6},
              "size":{
                "width":540,
                "height":19}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"2bef87c6b612443d814a873ce10c6e28",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'微软雅黑 Regular', '微软雅黑'",
                  "horizontalAlignment":"right",
                  "location":{
                    "x":660,
                    "y":6},
                  "size":{
                    "width":540,
                    "height":19}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"315dd3063b454753b9694c00bdb7bac0",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":200,
                "y":50},
              "size":{
                "width":150,
                "height":70},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFD7D7D7}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"e3835d78c26e4225b56136c0f7cee8e9",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":200,
                    "y":50},
                  "size":{
                    "width":150,
                    "height":70},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFD7D7D7}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/物流/u31.png"}},
{
            "id":"2ffd3ddb833f48348e4ffdbba2c2ba86",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontSize":"24px",
              "location":{
                "x":370,
                "y":77},
              "size":{
                "width":130,
                "height":28}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"428b4de1cfa54a9794166f743cdd9895",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"24px",
                  "location":{
                    "x":370,
                    "y":77},
                  "size":{
                    "width":130,
                    "height":28}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}}]}},
    "526482f429714d2da20c04d5a7d4329e":{
      "packageId":"526482f429714d2da20c04d5a7d4329e",
      "type":"Axure:Master",
      "name":"物流底部",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"应用字体",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"6d839a3937d045bf813b8be7d50e2149",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFFE4E4E4},
              "location":{
                "x":0,
                "y":5},
              "size":{
                "width":1400,
                "height":100},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFD7D7D7}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"960f638a92ca40d4bab16f14077f2f59",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFE4E4E4},
                  "location":{
                    "x":0,
                    "y":5},
                  "size":{
                    "width":1400,
                    "height":100},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFD7D7D7}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/物流/u1.png"}},
{
            "id":"90d533b4c8c24b3883b34a888ba79377",
            "label":"",
            "type":"horizontalLine",
            "styleType":"horizontalLine",
            "visible":true,
            "style":{
              "size":{
                "width":1400,
                "height":10},
              "borderWidth":"2",
              "borderFill":{
                "fillType":"solid",
                "color":0xFFD7D7D7}},
            "adaptiveStyles":{
},
            "images":{
              "start~":"resources/images/transparent.gif",
              "end~":"resources/images/transparent.gif",
              "line~":"images/物流/u3_line.png"}},
{
            "id":"1a689a258f484998bcd2508e44f2c22d",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "horizontalAlignment":"center",
              "lineSpacing":"20px",
              "location":{
                "x":346,
                "y":35},
              "size":{
                "width":708,
                "height":40}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"ea03187483ce4b12a1e0624a4f493d0a",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "horizontalAlignment":"center",
                  "lineSpacing":"20px",
                  "location":{
                    "x":346,
                    "y":35},
                  "size":{
                    "width":708,
                    "height":40}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}}]}}},
  "objectPaths":{
    "7f89581bfaad42dbb98e91429d78d8d6":{
      "scriptId":"u0",
      "be355ce83e944039947e531f2a3c65bf":{
        "scriptId":"u1"},
      "7ad610fe1fd94f489f35d1adf33b9af1":{
        "scriptId":"u2"},
      "aa3cf84e2bbd46a28151af5ccb7dfbf6":{
        "scriptId":"u3"},
      "cf98c532bd864dcc8adeb788cba04559":{
        "scriptId":"u4"},
      "6007835eb6e94566a4ce3334bd18ac62":{
        "scriptId":"u5"},
      "384a059abd7b46e298aafb2cd9c43187":{
        "scriptId":"u6"},
      "7c9058fa398c4796a04243c49a790a49":{
        "scriptId":"u7"},
      "438b60b6102f4768af4f0703a5815f11":{
        "scriptId":"u8"},
      "d4dbd3f981904f4fa63897125413dd32":{
        "scriptId":"u9"},
      "609d5aa69b7f4e68b5e6717d43d879bd":{
        "scriptId":"u10"},
      "8a3db1216f984f9cb223ca8379348c88":{
        "scriptId":"u11"},
      "156ee2878c014482ad208a835bfdfd57":{
        "scriptId":"u12"},
      "a982eb6988b44874aec2f7a7563f3bbc":{
        "scriptId":"u13"},
      "3c448fc8af0f4a8e9fb1b5c15b818d05":{
        "scriptId":"u14"},
      "dfba4f993e4e48d4b2d57c920a9037ef":{
        "scriptId":"u15"},
      "3a4567cc67374e3d95142abc1567d0bd":{
        "scriptId":"u16"},
      "28346d4547e147abb42f1e03fe9d2d51":{
        "scriptId":"u17"},
      "11a8cd2c460a4915858ba5e52d96207c":{
        "scriptId":"u18"},
      "774e6c3744c644c2bd17b7fa7892feac":{
        "scriptId":"u19"},
      "f9137a915a3f4fc2b4388e5d7f1767ba":{
        "scriptId":"u20"},
      "148da07c87f142879097b9a411344180":{
        "scriptId":"u21"},
      "4d20535595e94f17ba4488bc15e48676":{
        "scriptId":"u22"},
      "56f736c3d24947ab9a3e62c329fd19a4":{
        "scriptId":"u23"},
      "2bef87c6b612443d814a873ce10c6e28":{
        "scriptId":"u24"},
      "315dd3063b454753b9694c00bdb7bac0":{
        "scriptId":"u25"},
      "e3835d78c26e4225b56136c0f7cee8e9":{
        "scriptId":"u26"},
      "2ffd3ddb833f48348e4ffdbba2c2ba86":{
        "scriptId":"u27"},
      "428b4de1cfa54a9794166f743cdd9895":{
        "scriptId":"u28"}},
    "8c240d25d50b4d439aa8015bd587e9e1":{
      "scriptId":"u29",
      "6d839a3937d045bf813b8be7d50e2149":{
        "scriptId":"u30"},
      "960f638a92ca40d4bab16f14077f2f59":{
        "scriptId":"u31"},
      "90d533b4c8c24b3883b34a888ba79377":{
        "scriptId":"u32"},
      "1a689a258f484998bcd2508e44f2c22d":{
        "scriptId":"u33"},
      "ea03187483ce4b12a1e0624a4f493d0a":{
        "scriptId":"u34"}},
    "05bd801f271145e29b0d8ab0affabce7":{
      "scriptId":"u35"},
    "f657f1aa8ad048ac84181fd650388b51":{
      "scriptId":"u36"},
    "9ce485a2f92944f9815e15dd82a6355e":{
      "scriptId":"u37"},
    "d5868a5bcd214957a7b3dfd22ae78aba":{
      "scriptId":"u38"},
    "394c49cd7a9b4cec9787487b2960ef97":{
      "scriptId":"u39"},
    "7596e3512edc4b7d89e92837b70dd516":{
      "scriptId":"u40"},
    "91a05b1257f34c7895d13a610307d217":{
      "scriptId":"u41"},
    "bdce72107dcc45ff80da70584eb32048":{
      "scriptId":"u42"},
    "ed9c88bda82845759219174c65abf572":{
      "scriptId":"u43"},
    "3d74846235e14a978dd91b040a8b4f3a":{
      "scriptId":"u44"},
    "dbf4efe14aed431b94a2ea8f35038128":{
      "scriptId":"u45"},
    "94c48ed1432949baae36555b4d55ae91":{
      "scriptId":"u46"},
    "3d179ebff8c64b319268e88c56bbf859":{
      "scriptId":"u47"},
    "3548c86004ea42d38d2e59cf119bf2ae":{
      "scriptId":"u48"},
    "d27b2a3a454a44199efb01514ee5bbfa":{
      "scriptId":"u49"},
    "9b5bf400a85d444389896c6f34e857d3":{
      "scriptId":"u50"},
    "676170529be5428bb36cf7b439e1c68b":{
      "scriptId":"u51"},
    "07a443ea144c40a9898ec469d02edd02":{
      "scriptId":"u52"},
    "048bd1e665a644eeb3601f6668ba22ec":{
      "scriptId":"u53"},
    "1e3b578c74cd467faadaa138bec2fbb4":{
      "scriptId":"u54"},
    "97c23bc071bd4754b719def6d04a2b4a":{
      "scriptId":"u55"},
    "8f9b2b4361344e2cbb5a7eba2eea190d":{
      "scriptId":"u56"},
    "3badc887742549d2a0c4a6ca7f60a421":{
      "scriptId":"u57"},
    "47ad76af79384dbbb03ebc3451aedd08":{
      "scriptId":"u58"},
    "dca8ca68ca0d4624bd7190990ee672b9":{
      "scriptId":"u59"},
    "316b095ae7c74c12b34eb88c90ba6dcc":{
      "scriptId":"u60"},
    "4030ee7223374da690b44d7b700343c9":{
      "scriptId":"u61"},
    "7e8e0b337c20459b9a408cdd8e9fb815":{
      "scriptId":"u62"},
    "81b89a87cda74bfba8e89ad2631e3919":{
      "scriptId":"u63"},
    "439e422a556c4866a80ca142ad5f72f2":{
      "scriptId":"u64"},
    "119dd3f2c22048f195ce0954c6504723":{
      "scriptId":"u65"},
    "0e45421250b940cba9046fc8164112d0":{
      "scriptId":"u66"},
    "19a26e94782847b680d7a7798b3256e6":{
      "scriptId":"u67"},
    "6649a330d70347e199790d64645718b1":{
      "scriptId":"u68"},
    "1fd5bda6ae164c5dab0ecb01a2381acf":{
      "scriptId":"u69"},
    "b0a0946c663c4c5aaed57cbe2a69f0c0":{
      "scriptId":"u70"},
    "5390720076284e68bd72cf3cdfcfb821":{
      "scriptId":"u71"},
    "9df196dc16804d8cb141f200587f27bf":{
      "scriptId":"u72"},
    "8b8edcfa65754fff9c09aacb3db7f4eb":{
      "scriptId":"u73"},
    "b3cb35822f4f4ed0afd3b7a6ae570267":{
      "scriptId":"u74"},
    "c577e65f3cc04a0ba20fe43997afd619":{
      "scriptId":"u75"},
    "fd622a7a47a2477b9c6b7014f49c70f5":{
      "scriptId":"u76"},
    "39a130a90d6a4eb192546f8f480e54ec":{
      "scriptId":"u77"},
    "8d500023ab764284aaa1d85160b7bcc9":{
      "scriptId":"u78"},
    "c7817f8a2363463f924bbffcbe127973":{
      "scriptId":"u79"},
    "3942040b06e34cc28fdad26403d17ab8":{
      "scriptId":"u80"},
    "26aa46ff50c845ad9273820a6aa17b00":{
      "scriptId":"u81"},
    "069e4bd5c8b54a9882614d4f4c1daaed":{
      "scriptId":"u82"},
    "2b0a775a07cb4138a09059a0df9c9cb2":{
      "scriptId":"u83"},
    "adcdbd86da4944638773bf76775563d3":{
      "scriptId":"u84"},
    "a3711f1bf46444078dc7b77841e125ae":{
      "scriptId":"u85"},
    "bb0f0a1dc3c84ababeab417fe124d91e":{
      "scriptId":"u86"},
    "e5aecee15af049c5b54b284d08e15517":{
      "scriptId":"u87"},
    "c5b6dec984054043b41ef1289cdb64a1":{
      "scriptId":"u88"},
    "bdd22eede1b848dab46f4e052faaeb10":{
      "scriptId":"u89"},
    "91d51a042b164971aa20e6c74a8b0af3":{
      "scriptId":"u90"},
    "cd32d8f6ca7e420d9e9f9f482214b7f6":{
      "scriptId":"u91"},
    "0229b494f5644ca186201585cdcd9150":{
      "scriptId":"u92"},
    "518b11d8bf214064bfa0b139168acc13":{
      "scriptId":"u93"},
    "0637ca2768df40b3a4786a50bcd283d4":{
      "scriptId":"u94"},
    "ef37a1cd72594833ad5ba078ef6d54f4":{
      "scriptId":"u95"},
    "7690b197289d4a3880ec309588ce3bb3":{
      "scriptId":"u96"},
    "927923e6d8bc452e89ad245942e939bf":{
      "scriptId":"u97"},
    "b58439355ca841bea56ca87afe3c8118":{
      "scriptId":"u98"},
    "4978a2b7d3d94897b831dcce5138e445":{
      "scriptId":"u99"},
    "a2c0f4e67a124070a54c399ac606a8f0":{
      "scriptId":"u100"},
    "7df3c2ef3be44743948ee537f634e3da":{
      "scriptId":"u101"},
    "fdef81cdc293429b82e66465d9e10eab":{
      "scriptId":"u102"},
    "00d14424f44d4065b72248d71a659a59":{
      "scriptId":"u103"},
    "606a8b86389f4442ad8050489e58d362":{
      "scriptId":"u104"},
    "14d12f8c41b34b38a7d56b00eb283cf7":{
      "scriptId":"u105"},
    "682ea5f508314252ade111cdb3c15adf":{
      "scriptId":"u106"},
    "0bf282564bc840ae8573901454ec6e32":{
      "scriptId":"u107"},
    "b1933968507f48838dd7e00d34d11989":{
      "scriptId":"u108"},
    "f3222abe15ba4406b27c4eea99bf983c":{
      "scriptId":"u109"},
    "ff5afccf082b4441b40d9cc5d1113645":{
      "scriptId":"u110"},
    "1a25936ab3d748218cc4cb5f5adc2aa3":{
      "scriptId":"u111"},
    "5bc956f721c4452291572654263dba31":{
      "scriptId":"u112"},
    "10ca8942844b4d9d8459432922054dd9":{
      "scriptId":"u113"},
    "a9f32289a4f948798baac12310582ee5":{
      "scriptId":"u114"},
    "fe48d9a9ec074cb2ae4f481317b5918f":{
      "scriptId":"u115"},
    "ee4b6d9368fa4b67b6ea8a5165dc5838":{
      "scriptId":"u116"},
    "addcb34a51204445a831edb2043f10d4":{
      "scriptId":"u117"},
    "538dfd03ee454d72ac0ab27158bf8dfd":{
      "scriptId":"u118"},
    "c20b8b17ae0a49688df77b2435bd7471":{
      "scriptId":"u119"},
    "0cc3e640bb1446c1a64c166bc5043ec7":{
      "scriptId":"u120"},
    "10b13cc9133b40baac248e7adfb2bcfb":{
      "scriptId":"u121"},
    "56d834b68aed4bca97b94d0d99cbc038":{
      "scriptId":"u122"},
    "951bbd6ee0c547848b5ef99b09670937":{
      "scriptId":"u123"},
    "9dbea300d2474b4399ff42e3321e580e":{
      "scriptId":"u124"},
    "22d40c89d74d4cd797aad2c8ab59a30a":{
      "scriptId":"u125"},
    "be43435f333d40d8acc2111de801266e":{
      "scriptId":"u126"},
    "66c2227f95c44ce78d89c5447e7f7e07":{
      "scriptId":"u127"},
    "1c70e48e37d5470ca5e1e219b6c9e3a5":{
      "scriptId":"u128"},
    "e2616b928b5541619996e3731796b92c":{
      "scriptId":"u129"}}});