$axure.loadCurrentPage({
  "url":"已完成_4.html",
  "generationDate":new Date(1432872292338.34),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"3c6b958bc70246f599a4e608caf0100e",
    "type":"Axure:Page",
    "name":"已完成",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"6a9570a5b47e438e9e6c067e1340e419",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":200,
              "y":150},
            "size":{
              "width":200,
              "height":80},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFD7D7D7}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"389af8510dff460bafd2baba301b4ed1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":200,
                  "y":150},
                "size":{
                  "width":200,
                  "height":80},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的工作台/u26.png"}},
{
          "id":"505ba109dc7748739ee333fee152afa6",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFE4E4E4},
            "location":{
              "x":200,
              "y":230},
            "size":{
              "width":200,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFD7D7D7}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"083394ea89c14d89b18cec264a6d2d80",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4},
                "location":{
                  "x":200,
                  "y":230},
                "size":{
                  "width":200,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的工作台/u28.png"}},
{
          "id":"f0943801463441c6b86dbfbdf692d613",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":200,
              "y":330},
            "size":{
              "width":200,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFD7D7D7}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e580c0d30b9b457bbec409af46e58605",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":200,
                  "y":330},
                "size":{
                  "width":200,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的工作台/u30.png"}},
{
          "id":"d3b4169869324760b3f6fbc2a5ba8013",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":1007}},
          "adaptiveStyles":{
},
          "masterId":"9aa3da306ba24637b281c884b1c30bca"},
{
          "id":"5518d313883744b38c9356902ebd13d5",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "fill":{
              "fillType":"solid",
              "color":0xFFE4E4E4},
            "location":{
              "x":210,
              "y":300},
            "size":{
              "width":190,
              "height":30},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFD7D7D7}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8d15f01631164b62bc55d803c7b30069",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4},
                "location":{
                  "x":210,
                  "y":300},
                "size":{
                  "width":190,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/管理资源单/u233.png"}},
{
          "id":"e714c54b7ffb4becbe28d1f8fa417fc6",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "location":{
              "x":210,
              "y":270},
            "size":{
              "width":190,
              "height":30},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFD7D7D7}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cbdb2ac0924b4600a615190e3f2b7f1e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "location":{
                  "x":210,
                  "y":270},
                "size":{
                  "width":190,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/管理资源单/u235.png"}},
{
          "id":"b762bf7e2fc347e6bcfd9508cdaf5087",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
},
          "adaptiveStyles":{
},
          "masterId":"d5b739f105d347138233b0627c50cf7b"},
{
          "id":"57fdc7f49da543b78e25fc007d4d889c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":420,
              "y":266},
            "size":{
              "width":780,
              "height":724},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFD7D7D7}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3ad4f1bcf3da481880603dd0571cf2c0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":420,
                  "y":266},
                "size":{
                  "width":780,
                  "height":724},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/托运管理_1/u37.png"}},
{
          "id":"1bdc033146684facbc45ab0c80d7ccb2",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":420,
              "y":266},
            "size":{
              "width":780,
              "height":30},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFD7D7D7}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"14e601d3b9c44c7683f7cf976e219a76",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":420,
                  "y":266},
                "size":{
                  "width":780,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/竞价管理/u57.png"}},
{
          "id":"9ec374db650d4c628309f6e60a3858fc",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontWeight":"700",
            "location":{
              "x":591,
              "y":273},
            "size":{
              "width":111,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"435420d6ccc247c386a72e5977c014fa",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"700",
                "location":{
                  "x":591,
                  "y":273},
                "size":{
                  "width":111,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"83d85188580540f8999c690ca1d9be85",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontWeight":"700",
            "location":{
              "x":798,
              "y":273},
            "size":{
              "width":80,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f1b3b386045244daa7686561c382c03f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"700",
                "location":{
                  "x":798,
                  "y":273},
                "size":{
                  "width":80,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6606678ad7824fe3b9a9cd96bb7eff21",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":591,
              "y":315},
            "size":{
              "width":239,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d6666a32c0b348adb5a9df7def60b7b1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":591,
                  "y":315},
                "size":{
                  "width":239,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"25d3821d35d94a7882bfd64c6dcb2a8c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":591,
              "y":349},
            "size":{
              "width":239,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"47e8fb01c10e4b93bc6ec2fb7a22ec79",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":591,
                  "y":349},
                "size":{
                  "width":239,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0688f590312b4165a9e310a8a3d486ed",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":591,
              "y":380},
            "size":{
              "width":239,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"43e9ebc9eef44087bb35aff821ea7511",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":591,
                  "y":380},
                "size":{
                  "width":239,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f45c5abee4db4700807ca5fa4983c44b",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":436,
              "y":416},
            "size":{
              "width":748,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFD7D7D7}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/托运管理_1/u51_line.png"}},
{
          "id":"4e4e0f8e16774284b75c348a6cff4a08",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"center",
            "location":{
              "x":768,
              "y":315},
            "size":{
              "width":103,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"be813b1ecd7d49afa47a92f8364f4581",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "location":{
                  "x":768,
                  "y":315},
                "size":{
                  "width":103,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7f30cb91aac34ffa8996c395a36977f1",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontWeight":"700",
            "location":{
              "x":944,
              "y":273},
            "size":{
              "width":105,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"37ec3aa36ea044cc965e9f5cb91bce2e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"700",
                "location":{
                  "x":944,
                  "y":273},
                "size":{
                  "width":105,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4f4c8348bffb494bb0368c7307a33b51",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":944,
              "y":315},
            "size":{
              "width":244,
              "height":32}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"caeaedb317a242688d36477bacdf02bd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":944,
                  "y":315},
                "size":{
                  "width":244,
                  "height":32}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e6b7a15c73164e91bbb3983276cab9ce",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":591,
              "y":446},
            "size":{
              "width":239,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0d90fe66b8b3453eb7e8076adac28d11",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":591,
                  "y":446},
                "size":{
                  "width":239,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9aacaff6c340438facdb6a92b9ce9850",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":591,
              "y":480},
            "size":{
              "width":239,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"35cab221d9924caf9a0a1c608d05b939",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":591,
                  "y":480},
                "size":{
                  "width":239,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a09e6831b39f40c485bbbefafb14a303",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":591,
              "y":511},
            "size":{
              "width":239,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4408f6d7e0ac4822a2dd25ba57a9b47c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":591,
                  "y":511},
                "size":{
                  "width":239,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"003c46880c9d41898bb75a7f80f7d8e9",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":436,
              "y":547},
            "size":{
              "width":748,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFD7D7D7}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/托运管理_1/u51_line.png"}},
{
          "id":"6719b05e5a244bbf8aa9038d0a68a3a4",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":944,
              "y":507},
            "size":{
              "width":105,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"e6c43ced7e4f4d719b908355548c0c6b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":591,
              "y":585},
            "size":{
              "width":239,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"18d9905d49444301b8f773063e176938",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":591,
                  "y":585},
                "size":{
                  "width":239,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e398157832cf4d31aa607c3259d20557",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":591,
              "y":619},
            "size":{
              "width":239,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"319e709681df439abb9214fe2f03f367",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":591,
                  "y":619},
                "size":{
                  "width":239,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c03994deee87475893771201fcadaf8c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":591,
              "y":650},
            "size":{
              "width":239,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a57cc7a2be564c0dab47af2c4b8acbed",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":591,
                  "y":650},
                "size":{
                  "width":239,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"895223c5e4c24c7eb3c1fab7dcee32bc",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":436,
              "y":686},
            "size":{
              "width":748,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFD7D7D7}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/托运管理_1/u51_line.png"}},
{
          "id":"d4df66d4263f4d00a3ec473418dbd24c",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":944,
              "y":646},
            "size":{
              "width":105,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"54e50fadf1f24cf5b19d6028d3ce14cc",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":591,
              "y":717},
            "size":{
              "width":239,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c0350bcd533446aa9ece9605aa13a16b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":591,
                  "y":717},
                "size":{
                  "width":239,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e5402dd1d858469d9b57dd036c91ab07",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":591,
              "y":751},
            "size":{
              "width":239,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ad39ffa6cce04532989b2cb3b6397cec",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":591,
                  "y":751},
                "size":{
                  "width":239,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b8bdedd0ecc34eacb73bba0ec78d75d0",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":591,
              "y":782},
            "size":{
              "width":239,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8dd518eaa57c466dbf94148a7e8894eb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":591,
                  "y":782},
                "size":{
                  "width":239,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c0bfa3cb5f0e4968980228c521b4f724",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":436,
              "y":817},
            "size":{
              "width":748,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFD7D7D7}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/托运管理_1/u51_line.png"}},
{
          "id":"3c55ecee29784ff38ef1da0f353ea0b1",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":944,
              "y":716},
            "size":{
              "width":244,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a2530367138740ae9026811820c2eb18",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":944,
                  "y":716},
                "size":{
                  "width":244,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d989a79a66c94c7ab9a06f9e0b1981d3",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":944,
              "y":777},
            "size":{
              "width":105,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"1cc280e7d8234d94b3353db275a8ab10",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":591,
              "y":855},
            "size":{
              "width":239,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fe7c6e0de3a84513914cfa97a4857f81",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":591,
                  "y":855},
                "size":{
                  "width":239,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2ab9a0b138b7468c9e35abf7987cd68f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":591,
              "y":889},
            "size":{
              "width":239,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1a6034c24d6b4ed5881ffc93116dea92",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":591,
                  "y":889},
                "size":{
                  "width":239,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"598b38209af240c6b2357db62127f09c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":591,
              "y":920},
            "size":{
              "width":239,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"58a03a54159645e68b07add840ac6d91",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":591,
                  "y":920},
                "size":{
                  "width":239,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"82d80cc26e914c919b8dea4f7fb8460b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":944,
              "y":855},
            "size":{
              "width":244,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1848fbaaca4f4bb9a43bf9aab8a400de",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":944,
                  "y":855},
                "size":{
                  "width":244,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9770728817f7457f8396ff0e80724b06",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":944,
              "y":916},
            "size":{
              "width":105,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"f45e75f603d7445a83256957afd34cef",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":576,
              "y":960},
            "size":{
              "width":504,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e3617882dd4b49f28cc668aaa3fe78d0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":576,
                  "y":960},
                "size":{
                  "width":504,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的收藏/u301.png"}},
{
          "id":"5920a1b2f6804f769219cdc5b3c05ac8",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":420,
              "y":150},
            "size":{
              "width":780,
              "height":100},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFD7D7D7}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9651cebbc52f451da0bf7ba5a9e9ba3b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":420,
                  "y":150},
                "size":{
                  "width":780,
                  "height":100},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/托运管理_1/u107.png"}},
{
          "id":"d533f23f02d14c489160f262078d49e1",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":436,
              "y":215},
            "size":{
              "width":111,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dfc6277cd0154409b295e72e4a30468e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":436,
                  "y":215},
                "size":{
                  "width":111,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ea66a7dbffe344878f1400c70d9466ac",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":502,
              "y":211},
            "size":{
              "width":188,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"6e9b41ea696f445b869b568697c4f870",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":902,
              "y":169},
            "size":{
              "width":111,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"15318c5e1da2494ea7957c0459e58541",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":902,
                  "y":169},
                "size":{
                  "width":111,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1267df29a90d4b7287717a5561f346ed",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":967,
              "y":165},
            "size":{
              "width":135,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"efc5ceff2d8a423a9441501f0fcc8272",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":700,
              "y":211},
            "size":{
              "width":172,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"8fa0dfe2496140dca4c10bb22d608480",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":436,
              "y":170},
            "size":{
              "width":111,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bbda20f173094367b8da0cc0ac59818a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":436,
                  "y":170},
                "size":{
                  "width":111,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0c16b5932fba49d5b8d8baaa694462e6",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontWeight":"700",
            "location":{
              "x":436,
              "y":273},
            "size":{
              "width":111,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"58a7f9a35dda48d2bc0f20540dac2fc8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"700",
                "location":{
                  "x":436,
                  "y":273},
                "size":{
                  "width":111,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e9e4ca3ac583471e8c634d6e9a8e508d",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":944,
              "y":371},
            "size":{
              "width":105,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"276fe8a34e414a738208ee5041c31f00",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":436,
              "y":306},
            "size":{
              "width":84,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d7f598d05b64410a80060d601d56695a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":436,
                  "y":306},
                "size":{
                  "width":84,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"06a0e3b4b20c44d49437c3ac0963623a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":436,
              "y":436},
            "size":{
              "width":84,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bd1fb68d4efa4a3ebe744cd01321c1bb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":436,
                  "y":436},
                "size":{
                  "width":84,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0fb40574220040008652e9faf2b1dfeb",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":436,
              "y":585},
            "size":{
              "width":84,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"31d8d91b051447bf97e94c9e8f328de9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":436,
                  "y":585},
                "size":{
                  "width":84,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"cdbd955efe284f11901e66fdee80a6e2",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":436,
              "y":717},
            "size":{
              "width":84,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"24aee4407e2744f4a6c53d4756116560",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":436,
                  "y":717},
                "size":{
                  "width":84,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6256a90cd24244edb7c8eb73a2f80a7a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":436,
              "y":855},
            "size":{
              "width":84,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1a874fe5c2644dbe88e983ae4bd96094",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":436,
                  "y":855},
                "size":{
                  "width":84,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"48486274ae3d47659dd4279395dbbb7d",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":502,
              "y":167},
            "size":{
              "width":135,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"e0751dce6a6740e4b8268f89d096ebb1",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":668,
              "y":168},
            "size":{
              "width":114,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c05eee5f8d36478e919480a90c730188",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":668,
                  "y":168},
                "size":{
                  "width":114,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d178f862db8a4d818f78c5daaea74c69",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":737,
              "y":164},
            "size":{
              "width":135,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"26206862df844480b86a82c46b72ef9a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":944,
              "y":446},
            "size":{
              "width":244,
              "height":32}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c9c7beee85ef406c8434915d5fcb114f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":944,
                  "y":446},
                "size":{
                  "width":244,
                  "height":32}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"fe186e5cb5c94ea09fa0a4855cc51841",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":944,
              "y":585},
            "size":{
              "width":244,
              "height":32}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ad21c346e429451487a5dabf79288fde",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":944,
                  "y":585},
                "size":{
                  "width":244,
                  "height":32}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7e1243d8ed994e679db9c9d8150b45e4",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"center",
            "location":{
              "x":768,
              "y":446},
            "size":{
              "width":103,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8b162e21863e41f281458129c2b3e3d8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "location":{
                  "x":768,
                  "y":446},
                "size":{
                  "width":103,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"be44672eddfb4575926606f592093372",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"center",
            "location":{
              "x":768,
              "y":585},
            "size":{
              "width":103,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c25dea37bd334e808c8c54598480979c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "location":{
                  "x":768,
                  "y":585},
                "size":{
                  "width":103,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6fb41b65abac47628cb8b35d2ee8b176",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"center",
            "location":{
              "x":768,
              "y":717},
            "size":{
              "width":103,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bbb331d44cd3442e81ec859ed3487889",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "location":{
                  "x":768,
                  "y":717},
                "size":{
                  "width":103,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"dac8db83a8ea4825b4d33ad2183f03a4",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"center",
            "location":{
              "x":768,
              "y":855},
            "size":{
              "width":103,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a4f45eb945fc41a9a7ddc131124496f3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "location":{
                  "x":768,
                  "y":855},
                "size":{
                  "width":103,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
    "9aa3da306ba24637b281c884b1c30bca":{
      "packageId":"9aa3da306ba24637b281c884b1c30bca",
      "type":"Axure:Master",
      "name":"交易员底部",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"应用字体",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"aa94056b817049cbb1fa6bacb8c1e519",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "size":{
                "width":1400,
                "height":40},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFD7D7D7}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"d0f70829d22f42fea545dfa7923b52be",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "size":{
                    "width":1400,
                    "height":40},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFD7D7D7}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/首页/u13.png"}}]}},
    "d5b739f105d347138233b0627c50cf7b":{
      "packageId":"d5b739f105d347138233b0627c50cf7b",
      "type":"Axure:Master",
      "name":"交易员头部--托运",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"应用字体",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"ad29d0868e2d4e1ea04d2e3813cac53e",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "size":{
                "width":1400,
                "height":90},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFD7D7D7}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"705ba8054db8459aa453d6e8970360e1",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "size":{
                    "width":1400,
                    "height":90},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFD7D7D7}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/我的工作台/u3.png"}},
{
            "id":"435294aeef7344768378c778f254ae49",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":200,
                "y":15},
              "size":{
                "width":200,
                "height":60},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFD7D7D7}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"423f499025e441208a01286ce6aefd3d",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":200,
                    "y":15},
                  "size":{
                    "width":200,
                    "height":60},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFD7D7D7}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/我的工作台/u5.png"}},
{
            "id":"5bff7bb0f32e4aaba352a33b10354ace",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFFF2F2F2},
              "location":{
                "x":0,
                "y":90},
              "size":{
                "width":1400,
                "height":35},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFD7D7D7}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"4f781b78feb94e5c9e8d524ff73eadfc",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFF2F2F2},
                  "location":{
                    "x":0,
                    "y":90},
                  "size":{
                    "width":1400,
                    "height":35},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFD7D7D7}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/首页/u33.png"}},
{
            "id":"08ae0434c50140e782a3740366b35ef6",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":200,
                "y":90},
              "size":{
                "width":130,
                "height":35},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFD7D7D7}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"98765ab47746412d8d002e805dd3f5c8",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":200,
                    "y":90},
                  "size":{
                    "width":130,
                    "height":35},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFD7D7D7}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/我的工作台/u11.png"}},
{
            "id":"5b1950c85d9d43979ce7ee038d82addd",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":330,
                "y":90},
              "size":{
                "width":130,
                "height":35},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFD7D7D7}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"922258fa17a1468e89be4de887eb9242",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":330,
                    "y":90},
                  "size":{
                    "width":130,
                    "height":35},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFD7D7D7}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/我的工作台/u11.png"}},
{
            "id":"196b102fa5434693932ec2ccadc2aa72",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "horizontalAlignment":"right",
              "location":{
                "x":940,
                "y":15},
              "size":{
                "width":260,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"05799b485a82452f859a0923a542670d",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "horizontalAlignment":"right",
                  "location":{
                    "x":940,
                    "y":15},
                  "size":{
                    "width":260,
                    "height":16}},
                "adaptiveStyles":{
},
                "objects":[{
                    "id":"9224b06f5bc3462d9761fb8b32aaaefc",
                    "label":"",
                    "type":"hyperlink",
                    "styleType":"hyperlink",
                    "visible":true,
                    "style":{
},
                    "adaptiveStyles":{
},
                    "interactionMap":{
                      "onClick":{
                        "description":"OnClick",
                        "cases":[{
                            "description":"用例 1",
                            "isNewIfGroup":false,
                            "actions":[{
                                "action":"linkWindow",
                                "description":"在 当前窗口 打开 帐号设置",
                                "target":{
                                  "targetType":"page",
                                  "url":"帐号设置.html",
                                  "includeVariables":true},
                                "linkType":"current"}]}]}},
                    "tabbable":true}]}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"03c2d1c0a018442fbae9cadc97fdbf9e",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":460,
                "y":90},
              "size":{
                "width":130,
                "height":35},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFD7D7D7}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"e3ae0d1bffa6454e953785c75dd9411e",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":460,
                    "y":90},
                  "size":{
                    "width":130,
                    "height":35},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFD7D7D7}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/我的工作台/u11.png"}},
{
            "id":"29e560d07ab1441c8bd2c912e6128056",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":590,
                "y":90},
              "size":{
                "width":130,
                "height":35},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFD7D7D7}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"e21c32341ad54afcbba6d7060f2aed87",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":590,
                    "y":90},
                  "size":{
                    "width":130,
                    "height":35},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFD7D7D7}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/我的工作台/u11.png"}},
{
            "id":"a93032c21bff4eff9ce74ad7de209ec8",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":720,
                "y":90},
              "size":{
                "width":130,
                "height":35},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFD7D7D7}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"8f58a485ce114857b88238e6126eea08",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":720,
                    "y":90},
                  "size":{
                    "width":130,
                    "height":35},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFD7D7D7}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/我的工作台/u11.png"}},
{
            "id":"55c1a272476d4a028543b54a8dbbc346",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFFE4E4E4},
              "location":{
                "x":850,
                "y":90},
              "size":{
                "width":130,
                "height":35},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFD7D7D7}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"227b88b93913401bba3bd8014f0993e8",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFE4E4E4},
                  "location":{
                    "x":850,
                    "y":90},
                  "size":{
                    "width":130,
                    "height":35},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFD7D7D7}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/我的工作台/u9.png"}},
{
            "id":"30e27b2aeacd454b8ddd21f178272d3a",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":980,
                "y":90},
              "size":{
                "width":130,
                "height":35},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFD7D7D7}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"7851308e4e85456daf8cce58bc2f888f",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":980,
                    "y":90},
                  "size":{
                    "width":130,
                    "height":35},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFD7D7D7}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/我的工作台/u11.png"}}]}}},
  "objectPaths":{
    "6a9570a5b47e438e9e6c067e1340e419":{
      "scriptId":"u0"},
    "389af8510dff460bafd2baba301b4ed1":{
      "scriptId":"u1"},
    "505ba109dc7748739ee333fee152afa6":{
      "scriptId":"u2"},
    "083394ea89c14d89b18cec264a6d2d80":{
      "scriptId":"u3"},
    "f0943801463441c6b86dbfbdf692d613":{
      "scriptId":"u4"},
    "e580c0d30b9b457bbec409af46e58605":{
      "scriptId":"u5"},
    "d3b4169869324760b3f6fbc2a5ba8013":{
      "scriptId":"u6",
      "aa94056b817049cbb1fa6bacb8c1e519":{
        "scriptId":"u7"},
      "d0f70829d22f42fea545dfa7923b52be":{
        "scriptId":"u8"}},
    "5518d313883744b38c9356902ebd13d5":{
      "scriptId":"u9"},
    "8d15f01631164b62bc55d803c7b30069":{
      "scriptId":"u10"},
    "e714c54b7ffb4becbe28d1f8fa417fc6":{
      "scriptId":"u11"},
    "cbdb2ac0924b4600a615190e3f2b7f1e":{
      "scriptId":"u12"},
    "b762bf7e2fc347e6bcfd9508cdaf5087":{
      "scriptId":"u13",
      "ad29d0868e2d4e1ea04d2e3813cac53e":{
        "scriptId":"u14"},
      "705ba8054db8459aa453d6e8970360e1":{
        "scriptId":"u15"},
      "435294aeef7344768378c778f254ae49":{
        "scriptId":"u16"},
      "423f499025e441208a01286ce6aefd3d":{
        "scriptId":"u17"},
      "5bff7bb0f32e4aaba352a33b10354ace":{
        "scriptId":"u18"},
      "4f781b78feb94e5c9e8d524ff73eadfc":{
        "scriptId":"u19"},
      "08ae0434c50140e782a3740366b35ef6":{
        "scriptId":"u20"},
      "98765ab47746412d8d002e805dd3f5c8":{
        "scriptId":"u21"},
      "5b1950c85d9d43979ce7ee038d82addd":{
        "scriptId":"u22"},
      "922258fa17a1468e89be4de887eb9242":{
        "scriptId":"u23"},
      "196b102fa5434693932ec2ccadc2aa72":{
        "scriptId":"u24"},
      "05799b485a82452f859a0923a542670d":{
        "scriptId":"u25"},
      "9224b06f5bc3462d9761fb8b32aaaefc":{
        "scriptId":"u26"},
      "03c2d1c0a018442fbae9cadc97fdbf9e":{
        "scriptId":"u27"},
      "e3ae0d1bffa6454e953785c75dd9411e":{
        "scriptId":"u28"},
      "29e560d07ab1441c8bd2c912e6128056":{
        "scriptId":"u29"},
      "e21c32341ad54afcbba6d7060f2aed87":{
        "scriptId":"u30"},
      "a93032c21bff4eff9ce74ad7de209ec8":{
        "scriptId":"u31"},
      "8f58a485ce114857b88238e6126eea08":{
        "scriptId":"u32"},
      "55c1a272476d4a028543b54a8dbbc346":{
        "scriptId":"u33"},
      "227b88b93913401bba3bd8014f0993e8":{
        "scriptId":"u34"},
      "30e27b2aeacd454b8ddd21f178272d3a":{
        "scriptId":"u35"},
      "7851308e4e85456daf8cce58bc2f888f":{
        "scriptId":"u36"}},
    "57fdc7f49da543b78e25fc007d4d889c":{
      "scriptId":"u37"},
    "3ad4f1bcf3da481880603dd0571cf2c0":{
      "scriptId":"u38"},
    "1bdc033146684facbc45ab0c80d7ccb2":{
      "scriptId":"u39"},
    "14e601d3b9c44c7683f7cf976e219a76":{
      "scriptId":"u40"},
    "9ec374db650d4c628309f6e60a3858fc":{
      "scriptId":"u41"},
    "435420d6ccc247c386a72e5977c014fa":{
      "scriptId":"u42"},
    "83d85188580540f8999c690ca1d9be85":{
      "scriptId":"u43"},
    "f1b3b386045244daa7686561c382c03f":{
      "scriptId":"u44"},
    "6606678ad7824fe3b9a9cd96bb7eff21":{
      "scriptId":"u45"},
    "d6666a32c0b348adb5a9df7def60b7b1":{
      "scriptId":"u46"},
    "25d3821d35d94a7882bfd64c6dcb2a8c":{
      "scriptId":"u47"},
    "47e8fb01c10e4b93bc6ec2fb7a22ec79":{
      "scriptId":"u48"},
    "0688f590312b4165a9e310a8a3d486ed":{
      "scriptId":"u49"},
    "43e9ebc9eef44087bb35aff821ea7511":{
      "scriptId":"u50"},
    "f45c5abee4db4700807ca5fa4983c44b":{
      "scriptId":"u51"},
    "4e4e0f8e16774284b75c348a6cff4a08":{
      "scriptId":"u52"},
    "be813b1ecd7d49afa47a92f8364f4581":{
      "scriptId":"u53"},
    "7f30cb91aac34ffa8996c395a36977f1":{
      "scriptId":"u54"},
    "37ec3aa36ea044cc965e9f5cb91bce2e":{
      "scriptId":"u55"},
    "4f4c8348bffb494bb0368c7307a33b51":{
      "scriptId":"u56"},
    "caeaedb317a242688d36477bacdf02bd":{
      "scriptId":"u57"},
    "e6b7a15c73164e91bbb3983276cab9ce":{
      "scriptId":"u58"},
    "0d90fe66b8b3453eb7e8076adac28d11":{
      "scriptId":"u59"},
    "9aacaff6c340438facdb6a92b9ce9850":{
      "scriptId":"u60"},
    "35cab221d9924caf9a0a1c608d05b939":{
      "scriptId":"u61"},
    "a09e6831b39f40c485bbbefafb14a303":{
      "scriptId":"u62"},
    "4408f6d7e0ac4822a2dd25ba57a9b47c":{
      "scriptId":"u63"},
    "003c46880c9d41898bb75a7f80f7d8e9":{
      "scriptId":"u64"},
    "6719b05e5a244bbf8aa9038d0a68a3a4":{
      "scriptId":"u65"},
    "e6c43ced7e4f4d719b908355548c0c6b":{
      "scriptId":"u66"},
    "18d9905d49444301b8f773063e176938":{
      "scriptId":"u67"},
    "e398157832cf4d31aa607c3259d20557":{
      "scriptId":"u68"},
    "319e709681df439abb9214fe2f03f367":{
      "scriptId":"u69"},
    "c03994deee87475893771201fcadaf8c":{
      "scriptId":"u70"},
    "a57cc7a2be564c0dab47af2c4b8acbed":{
      "scriptId":"u71"},
    "895223c5e4c24c7eb3c1fab7dcee32bc":{
      "scriptId":"u72"},
    "d4df66d4263f4d00a3ec473418dbd24c":{
      "scriptId":"u73"},
    "54e50fadf1f24cf5b19d6028d3ce14cc":{
      "scriptId":"u74"},
    "c0350bcd533446aa9ece9605aa13a16b":{
      "scriptId":"u75"},
    "e5402dd1d858469d9b57dd036c91ab07":{
      "scriptId":"u76"},
    "ad39ffa6cce04532989b2cb3b6397cec":{
      "scriptId":"u77"},
    "b8bdedd0ecc34eacb73bba0ec78d75d0":{
      "scriptId":"u78"},
    "8dd518eaa57c466dbf94148a7e8894eb":{
      "scriptId":"u79"},
    "c0bfa3cb5f0e4968980228c521b4f724":{
      "scriptId":"u80"},
    "3c55ecee29784ff38ef1da0f353ea0b1":{
      "scriptId":"u81"},
    "a2530367138740ae9026811820c2eb18":{
      "scriptId":"u82"},
    "d989a79a66c94c7ab9a06f9e0b1981d3":{
      "scriptId":"u83"},
    "1cc280e7d8234d94b3353db275a8ab10":{
      "scriptId":"u84"},
    "fe7c6e0de3a84513914cfa97a4857f81":{
      "scriptId":"u85"},
    "2ab9a0b138b7468c9e35abf7987cd68f":{
      "scriptId":"u86"},
    "1a6034c24d6b4ed5881ffc93116dea92":{
      "scriptId":"u87"},
    "598b38209af240c6b2357db62127f09c":{
      "scriptId":"u88"},
    "58a03a54159645e68b07add840ac6d91":{
      "scriptId":"u89"},
    "82d80cc26e914c919b8dea4f7fb8460b":{
      "scriptId":"u90"},
    "1848fbaaca4f4bb9a43bf9aab8a400de":{
      "scriptId":"u91"},
    "9770728817f7457f8396ff0e80724b06":{
      "scriptId":"u92"},
    "f45e75f603d7445a83256957afd34cef":{
      "scriptId":"u93"},
    "e3617882dd4b49f28cc668aaa3fe78d0":{
      "scriptId":"u94"},
    "5920a1b2f6804f769219cdc5b3c05ac8":{
      "scriptId":"u95"},
    "9651cebbc52f451da0bf7ba5a9e9ba3b":{
      "scriptId":"u96"},
    "d533f23f02d14c489160f262078d49e1":{
      "scriptId":"u97"},
    "dfc6277cd0154409b295e72e4a30468e":{
      "scriptId":"u98"},
    "ea66a7dbffe344878f1400c70d9466ac":{
      "scriptId":"u99"},
    "6e9b41ea696f445b869b568697c4f870":{
      "scriptId":"u100"},
    "15318c5e1da2494ea7957c0459e58541":{
      "scriptId":"u101"},
    "1267df29a90d4b7287717a5561f346ed":{
      "scriptId":"u102"},
    "efc5ceff2d8a423a9441501f0fcc8272":{
      "scriptId":"u103"},
    "8fa0dfe2496140dca4c10bb22d608480":{
      "scriptId":"u104"},
    "bbda20f173094367b8da0cc0ac59818a":{
      "scriptId":"u105"},
    "0c16b5932fba49d5b8d8baaa694462e6":{
      "scriptId":"u106"},
    "58a7f9a35dda48d2bc0f20540dac2fc8":{
      "scriptId":"u107"},
    "e9e4ca3ac583471e8c634d6e9a8e508d":{
      "scriptId":"u108"},
    "276fe8a34e414a738208ee5041c31f00":{
      "scriptId":"u109"},
    "d7f598d05b64410a80060d601d56695a":{
      "scriptId":"u110"},
    "06a0e3b4b20c44d49437c3ac0963623a":{
      "scriptId":"u111"},
    "bd1fb68d4efa4a3ebe744cd01321c1bb":{
      "scriptId":"u112"},
    "0fb40574220040008652e9faf2b1dfeb":{
      "scriptId":"u113"},
    "31d8d91b051447bf97e94c9e8f328de9":{
      "scriptId":"u114"},
    "cdbd955efe284f11901e66fdee80a6e2":{
      "scriptId":"u115"},
    "24aee4407e2744f4a6c53d4756116560":{
      "scriptId":"u116"},
    "6256a90cd24244edb7c8eb73a2f80a7a":{
      "scriptId":"u117"},
    "1a874fe5c2644dbe88e983ae4bd96094":{
      "scriptId":"u118"},
    "48486274ae3d47659dd4279395dbbb7d":{
      "scriptId":"u119"},
    "e0751dce6a6740e4b8268f89d096ebb1":{
      "scriptId":"u120"},
    "c05eee5f8d36478e919480a90c730188":{
      "scriptId":"u121"},
    "d178f862db8a4d818f78c5daaea74c69":{
      "scriptId":"u122"},
    "26206862df844480b86a82c46b72ef9a":{
      "scriptId":"u123"},
    "c9c7beee85ef406c8434915d5fcb114f":{
      "scriptId":"u124"},
    "fe186e5cb5c94ea09fa0a4855cc51841":{
      "scriptId":"u125"},
    "ad21c346e429451487a5dabf79288fde":{
      "scriptId":"u126"},
    "7e1243d8ed994e679db9c9d8150b45e4":{
      "scriptId":"u127"},
    "8b162e21863e41f281458129c2b3e3d8":{
      "scriptId":"u128"},
    "be44672eddfb4575926606f592093372":{
      "scriptId":"u129"},
    "c25dea37bd334e808c8c54598480979c":{
      "scriptId":"u130"},
    "6fb41b65abac47628cb8b35d2ee8b176":{
      "scriptId":"u131"},
    "bbb331d44cd3442e81ec859ed3487889":{
      "scriptId":"u132"},
    "dac8db83a8ea4825b4d33ad2183f03a4":{
      "scriptId":"u133"},
    "a4f45eb945fc41a9a7ddc131124496f3":{
      "scriptId":"u134"}}});